# Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>, 2015. #zanata
# Jiri Dostal <jdostal@redhat.com>, 2018. #zanata
# Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-04-28 14:47+0200\n"
"PO-Revision-Date: 2022-04-01 18:12+0000\n"
"Last-Translator: David Medina <medipas@gmail.com>\n"
"Language-Team: Catalan <https://l10n.opensuse.org/projects/uyuni/backend/ca/"
">\n"
"Language: ca\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Weblate 4.9.1\n"

#: ../server/apacheAuth.py:66
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "testimoni incomplet del servidor intermediari: %s"

#: ../server/apacheAuth.py:84
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr ""
"La signatura de l'intermediari enviada %s no coincideix amb la nostra %s."

#: ../server/apacheAuth.py:119
msgid "declined proxy authentication"
msgstr "s'ha rebutjat l'autenticació d'intermediari"

#: ../server/apacheRequest.py:59
#, python-format
msgid "Invalid request received (%s)."
msgstr "Es va rebre una petició no vàlida (%s)."

#: ../server/apacheRequest.py:120
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""
"MISSATGE IMPORTANT SEGÜENT:\n"
"%s"

#: ../server/apacheRequest.py:149
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""
"Mentre s'executava '%s': es va capturar\n"
"%s : %s\n"

#: ../server/apacheRequest.py:606
#, python-format
msgid "Invalid URI %s"
msgstr "L'URI %s no és vàlid"

#: ../server/configFilesHandler.py:129 ../server/handlers/app/packages.py:192
#: ../server/handlers/xmlrpc/registration.py:217
#: ../server/handlers/xmlrpc/registration.py:1170
#: ../server/handlers/xmlrpc/registration.py:1272
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   El compte %s s'ha desactivat en aquest servidor.\n"
"                   Poseu-vos en contacte amb l'administrador de "
"l'organització per obtenir més ajuda."

#: ../server/handlers/applet/applet.py:78
#, python-brace-format
msgid "Your system was not found in the {PRODUCT_NAME} database"
msgstr "El sistema no s'ha trobat a la base de dades de {PRODUCT_NAME}"

#: ../server/handlers/sat/auth.py:45
msgid "ISS is disabled on this server."
msgstr "ISS està desactivat en aquest servidor."

#: ../server/handlers/sat/auth.py:50
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "El servidor \"%s\" no està habilitat per a l'ISS."

#: ../server/handlers/xmlrpc/errata.py:64
#, python-format
msgid "Expected a package name, not: %s"
msgstr "S'esperava un nom de paquet, no %s"

#: ../server/handlers/xmlrpc/errata.py:115
#, python-format
msgid "Expected a package, not: %s"
msgstr "S'esperava un paquet, no: %s"

#: ../server/handlers/xmlrpc/proxy.py:65
#, python-format
msgid "SUSE Manager Proxy service not enabled for server profile: \"%s\""
msgstr ""
"El servei d'intermediari de SUSE Manager no està habilitat per al perfil del "
"servidor: %s"

#: ../server/handlers/xmlrpc/proxy.py:85
msgid "Invalid session key"
msgstr "la clau de sessió no és vàlida"

#: ../server/handlers/xmlrpc/proxy.py:93
msgid "This server ID no longer exists"
msgstr "Aquest ID de servidor ja no existeix"

#: ../server/handlers/xmlrpc/queue.py:434
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr "Tipus de valor d'acció no vàlid: %s (%s)"

#: ../server/handlers/xmlrpc/queue.py:462
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "L'acció %s no pertany al servidor %s"

#: ../server/handlers/xmlrpc/registration.py:196
msgid "Required data missing"
msgstr "Falten les dades necessàries"

#: ../server/handlers/xmlrpc/registration.py:200
msgid "Required members missing"
msgstr "Membres obligatoris desapareguts"

#: ../server/handlers/xmlrpc/registration.py:209
msgid "Attempt to register a system to an invalid username"
msgstr "Intenteu registrar un sistema amb un nom d'usuari no vàlid"

#: ../server/handlers/xmlrpc/registration.py:841
msgid "Invalid system release version requested"
msgstr "S'ha sol·licitat una versió de llançament del sistema no vàlida."

#: ../server/handlers/xmlrpc/registration.py:1065
msgid ""
"Unable to find a valid network interface, both ipaddr and ip6addr not found."
msgstr ""
"No s'ha pogut trobar una interfície de xarxa vàlida, no s'han trobat ni "
"ipaddr ni ip6addr."

#: ../server/handlers/xmlrpc/registration.py:1117
#, python-brace-format
msgid "{PRODUCT_NAME} Welcome Message"
msgstr "Missatge de benvinguda de {PRODUCT_NAME}"

#: ../server/handlers/xmlrpc/registration.py:1127
msgid "Privacy Statement"
msgstr "Declaració de privacitat"

#: ../server/handlers/xmlrpc/registration.py:1148
msgid "Expected a dictionary as a product argument"
msgstr "S'esperava un diccionari com a argument de producte."

#: ../server/handlers/xmlrpc/registration.py:1339
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr "El valor %s no és vàlid per a %s (%s)"

#: ../server/handlers/xmlrpc/scap.py:104
msgid "Invalid system_id/action_id pair."
msgstr "Parell system_id / action_id no vàlid."

#: ../server/handlers/xmlrpc/up2date.py:233
#, python-format
msgid "Invalid value %s (%s)"
msgstr "Valor no vàlid %s (%s)"

#: ../server/importlib/userAuth.py:98
msgid "You are not authorized to manage packages in the null org"
msgstr "No esteu autoritzat per gestionar els paquets de l'organització nul·la"

#: ../server/importlib/userAuth.py:103
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "No esteu autoritzat per gestionar els paquets de l'organització %s"

#: ../server/importlib/userAuth.py:121
msgid "You are not allowed to perform administrative tasks"
msgstr "No esteu autoritzat per realitzar les tasques administratives"

#: ../server/importlib/userAuth.py:144
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr ""
"No esteu autoritzat per gestionar el canal %s, o no existeix aquest canal"

#: ../server/importlib/userAuth.py:204
#, python-format
msgid ""
"\n"
"               %s Account has been deactivated on this server.\n"
"               Please contact your Org administrator for more help."
msgstr ""
"\n"
"               El compte %s s'ha desactivat en aquest servidor.\n"
"               Poseu-vos en contacte amb l'administrador de l'organització "
"per obtenir més ajuda."

#: ../server/rhnChannel.py:1999
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""
"El compte no té accés a cap canal que coincideixi (release=%(release)s, arch="
"%(arch)s)%(www_activation)s"

#: ../server/rhnChannel.py:2014
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr "Permisos de subscripció insuficients per al llançament (%s, %s"

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2278 ../server/rhnChannel.py:2293
msgid "System Registered but Inactive"
msgstr "Sistema registrat però inactiu"

#: ../server/rhnChannel.py:2279
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""
"\n"
"Combinació d'arquitectura i versió del sistema operatiu no vàlida (%s, %s).\n"
"El vostre sistema s'ha registrat, però no rebrà actualitzacions\n"
"perquè no es podia subscriure a un canal de base.\n"
"Poseu-vos en contacte amb l'administrador de la vostra organització per "
"obtenir ajuda.\n"

#: ../server/rhnChannel.py:2286
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Aquest sistema s'ha registrat correctament, però encara no té dret al\n"
"  servei. Perquè aquest sistema tingui dret al servei, inicieu sessió al "
"lloc web a\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnChannel.py:2294
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Aquest sistema s'ha registrat correctament, però no hi ha drets de servei\n"
"  disponibles. Perquè aquest sistema tingui dret al servei, inicieu sessió "
"al lloc web a\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr "Si us plau, executeu rhn_register com a arrel en aquest client."

#: ../server/rhnHandler.py:75
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr "Servei no habilitat per al perfil del sistema: \"%s\""

#: ../server/rhnPackage.py:49 ../server/rhnPackage.py:87
#: ../server/rhnPackage.py:107 ../server/rhnPackage.py:158
#, python-format
msgid "Invalid RPM package %s requested"
msgstr "S'ha sol·licitat el paquet RPM %s no vàlid."

#: ../server/rhnPackage.py:112
msgid "Package not found"
msgstr "Paquet no trobat"

#: ../server/rhnServer/server_class.py:97
#, python-format
msgid "Architecture `%s' is not supported"
msgstr "L'arquitectura %s no és compatible."

#: ../server/rhnServer/server_token.py:78
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "El testimoni `%s' té més d'un canal base assignat"

#: ../server/rhnServer/server_token.py:80
msgid "Conflicting base channels"
msgstr "Canals bàsics conflictius"

#: ../server/rhnServer/server_token.py:190
#, python-format
msgid "Failed to add server to group %s"
msgstr "No s'ha pogut afegir el servidor al grup %s"

#: ../server/rhnServer/server_token.py:503
#, python-format
msgid "Maximum usage count of %s reached"
msgstr "S'ha assolit el recompte màxim d'ús de %s"

#: ../server/rhnServer/server_token.py:744
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""
"No s'admet l'apilament de testimonis de reregistre amb diferents drets de "
"base."

#: ../server/rhnServer/server_token.py:811
#, python-format
msgid "Could not find token '%s'"
msgstr "No es va poder tovar el testimoni '%s'"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:843
msgid "Tokens from mismatching orgs"
msgstr "Testimonis d'organitzacions que no coincideixen"

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:853
msgid "Kickstart session mismatch"
msgstr "La sessió de Kickstart no coincideix"

#: ../server/rhnServer/server_token.py:877
msgid "Stacking of re-registration tokens is not supported"
msgstr "No s'admet l'apilament de testimonis de reregistre."

#: ../server/rhnUser.py:289 ../server/rhnUser.py:292
msgid "Invalid username/password combination"
msgstr "Combinació de nom d'usuari i contrasenya no vàlida"

#. nope, not reserved either
#: ../server/rhnUser.py:467
#, python-format
msgid "Username `%s' has not been reserved"
msgstr "El nom d'usuari %s no s'ha reservat."

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:473
msgid "E-mail address not specified"
msgstr "Adreça de correu electrònic no especificada"

#: ../server/rhnUser.py:509
#, python-format
msgid "username should be at least %d characters"
msgstr "El nom d'usuari ha de tenir com a mínim %d caràcters."

#: ../server/rhnUser.py:512
#, python-format
msgid "username should be less than %d characters"
msgstr "El nom d'usuari ha de tenir menys de %d caràcters."

#: ../server/rhnUser.py:523
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr "nom d'usuari = %s, caràcter no vàlid: %s"

#: ../server/rhnUser.py:542
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr "Limiteu l'adreça de correu electrònic a %s caràcters."

#: ../server/rhnUser.py:623
#, python-format
msgid "password must be at least %d characters"
msgstr "la contrasenya ha de tenir com a mínim %d caràcters"

#: ../server/rhnUser.py:626
#, python-format
msgid "Password must be shorter than %d characters"
msgstr "La contrasenya ha de tenir menys de %d caràcters."

#: ../server/rhnUser.py:644
#, python-format
msgid "password contains character `%s'"
msgstr "la contrasenya conté el caràcter %s"

#: ../server/rhnUser.py:651
#, python-format
msgid "username should be at least %d characters long"
msgstr "El nom d'usuari ha de tenir com a mínim %d caràcters."

#: ../server/rhnUser.py:662
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr "No es poden registrar els noms d'usuari que acaben en %s."

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:53
msgid "This does not appear to be a valid username."
msgstr "Aquest no sembla un nom d'usuari vàlid."

#: ../common/rhnException.py:54
msgid "Invalid username and password combination."
msgstr "Combinació de nom d'usuari i contrasenya no vàlida."

#: ../common/rhnException.py:55
msgid "This login is already taken, or the password is incorrect."
msgstr "Aquest inici de sessió ja s'ha fet o la contrasenya és incorrecta."

#: ../common/rhnException.py:56
msgid "Permission denied."
msgstr "Permís denegat."

#: ../common/rhnException.py:57
msgid "Object not found."
msgstr "Objecte no trobat."

#: ../common/rhnException.py:58
msgid "Invalid System Digital ID."
msgstr "ID digital del sistema no vàlid."

#: ../common/rhnException.py:59
msgid "Invalid System Credentials."
msgstr "Credencials del sistema no vàlides."

#: ../common/rhnException.py:60
msgid "Could not retrieve user data from database."
msgstr "No s'han pogut recuperar les dades d'usuari de la base de dades."

#: ../common/rhnException.py:61
msgid "Valid username required."
msgstr "Es requereix un nom d'usuari vàlid."

#: ../common/rhnException.py:62
msgid "Valid password required."
msgstr "Es requereix una contrasenya vàlida."

#: ../common/rhnException.py:63
msgid "Minimum username length violation."
msgstr "Incompliment de la longitud mínima del nom d'usuari."

#: ../common/rhnException.py:64
msgid "Minimum password length violation."
msgstr "Incompliment de la longitud mínima de la contrasenya."

#: ../common/rhnException.py:65
msgid "The username contains invalid characters."
msgstr "El nom d'usuari conté caràcters no vàlids."

#: ../common/rhnException.py:66
msgid "File not found."
msgstr "Fitxer no trobat."

#: ../common/rhnException.py:67
msgid "Architecture and OS version combination is not supported."
msgstr ""
"La combinació d'arquitectura i versió del sistema operatiu no és compatible."

#: ../common/rhnException.py:68
msgid "Could not retrieve system data from database."
msgstr "No s'han pogut recuperar les dades del sistema de la base de dades."

#: ../common/rhnException.py:69
msgid "Invalid arguments passed to function."
msgstr "S'han passat arguments no vàlids a la funció."

#: ../common/rhnException.py:70
msgid "Unable to retrieve requested entry."
msgstr "No es pot recuperar l'entrada sol·licitada."

#: ../common/rhnException.py:71
msgid "Could not update database entry."
msgstr "No s'ha pogut actualitzar l'entrada de la base de dades."

#: ../common/rhnException.py:72
msgid "Unsupported server architecture."
msgstr "L'arquitectura del servidor no està admesa."

#: ../common/rhnException.py:73
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running mgr_register as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     La funcionalitat del servidor anònim ja no està disponible.\n"
"\n"
"     Si us plau, torneu a registrar aquest sistema executant mgr_register "
"com a root.\n"
"     Visiteu https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     o inicieu sessió a https://%(hostname)s i des de la pestanya Visió "
"general,\n"
"     seleccioneu Gestió de subscripcions, per habilitar el servei per a "
"aquest sistema.\n"
"     "

#: ../common/rhnException.py:81
msgid "Record not available in the database."
msgstr "Registre no disponible a la base de dades."

#: ../common/rhnException.py:82
msgid "Invalid value for entry."
msgstr "Valor no vàlid per a l'entrada."

#: ../common/rhnException.py:83
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for SUSE Manager.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     Aquest sistema no té un dret vàlid per a SUSE Manager.\n"
"     Visiteu https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     o inicieu sessió a https://%(hostname)s i des de la pestanya Visió "
"general,\n"
"     seleccioneu Gestió de subscripcions, per habilitar el servei per a "
"aquest sistema.\n"
"     "

#: ../common/rhnException.py:89
msgid "Channel error"
msgstr "Error del canal"

#: ../common/rhnException.py:90
msgid "Client session token is invalid."
msgstr "El testimoni de la sessió del client no és vàlid."

#: ../common/rhnException.py:91
msgid "Client session token has expired."
msgstr "El testimoni de la sessió del client ha vençut."

#: ../common/rhnException.py:92
msgid "You are not authorized to retrieve the requested object."
msgstr "No esteu autoritzat per recuperar l'objecte sol·licitat."

#: ../common/rhnException.py:93
msgid "Invalid action"
msgstr "Acció no vàlida"

#: ../common/rhnException.py:94
msgid "You are not allowed to perform administrative tasks on this system."
msgstr ""
"No esteu autoritzat per realitzar les tasques administratives en aquest "
"sistema."

#: ../common/rhnException.py:96
msgid "The system is already subscribed to the specified channel."
msgstr "El sistema ja està subscrit al canal especificat."

#: ../common/rhnException.py:97
msgid "The system is not currently subscribed to the specified channel."
msgstr "El sistema actualment no està subscrit al canal especificat."

#: ../common/rhnException.py:98
msgid "The specified channel does not exist."
msgstr "El canal especificat no existeix."

#: ../common/rhnException.py:99
msgid "Invalid channel version."
msgstr "La versió del canal no és vàlida."

#: ../common/rhnException.py:100
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""
"\n"
"     S'han superat els límits de pertinença a grups d'usuaris.\n"
"\n"
"     La configuració actual del compte no us permet afegir-hi un altre\n"
"     compte d'usuari. Si us plau, consulteu amb l'administrador de "
"l'organització\n"
"     compte si el nombre màxim d'usuaris autoritzats a subscriure's al "
"servidor necessita\n"
"     canvis.\n"
"     "

#: ../common/rhnException.py:108
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""
"\n"
"     S'han superat els límits de pertinença al grup del sistema.\n"
"\n"
"     La configuració actual del compte no us permet afegir-hi un altre\n"
"     perfil del sistema. Si us plau, consulteu amb l'administrador de "
"l'organització\n"
"     la modificació del nombre màxim de perfils de sistema que hi poden "
"haver\n"
"     subscrits al compte.\n"
"     "

#: ../common/rhnException.py:116
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""
"\n"
"     Arquitectura no vàlida.\n"
"\n"
"     L'arquitectura del paquet no és compatible amb\n"
"     "

#: ../common/rhnException.py:121
msgid "Invalid RPM header"
msgstr "Capçalera RPM no vàlida"

#: ../common/rhnException.py:122
msgid ""
"\n"
"    This system is already registered as a Salt Minion. If you want to "
"register it as a traditional client\n"
"    please delete it first via the web UI or API and then register it using "
"the traditional tools.\n"
"    "
msgstr ""
"\n"
"    Aquest sistema ja està registrat com a Salt Minion. Si el voleu "
"registrar com a client tradicional\n"
"    si us plau, suprimiu-lo primer mitjançant la interfície d'usuari web o "
"l'API i després registreu-lo amb les eines tradicionals.\n"
"    "

#. For the uploading tools
#: ../common/rhnException.py:127
msgid "Invalid information uploaded to the server"
msgstr "Informació no vàlida pujada al servidor"

#: ../common/rhnException.py:128
msgid "Error uploading network interfaces configuration."
msgstr ""
"S'ha produït un error en pujar la configuració de les interfícies de xarxa."

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""
"\n"
"     No s'ha pogut carregar el paquet a causa d'una infracció de la "
"restricció d'unicitat.\n"
"     Assegureu-vos que el paquet no tingui cap dependència duplicada o\n"
"    si ja no existeix al servidor.\n"
"     "

#: ../common/rhnException.py:134
msgid ""
"\n"
"     The --force mgrpush option is disabled on this server.\n"
"     Please contact your SUSE Manager administrator for more help.\n"
"     "
msgstr ""
"\n"
"     L'opció --force mgrpush està desactivada en aquest servidor.\n"
"     Poseu-vos en contacte amb l'administrador de SUSE Manager per obtenir "
"més ajuda.\n"
"     "

#. 60-70: token errors
#: ../common/rhnException.py:140
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""
"\n"
"     No s'ha pogut trobar el testimoni d'activació especificat al servidor.\n"
"     Torneu-ho a provar amb una clau vàlida.\n"
"     "

#: ../common/rhnException.py:144
msgid "Too many systems registered using this registration token"
msgstr ""
"Hi ha massa sistemes registrats que utilitzen aquest testimoni de "
"registrament"

#: ../common/rhnException.py:145
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr "El testimoni conté ajustos no vàlids, en desús i insuficients"

#: ../common/rhnException.py:146
msgid "Conflicting activation tokens"
msgstr "Conflicte en els testimonis d'activació"

#. 70-80: channel subscription errors
#: ../common/rhnException.py:149
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""
"\n"
"     No s'ha trobat cap canal de base coincident per al vostre sistema.\n"
"     "

#: ../common/rhnException.py:152
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""
"\n"
"     No teniu permís de subscripció al canal designat.\n"
"     Consulteu el canal de l'organització o els administradors\n"
"     per a més detalls.\n"
"     "

#: ../common/rhnException.py:157
msgid "You can not unsubscribe from base channel."
msgstr "No us podeu de-subscriure del canal base."

#: ../common/rhnException.py:158
msgid "SUSE Manager or Proxy channel can not be subscribed."
msgstr "No es pot subscriure al canal SUSE Manager o Proxy."

#. 80-90: server group errors
#: ../common/rhnException.py:161
msgid "There was an error while trying to join the system to its groups"
msgstr "S'ha produït un error en intentar afegir el sistema als seus grups."

#. 90-100: entitlement errors
#: ../common/rhnException.py:164
msgid "Unable to entitle system"
msgstr "No es pot donar el dret al sistema"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:167
msgid "Maximum e-mail length violation."
msgstr "Incompliment de la longitud màxima del correu electrònic."

#: ../common/rhnException.py:168
msgid "This system has been previously registered."
msgstr "Aquest sistema s'ha registrat prèviament."

#: ../common/rhnException.py:169
msgid "Invalid username"
msgstr "El nom d'usuari no és vàlid"

#. 140-159 applet errors
#: ../common/rhnException.py:172
msgid "Unable to look up server"
msgstr "No es pot cercar el servidor."

#. 160-179: OSAD errors
#: ../common/rhnException.py:175
msgid "Required argument is missing"
msgstr "Falta l'argument obligatori"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:178
msgid "No entitlement information tied to hardware"
msgstr "No hi ha informació de drets vinculada al maquinari."

#: ../common/rhnException.py:179
msgid "Installation number is not entitling"
msgstr "El número d'instal·lació no hi dona dret."

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:182
msgid "Maximum username length violation"
msgstr "Incompliment de la longitud màxima del nom d'usuari"

#: ../common/rhnException.py:183
msgid "Maximum password length violation"
msgstr "Incompliment de la longitud màxima de la contrasenya"

#: ../common/rhnException.py:184
msgid "This user has read only API access. Action denied."
msgstr "Aquest usuari només té accés a l'API de lectura. Acció denegada."

#: ../common/rhnException.py:186
msgid "System Name cannot be less than 1 character"
msgstr "El nom del sistema no pot tenir menys d'1 caràcter."

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:190
msgid "SUSE Manager Proxy error."
msgstr "Error del servidor intermediari de SUSE Manager."

#: ../common/rhnException.py:191
msgid "SUSE Manager Proxy unable to login."
msgstr "L'intermediari de SUSE Manager no pot iniciar la sessió."

#. issued by a SUSE Manager Server/Satellite to the proxy
#: ../common/rhnException.py:193
msgid ""
"\n"
"     SUSE Manager Proxy system ID does not match a Spacewalk Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""
"\n"
"     L'identificador del sistema de l'intermediari de SUSE Manager no "
"coincideix\n"
"     amb un servidor intermediari Spacewalk a la base de dades.\n"
"     "

#: ../common/rhnException.py:197
msgid "SUSE Manager Proxy session token is invalid."
msgstr "El testimoni de sessió de l'intermediari de SUSE Manager no és vàlid."

#: ../common/rhnException.py:198
msgid "SUSE Manager Proxy session token has expired."
msgstr "El testimoni de sessió de l'intermediari de SUSE Manager ha caducat."

#. 2000-2999: Red Hat Satellite specific errors:
#: ../common/rhnException.py:202
msgid ""
"\n"
"      user creation is not allowed via mgr_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""
"\n"
"      no es permet la creació d'usuaris mitjançant mgr_register;\n"
"     poseu-vos en contacte amb l'administrador del sistema per crear el "
"compte.\n"
"     "

#: ../common/rhnException.py:206
msgid ""
"\n"
"     This SUSE Manager server is not allowed to use Inter Server Sync on "
"this server\n"
"     "
msgstr ""
"\n"
"     Aquest servidor de SUSE Manager no pot usar Inter Server Sync en aquest "
"servidor.\n"
"     "

#: ../common/rhnException.py:209
msgid ""
"\n"
"     Inter Server Sync is disabled on this SUSE Manager Server.\n"
"     "
msgstr ""
"\n"
"     La sincronització entre servidors està desactivada en aquest servidor "
"de SUSE Manager.\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:214
msgid "Invalid datatype passed"
msgstr "Es va passar un tipus de dades no vàlid"

#: ../common/rhnException.py:215
msgid "Unable to retrieve channel"
msgstr "No es pot recuperar el canal"

#: ../common/rhnException.py:216
msgid "Unable to retrieve package"
msgstr "No es pot recuperar el paquet"

#: ../common/rhnException.py:217
msgid "Unable to retrieve erratum"
msgstr "No es pot recuperar l'errata"

#: ../common/rhnException.py:218
msgid "File is missing"
msgstr "Falta el fitxer"

#: ../common/rhnException.py:219
msgid "Function retrieval error"
msgstr "Error en la recuperació de la funció"

#: ../common/rhnException.py:220
msgid "Function execution error"
msgstr "Error en l'execució de la funció"

#: ../common/rhnException.py:221
msgid "Missing version string"
msgstr "Falta la cadena de la versió"

#: ../common/rhnException.py:222
msgid "Invalid version string"
msgstr "La cadena de la versió no és vàlida"

#: ../common/rhnException.py:223
msgid "Mismatching versions"
msgstr "Les versions no coincideixen"

#: ../common/rhnException.py:224
msgid "Invalid channel version"
msgstr "La versió del canal no és vàlida"

#: ../common/rhnException.py:225
msgid "No comps file for channel"
msgstr "No hi ha el fitxer comps per al canal"

#: ../common/rhnException.py:226
msgid "Unable to retrieve comps file"
msgstr "No es pot recuperar el fitxer comps"

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:229
msgid "Configuration action missing"
msgstr "Falta l'acció de configuració"

#: ../common/rhnException.py:230
msgid "File too large"
msgstr "El fitxer és massa gran"

#: ../common/rhnException.py:231
msgid "File contains binary data"
msgstr "El fitxer conté dades binàries"

#: ../common/rhnException.py:232
msgid "Configuration channel is not empty"
msgstr "El canal de configuració no està buit"

#: ../common/rhnException.py:233
msgid "Permission error"
msgstr "Error de permís"

#: ../common/rhnException.py:234
msgid "Content missing for configuration file"
msgstr "Falta contingut per al fitxer de configuració"

#: ../common/rhnException.py:235
msgid "Template delimiters not specified"
msgstr "Delimitadors de plantilla no especificats"

#: ../common/rhnException.py:236
msgid "Configuration channel does not exist"
msgstr "El canal de configuració no existeix"

#: ../common/rhnException.py:237
msgid "Configuration channel already exists"
msgstr "El canal de configuració ja existeix"

#: ../common/rhnException.py:238
msgid "File missing from configuration channel"
msgstr "Falta el fitxer al canal de configuració."

#: ../common/rhnException.py:239
msgid "Different revision of this file is uploaded"
msgstr "Es penja una revisió diferent d'aquest fitxer"

#: ../common/rhnException.py:240
msgid "File already uploaded to configuration channel"
msgstr "El fitxer ja s'ha penjat al canal de configuració."

#: ../common/rhnException.py:241
msgid "File size exceeds remaining quota space"
msgstr "La mida del fitxer supera l'espai de quota restant."

#: ../common/rhnException.py:242
msgid "Full path of file must be specified"
msgstr "Cal especificar el camí complet del fitxer."

#: ../common/rhnException.py:243
msgid "Invalid revision number"
msgstr "El número de revisió no és vàlid"

#: ../common/rhnException.py:244
msgid "Cannot compare files of different file type"
msgstr "No es poden comparar els fitxers de diferent tipus de fitxer"

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:247
msgid "SCAP results file transfer is invalid or incomplete"
msgstr ""
"La transferència de fitxers de resultats SCAP no és vàlida o és incompleta."

#: ../common/rhnException.py:248
msgid "Error composing directory path for detailed SCAP results"
msgstr ""
"Error en redactar la ruta del directori per obtenir resultats SCAP detallats"

#: ../common/rhnException.py:249
msgid "Error composing file path for detailed SCAP results"
msgstr ""
"Error en redactar la ruta del fitxer per obtenir resultats SCAP detallats"

#: ../common/rhnException.py:250
msgid "Invalid content encoding"
msgstr "La codificació de contingut no és vàlida."

#: ../common/rhnException.py:297
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at scc.suse.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""
"\n"
"     S'ha produït un error en processar la sol·licitud. Si aquest problema\n"
"     persisteix, introduïu un informe d'error a scc.suse.com.\n"
"     Si trieu enviar l'informe d'error, assegureu-vos d'incloure-hi\n"
"     detalls del que s'estava intentant fer quan es va produir l'error i\n"
"     detalls sobre com reproduir el problema.\n"

#: ../common/rhnException.py:349
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""
"Missatge d'error:\n"
"    %s\n"

#: ../common/rhnException.py:351
#, python-format
msgid "Error Class Code: %s\n"
msgstr "Codi de la classe d'error: %s\n"

#: ../common/rhnException.py:354
#, python-format
msgid "Error Class Info: %s\n"
msgstr "Informació de la classe d'error: %s\n"

#: ../common/rhnException.py:356
#, python-format
msgid "Explanation: %s"
msgstr "Explicació: %s"

#: ../common/rhnTB.py:201
#, python-format
msgid "ERROR: %s %s: %s"
msgstr "ERROR: %s %s: %s"

#: ../common/rhnTB.py:203
#, python-format
msgid "TRACEBACK: %s"
msgstr "TRAÇABILITAT: %s"

#: ../satellite_tools/disk_dumper/iss.py:1294
#: ../satellite_tools/disk_dumper/iss.py:1298
#, python-format
msgid "format of %s should be at least YYYYMMDD.\n"
msgstr "El format de %s hauria de ser com a mínim AAAAMMDD.\n"

#: ../satellite_tools/messages.py:26
#, python-format
msgid ""
"\n"
"ERROR: executing step %s. Error is:\n"
"%s\n"
msgstr ""
"\n"
"ERROR: s'executa el pas %s. L'error és aquest:\n"
"%s\n"

#: ../satellite_tools/messages.py:31
#, python-format
msgid ""
"\n"
"ERROR: there was a problem accessing the channel data from your temporary\n"
"       repository. Did you migrate all of the data from the channel ISOs\n"
"       do this directory? If so, please recheck the channels ISOs, ensure\n"
"       that you have them all, and then iteratively remount and repopulate\n"
"       the temporary repository (%s).\n"
msgstr ""
"\n"
"ERROR: s'ha produït un problema en accedir a les dades del canal des del\n"
"       repositori temporal. Heu migrat totes les dades de les ISO del canal\n"
"       a aquest directori? Si és així, torneu a comprovar les ISO dels "
"canals, assegureu-vos\n"
"       que les tingueu totes i després torneu a muntar i repoblar "
"iterativament\n"
"       el dipòsit temporal (%s).\n"

#: ../satellite_tools/messages.py:39
#, python-format
msgid ""
"\n"
"ERROR: there was a problem synchronizing the information.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"ERROR: hi ha hagut un problema en sincronitzar la informació.\n"
"       Missatge d'error: %s\n"

#: ../satellite_tools/messages.py:44
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       Depending on the specific error details, please review your "
"configuration,\n"
"       basic network connectivity, and/or name resolution, and try again.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"ERROR: S'ha produït un problema en comunicar-se amb l'ISS mestre.\n"
"       En funció dels detalls específics de l'error, reviseu la "
"configuració,\n"
"       la connectivitat bàsica de xarxa i / o la resolució de noms i torneu-"
"ho a provar.\n"
"       Missatge d'error: %s\n"

#: ../satellite_tools/messages.py:51
#, python-format
msgid ""
"\n"
"ERROR: a child-channel cannot be synced without its parent being synced as\n"
"       well. A parent needs to be either (a) previously synced or (b) "
"synced\n"
"       in tandem with the desired child-channel. Missing parents for this\n"
"       transaction:\n"
"       %s\n"
msgstr ""
"\n"
"ERROR: no es pot sincronitzar un canal secundari sense que el pare també\n"
"        se sincronitzi . Un pare ha d'estar (a) sincronitzat prèviament o "
"(b) sincronitzat\n"
"       conjuntament amb el canal fill desitjat. Falten pares per a aquesta\n"
"       transacció:\n"
"       %s\n"

#: ../satellite_tools/messages.py:59
#, python-format
msgid ""
"\n"
"ERROR: you are not entitled to sync a channel in this set of channels.\n"
"Please contact your SUSE Manager contact\n"
"%s"
msgstr ""
"\n"
"ERROR: no teniu dret a sincronitzar un canal en aquest conjunt de canals.\n"
"Poseu-vos en contacte amb el gestor de SUSE.\n"
"%s"

#: ../satellite_tools/messages.py:64
#, python-format
msgid "  ERROR: not enough free space (%s KB) on device."
msgstr "  ERROR: no hi ha prou espai lliure (%s KB) al dispositiu."

#: ../satellite_tools/messages.py:66
#, python-format
msgid "    %3d/%s Fetch successful: %s (%s bytes)"
msgstr "    %3d/%s Obtenció correcta: %s (%s bytes)"

#: ../satellite_tools/messages.py:67
#, python-format
msgid "    Extinct package:  %s"
msgstr "    Paquet extingit: %s"

#: ../satellite_tools/messages.py:68
#, python-format
msgid "   Total size: %s"
msgstr "   Mida total: %s"

#: ../satellite_tools/messages.py:69
#, python-format
msgid "      Downloaded %s of %s. Estimated remaining time: %s"
msgstr "      S'ha baixat %s de %s. Temps restant estimat: %s"

#: ../satellite_tools/messages.py:70
#, python-format
msgid "    Fetch unsuccessful: %s"
msgstr "    L'obtenció no s'ha fet correctament: %s"

#: ../satellite_tools/messages.py:71
#, python-format
msgid "   RPM fetch summary: %s"
msgstr "   Resum de l'obtenció d'RPM: %s"

#: ../satellite_tools/messages.py:72
#, python-format
msgid "       success: %d"
msgstr "       correcte: %d"

#: ../satellite_tools/messages.py:73
#, python-format
msgid "       failed:  %d"
msgstr "       ha fallat:  %d"

#: ../satellite_tools/messages.py:74
#, python-format
msgid "       extinct: %d"
msgstr "       extingit: %d"

#: ../satellite_tools/messages.py:76
#, python-format
msgid "   Retrieving / parsing *relevant* package metadata: %s (%s)"
msgstr ""
"   Recuperant / analitzant les metadades del paquet *rellevant*: %s (%s)"

#: ../satellite_tools/messages.py:77
#, python-format
msgid "   Retrieving / parsing errata data: %s (%s)"
msgstr "   Recuperant / analitzant dades d'errates: %s (%s)"

#: ../satellite_tools/messages.py:78
#, python-format
msgid "   Retrieving / parsing kickstart data: %s (%s)"
msgstr "   Recuperant / analitzant les dades de Kickstart: %s (%s)"

#: ../satellite_tools/messages.py:79
#, python-format
msgid "   Retrieving / parsing kickstart tree files: %s (%s)"
msgstr ""
"   Recuperant / analitzant els fitxers de l'arbre de Kickstart: %s (%s)"

#: ../satellite_tools/messages.py:80
#, python-format
msgid "   Importing *relevant* package metadata: %s (%s)"
msgstr "   Importació de metadades del paquet *rellevant*: %s (%s)"

#: ../satellite_tools/messages.py:81
msgid "   * WARNING: this may be a slow process."
msgstr "   * ADVERTÈNCIA: aquest pot ser un procés lent."

#: ../satellite_tools/messages.py:82
msgid "Linking packages to channels"
msgstr "Enllaç de paquets a canals"

#: ../satellite_tools/messages.py:83
#, python-format
msgid "   Importing *relevant* errata: %s (%s)"
msgstr "   Important errates *rellevants*: %s (%s)"

#: ../satellite_tools/messages.py:84
msgid "   No new kickstartable tree to import"
msgstr "   No hi ha cap arbre de taula d'inici nou per importar."

#: ../satellite_tools/messages.py:85
#, python-format
msgid "Importing kickstartable trees (%d)"
msgstr "Importació d'arbres de taules d'inici (%d)"

#: ../satellite_tools/messages.py:86
#, python-format
msgid "Imported kickstartable trees (%d)"
msgstr "Arbres de taules d'inici importats (%d)"

#: ../satellite_tools/reposync.py:115 ../satellite_tools/satsync.py:439
msgid "+++ sending log as an email +++"
msgstr "+++ enviament de registre com a correu electrònic +++"

#: ../satellite_tools/reposync.py:118
#, python-format
msgid "%s sync. report from %s"
msgstr "Informe de sincronització de %s de %s"

#: ../satellite_tools/reposync.py:126 ../satellite_tools/satsync.py:449
msgid "+++ email requested, but there is nothing to send +++"
msgstr "+++ correu electrònic sol·licitat, però no hi ha res per enviar +++"

#: ../satellite_tools/rhn_satellite_activate.py:198
#, python-format
msgid ""
"\"%s\" (specified in commandline)\n"
"could not be opened and read:\n"
"%s"
msgstr ""
"%s (especificat a la línia d'ordres)\n"
"no s'ha pogut obrir ni llegir:\n"
"%s"

#: ../satellite_tools/rhn_satellite_activate.py:205
#, python-format
msgid ""
"\"%s\" could not be opened\n"
"and/or written to:\n"
"%s"
msgstr ""
"%s no s'ha pogut obrir\n"
"ni escriure-hi:\n"
"%s"

#: ../satellite_tools/satsync.py:258
#, python-format
msgid "No handler for step %s"
msgstr "No hi ha controlador per al pas %s"

#. Try one more time - this time it should be faster since
#. everything should be cached
#: ../satellite_tools/satsync.py:270
msgid "Environment changed, trying again..."
msgstr "L'entorn ha canviat, es torna a provar..."

#: ../satellite_tools/satsync.py:277
msgid "ERROR: Encountered IntegrityError: \n"
msgstr "ERROR: s'ha trobat un error d'integritat: \n"

#: ../satellite_tools/satsync.py:285
msgid "Repeated failures"
msgstr "Fallades repetides"

#: ../satellite_tools/satsync.py:290
#, python-format
msgid ""
"    Import complete:\n"
"        Begin time: %s\n"
"        End time:   %s\n"
"        Elapsed:    %s\n"
"          "
msgstr ""
"    Importació completada:\n"
"        Hora d'inici: %s\n"
"        Hora d'acabament: %s\n"
"        Transcorregut: %s\n"
"          "

#: ../satellite_tools/satsync.py:311
msgid "hours"
msgstr "hores"

#: ../satellite_tools/satsync.py:311
msgid "minutes"
msgstr "minuts"

#: ../satellite_tools/satsync.py:311
msgid "seconds"
msgstr "segons"

#: ../satellite_tools/satsync.py:357
msgid ""
"ERROR: The dump is missing package data, use --no-rpms to skip this step or "
"fix the content to include package data."
msgstr ""
"ERROR: falten dades del paquet a l'abocament, useu --no-rpms per ometre "
"aquest pas o corregiu el contingut per incloure dades del paquet."

#. the orgs() method doesn't exist; that's fine we just
#. won't sync the orgs
#: ../satellite_tools/satsync.py:404
msgid "The SUSE Manager master does not support syncing orgs data."
msgstr ""
"El mestre de SUSE Manager no admet la sincronització de dades de "
"l'organització."

#: ../satellite_tools/satsync.py:404
msgid "Skipping..."
msgstr "S'omet..."

#: ../satellite_tools/satsync.py:442
#, python-format
msgid "SUSE Manager Inter Server sync. report from %s"
msgstr "Informe de sincronització entre servidors de SUSE Manager de %s"

#: ../satellite_tools/satsync.py:520
msgid " - file-system synchronization"
msgstr " - sincronització del sistema de fitxers"

#: ../satellite_tools/satsync.py:532 ../satellite_tools/satsync.py:540
msgid " - live synchronization"
msgstr " - sincronització en directe"

#: ../satellite_tools/satsync.py:533
#, python-brace-format
msgid ""
"ERROR: Live content synchronizing with RHN Classic Hosted is no longer "
"supported.\n"
"Please use the cdn-sync command instead unless you are attempting to sync "
"from another {PRODUCT_NAME} via Inter-Server-Sync (ISS), or from local "
"content on disk via Channel Dump ISOs."
msgstr ""
"ERROR: la sincronització de contingut en directe amb RHN Classic Hosted ja "
"no és compatible.\n"
"Si us plau, useu l'ordre cdn-sync tret que intenteu sincronitzar des d'un "
"altre {PRODUCT_NAME} mitjançant Inter-Server-Sync (ISS) o des del contingut "
"local del disc mitjançant les ISO d'abocament de canals."

#: ../satellite_tools/satsync.py:541
#, python-format
msgid "   url: %s"
msgstr "   url: %s"

#: ../satellite_tools/satsync.py:542
#, python-format
msgid "   debug/output level: %s"
msgstr "   nivell de depuració / sortida: %s"

#: ../satellite_tools/satsync.py:552
msgid "ERROR: this server must be registered with SUSE Manager."
msgstr "ERROR: aquest servidor ha d'estar registrat amb SUSE Manager."

#: ../satellite_tools/satsync.py:574
#, python-format
msgid "Retrieving / parsing %s data"
msgstr "Recuperant / analitzant les dades de %s"

#: ../satellite_tools/satsync.py:584 ../satellite_tools/satsync.py:599
msgid "*** SYSTEM INTERRUPT CALLED ***"
msgstr "*** S'ha cridat una interrupció del sistema ***"

#: ../satellite_tools/satsync.py:592
msgid "ERROR: fatal parser exception occurred "
msgstr "ERROR: s'ha produït una excepció fatal de l'analitzador "

#: ../satellite_tools/satsync.py:593
#, python-format
msgid "(line: %s, col: %s msg: %s)"
msgstr "(línia: %s, col.: %s missatge: %s)"

#: ../satellite_tools/satsync.py:597
#, python-format
msgid "ERROR: parser exception occurred: %s"
msgstr "ERROR: s'ha produït una excepció de l'analitzador: %s"

#: ../satellite_tools/satsync.py:602
msgid "ERROR: exception (during parse) occurred: "
msgstr "ERROR: s'ha produït una excepció (durant l'anàlisi): "

#: ../satellite_tools/satsync.py:603
#, python-format
msgid ""
"   Encountered some errors with %s data (see logs (%s) for more information)"
msgstr ""
"   S'han trobat alguns errors amb les dades de %s (vegeu els registres (%s) "
"per obtenir més informació)"

#: ../satellite_tools/satsync.py:605
#, python-format
msgid "   Encountered some errors with %s data:"
msgstr "   S'han trobat alguns errors amb les dades de %s:"

#: ../satellite_tools/satsync.py:606
#, python-format
msgid "   ------- %s PARSE/IMPORT ERROR -------"
msgstr "   ------- %s ERROR D'ANÀLISI / IMPORTACIÓ -------"

#: ../satellite_tools/satsync.py:608
msgid "   ---------------------------------------"
msgstr "   ---------------------------------------"

#: ../satellite_tools/satsync.py:611
#, python-format
msgid "%s data complete"
msgstr "Dades completades: %s"

#: ../satellite_tools/satsync.py:664
msgid "Retrieving / parsing channel data"
msgstr "Recuperació / anàlisi de dades del canal"

#: ../satellite_tools/satsync.py:717
msgid "Channel data complete"
msgstr "Dades del canal completades"

#: ../satellite_tools/satsync.py:735
#, python-format
msgid "%10s import from %s"
msgstr "%10s importa des de %s"

#: ../satellite_tools/satsync.py:738
#, python-format
msgid "%10s import from %s - %s"
msgstr "%10s importa des de %s - %s"

#: ../satellite_tools/satsync.py:742
#, python-format
msgid "%10s"
msgstr "%10s"

#: ../satellite_tools/satsync.py:749
msgid "p"
msgstr "p"

#: ../satellite_tools/satsync.py:751
msgid "."
msgstr "."

#: ../satellite_tools/satsync.py:757
msgid "   p = previously imported/synced channel"
msgstr "   p = canal importat / sincronitzat prèviament"

#: ../satellite_tools/satsync.py:758
msgid "   . = channel not yet imported/synced"
msgstr "   . = canal encara no importat / sincronitzat"

#: ../satellite_tools/satsync.py:764
msgid "   e = channel no longer supported (end-of-service)"
msgstr "   e = el canal ja no és compatible (fi del servei)"

#: ../satellite_tools/satsync.py:766
msgid "   ? = channel label invalid --- typo?"
msgstr "   ? = l'etiqueta del canal no és vàlida --- error ortogràfic?"

#: ../satellite_tools/satsync.py:770
#, python-format
msgid "   %s:"
msgstr "   %s:"

#: ../satellite_tools/satsync.py:771
#, python-format
msgid "      %s %-40s %4s %s"
msgstr "      %s %-40s %4s %s"

#: ../satellite_tools/satsync.py:772
msgid "base-channels"
msgstr "canals base"

#: ../satellite_tools/satsync.py:785 ../satellite_tools/satsync.py:1619
msgid "NONE RELEVANT"
msgstr "CAP DE RELLEVANT"

#: ../satellite_tools/satsync.py:807
msgid "end-of-service"
msgstr "fi del servei"

#: ../satellite_tools/satsync.py:808
msgid "e"
msgstr "e"

#: ../satellite_tools/satsync.py:814
msgid "   typos:"
msgstr "   errors tipogràfics:"

#: ../satellite_tools/satsync.py:815
msgid "?"
msgstr "?"

#: ../satellite_tools/satsync.py:830
#, python-format
msgid "XXX: imported channels: %s"
msgstr "XXX: canals importats: %s"

#: ../satellite_tools/satsync.py:831
#, python-format
msgid "XXX:   cached channels: %s"
msgstr "XXX: canals en memòria cau: %s"

#: ../satellite_tools/satsync.py:836
msgid "XXX: list channels called"
msgstr "XXX: llista els canals trucats"

#: ../satellite_tools/satsync.py:854
msgid "ERROR: these channels either do not exist or are not available:"
msgstr "ERROR: aquests canals no existeixen o no estan disponibles:"

#: ../satellite_tools/satsync.py:858
#, python-format
msgid "       (to see a list of channel labels: %s --list-channels)"
msgstr ""
"       (per veure una llista d'etiquetes de canals: %s --list-channels)"

#: ../satellite_tools/satsync.py:903
#, python-format
msgid "   Retrieving / parsing short package metadata: %s (%s)"
msgstr "   Recuperant / analitzant les metadades breus del paquet: %s (%s)"

#: ../satellite_tools/satsync.py:981
#, python-format
msgid "Diffing package metadata (what's missing locally?): %s"
msgstr "Metadades de paquets diferents (què falta localment?): %s"

#: ../satellite_tools/satsync.py:987 ../satellite_tools/satsync.py:1270
msgid "Diffing:    "
msgstr "Diferències:    "

#: ../satellite_tools/satsync.py:1004
msgid "ERROR: incremental dump skipped"
msgstr "ERROR: s'ha omès l'abocament incremental"

#: ../satellite_tools/satsync.py:1095
msgid "Downloading rpm packages"
msgstr "Baixada de paquets rpm"

#: ../satellite_tools/satsync.py:1100
#, python-format
msgid "   Fetching any missing RPMs: %s (%s)"
msgstr "   Obtenint els RPM que manquen: %s (%s)"

#: ../satellite_tools/satsync.py:1101 ../satellite_tools/satsync.py:1169
msgid "NONE MISSING"
msgstr "NO EN MANCA CAP"

#: ../satellite_tools/satsync.py:1110
msgid "Processing rpm packages complete"
msgstr "S'ha completat el processament dels paquets rpm."

#: ../satellite_tools/satsync.py:1137
msgid "Downloading package metadata"
msgstr "Baixada de metadades de paquets"

#: ../satellite_tools/satsync.py:1162
msgid "Downloading srpm packages"
msgstr "Baixada de paquets srpm"

#: ../satellite_tools/satsync.py:1168
#, python-format
msgid "   Fetching any missing SRPMs: %s (%s)"
msgstr "   Obtenint els SRPM que manquen: %s (%s)"

#: ../satellite_tools/satsync.py:1265
#, python-format
msgid "Diffing source package metadata (what's missing locally?): %s"
msgstr "Diferents metadades del paquet font (què manca localment?): %s"

#: ../satellite_tools/satsync.py:1276
msgid "Downloading source package metadata"
msgstr "Baixada de metadades del paquet font"

#: ../satellite_tools/satsync.py:1354 ../satellite_tools/satsync.py:2049
#, python-format
msgid "Unable to save file %s: %s"
msgstr "No es pot desar el fitxer %s: %s"

#. for
#. Retried a number of times and it still failed; log the
#. file as being failed and move on
#: ../satellite_tools/satsync.py:1361
#, python-format
msgid "Failed to fetch file %s"
msgstr "No s'ha pogut obtenir el fitxer %s"

#: ../satellite_tools/satsync.py:1366
msgid "Downloading kickstartable trees metadata"
msgstr "Baixada de metadades d'arbres de la taula d'inici"

#: ../satellite_tools/satsync.py:1381
msgid "Downloading kickstartable trees files"
msgstr "Baixada de fitxers d'arbres de la taula d'inici"

#: ../satellite_tools/satsync.py:1520
#, python-format
msgid "Grabbing all patches for channel %s"
msgstr "Agafant tots els pedaços per al canal %s"

#: ../satellite_tools/satsync.py:1570
msgid "Downloading patch data"
msgstr "Baixada de dades del pedaç"

#: ../satellite_tools/satsync.py:1572
msgid "Forcing download of all patch data for requested channels."
msgstr ""
"Es força la baixada de totes les dades del pedaç dels canals sol·licitats."

#: ../satellite_tools/satsync.py:1587
msgid "Downloading patch data complete"
msgstr "S'ha completat la baixada de les dades del pedaç."

#: ../satellite_tools/satsync.py:1592 ../satellite_tools/satsync.py:1613
msgid "Downloading:"
msgstr "Baixada:"

#: ../satellite_tools/satsync.py:1595
msgid " - complete"
msgstr " - completa"

#: ../satellite_tools/satsync.py:1640
msgid "Importing source package metadata"
msgstr "Importació de metadades del paquet font"

#: ../satellite_tools/satsync.py:1643
msgid "Importing package metadata"
msgstr "Importació de metadades del paquet"

#: ../satellite_tools/satsync.py:1651
msgid "Importing:  "
msgstr "Importació:  "

#. not in the cache
#: ../satellite_tools/satsync.py:1725
msgid ""
"Package Not Found in Cache, Clear the Cache "
"to                                  Regenerate it."
msgstr ""
"No s'ha trobat el paquet a la memòria cau. Esborreu la memòria cau per "
"regenerar-la."

#: ../satellite_tools/satsync.py:1731
msgid "Importing channel patches"
msgstr "Importació de pedaços de canal"

#: ../satellite_tools/satsync.py:1736
#, python-format
msgid "Importing %s patches for channel %s."
msgstr "Important %s pedaços per al canal %s."

#. Incomplete configuration
#: ../satellite_tools/satsync.py:2135
msgid "ERROR: server.mount_point not set in the configuration file"
msgstr "ERROR: server.mount_point no establert al fitxer de configuració."

#: ../satellite_tools/satsync.py:2139
#, python-format
msgid "ERROR: server.mount_point %s do not exist"
msgstr "ERROR: server.mount_point %s no existeix."

#: ../satellite_tools/satsync.py:2144
#, python-format
msgid "ERROR: path under server.mount_point (%s)  do not exist"
msgstr "ERROR: la ruta a server.mount_point (%s) no existeix."

#: ../satellite_tools/satsync.py:2221
#, python-format
msgid "Commandline: %s"
msgstr "Línia d'ordres: %s"

#: ../satellite_tools/satsync.py:2224
#, python-format
msgid ""
"DEBUG ONLY: max. batch-size for XML/database-import processing (1..%s).\"man "
"mgr-inter-sync\" for more information."
msgstr ""
"NOMÉS DEPURACIÓ: mida màxima del lot per al processament d'importació XML/"
"base de dades (1..%s). Vegeu \"man mgr-inter-sync\" per a més informació."

#: ../satellite_tools/satsync.py:2227
msgid "alternative SSL CA Cert (fullpath to cert file)"
msgstr "Certificat CA SSL alternatiu (camí complet al fitxer de certificat)"

#: ../satellite_tools/satsync.py:2229
msgid "process data for this channel only"
msgstr "processa dades només per a aquest canal"

#: ../satellite_tools/satsync.py:2231
msgid ""
"disk dump will be considered to be a full export; see \"man mgr-inter-sync\" "
"for more information."
msgstr ""
"l'abocament de disc es considerarà una exportació completa; vegeu \"man mgr-"
"inter-sync\" per a més informació."

#: ../satellite_tools/satsync.py:2234
msgid "existing custom channels will also be synced (unless -c is used)"
msgstr ""
"els canals personalitzats existents també se sincronitzaran (tret que s'usi -"
"c)"

#: ../satellite_tools/satsync.py:2236
#, python-format
msgid ""
"override debug level set in /etc/rhn/rhn.conf (which is currently set at %s)."
msgstr ""
"omet el nivell de depuració establert a /etc/rhn/rhn.conf (que actualment "
"està establert a %s)."

#: ../satellite_tools/satsync.py:2238
#, python-format
msgid "requested version of XML dump (default: %s)"
msgstr "versió sol·licitada de l'abocament XML (per defecte: %s)"

#: ../satellite_tools/satsync.py:2240
msgid "e-mail a report of what was synced/imported"
msgstr ""
"envia per correu electrònic un informe del que s'ha sincronitzat / importat"

#: ../satellite_tools/satsync.py:2242
msgid "forcibly process all (not a diff of) patch metadata"
msgstr "processa a la força totes les metadades del pedaç (no una diferència)"

#: ../satellite_tools/satsync.py:2244
msgid "Do not use an http proxy under any circumstances."
msgstr "No useu un servidor intermediari http en cap circumstància."

#: ../satellite_tools/satsync.py:2246
msgid "alternative http proxy (hostname:port)"
msgstr "intermediari http alternatiu (nom d'amfitrió:port)"

#: ../satellite_tools/satsync.py:2248
msgid "alternative http proxy username"
msgstr "nom d'usuari alternatiu de l'intermediari http"

#: ../satellite_tools/satsync.py:2250
msgid "alternative http proxy password"
msgstr "contrasenya alternativa de l'intermediari http"

#: ../satellite_tools/satsync.py:2252
msgid "parent SUSE Manager to import content from"
msgstr "SUSE Manager principal per importar-ne contingut"

#: ../satellite_tools/satsync.py:2254
msgid "list all available channels and exit"
msgstr "llista tots els canals disponibles i surt"

#: ../satellite_tools/satsync.py:2256
msgid "help on all error codes mgr-inter-sync returns"
msgstr "ajuda sobre tots els codis d'error que retorna mgr-inter-sync"

#: ../satellite_tools/satsync.py:2258
msgid "source mount point for import - disk update only"
msgstr ""
"punt de muntatge d'origen per a la importació - només actualització del disc"

#: ../satellite_tools/satsync.py:2260
msgid "do not process patch data"
msgstr "no processis les dades del pedaç"

#: ../satellite_tools/satsync.py:2262
msgid "do not process kickstart data (provisioning only)"
msgstr "no processis les dades de Kickstart (només aprovisionament)"

#: ../satellite_tools/satsync.py:2264
msgid "do not process full package metadata"
msgstr "no processis les metadades del paquet complet"

#: ../satellite_tools/satsync.py:2266
msgid "do not download, or process any RPMs"
msgstr "no baixis ni processis cap RPM"

#: ../satellite_tools/satsync.py:2268
msgid "org to which the sync imports data. defaults to the admin account"
msgstr ""
"org a la qual la sincronització importa les dades - per defecte al compte "
"d'administrador"

#: ../satellite_tools/satsync.py:2270
msgid "print the configuration and exit"
msgstr "imprimeix la configuració i surt"

#: ../satellite_tools/satsync.py:2272
msgid "alternative server with which to connect (hostname)"
msgstr "servidor alternatiu amb el qual connectar-se (nom d'amfitrió)"

#: ../satellite_tools/satsync.py:2274
msgid "synchronize to this step (man mgr-inter-sync for more info)"
msgstr "sincronitza amb aquest pas (man mgr-inter-sync per a més informació)"

#: ../satellite_tools/satsync.py:2276
msgid "write complete data to tempfile before streaming to remainder of app"
msgstr ""
"escriu dades completes al fitxer temporal abans de transmetre a la resta de "
"l'aplicació"

#: ../satellite_tools/satsync.py:2278
msgid "DEBUG ONLY: alternative path to digital system id"
msgstr "NOMÉS DEPURACIÓ: camí alternatiu a l'identificador del sistema digital"

#: ../satellite_tools/satsync.py:2280
msgid "alternative email address(es) for sync output (--email option)"
msgstr ""
"adreces de correu electrònic alternatives per a la sortida de sincronització "
"(opció --email)"

#: ../satellite_tools/satsync.py:2282
msgid "do not remove rpms when importing from local dump"
msgstr "no suprimeixis els rpm en importar des de l'abocament local"

#: ../satellite_tools/satsync.py:2284
msgid ""
"the fully qualified domain name of the master Satellite. Valid with --mount-"
"point only. Required if you want to import org data and channel permissions."
msgstr ""
"el nom de domini totalment qualificat del Satèl·lit principal. Vàlid només "
"amb --mount-point. Necessari si voleu importar dades de l'organització i "
"permisos de canal."

#: ../satellite_tools/satsync.py:2294
#, python-format
msgid "ERROR: these arguments make no sense in this context (try --help): %s"
msgstr ""
"ERROR: aquests arguments no tenen sentit en aquest context (proveu --help): "
"%s"

#. An SQL error is fatal... crash and burn
#: ../satellite_tools/satsync.py:2306
#, python-format
msgid "ERROR: Can't connect to the database: %s"
msgstr "ERROR! No es pot connectar a la base de dades: %s"

#: ../satellite_tools/satsync.py:2307
msgid "ERROR: Check if your database is running."
msgstr "ERROR: comproveu si la vostra base de dades s'executa."

#: ../satellite_tools/satsync.py:2340
#, python-format
msgid "ERROR: --debug-level takes an in integer value within the range %s."
msgstr "ERROR: --debug-level pren un valor enter dins l'interval %s."

#: ../satellite_tools/satsync.py:2342
msgid "  0  - little logging/messaging."
msgstr "  0 - poc registre / missatgeria."

#: ../satellite_tools/satsync.py:2343
msgid "  1  - minimal logging/messaging."
msgstr "  1 - registre / missatge mínim."

#: ../satellite_tools/satsync.py:2344
msgid "  2  - normal level of logging/messaging."
msgstr "  2 - nivell normal de registre / missatge."

#: ../satellite_tools/satsync.py:2345
msgid "  3  - lots of logging/messaging."
msgstr "  3 - molts registres / missatges."

#: ../satellite_tools/satsync.py:2346
msgid "  4+ - excessive logging/messaging."
msgstr "  4+ - registres / missatges excessius."

#: ../satellite_tools/satsync.py:2359
msgid "ERROR: The --master option is only valid with the --mount-point option"
msgstr "ERROR: l'opció --master només és vàlida amb l'opció --mount-point"

#: ../satellite_tools/satsync.py:2369
#, python-format
msgid "ERROR: Unable to lookup Org Id %s"
msgstr "ERROR: no es pot cercar l'identificador d'organització %s"

#: ../satellite_tools/satsync.py:2378
msgid ""
"WARNING: --list-channels option overrides any --step option. --step ignored."
msgstr ""
"ADVERTIMENT: l'opció --list-channels anul·la qualsevol opció --step. --pas "
"ignorat."

#: ../satellite_tools/satsync.py:2393
#, python-format
msgid ""
"ERROR: '%s' is not a valid step. See 'man mgr-inter-sync' for more detail."
msgstr ""
"ERROR: %s no és un pas vàlid. Vegeu \"man mgr-inter-sync\" per obtenir-ne "
"més detalls."

#: ../satellite_tools/satsync.py:2425
msgid ""
"ERROR: No channels currently imported; try mgr-inter-sync --list-channels; "
"then mgr-inter-sync -c chn0 -c chn1..."
msgstr ""
"ERROR: no s'ha importat cap canal actualment; proveu mgr-inter-sync --list-"
"channels; llavors mgr-inter-sync -c chn0 -c chn1..."

#. int(None) --> TypeError
#. int('a')  --> ValueError
#: ../satellite_tools/satsync.py:2474 ../satellite_tools/satsync.py:2478
msgid "ERROR: --batch-size must have a value within the range: 1..50"
msgstr "ERROR: --batch-size ha de tenir un valor dins de l'interval: 1-50"

#: ../satellite_tools/satsync.py:2486
#, python-format
msgid "ERROR: no such directory %s"
msgstr "ERROR: no hi ha el directori %s"

#: ../satellite_tools/satsync.py:2491
msgid "Error Codes: Returned codes means:"
msgstr "Codis d'error: els codis retornats signifiquen el següent:"

#: ../satellite_tools/satsync.py:2492
msgid " -1  - Could not lock file or KeyboardInterrupt or SystemExit"
msgstr ""
" -1 - No s'ha pogut bloquejar el fitxer o la interrupció del teclat o la "
"sortida del sistema"

#: ../satellite_tools/satsync.py:2493
msgid "  0  - User interrupted or intentional exit"
msgstr "  0 - Interrupció de l'usuari o sortida intencionada"

#: ../satellite_tools/satsync.py:2494
msgid "  1  - attempting to run more than one instance of mgr-inter-sync."
msgstr "  1 - Intent d'executar més d'una instància de mgr-inter-sync."

#: ../satellite_tools/satsync.py:2495
msgid "  2  - Unable to find synchronization tools."
msgstr "  2 - No es poden trobar eines de sincronització."

#: ../satellite_tools/satsync.py:2496
msgid "  3  - a general socket exception occurred"
msgstr "  3  - S'ha produït una excepció de sòcol general"

#: ../satellite_tools/satsync.py:2497
msgid "  4  - an SSL error occurred. Recheck your SSL settings."
msgstr ""
"  4 - S'ha produït un error d'SSL. Torneu a comprovar la configuració d'SSL."

#: ../satellite_tools/satsync.py:2498
msgid "  5  - ISS error"
msgstr "  5 - Error d'ISS"

#: ../satellite_tools/satsync.py:2499
msgid "  6  - unhandled exception occurred"
msgstr "  6 - S'ha produït una excepció no gestionada"

#: ../satellite_tools/satsync.py:2500
msgid "  7  - unknown sync error"
msgstr "  7 - error de sincronització desconegut"

#: ../satellite_tools/satsync.py:2501
msgid "  8  - ERROR: must be root to execute"
msgstr "  8 - ERROR: ha de ser root per executar-se"

#: ../satellite_tools/satsync.py:2502
msgid "  9  - rpclib fault during synchronization init"
msgstr "  9 - Error de rpclib durant l'inici de la sincronització"

#: ../satellite_tools/satsync.py:2503
msgid "  10 - synchronization init error"
msgstr "  10 - Error d'inici de sincronització"

#: ../satellite_tools/satsync.py:2504
msgid "  11 - Error parsing XML stream"
msgstr "  11 - Error en analitzar el flux XML"

#: ../satellite_tools/satsync.py:2505
msgid "  12 - Channel do not exist"
msgstr "  12 - El canal no existeix"

#: ../satellite_tools/satsync.py:2506
msgid "  13 - SQL error during importing package metadata"
msgstr "  13 - Error SQL durant la importació de metadades del paquet"

#: ../satellite_tools/satsync.py:2507
msgid "  14 - SQL error during linking channel packages"
msgstr "  14 - Error SQL durant l'enllaç de paquets de canal"

#: ../satellite_tools/satsync.py:2508
msgid "  15 - SQL error during xml processing"
msgstr "  15 - Error SQL durant el processament d'xml"

#: ../satellite_tools/satsync.py:2509
msgid "  16 - server.mount_point not set in the configuration file"
msgstr "  16 - server.mount_point no establert al fitxer de configuració"

#: ../satellite_tools/satsync.py:2510
msgid ""
"  17 - SQL error during retrieving the channels already imported in the SUSE "
"Manager database"
msgstr ""
"  17 - Error SQL durant la recuperació dels canals ja importats a la base de "
"dades de SUSE Manager"

#: ../satellite_tools/satsync.py:2511
msgid "  18 - Wrong db connection string in rhn.conf"
msgstr "  18 - Cadena de connexió de base de dades incorrecta a rhn.conf"

#: ../satellite_tools/satsync.py:2512
msgid "  19 - Bad arguments"
msgstr "  19 - Arguments incorrectes"

#: ../satellite_tools/satsync.py:2513
msgid "  20 - Could not connect to db."
msgstr "  20 - No s'ha pogut connectar a la base de dades."

#: ../satellite_tools/satsync.py:2514
msgid "  21 - Bad debug level"
msgstr "  21 - Nivell de depuració incorrecte"

#: ../satellite_tools/satsync.py:2515
msgid "  22 - Not valid step"
msgstr "  22 - Pas no vàlid"

#: ../satellite_tools/satsync.py:2516
msgid "  24 - no such file"
msgstr "  24 - No hi ha aquest fitxer"

#: ../satellite_tools/satsync.py:2517
msgid "  25 - no such directory"
msgstr "  25 - No hi ha aquest directori"

#: ../satellite_tools/satsync.py:2518
msgid "  26 - mount_point does not exist"
msgstr "  26 - El punt de muntatge no existeix"

#: ../satellite_tools/satsync.py:2519
msgid "  27 - No such org"
msgstr "  27 - No hi ha tal org"

#: ../satellite_tools/satsync.py:2520
msgid "  28 - error: --master is only valid with --mount-point"
msgstr "  28 - error: --master només és vàlid amb --mount-point"

#: ../satellite_tools/satsync.py:2527
#, python-format
msgid "ERROR: unknown dump version, try one of %s"
msgstr "ERROR: versió d'abocament desconeguda, proveu-ne una de %s"

#, fuzzy
#~ msgid "Invalid crash name"
#~ msgstr "El nom del paquet no és vàlid"

#, fuzzy
#~ msgid "Red Hat Satellite Welcome Message"
#~ msgstr "Missatge de benvinguda a la Red Hat Network"
