# Piotr Drąg <piotrdrag@gmail.com>, 2016. #zanata
# Piotr Drąg <piotrdrag@gmail.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-02-02 15:23+0100\n"
"PO-Revision-Date: 2018-03-16 04:50+0000\n"
"Last-Translator: Piotr Drąg <piotrdrag@gmail.com>\n"
"Language-Team: Polish\n"
"Language: pl\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
"|| n%100>=20) ? 1 : 2)\n"
"X-Generator: Zanata 4.6.2\n"

#: ../server/apacheAuth.py:72
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "niepełny token uwierzytelnienia pośrednika: %s"

#: ../server/apacheAuth.py:103
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr "Wysłany podpis pośrednika %s nie zgadza się z naszym %s."

#: ../server/apacheAuth.py:142
msgid "declined proxy authentication"
msgstr "odmówiono uwierzytelnienia pośrednika"

#: ../server/apacheRequest.py:67
#, python-format
msgid "Invalid request received (%s)."
msgstr "Otrzymano nieprawidłowe żądanie (%s)."

#. Send the message as a fault.
#: ../server/apacheRequest.py:134
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""
"WAŻNY KOMUNIKAT:\n"
"%s"

#: ../server/apacheRequest.py:164
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""
"Podczas wykonywania „%s”: przechwycono\n"
"%s: %s\n"

#. pylint: disable-next=consider-using-f-string
#: ../server/apacheRequest.py:679
#, python-format
msgid "Invalid URI %s"
msgstr "Nieprawidłowy adres URI %s"

#: ../server/configFilesHandler.py:141 ../server/handlers/app/packages.py:220
#: ../server/handlers/xmlrpc/registration.py:247
#: ../server/handlers/xmlrpc/registration.py:1276
#: ../server/handlers/xmlrpc/registration.py:1395
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   Konto %s zostało dezaktywowane na tym serwerze.\n"
"                   Proszę skontaktować się z administratorem organizacji po "
"więcej pomocy."

#: ../server/handlers/applet/applet.py:84
#, fuzzy, python-brace-format
msgid "Your system was not found in the {PRODUCT_NAME} database"
msgstr "Nie odnaleziono systemu w bazie danych usługi RHN"

#: ../server/handlers/sat/auth.py:46
#, fuzzy
msgid "ISS is disabled on this server."
msgstr "W tej usłudze Satellite wyłączono ISS."

#: ../server/handlers/sat/auth.py:53
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "Nie włączono serwera „%s” dla ISS."

#: ../server/handlers/xmlrpc/errata.py:71
#, python-format
msgid "Expected a package name, not: %s"
msgstr "Oczekiwano nazwy pakietu, nie: %s"

#: ../server/handlers/xmlrpc/errata.py:127
#, python-format
msgid "Expected a package, not: %s"
msgstr "Oczekiwano pakietu, nie: %s"

#: ../server/handlers/xmlrpc/proxy.py:70
#, fuzzy, python-format
msgid "SUSE Manager Proxy service not enabled for server profile: \"%s\""
msgstr "Usługa Spacewalk Proxy nie jest włączona dla profilu serwera: „%s”"

#: ../server/handlers/xmlrpc/proxy.py:92
msgid "Invalid session key"
msgstr "Nieprawidłowy klucz sesji"

#: ../server/handlers/xmlrpc/proxy.py:100
msgid "This server ID no longer exists"
msgstr "Ten identyfikator serwera już nie istnieje"

#: ../server/handlers/xmlrpc/queue.py:490
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr "Nieprawidłowy typ wartości działania %s (%s)"

#: ../server/handlers/xmlrpc/queue.py:525
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "Działanie %s nie należy do serwera %s"

#: ../server/handlers/xmlrpc/registration.py:225
msgid "Required data missing"
msgstr "Brak wymaganych danych"

#: ../server/handlers/xmlrpc/registration.py:230
msgid "Required members missing"
msgstr "Brak wymaganych członków"

#: ../server/handlers/xmlrpc/registration.py:238
msgid "Attempt to register a system to an invalid username"
msgstr "Próba zarejestrowania systemu do nieprawidłowej nazwy użytkownika"

#: ../server/handlers/xmlrpc/registration.py:897
msgid "Invalid system release version requested"
msgstr "Zażądano nieprawidłowej wersji wydania systemu"

#: ../server/handlers/xmlrpc/registration.py:1153
msgid ""
"Unable to find a valid network interface, both ipaddr and ip6addr not found."
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:1219
#, python-brace-format
msgid "{PRODUCT_NAME} Welcome Message"
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:1230
#, fuzzy
msgid "Privacy Statement"
msgstr "Oświadczenie o prywatności usługi Red Hat Satellite"

#: ../server/handlers/xmlrpc/registration.py:1252
msgid "Expected a dictionary as a product argument"
msgstr "Oczekiwano słownika jako parametr produktu"

#: ../server/handlers/xmlrpc/registration.py:1470
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr "Nieprawidłowa wartość „%s” dla %s (%s)"

#: ../server/handlers/xmlrpc/scap.py:125
msgid "Invalid system_id/action_id pair."
msgstr "Nieprawidłowa para system_id/action_id."

#. pylint: disable-next=invalid-name
#: ../server/handlers/xmlrpc/up2date.py:264
#, python-format
msgid "Invalid value %s (%s)"
msgstr "Nieprawidłowa wartość %s (%s)"

#: ../server/importlib/userAuth.py:109
msgid "You are not authorized to manage packages in the null org"
msgstr "Brak upoważnienia do zarządzania pakietami w pustej organizacji"

#: ../server/importlib/userAuth.py:115
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "Użytkownik nie może zarządzać pakietami w organizacji %s"

#. ok, you're a regular user who doesn't manage any channels.
#. take a hike.
#: ../server/importlib/userAuth.py:132
msgid "You are not allowed to perform administrative tasks"
msgstr "Użytkownik nie może wykonywać zadań administracyjnych"

#: ../server/importlib/userAuth.py:159
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr "Użytkownik nie może zarządzać kanałem %s lub ten kanał nie istnieje"

#: ../server/importlib/userAuth.py:229
#, fuzzy, python-format
msgid ""
"\n"
"               %s Account has been deactivated on this server.\n"
"               Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   Konto %s zostało dezaktywowane na tym serwerze.\n"
"                   Proszę skontaktować się z administratorem organizacji po "
"więcej pomocy."

#: ../server/rhnChannel.py:2216
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""
"Konto nie ma dostępu do żadnych kanałów pasujących do (wydanie: "
"„%(release)s”, architektura: „%(arch)s”)%(www_activation)s"

#: ../server/rhnChannel.py:2235
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr "Niewystarczające uprawnienia subskrypcji dla wydania (%s, %s"

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2549 ../server/rhnChannel.py:2568
msgid "System Registered but Inactive"
msgstr "Zarejestrowano system, ale nie jest aktywny"

#: ../server/rhnChannel.py:2551
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""
"\n"
"Nieprawidłowe połączenie architektury i wydania systemu operacyjnego (%s, "
"%s).\n"
"System został zarejestrowany , ale nie będzie otrzymywał aktualizacji,\n"
"ponieważ nie jest subskrybowany do podstawowego kanału.\n"
"Proszę skontaktować się z administratorem organizacji po pomoc.\n"

#: ../server/rhnChannel.py:2560
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Ten system został pomyślnie zarejestrowany, ale nie ma ważności\n"
"  do usługi. Aby uprawnić ten system do usługi, należy zalogować się na "
"stronie WWW pod adresem:\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnChannel.py:2570
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Ten system został pomyślnie zarejestrowany, ale żadne ważności\n"
"  nie były dostępne. Aby uprawnić ten system do usługi, należy zalogować się "
"na stronie WWW pod adresem:\n"
"\n"
"  %(entitlement_url)s\n"

#. Invalid server certificate.
#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr "Proszę wykonać polecenie rhn_register jako root na tym kliencie"

#: ../server/rhnHandler.py:76
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr "Usługa jest niedostępna dla profilu systemu: „%s”"

#: ../server/rhnPackage.py:52 ../server/rhnPackage.py:98
#: ../server/rhnPackage.py:118 ../server/rhnPackage.py:179
#, python-format
msgid "Invalid RPM package %s requested"
msgstr "Zażądano nieprawidłowego pakietu RPM %s"

#: ../server/rhnPackage.py:124
msgid "Package not found"
msgstr "Nie odnaleziono pakietu"

#: ../server/rhnServer/server_class.py:105
#, python-format
msgid "Architecture `%s' is not supported"
msgstr "Architektura „%s” jest nieobsługiwana"

#: ../server/rhnServer/server_token.py:86
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "Token „%s” ma przydzielony więcej niż jeden kanał podstawowy"

#: ../server/rhnServer/server_token.py:89
msgid "Conflicting base channels"
msgstr "Sprzeczne kanały podstawowe"

#: ../server/rhnServer/server_token.py:223
#, python-format
msgid "Failed to add server to group %s"
msgstr "Dodanie serwera do grupy %s się nie powiodło"

#: ../server/rhnServer/server_token.py:574
#, python-format
msgid "Maximum usage count of %s reached"
msgstr "Osiągnięto maksymalne użycie %s"

#: ../server/rhnServer/server_token.py:869
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""
"Nakładanie tokenów ponownej rejestracji na stos z różnymi podstawowymi "
"ważnościami jest nieobsługiwane"

#: ../server/rhnServer/server_token.py:946
#, python-format
msgid "Could not find token '%s'"
msgstr "Nie można odnaleźć tokenu „%s”"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:979
msgid "Tokens from mismatching orgs"
msgstr "Tokeny z niepasujących organizacji"

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:989
msgid "Kickstart session mismatch"
msgstr "Niepasująca sesja kickstart"

#: ../server/rhnServer/server_token.py:1013
msgid "Stacking of re-registration tokens is not supported"
msgstr "Nakładanie tokenów ponownej rejestracji na stos jest nieobsługiwane"

#: ../server/rhnUser.py:326 ../server/rhnUser.py:329
msgid "Invalid username/password combination"
msgstr "Nieprawidłowe połączenie nazwy użytkownika i hasła"

#. nope, not reserved either
#: ../server/rhnUser.py:526
#, python-format
msgid "Username `%s' has not been reserved"
msgstr "Nazwa użytkownika „%s” nie została zastrzeżona"

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:532
msgid "E-mail address not specified"
msgstr "Nie podano adresu e-mail"

#: ../server/rhnUser.py:574
#, python-format
msgid "username should be at least %d characters"
msgstr "nazwa użytkownika musi mieć co najmniej %d znaków"

#: ../server/rhnUser.py:578
#, python-format
msgid "username should be less than %d characters"
msgstr "nazwa użytkownika musi mieć mniej niż %d znaków"

#: ../server/rhnUser.py:592
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr "nazwa użytkownika to „%s”, nieprawidłowy znak „%s”"

#: ../server/rhnUser.py:613
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr "Proszę ograniczyć adres e-mail do %s znaków"

#: ../server/rhnUser.py:701
#, python-format
msgid "password must be at least %d characters"
msgstr "hasło musi mieć co najmniej %d znaków"

#: ../server/rhnUser.py:705
#, python-format
msgid "Password must be shorter than %d characters"
msgstr "Hasło musi być krótsze niż %d znaków"

#: ../server/rhnUser.py:721
#, python-format
msgid "password contains character `%s'"
msgstr "hasło zawiera znak „%s”"

#: ../server/rhnUser.py:730
#, python-format
msgid "username should be at least %d characters long"
msgstr "nazwa użytkownika musi mieć co najmniej %d znaków"

#: ../server/rhnUser.py:741
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr "Nie można rejestrować nazw użytkowników kończących się znakiem %s"

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:55
msgid "This does not appear to be a valid username."
msgstr "To nie jest prawidłowa nazwa użytkownika."

#: ../common/rhnException.py:56
msgid "Invalid username and password combination."
msgstr "Nieprawidłowe połączenie nazwy użytkownika i hasła."

#: ../common/rhnException.py:57
msgid "This login is already taken, or the password is incorrect."
msgstr "Ten login jest zajęty lub hasło jest niepoprawne."

#: ../common/rhnException.py:58
msgid "Permission denied."
msgstr "Odmowa uprawnień."

#: ../common/rhnException.py:59
msgid "Object not found."
msgstr "Nie odnaleziono obiektu."

#: ../common/rhnException.py:60
msgid "Invalid System Digital ID."
msgstr "Nieprawidłowy cyfrowy identyfikator systemu."

#: ../common/rhnException.py:61
msgid "Invalid System Credentials."
msgstr "Nieprawidłowe dane uwierzytelniające systemu."

#: ../common/rhnException.py:62
msgid "Could not retrieve user data from database."
msgstr "Nie można pobrać danych użytkownika z bazy danych."

#: ../common/rhnException.py:63
msgid "Valid username required."
msgstr "Wymagana jest prawidłowa nazwa użytkownika."

#: ../common/rhnException.py:64
msgid "Valid password required."
msgstr "Wymagane jest prawidłowe hasło."

#: ../common/rhnException.py:65
msgid "Minimum username length violation."
msgstr "Naruszono minimalną długość nazwy użytkownika."

#: ../common/rhnException.py:66
msgid "Minimum password length violation."
msgstr "Naruszono minimalną długość hasła."

#: ../common/rhnException.py:67
msgid "The username contains invalid characters."
msgstr "Nazwa użytkownika zawiera nieprawidłowe znaki."

#: ../common/rhnException.py:68
msgid "File not found."
msgstr "Nie odnaleziono pliku."

#: ../common/rhnException.py:69
msgid "Architecture and OS version combination is not supported."
msgstr "Nieobsługiwane połączenie architektury i wersji systemu operacyjnego."

#: ../common/rhnException.py:70
msgid "Could not retrieve system data from database."
msgstr "Nie można pobrać danych systemu z bazy danych."

#: ../common/rhnException.py:71
msgid "Invalid arguments passed to function."
msgstr "Do funkcji przekazano nieprawidłowe parametry."

#: ../common/rhnException.py:72
msgid "Unable to retrieve requested entry."
msgstr "Nie można pobrać żądanego wpisu."

#: ../common/rhnException.py:73
msgid "Could not update database entry."
msgstr "Nie można zaktualizować wpisu bazy danych."

#: ../common/rhnException.py:74
msgid "Unsupported server architecture."
msgstr "Nieobsługiwana architektura serwera."

#: ../common/rhnException.py:76
#, fuzzy, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running mgr_register as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     Funkcja anonimowego serwera nie jest już dostępna.\n"
"\n"
"     Proszę ponownie zarejestrować ten system wykonując polecenie "
"rhn_register\n"
"     jako root.\n"
"     Proszę odwiedzić https://%(hostname)s/rhn/systems/SystemEntitlements."
"do\n"
"     lub zalogować się na https://%(hostname)s i z karty „Przegląd”\n"
"     wybrać „Zarządzanie subskrypcją”, aby włączyć usługę dla tego systemu.\n"
"     "

#: ../common/rhnException.py:85
msgid "Record not available in the database."
msgstr "Wpis jest niedostępny w bazie danych."

#: ../common/rhnException.py:86
msgid "Invalid value for entry."
msgstr "Nieprawidłowa wartość wpisu."

#: ../common/rhnException.py:88
#, fuzzy, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for SUSE Manager.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     Ten system nie ma prawidłowej ważności dla usługi Red Hat Satellite.\n"
"     Proszę odwiedzić https://%(hostname)s/rhn/systems/SystemEntitlements."
"do\n"
"     lub zalogować się na https://%(hostname)s i z karty „Przegląd”\n"
"     wybrać „Zarządzanie subskrypcją”, aby włączyć usługę dla tego systemu.\n"
"     "

#: ../common/rhnException.py:95
msgid "Channel error"
msgstr "Błąd kanału"

#: ../common/rhnException.py:96
msgid "Client session token is invalid."
msgstr "Nieprawidłowy token sesji klienta."

#: ../common/rhnException.py:97
msgid "Client session token has expired."
msgstr "Token sesji klienta wygasł."

#: ../common/rhnException.py:98
msgid "You are not authorized to retrieve the requested object."
msgstr "Brak upoważnienia do pobierania żądanego obiektu."

#: ../common/rhnException.py:99
msgid "Invalid action"
msgstr "Nieprawidłowe działanie"

#: ../common/rhnException.py:101
msgid "You are not allowed to perform administrative tasks on this system."
msgstr "Użytkownik nie może wykonywać zadań administracyjnych w tym systemie."

#: ../common/rhnException.py:104
msgid "The system is already subscribed to the specified channel."
msgstr "Ten system już subskrybuje podany kanał."

#: ../common/rhnException.py:105
msgid "The system is not currently subscribed to the specified channel."
msgstr "Ten system obecnie nie subskrybuje podanego kanału."

#: ../common/rhnException.py:106
msgid "The specified channel does not exist."
msgstr "Podany kanał nie istnieje."

#: ../common/rhnException.py:107
msgid "Invalid channel version."
msgstr "Nieprawidłowa wersja kanału."

#: ../common/rhnException.py:109
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""
"\n"
"     Przekroczono ograniczenia członkostwa w grupach użytkowników.\n"
"\n"
"     Obecne ustawienia konta nie pozwalają na dodawanie kolejnego\n"
"     konta użytkownika. Proszę zapytać administratora organizacji o konto,\n"
"     jeśli maksymalna liczba użytkowników mogących subskrybować serwer\n"
"     musi zostać zmieniona.\n"
"     "

#: ../common/rhnException.py:119
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""
"\n"
"     Przekroczono ograniczenia członkostwa w grupach systemu.\n"
"\n"
"     Obecne ustawienia konta nie pozwalają na dodawanie kolejnego\n"
"     profilu systemu. Proszę zapytać administratora organizacji\n"
"     o zmodyfikowanie maksymalnej liczby profili systemów, jaka może\n"
"     subskrybować konto.\n"
"     "

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""
"\n"
"     Nieprawidłowa architektura.\n"
"\n"
"     Architektura pakietu nie jest obsługiwana przez\n"
"     "

#: ../common/rhnException.py:136
msgid "Invalid RPM header"
msgstr "Nieprawidłowy nagłówek pakietu RPM"

#: ../common/rhnException.py:138
msgid ""
"\n"
"    This system is already registered as a Salt Minion. If you want to "
"register it as a traditional client\n"
"    please delete it first via the web UI or API and then register it using "
"the traditional tools.\n"
"    "
msgstr ""

#. For the uploading tools
#: ../common/rhnException.py:144
msgid "Invalid information uploaded to the server"
msgstr "Do serwera wysłano nieprawidłowe informacje"

#: ../common/rhnException.py:145
msgid "Error uploading network interfaces configuration."
msgstr "Błąd podczas wysyłania konfiguracji interfejsów sieciowych."

#: ../common/rhnException.py:147
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""
"\n"
"     Wysłanie pakietu się nie powiodło z powodu naruszenia ograniczenia "
"unikalności.\n"
"     Proszę się upewnić, że pakiet nie ma podwójnych zależności lub\n"
"     nie istnieje już na serwerze\n"
"     "

#: ../common/rhnException.py:154
#, fuzzy
msgid ""
"\n"
"     The --force mgrpush option is disabled on this server.\n"
"     Please contact your SUSE Manager administrator for more help.\n"
"     "
msgstr ""
"\n"
"     Na tym serwerze wyłączono opcję „--force rhnpush”.\n"
"     Proszę skontaktować się z administratorem usługi Satellite po więcej "
"pomocy.\n"
"     "

#: ../common/rhnException.py:161
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""
"\n"
"     Nie można odnaleźć podanego tokenu aktywacji na serwerze.\n"
"     Proszę spróbować ponownie za pomocą prawidłowego klucza.\n"
"     "

#: ../common/rhnException.py:166
msgid "Too many systems registered using this registration token"
msgstr "Za pomocą tego tokenu rejestracji zarejestrowano za dużo systemów"

#: ../common/rhnException.py:167
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr ""
"Token zawiera nieprawidłowe, przestarzałe lub niewystarczające ustawienia"

#: ../common/rhnException.py:168
msgid "Conflicting activation tokens"
msgstr "Sprzeczne tokeny aktywacji"

#: ../common/rhnException.py:171
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""
"\n"
"     Nie odnaleziono pasującego kanału podstawowego dla systemu.\n"
"     "

#: ../common/rhnException.py:176
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""
"\n"
"     Nie ma uprawnienia subskrypcji dla wyznaczonego kanału.\n"
"     Kanał organizacji lub administratorzy organizacji mają więcej "
"informacji.\n"
"     "

#: ../common/rhnException.py:182
msgid "You can not unsubscribe from base channel."
msgstr "Nie można zrezygnować z subskrypcji podstawowego kanału."

#: ../common/rhnException.py:183
#, fuzzy
msgid "SUSE Manager or Proxy channel can not be subscribed."
msgstr "Nie można subskrybować kanału Satellite lub Proxy."

#. 80-90: server group errors
#: ../common/rhnException.py:185
msgid "There was an error while trying to join the system to its groups"
msgstr "Wystąpił błąd podczas próby dołączenia systemu do jego grup"

#. 90-100: entitlement errors
#: ../common/rhnException.py:187
msgid "Unable to entitle system"
msgstr "Nie można upoważnić systemu"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:189
msgid "Maximum e-mail length violation."
msgstr "Naruszono maksymalną długość adresu e-mail."

#: ../common/rhnException.py:190
msgid "This system has been previously registered."
msgstr "Ten system został poprzednio zarejestrowany."

#: ../common/rhnException.py:191
msgid "Invalid username"
msgstr "Nieprawidłowa nazwa użytkownika"

#. 140-159 applet errors
#: ../common/rhnException.py:193
msgid "Unable to look up server"
msgstr "Nie można odnaleźć serwera"

#. 160-179: OSAD errors
#: ../common/rhnException.py:195
msgid "Required argument is missing"
msgstr "Brak wymaganego parametru"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:197
msgid "No entitlement information tied to hardware"
msgstr "Brak informacji o ważności powiązanych z tym sprzętem"

#: ../common/rhnException.py:198
msgid "Installation number is not entitling"
msgstr "Numer instalacji nie jest ważny"

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:200
msgid "Maximum username length violation"
msgstr "Naruszono maksymalną długość nazwy użytkownika"

#: ../common/rhnException.py:201
msgid "Maximum password length violation"
msgstr "Naruszono maksymalną długość hasła"

#: ../common/rhnException.py:202
msgid "This user has read only API access. Action denied."
msgstr "Ten użytkownik ma dostęp do API tylko do odczytu. Odmowa działania."

#: ../common/rhnException.py:203
msgid "System Name cannot be less than 1 character"
msgstr "Nazwa systemu nie może być krótsza niż 1 znak"

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:206
#, fuzzy
msgid "SUSE Manager Proxy error."
msgstr "Błąd usługi Spacewalk Proxy."

#: ../common/rhnException.py:207
#, fuzzy
msgid "SUSE Manager Proxy unable to login."
msgstr "Nie można zalogować usługi Spacewalk Proxy."

#: ../common/rhnException.py:210
#, fuzzy
msgid ""
"\n"
"     SUSE Manager Proxy system ID does not match a Spacewalk Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""
"\n"
"     Identyfikator systemu usługi Spacewalk Proxy nie pasuje do serwera "
"Spacewalk Proxy\n"
"     w bazie danych.\n"
"     "

#: ../common/rhnException.py:215
#, fuzzy
msgid "SUSE Manager Proxy session token is invalid."
msgstr "Token sesji usługi Spacewalk Proxy jest nieprawidłowy."

#: ../common/rhnException.py:216
#, fuzzy
msgid "SUSE Manager Proxy session token has expired."
msgstr "Token sesji usługi Spacewalk Proxy wygasł."

#: ../common/rhnException.py:220
#, fuzzy
msgid ""
"\n"
"      user creation is not allowed via mgr_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""
"\n"
"     tworzenie użytkownika za pomocą polecenia rhn_register nie jest "
"dozwolone.\n"
"     Proszę skontaktować się z administratorem systemu w celu utworzenia "
"konta.\n"
"     "

#: ../common/rhnException.py:226
#, fuzzy
msgid ""
"\n"
"     This SUSE Manager server is not allowed to use Inter Server Sync on "
"this server\n"
"     "
msgstr ""
"\n"
"     Ten serwer usługi Satellite ne może używać Inter Satellite Sync na tej "
"usłudze Satellite\n"
"     "

#: ../common/rhnException.py:231
#, fuzzy
msgid ""
"\n"
"     Inter Server Sync is disabled on this SUSE Manager Server.\n"
"     "
msgstr ""
"\n"
"     Inter Satellite Sync jest wyłączone na tej usłudze Satellite.\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:236
msgid "Invalid datatype passed"
msgstr "Przekazano nieprawidłowy typ danych"

#: ../common/rhnException.py:237
msgid "Unable to retrieve channel"
msgstr "Nie można pobrać kanału"

#: ../common/rhnException.py:238
msgid "Unable to retrieve package"
msgstr "Nie można pobrać pakietu"

#: ../common/rhnException.py:239
msgid "Unable to retrieve erratum"
msgstr "Nie można pobrać poprawki"

#: ../common/rhnException.py:240
msgid "File is missing"
msgstr "Brak pliku"

#: ../common/rhnException.py:241
msgid "Function retrieval error"
msgstr "Błąd pobierania funkcji"

#: ../common/rhnException.py:242
msgid "Function execution error"
msgstr "Błąd wykonywania funkcji"

#: ../common/rhnException.py:243
msgid "Missing version string"
msgstr "Brak ciągu wersji"

#: ../common/rhnException.py:244
msgid "Invalid version string"
msgstr "Nieprawidłowy ciąg wersji"

#: ../common/rhnException.py:245
msgid "Mismatching versions"
msgstr "Niepasujące wersje"

#: ../common/rhnException.py:246
msgid "Invalid channel version"
msgstr "Nieprawidłowa wersja kanału"

#: ../common/rhnException.py:247
msgid "No comps file for channel"
msgstr "Brak pliku comps dla kanału"

#: ../common/rhnException.py:248
msgid "Unable to retrieve comps file"
msgstr "Nie można pobrać pliku comps"

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:250
msgid "Configuration action missing"
msgstr "Brak działania konfiguracji"

#: ../common/rhnException.py:251
msgid "File too large"
msgstr "Plik jest za duży"

#: ../common/rhnException.py:252
msgid "File contains binary data"
msgstr "Plik zawiera binarne dane"

#: ../common/rhnException.py:253
msgid "Configuration channel is not empty"
msgstr "Kanał konfiguracji nie jest pusty"

#: ../common/rhnException.py:254
msgid "Permission error"
msgstr "Błąd uprawnień"

#: ../common/rhnException.py:255
msgid "Content missing for configuration file"
msgstr "Brak treści pliku konfiguracji"

#: ../common/rhnException.py:256
msgid "Template delimiters not specified"
msgstr "Nie podano separatorów szablonu"

#: ../common/rhnException.py:257
msgid "Configuration channel does not exist"
msgstr "Kanał konfiguracji nie istnieje"

#: ../common/rhnException.py:258
msgid "Configuration channel already exists"
msgstr "Kanał konfiguracji już istnieje"

#: ../common/rhnException.py:259
msgid "File missing from configuration channel"
msgstr "Brak pliku z kanału konfiguracji"

#: ../common/rhnException.py:260
msgid "Different revision of this file is uploaded"
msgstr "Inna wersja tego pliku została wysłana"

#: ../common/rhnException.py:261
msgid "File already uploaded to configuration channel"
msgstr "Już wysłano plik do kanału konfiguracji"

#: ../common/rhnException.py:262
msgid "File size exceeds remaining quota space"
msgstr "Rozmiar pliku przekracza pozostałe miejsce przydziału"

#: ../common/rhnException.py:263
msgid "Full path of file must be specified"
msgstr "Należy podać pełną ścieżkę do pliku"

#: ../common/rhnException.py:264
msgid "Invalid revision number"
msgstr "Nieprawidłowy numer wersji"

#: ../common/rhnException.py:265
msgid "Cannot compare files of different file type"
msgstr "Nie można porównywać plików różnego typu"

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:267
msgid "SCAP results file transfer is invalid or incomplete"
msgstr "Przesyłanie pliku wyników SCAP jest nieprawidłowe lub niepełne"

#: ../common/rhnException.py:268
msgid "Error composing directory path for detailed SCAP results"
msgstr ""
"Błąd podczas składania ścieżki do katalogu dla szczegółowych wyników SCAP"

#: ../common/rhnException.py:269
msgid "Error composing file path for detailed SCAP results"
msgstr "Błąd podczas składania ścieżki do pliku dla szczegółowych wyników SCAP"

#: ../common/rhnException.py:270
msgid "Invalid content encoding"
msgstr "Nieprawidłowe kodowanie treści"

#: ../common/rhnException.py:319
#, fuzzy
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at scc.suse.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""
"\n"
"     Wystąpił błąd podczas przetwarzania żądania. Jeśli problem\n"
"     się powtarza, proszę zgłosić błąd na stronie bugzilla.redhat.com.\n"
"     Jeśli błąd zostanie zgłoszony, to proszę dołączyć informacje\n"
"     o próbowanym działaniu, kiedy wystąpił błąd i informacje o sposobie\n"
"     powtórzenia tego problemu.\n"

#: ../common/rhnException.py:371
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""
"Komunikat o błędzie:\n"
"    %s\n"

#: ../common/rhnException.py:373
#, python-format
msgid "Error Class Code: %s\n"
msgstr "Kod klasy błędu: %s\n"

#: ../common/rhnException.py:376
#, python-format
msgid "Error Class Info: %s\n"
msgstr "Informacje o klasie błędu: %s\n"

#: ../common/rhnException.py:378
#, python-format
msgid "Explanation: %s"
msgstr "Wyjaśnienie: %s"

#: ../common/rhnTB.py:220
#, python-format
msgid "ERROR: %s %s: %s"
msgstr "BŁĄD: %s %s: %s"

#: ../common/rhnTB.py:221
#, python-format
msgid "TRACEBACK: %s"
msgstr "WYJĄTEK: %s"

#: ../satellite_tools/disk_dumper/iss.py:1636
#: ../satellite_tools/disk_dumper/iss.py:1642
#, python-format
msgid "format of %s should be at least YYYYMMDD.\n"
msgstr ""

#: ../satellite_tools/messages.py:28
#, python-format
msgid ""
"\n"
"ERROR: executing step %s. Error is:\n"
"%s\n"
msgstr ""

#: ../satellite_tools/messages.py:35
#, python-format
msgid ""
"\n"
"ERROR: there was a problem accessing the channel data from your temporary\n"
"       repository. Did you migrate all of the data from the channel ISOs\n"
"       do this directory? If so, please recheck the channels ISOs, ensure\n"
"       that you have them all, and then iteratively remount and repopulate\n"
"       the temporary repository (%s).\n"
msgstr ""

#: ../satellite_tools/messages.py:45
#, python-format
msgid ""
"\n"
"ERROR: there was a problem synchronizing the information.\n"
"       Error message: %s\n"
msgstr ""

#: ../satellite_tools/messages.py:52
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       Depending on the specific error details, please review your "
"configuration,\n"
"       basic network connectivity, and/or name resolution, and try again.\n"
"       Error message: %s\n"
msgstr ""

#: ../satellite_tools/messages.py:61
#, python-format
msgid ""
"\n"
"ERROR: a child-channel cannot be synced without its parent being synced as\n"
"       well. A parent needs to be either (a) previously synced or (b) "
"synced\n"
"       in tandem with the desired child-channel. Missing parents for this\n"
"       transaction:\n"
"       %s\n"
msgstr ""

#: ../satellite_tools/messages.py:71
#, python-format
msgid ""
"\n"
"ERROR: you are not entitled to sync a channel in this set of channels.\n"
"Please contact your SUSE Manager contact\n"
"%s"
msgstr ""

#: ../satellite_tools/messages.py:77
#, python-format
msgid "  ERROR: not enough free space (%s KB) on device."
msgstr ""

#: ../satellite_tools/messages.py:79
#, python-format
msgid "    %3d/%s Fetch successful: %s (%s bytes)"
msgstr ""

#: ../satellite_tools/messages.py:80
#, fuzzy, python-format
msgid "    Extinct package:  %s"
msgstr "Oczekiwano pakietu, nie: %s"

#: ../satellite_tools/messages.py:81
#, python-format
msgid "   Total size: %s"
msgstr ""

#: ../satellite_tools/messages.py:83
#, python-format
msgid "      Downloaded %s of %s. Estimated remaining time: %s"
msgstr ""

#: ../satellite_tools/messages.py:85
#, python-format
msgid "    Fetch unsuccessful: %s"
msgstr ""

#: ../satellite_tools/messages.py:86
#, python-format
msgid "   RPM fetch summary: %s"
msgstr ""

#: ../satellite_tools/messages.py:87
#, python-format
msgid "       success: %d"
msgstr ""

#: ../satellite_tools/messages.py:88
#, python-format
msgid "       failed:  %d"
msgstr ""

#: ../satellite_tools/messages.py:89
#, python-format
msgid "       extinct: %d"
msgstr ""

#: ../satellite_tools/messages.py:91
#, python-format
msgid "   Retrieving / parsing *relevant* package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:92
#, python-format
msgid "   Retrieving / parsing errata data: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:93
#, python-format
msgid "   Retrieving / parsing kickstart data: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:94
#, python-format
msgid "   Retrieving / parsing kickstart tree files: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:95
#, python-format
msgid "   Importing *relevant* package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:96
msgid "   * WARNING: this may be a slow process."
msgstr ""

#: ../satellite_tools/messages.py:97
#, fuzzy
msgid "Linking packages to channels"
msgstr "Sprzeczne kanały podstawowe"

#: ../satellite_tools/messages.py:98
#, python-format
msgid "   Importing *relevant* errata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:99
msgid "   No new kickstartable tree to import"
msgstr ""

#: ../satellite_tools/messages.py:100
#, python-format
msgid "Importing kickstartable trees (%d)"
msgstr ""

#: ../satellite_tools/messages.py:101
#, python-format
msgid "Imported kickstartable trees (%d)"
msgstr ""

#: ../satellite_tools/reposync.py:136 ../satellite_tools/satsync.py:516
msgid "+++ sending log as an email +++"
msgstr ""

#: ../satellite_tools/reposync.py:139
#, python-format
msgid "%s sync. report from %s"
msgstr ""

#: ../satellite_tools/reposync.py:149 ../satellite_tools/satsync.py:528
msgid "+++ email requested, but there is nothing to send +++"
msgstr ""

#: ../satellite_tools/satsync.py:305
#, python-format
msgid "No handler for step %s"
msgstr ""

#. Try one more time - this time it should be faster since
#. everything should be cached
#: ../satellite_tools/satsync.py:317
msgid "Environment changed, trying again..."
msgstr ""

#: ../satellite_tools/satsync.py:325
msgid "ERROR: Encountered IntegrityError: \n"
msgstr ""

#: ../satellite_tools/satsync.py:334
msgid "Repeated failures"
msgstr ""

#: ../satellite_tools/satsync.py:343
#, python-format
msgid ""
"    Import complete:\n"
"        Begin time: %s\n"
"        End time:   %s\n"
"        Elapsed:    %s\n"
"          "
msgstr ""

#: ../satellite_tools/satsync.py:369
msgid "hours"
msgstr ""

#: ../satellite_tools/satsync.py:369
msgid "minutes"
msgstr ""

#: ../satellite_tools/satsync.py:369
msgid "seconds"
msgstr ""

#: ../satellite_tools/satsync.py:422
msgid ""
"ERROR: The dump is missing package data, use --no-rpms to skip this step or "
"fix the content to include package data."
msgstr ""

#: ../satellite_tools/satsync.py:477
msgid "The SUSE Manager master does not support syncing orgs data."
msgstr ""

#: ../satellite_tools/satsync.py:478
msgid "Skipping..."
msgstr ""

#: ../satellite_tools/satsync.py:519
#, python-format
msgid "SUSE Manager Inter Server sync. report from %s"
msgstr ""

#: ../satellite_tools/satsync.py:607
msgid " - file-system synchronization"
msgstr ""

#: ../satellite_tools/satsync.py:623 ../satellite_tools/satsync.py:639
msgid " - live synchronization"
msgstr ""

#: ../satellite_tools/satsync.py:627
#, python-brace-format
msgid ""
"ERROR: Live content synchronizing with RHN Classic Hosted is no longer "
"supported.\n"
"Please use the cdn-sync command instead unless you are attempting to sync "
"from another {PRODUCT_NAME} via Inter-Server-Sync (ISS), or from local "
"content on disk via Channel Dump ISOs."
msgstr ""

#: ../satellite_tools/satsync.py:640
#, python-format
msgid "   url: %s"
msgstr ""

#: ../satellite_tools/satsync.py:641
#, python-format
msgid "   debug/output level: %s"
msgstr ""

#: ../satellite_tools/satsync.py:657
msgid "ERROR: this server must be registered with SUSE Manager."
msgstr ""

#: ../satellite_tools/satsync.py:683
#, python-format
msgid "Retrieving / parsing %s data"
msgstr ""

#: ../satellite_tools/satsync.py:693 ../satellite_tools/satsync.py:712
msgid "*** SYSTEM INTERRUPT CALLED ***"
msgstr ""

#: ../satellite_tools/satsync.py:706
msgid "ERROR: fatal parser exception occurred "
msgstr ""

#: ../satellite_tools/satsync.py:707
#, python-format
msgid "(line: %s, col: %s msg: %s)"
msgstr ""

#: ../satellite_tools/satsync.py:710
#, python-format
msgid "ERROR: parser exception occurred: %s"
msgstr ""

#: ../satellite_tools/satsync.py:715
msgid "ERROR: exception (during parse) occurred: "
msgstr ""

#: ../satellite_tools/satsync.py:719
#, python-format
msgid ""
"   Encountered some errors with %s data (see logs (%s) for more information)"
msgstr ""

#: ../satellite_tools/satsync.py:728
#, python-format
msgid "   Encountered some errors with %s data:"
msgstr ""

#: ../satellite_tools/satsync.py:729
#, python-format
msgid "   ------- %s PARSE/IMPORT ERROR -------"
msgstr ""

#: ../satellite_tools/satsync.py:732
msgid "   ---------------------------------------"
msgstr ""

#: ../satellite_tools/satsync.py:738
#, python-format
msgid "%s data complete"
msgstr ""

#: ../satellite_tools/satsync.py:817
msgid "Retrieving / parsing channel data"
msgstr ""

#: ../satellite_tools/satsync.py:892
msgid "Channel data complete"
msgstr ""

#: ../satellite_tools/satsync.py:911
#, python-format
msgid "%10s import from %s"
msgstr ""

#: ../satellite_tools/satsync.py:913
#, python-format
msgid "%10s import from %s - %s"
msgstr ""

#: ../satellite_tools/satsync.py:919
#, python-format
msgid "%10s"
msgstr ""

#: ../satellite_tools/satsync.py:927
msgid "p"
msgstr ""

#: ../satellite_tools/satsync.py:929
msgid "."
msgstr ""

#: ../satellite_tools/satsync.py:945
msgid "   p = previously imported/synced channel"
msgstr ""

#: ../satellite_tools/satsync.py:946
msgid "   . = channel not yet imported/synced"
msgstr ""

#: ../satellite_tools/satsync.py:952
msgid "   e = channel no longer supported (end-of-service)"
msgstr ""

#: ../satellite_tools/satsync.py:954
msgid "   ? = channel label invalid --- typo?"
msgstr ""

#: ../satellite_tools/satsync.py:958
#, python-format
msgid "   %s:"
msgstr ""

#: ../satellite_tools/satsync.py:959
#, python-format
msgid "      %s %-40s %4s %s"
msgstr ""

#: ../satellite_tools/satsync.py:960
#, fuzzy
msgid "base-channels"
msgstr "Sprzeczne kanały podstawowe"

#: ../satellite_tools/satsync.py:974 ../satellite_tools/satsync.py:1962
msgid "NONE RELEVANT"
msgstr ""

#: ../satellite_tools/satsync.py:999
msgid "end-of-service"
msgstr ""

#: ../satellite_tools/satsync.py:1000
msgid "e"
msgstr ""

#: ../satellite_tools/satsync.py:1006
msgid "   typos:"
msgstr ""

#: ../satellite_tools/satsync.py:1007
msgid "?"
msgstr ""

#: ../satellite_tools/satsync.py:1024
#, python-format
msgid "XXX: imported channels: %s"
msgstr ""

#: ../satellite_tools/satsync.py:1025
#, python-format
msgid "XXX:   cached channels: %s"
msgstr ""

#: ../satellite_tools/satsync.py:1030
msgid "XXX: list channels called"
msgstr ""

#: ../satellite_tools/satsync.py:1054
msgid "ERROR: these channels either do not exist or are not available:"
msgstr ""

#: ../satellite_tools/satsync.py:1061
#, python-format
msgid "       (to see a list of channel labels: %s --list-channels)"
msgstr ""

#: ../satellite_tools/satsync.py:1118
#, python-format
msgid "   Retrieving / parsing short package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/satsync.py:1208
#, python-format
msgid "Diffing package metadata (what's missing locally?): %s"
msgstr ""

#: ../satellite_tools/satsync.py:1218 ../satellite_tools/satsync.py:1560
msgid "Diffing:    "
msgstr ""

#: ../satellite_tools/satsync.py:1238
msgid "ERROR: incremental dump skipped"
msgstr ""

#: ../satellite_tools/satsync.py:1346
msgid "Downloading rpm packages"
msgstr ""

#: ../satellite_tools/satsync.py:1355
#, python-format
msgid "   Fetching any missing RPMs: %s (%s)"
msgstr ""

#: ../satellite_tools/satsync.py:1356 ../satellite_tools/satsync.py:1441
msgid "NONE MISSING"
msgstr ""

#: ../satellite_tools/satsync.py:1366
msgid "Processing rpm packages complete"
msgstr ""

#: ../satellite_tools/satsync.py:1396
msgid "Downloading package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1430
msgid "Downloading srpm packages"
msgstr ""

#: ../satellite_tools/satsync.py:1440
#, python-format
msgid "   Fetching any missing SRPMs: %s (%s)"
msgstr ""

#: ../satellite_tools/satsync.py:1550
#, python-format
msgid "Diffing source package metadata (what's missing locally?): %s"
msgstr ""

#: ../satellite_tools/satsync.py:1569
msgid "Downloading source package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1655 ../satellite_tools/satsync.py:2477
#, fuzzy, python-format
msgid "Unable to save file %s: %s"
msgstr "Nie można upoważnić systemu"

#. for
#. Retried a number of times and it still failed; log the
#. file as being failed and move on
#: ../satellite_tools/satsync.py:1661
#, python-format
msgid "Failed to fetch file %s"
msgstr ""

#: ../satellite_tools/satsync.py:1666
msgid "Downloading kickstartable trees metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1684
msgid "Downloading kickstartable trees files"
msgstr ""

#: ../satellite_tools/satsync.py:1841
#, python-format
msgid "Grabbing all patches for channel %s"
msgstr ""

#: ../satellite_tools/satsync.py:1895
msgid "Downloading patch data"
msgstr ""

#: ../satellite_tools/satsync.py:1897
msgid "Forcing download of all patch data for requested channels."
msgstr ""

#: ../satellite_tools/satsync.py:1915
msgid "Downloading patch data complete"
msgstr ""

#: ../satellite_tools/satsync.py:1924 ../satellite_tools/satsync.py:1955
msgid "Downloading:"
msgstr ""

#: ../satellite_tools/satsync.py:1930
msgid " - complete"
msgstr ""

#: ../satellite_tools/satsync.py:1984
msgid "Importing source package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1987
msgid "Importing package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1999
msgid "Importing:  "
msgstr ""

#: ../satellite_tools/satsync.py:2088
msgid ""
"Package Not Found in Cache, Clear the Cache "
"to                                  Regenerate it."
msgstr ""

#: ../satellite_tools/satsync.py:2096
msgid "Importing channel patches"
msgstr ""

#: ../satellite_tools/satsync.py:2103
#, python-format
msgid "Importing %s patches for channel %s."
msgstr ""

#. Incomplete configuration
#: ../satellite_tools/satsync.py:2563
msgid "ERROR: server.mount_point not set in the configuration file"
msgstr ""

#: ../satellite_tools/satsync.py:2569
#, python-format
msgid "ERROR: server.mount_point %s do not exist"
msgstr ""

#: ../satellite_tools/satsync.py:2579
#, python-format
msgid "ERROR: path under server.mount_point (%s)  do not exist"
msgstr ""

#: ../satellite_tools/satsync.py:2663
#, python-format
msgid "Commandline: %s"
msgstr ""

#: ../satellite_tools/satsync.py:2670
#, python-format
msgid ""
"DEBUG ONLY: max. batch-size for XML/database-import processing (1..%s).\"man "
"mgr-inter-sync\" for more information."
msgstr ""

#: ../satellite_tools/satsync.py:2678
msgid "alternative SSL CA Cert (fullpath to cert file)"
msgstr ""

#: ../satellite_tools/satsync.py:2684
msgid "process data for this channel only"
msgstr ""

#: ../satellite_tools/satsync.py:2690
msgid ""
"disk dump will be considered to be a full export; see \"man mgr-inter-sync\" "
"for more information."
msgstr ""

#: ../satellite_tools/satsync.py:2697
msgid "existing custom channels will also be synced (unless -c is used)"
msgstr ""

#: ../satellite_tools/satsync.py:2703
#, python-format
msgid ""
"override debug level set in /etc/rhn/rhn.conf (which is currently set at %s)."
msgstr ""

#: ../satellite_tools/satsync.py:2710
#, python-format
msgid "requested version of XML dump (default: %s)"
msgstr ""

#: ../satellite_tools/satsync.py:2716
msgid "e-mail a report of what was synced/imported"
msgstr ""

#: ../satellite_tools/satsync.py:2721
msgid "forcibly process all (not a diff of) patch metadata"
msgstr ""

#: ../satellite_tools/satsync.py:2726
msgid "Do not use an http proxy under any circumstances."
msgstr ""

#: ../satellite_tools/satsync.py:2731
msgid "alternative http proxy (hostname:port)"
msgstr ""

#: ../satellite_tools/satsync.py:2736
msgid "alternative http proxy username"
msgstr ""

#: ../satellite_tools/satsync.py:2741
msgid "alternative http proxy password"
msgstr ""

#: ../satellite_tools/satsync.py:2746
msgid "parent SUSE Manager to import content from"
msgstr ""

#: ../satellite_tools/satsync.py:2752
msgid "list all available channels and exit"
msgstr ""

#: ../satellite_tools/satsync.py:2757
msgid "help on all error codes mgr-inter-sync returns"
msgstr ""

#: ../satellite_tools/satsync.py:2763
msgid "source mount point for import - disk update only"
msgstr ""

#: ../satellite_tools/satsync.py:2765
msgid "do not process patch data"
msgstr ""

#: ../satellite_tools/satsync.py:2769
msgid "do not process kickstart data (provisioning only)"
msgstr ""

#: ../satellite_tools/satsync.py:2774
msgid "do not process full package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:2779
msgid "do not download, or process any RPMs"
msgstr ""

#: ../satellite_tools/satsync.py:2784
msgid "org to which the sync imports data. defaults to the admin account"
msgstr ""

#: ../satellite_tools/satsync.py:2790
#, fuzzy
msgid "print the configuration and exit"
msgstr "Kanał konfiguracji nie istnieje"

#: ../satellite_tools/satsync.py:2796
msgid "alternative server with which to connect (hostname)"
msgstr ""

#: ../satellite_tools/satsync.py:2801
msgid "synchronize to this step (man mgr-inter-sync for more info)"
msgstr ""

#: ../satellite_tools/satsync.py:2807
msgid "write complete data to tempfile before streaming to remainder of app"
msgstr ""

#: ../satellite_tools/satsync.py:2813
msgid "DEBUG ONLY: alternative path to digital system id"
msgstr ""

#: ../satellite_tools/satsync.py:2818
msgid "alternative email address(es) for sync output (--email option)"
msgstr ""

#: ../satellite_tools/satsync.py:2823
msgid "do not remove rpms when importing from local dump"
msgstr ""

#: ../satellite_tools/satsync.py:2829
msgid ""
"the fully qualified domain name of the master Satellite. Valid with --mount-"
"point only. Required if you want to import org data and channel permissions."
msgstr ""

#: ../satellite_tools/satsync.py:2843
#, python-format
msgid "ERROR: these arguments make no sense in this context (try --help): %s"
msgstr ""

#. An SQL error is fatal... crash and burn
#: ../satellite_tools/satsync.py:2856
#, python-format
msgid "ERROR: Can't connect to the database: %s"
msgstr ""

#: ../satellite_tools/satsync.py:2857
msgid "ERROR: Check if your database is running."
msgstr ""

#: ../satellite_tools/satsync.py:2906
#, python-format
msgid "ERROR: --debug-level takes an in integer value within the range %s."
msgstr ""

#: ../satellite_tools/satsync.py:2908
msgid "  0  - little logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2909
msgid "  1  - minimal logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2910
msgid "  2  - normal level of logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2911
msgid "  3  - lots of logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2912
msgid "  4+ - excessive logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2927
msgid "ERROR: The --master option is only valid with the --mount-point option"
msgstr ""

#: ../satellite_tools/satsync.py:2938
#, fuzzy, python-format
msgid "ERROR: Unable to lookup Org Id %s"
msgstr "Nie można odnaleźć serwera"

#: ../satellite_tools/satsync.py:2951
msgid ""
"WARNING: --list-channels option overrides any --step option. --step ignored."
msgstr ""

#: ../satellite_tools/satsync.py:2972
#, python-format
msgid ""
"ERROR: '%s' is not a valid step. See 'man mgr-inter-sync' for more detail."
msgstr ""

#: ../satellite_tools/satsync.py:3009
msgid ""
"ERROR: No channels currently imported; try mgr-inter-sync --list-channels; "
"then mgr-inter-sync -c chn0 -c chn1..."
msgstr ""

#: ../satellite_tools/satsync.py:3064 ../satellite_tools/satsync.py:3071
msgid "ERROR: --batch-size must have a value within the range: 1..50"
msgstr ""

#: ../satellite_tools/satsync.py:3081
#, python-format
msgid "ERROR: no such directory %s"
msgstr ""

#: ../satellite_tools/satsync.py:3087
msgid "Error Codes: Returned codes means:"
msgstr ""

#: ../satellite_tools/satsync.py:3088
msgid " -1  - Could not lock file or KeyboardInterrupt or SystemExit"
msgstr ""

#: ../satellite_tools/satsync.py:3089
msgid "  0  - User interrupted or intentional exit"
msgstr ""

#: ../satellite_tools/satsync.py:3090
msgid "  1  - attempting to run more than one instance of mgr-inter-sync."
msgstr ""

#: ../satellite_tools/satsync.py:3091
msgid "  2  - Unable to find synchronization tools."
msgstr ""

#: ../satellite_tools/satsync.py:3092
msgid "  3  - a general socket exception occurred"
msgstr ""

#: ../satellite_tools/satsync.py:3093
msgid "  4  - an SSL error occurred. Recheck your SSL settings."
msgstr ""

#: ../satellite_tools/satsync.py:3094
msgid "  5  - ISS error"
msgstr ""

#: ../satellite_tools/satsync.py:3095
msgid "  6  - unhandled exception occurred"
msgstr ""

#: ../satellite_tools/satsync.py:3096
msgid "  7  - unknown sync error"
msgstr ""

#: ../satellite_tools/satsync.py:3097
msgid "  8  - ERROR: must be root to execute"
msgstr ""

#: ../satellite_tools/satsync.py:3098
msgid "  9  - rpclib fault during synchronization init"
msgstr ""

#: ../satellite_tools/satsync.py:3099
msgid "  10 - synchronization init error"
msgstr ""

#: ../satellite_tools/satsync.py:3100
msgid "  11 - Error parsing XML stream"
msgstr ""

#: ../satellite_tools/satsync.py:3101
#, fuzzy
msgid "  12 - Channel do not exist"
msgstr "Podany kanał nie istnieje."

#: ../satellite_tools/satsync.py:3102
msgid "  13 - SQL error during importing package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:3103
msgid "  14 - SQL error during linking channel packages"
msgstr ""

#: ../satellite_tools/satsync.py:3104
msgid "  15 - SQL error during xml processing"
msgstr ""

#: ../satellite_tools/satsync.py:3105
msgid "  16 - server.mount_point not set in the configuration file"
msgstr ""

#: ../satellite_tools/satsync.py:3107
msgid ""
"  17 - SQL error during retrieving the channels already imported in the SUSE "
"Manager database"
msgstr ""

#: ../satellite_tools/satsync.py:3109
msgid "  18 - Wrong db connection string in rhn.conf"
msgstr ""

#: ../satellite_tools/satsync.py:3110
msgid "  19 - Bad arguments"
msgstr ""

#: ../satellite_tools/satsync.py:3111
msgid "  20 - Could not connect to db."
msgstr ""

#: ../satellite_tools/satsync.py:3112
msgid "  21 - Bad debug level"
msgstr ""

#: ../satellite_tools/satsync.py:3113
msgid "  22 - Not valid step"
msgstr ""

#: ../satellite_tools/satsync.py:3114
msgid "  24 - no such file"
msgstr ""

#: ../satellite_tools/satsync.py:3115
msgid "  25 - no such directory"
msgstr ""

#: ../satellite_tools/satsync.py:3116
msgid "  26 - mount_point does not exist"
msgstr ""

#: ../satellite_tools/satsync.py:3117
msgid "  27 - No such org"
msgstr ""

#: ../satellite_tools/satsync.py:3118
msgid "  28 - error: --master is only valid with --mount-point"
msgstr ""

#: ../satellite_tools/satsync.py:3127
#, python-format
msgid "ERROR: unknown dump version, try one of %s"
msgstr ""

#~ msgid "Crash information is invalid or incomplete"
#~ msgstr "Informacje o awarii są nieprawidłowe lub niepełne"

#~ msgid "Crash file information is invalid or incomplete"
#~ msgstr "Plik z informacjami o awarii jest nieprawidłowy lub niepełny"

#~ msgid "Error composing crash directory path"
#~ msgstr "Błąd podczas składania ścieżki do katalogu awarii"

#~ msgid "Error composing crash file path"
#~ msgstr "Błąd podczas składania ścieżki do pliku awarii"

#~ msgid "Invalid crash name"
#~ msgstr "Nieprawidłowa nazwa awarii"

#~ msgid "Crash reporting is disabled for this organization"
#~ msgstr "Zgłaszanie awarii jest wyłączone dla tej organizacji"

#~ msgid ""
#~ "\n"
#~ "If you have a registration number, please register with it first at "
#~ "http://www.redhat.com/apps/activate/ and then try again.\n"
#~ "\n"
#~ msgstr ""
#~ "\n"
#~ "Numer rejestracji należy najpierw zarejestrować pod adresem http://www."
#~ "redhat.com/apps/activate/ i spróbować ponownie.\n"
#~ "\n"

#~ msgid ""
#~ "\n"
#~ "Invalid Architecture and OS release combination (%s, %s).\n"
#~ "Your system has been registered, but will not receive updates\n"
#~ "because it is not subscribed to a channel. If you have not yet\n"
#~ "activated your product for service, please visit our website at:\n"
#~ "\n"
#~ "     http://www.redhat.com/apps/activate/\n"
#~ "\n"
#~ "...to activate your product."
#~ msgstr ""
#~ "\n"
#~ "Nieprawidłowe połączenie architektury i wydania systemu operacyjnego (%s, "
#~ "%s).\n"
#~ "System został zarejestrowany, ale nie będzie otrzymywał aktualizacji,\n"
#~ "ponieważ nie jest subskrybowany do kanału. Jeśli jeszcze nie\n"
#~ "aktywowano produktu do usługi, należy odwiedzić naszą stronę na:\n"
#~ " \n"
#~ "     http://www.redhat.com/apps/activate/\n"
#~ "\n"
#~ "…aby aktywować produkt."

#~ msgid "Red Hat Satellite Welcome Message"
#~ msgstr "Komunikat powitalny usługi Red Hat Satellite"
