# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Krishna Babu K <kkrothap@redhat.com>, 2010.
# Sree Ganesh <sthottem@redhat.com>, 2006, 2007.
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-03-28 14:30+0100\n"
"PO-Revision-Date: 2011-03-04 16:08+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Telugu (http://www.transifex.com/projects/p/fedora/language/"
"te/)\n"
"Language: te\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../server/apacheAuth.py:72
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr ""

#: ../server/apacheAuth.py:103
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr ""

#: ../server/apacheAuth.py:142
msgid "declined proxy authentication"
msgstr ""

#: ../server/apacheRequest.py:67
#, python-format
msgid "Invalid request received (%s)."
msgstr ""

#. Send the message as a fault.
#: ../server/apacheRequest.py:126
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""

#: ../server/apacheRequest.py:156
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""

#. pylint: disable-next=consider-using-f-string
#: ../server/apacheRequest.py:671
#, python-format
msgid "Invalid URI %s"
msgstr ""

#: ../server/handlers/app/packages.py:220
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""

#: ../server/handlers/sat/auth.py:46
msgid "ISS is disabled on this server."
msgstr ""

#: ../server/handlers/sat/auth.py:53
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr ""

#: ../server/handlers/xmlrpc/proxy.py:71
#, python-format
msgid ""
"SUSE Multi-Linux Manager Proxy service not enabled for server profile: \"%s\""
msgstr ""

#: ../server/handlers/xmlrpc/proxy.py:94
msgid "Invalid session key"
msgstr ""

#: ../server/handlers/xmlrpc/proxy.py:102
msgid "This server ID no longer exists"
msgstr ""

#: ../server/importlib/userAuth.py:109
msgid "You are not authorized to manage packages in the null org"
msgstr ""

#: ../server/importlib/userAuth.py:115
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr ""

#. ok, you're a regular user who doesn't manage any channels.
#. take a hike.
#: ../server/importlib/userAuth.py:132
msgid "You are not allowed to perform administrative tasks"
msgstr ""

#: ../server/importlib/userAuth.py:159
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr ""

#: ../server/importlib/userAuth.py:229
#, python-format
msgid ""
"\n"
"               %s Account has been deactivated on this server.\n"
"               Please contact your Org administrator for more help."
msgstr ""

#: ../server/rhnChannel.py:2217
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""

#: ../server/rhnChannel.py:2236
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr ""

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2550 ../server/rhnChannel.py:2569
msgid "System Registered but Inactive"
msgstr ""

#: ../server/rhnChannel.py:2552
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""

#: ../server/rhnChannel.py:2561
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""

#: ../server/rhnChannel.py:2571
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""

#. Invalid server certificate.
#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr ""

#: ../server/rhnHandler.py:76
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr ""

#: ../server/rhnPackage.py:52 ../server/rhnPackage.py:98
#: ../server/rhnPackage.py:118 ../server/rhnPackage.py:179
#, python-format
msgid "Invalid RPM package %s requested"
msgstr ""

#: ../server/rhnPackage.py:124
msgid "Package not found"
msgstr ""

#: ../server/rhnServer/server_class.py:103
#, python-format
msgid "Architecture `%s' is not supported"
msgstr ""

#: ../server/rhnServer/server_token.py:86
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr ""

#: ../server/rhnServer/server_token.py:89
msgid "Conflicting base channels"
msgstr ""

#: ../server/rhnServer/server_token.py:223
#, python-format
msgid "Failed to add server to group %s"
msgstr ""

#: ../server/rhnServer/server_token.py:574
#, python-format
msgid "Maximum usage count of %s reached"
msgstr ""

#: ../server/rhnServer/server_token.py:869
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""

#: ../server/rhnServer/server_token.py:946
#, python-format
msgid "Could not find token '%s'"
msgstr ""

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:979
msgid "Tokens from mismatching orgs"
msgstr ""

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:989
msgid "Kickstart session mismatch"
msgstr ""

#: ../server/rhnServer/server_token.py:1013
msgid "Stacking of re-registration tokens is not supported"
msgstr ""

#: ../server/rhnUser.py:327 ../server/rhnUser.py:330
msgid "Invalid username/password combination"
msgstr ""

#. nope, not reserved either
#: ../server/rhnUser.py:527
#, python-format
msgid "Username `%s' has not been reserved"
msgstr ""

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:533
msgid "E-mail address not specified"
msgstr ""

#: ../server/rhnUser.py:575
#, python-format
msgid "username should be at least %d characters"
msgstr ""

#: ../server/rhnUser.py:579
#, python-format
msgid "username should be less than %d characters"
msgstr ""

#: ../server/rhnUser.py:593
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr ""

#: ../server/rhnUser.py:614
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr ""

#: ../server/rhnUser.py:704
#, python-format
msgid "password must be at least %d characters"
msgstr ""

#: ../server/rhnUser.py:708
#, python-format
msgid "Password must be shorter than %d characters"
msgstr ""

#: ../server/rhnUser.py:724
#, python-format
msgid "password contains character `%s'"
msgstr ""

#: ../server/rhnUser.py:733
#, python-format
msgid "username should be at least %d characters long"
msgstr ""

#: ../server/rhnUser.py:744
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr ""

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:55
msgid "This does not appear to be a valid username."
msgstr ""

#: ../common/rhnException.py:56
msgid "Invalid username and password combination."
msgstr ""

#: ../common/rhnException.py:57
msgid "This login is already taken, or the password is incorrect."
msgstr ""

#: ../common/rhnException.py:58
msgid "Permission denied."
msgstr ""

#: ../common/rhnException.py:59
msgid "Object not found."
msgstr ""

#: ../common/rhnException.py:60
msgid "Invalid System Digital ID."
msgstr ""

#: ../common/rhnException.py:61
msgid "Invalid System Credentials."
msgstr ""

#: ../common/rhnException.py:62
msgid "Could not retrieve user data from database."
msgstr ""

#: ../common/rhnException.py:63
msgid "Valid username required."
msgstr ""

#: ../common/rhnException.py:64
msgid "Valid password required."
msgstr ""

#: ../common/rhnException.py:65
msgid "Minimum username length violation."
msgstr ""

#: ../common/rhnException.py:66
msgid "Minimum password length violation."
msgstr ""

#: ../common/rhnException.py:67
msgid "The username contains invalid characters."
msgstr ""

#: ../common/rhnException.py:68
msgid "File not found."
msgstr ""

#: ../common/rhnException.py:69
msgid "Architecture and OS version combination is not supported."
msgstr ""

#: ../common/rhnException.py:70
msgid "Could not retrieve system data from database."
msgstr ""

#: ../common/rhnException.py:71
msgid "Invalid arguments passed to function."
msgstr ""

#: ../common/rhnException.py:72
msgid "Unable to retrieve requested entry."
msgstr ""

#: ../common/rhnException.py:73
msgid "Could not update database entry."
msgstr ""

#: ../common/rhnException.py:74
msgid "Unsupported server architecture."
msgstr ""

#: ../common/rhnException.py:76
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running mgr_register as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:85
msgid "Record not available in the database."
msgstr ""

#: ../common/rhnException.py:86
msgid "Invalid value for entry."
msgstr ""

#: ../common/rhnException.py:88
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for SUSE Multi-Linux "
"Manager.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:95
msgid "Channel error"
msgstr ""

#: ../common/rhnException.py:96
msgid "Client session token is invalid."
msgstr ""

#: ../common/rhnException.py:97
msgid "Client session token has expired."
msgstr ""

#: ../common/rhnException.py:98
msgid "You are not authorized to retrieve the requested object."
msgstr ""

#: ../common/rhnException.py:99
msgid "Invalid action"
msgstr ""

#: ../common/rhnException.py:101
msgid "You are not allowed to perform administrative tasks on this system."
msgstr ""

#: ../common/rhnException.py:104
msgid "The system is already subscribed to the specified channel."
msgstr ""

#: ../common/rhnException.py:105
msgid "The system is not currently subscribed to the specified channel."
msgstr ""

#: ../common/rhnException.py:106
msgid "The specified channel does not exist."
msgstr ""

#: ../common/rhnException.py:107
msgid "Invalid channel version."
msgstr ""

#: ../common/rhnException.py:109
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""

#: ../common/rhnException.py:119
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""

#: ../common/rhnException.py:136
msgid "Invalid RPM header"
msgstr ""

#: ../common/rhnException.py:138
msgid ""
"\n"
"    This system is already registered as a Salt Minion. If you want to "
"register it as a traditional client\n"
"    please delete it first via the web UI or API and then register it using "
"the traditional tools.\n"
"    "
msgstr ""

#. For the uploading tools
#: ../common/rhnException.py:144
msgid "Invalid information uploaded to the server"
msgstr ""

#: ../common/rhnException.py:145
msgid "Error uploading network interfaces configuration."
msgstr ""

#: ../common/rhnException.py:147
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""

#: ../common/rhnException.py:154
msgid ""
"\n"
"     The --force mgrpush option is disabled on this server.\n"
"     Please contact your SUSE Multi-Linux Manager administrator for more "
"help.\n"
"     "
msgstr ""

#: ../common/rhnException.py:161
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""

#: ../common/rhnException.py:166
msgid "Too many systems registered using this registration token"
msgstr ""

#: ../common/rhnException.py:167
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr ""

#: ../common/rhnException.py:168
msgid "Conflicting activation tokens"
msgstr ""

#: ../common/rhnException.py:171
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:176
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""

#: ../common/rhnException.py:182
msgid "You can not unsubscribe from base channel."
msgstr ""

#: ../common/rhnException.py:183
msgid "SUSE Multi-Linux Manager or Proxy channel can not be subscribed."
msgstr ""

#. 80-90: server group errors
#: ../common/rhnException.py:185
msgid "There was an error while trying to join the system to its groups"
msgstr ""

#. 90-100: entitlement errors
#: ../common/rhnException.py:187
msgid "Unable to entitle system"
msgstr ""

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:189
msgid "Maximum e-mail length violation."
msgstr ""

#: ../common/rhnException.py:190
msgid "This system has been previously registered."
msgstr ""

#: ../common/rhnException.py:191
msgid "Invalid username"
msgstr ""

#. 140-159 applet errors
#: ../common/rhnException.py:193
msgid "Unable to look up server"
msgstr ""

#. 160-179: OSAD errors
#: ../common/rhnException.py:195
msgid "Required argument is missing"
msgstr ""

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:197
msgid "No entitlement information tied to hardware"
msgstr ""

#: ../common/rhnException.py:198
msgid "Installation number is not entitling"
msgstr ""

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:200
msgid "Maximum username length violation"
msgstr ""

#: ../common/rhnException.py:201
msgid "Maximum password length violation"
msgstr ""

#: ../common/rhnException.py:202
msgid "This user has read only API access. Action denied."
msgstr ""

#: ../common/rhnException.py:203
msgid "System Name cannot be less than 1 character"
msgstr ""

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:206
msgid "SUSE Multi-Linux Manager Proxy error."
msgstr ""

#: ../common/rhnException.py:207
msgid "SUSE Multi-Linux Manager Proxy unable to login."
msgstr ""

#: ../common/rhnException.py:210
msgid ""
"\n"
"     SUSE Multi-Linux Manager Proxy system ID does not match a Spacewalk "
"Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""

#: ../common/rhnException.py:215
msgid "SUSE Multi-Linux Manager Proxy session token is invalid."
msgstr ""

#: ../common/rhnException.py:216
msgid "SUSE Multi-Linux Manager Proxy session token has expired."
msgstr ""

#: ../common/rhnException.py:220
msgid ""
"\n"
"      user creation is not allowed via mgr_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""

#: ../common/rhnException.py:226
msgid ""
"\n"
"     This SUSE Multi-Linux Manager server is not allowed to use Inter Server "
"Sync on this server\n"
"     "
msgstr ""

#: ../common/rhnException.py:231
msgid ""
"\n"
"     Inter Server Sync is disabled on this SUSE Multi-Linux Manager Server.\n"
"     "
msgstr ""

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:236
msgid "Invalid datatype passed"
msgstr ""

#: ../common/rhnException.py:237
msgid "Unable to retrieve channel"
msgstr ""

#: ../common/rhnException.py:238
msgid "Unable to retrieve package"
msgstr ""

#: ../common/rhnException.py:239
msgid "Unable to retrieve erratum"
msgstr ""

#: ../common/rhnException.py:240
msgid "File is missing"
msgstr ""

#: ../common/rhnException.py:241
msgid "Function retrieval error"
msgstr ""

#: ../common/rhnException.py:242
msgid "Function execution error"
msgstr ""

#: ../common/rhnException.py:243
msgid "Missing version string"
msgstr ""

#: ../common/rhnException.py:244
msgid "Invalid version string"
msgstr ""

#: ../common/rhnException.py:245
msgid "Mismatching versions"
msgstr ""

#: ../common/rhnException.py:246
msgid "Invalid channel version"
msgstr ""

#: ../common/rhnException.py:247
msgid "No comps file for channel"
msgstr ""

#: ../common/rhnException.py:248
msgid "Unable to retrieve comps file"
msgstr ""

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:250
msgid "Configuration action missing"
msgstr ""

#: ../common/rhnException.py:251
msgid "File too large"
msgstr ""

#: ../common/rhnException.py:252
msgid "File contains binary data"
msgstr ""

#: ../common/rhnException.py:253
msgid "Configuration channel is not empty"
msgstr ""

#: ../common/rhnException.py:254
msgid "Permission error"
msgstr ""

#: ../common/rhnException.py:255
msgid "Content missing for configuration file"
msgstr ""

#: ../common/rhnException.py:256
msgid "Template delimiters not specified"
msgstr ""

#: ../common/rhnException.py:257
msgid "Configuration channel does not exist"
msgstr ""

#: ../common/rhnException.py:258
msgid "Configuration channel already exists"
msgstr ""

#: ../common/rhnException.py:259
msgid "File missing from configuration channel"
msgstr ""

#: ../common/rhnException.py:260
msgid "Different revision of this file is uploaded"
msgstr ""

#: ../common/rhnException.py:261
msgid "File already uploaded to configuration channel"
msgstr ""

#: ../common/rhnException.py:262
msgid "File size exceeds remaining quota space"
msgstr ""

#: ../common/rhnException.py:263
msgid "Full path of file must be specified"
msgstr ""

#: ../common/rhnException.py:264
msgid "Invalid revision number"
msgstr ""

#: ../common/rhnException.py:265
msgid "Cannot compare files of different file type"
msgstr ""

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:267
msgid "SCAP results file transfer is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:268
msgid "Error composing directory path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:269
msgid "Error composing file path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:270
msgid "Invalid content encoding"
msgstr ""

#: ../common/rhnException.py:317
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at scc.suse.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""

#: ../common/rhnException.py:368
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""

#: ../common/rhnException.py:370
#, python-format
msgid "Error Class Code: %s\n"
msgstr ""

#: ../common/rhnException.py:373
#, python-format
msgid "Error Class Info: %s\n"
msgstr ""

#: ../common/rhnException.py:375
#, python-format
msgid "Explanation: %s"
msgstr ""

#: ../common/rhnTB.py:220
#, python-format
msgid "ERROR: %s %s: %s"
msgstr ""

#: ../common/rhnTB.py:221
#, python-format
msgid "TRACEBACK: %s"
msgstr ""

#: ../satellite_tools/disk_dumper/iss.py:1634
#: ../satellite_tools/disk_dumper/iss.py:1640
#, python-format
msgid "format of %s should be at least YYYYMMDD.\n"
msgstr ""

#: ../satellite_tools/messages.py:28
#, python-format
msgid ""
"\n"
"ERROR: executing step %s. Error is:\n"
"%s\n"
msgstr ""

#: ../satellite_tools/messages.py:35
#, python-format
msgid ""
"\n"
"ERROR: there was a problem accessing the channel data from your temporary\n"
"       repository. Did you migrate all of the data from the channel ISOs\n"
"       do this directory? If so, please recheck the channels ISOs, ensure\n"
"       that you have them all, and then iteratively remount and repopulate\n"
"       the temporary repository (%s).\n"
msgstr ""

#: ../satellite_tools/messages.py:45
#, python-format
msgid ""
"\n"
"ERROR: there was a problem synchronizing the information.\n"
"       Error message: %s\n"
msgstr ""

#: ../satellite_tools/messages.py:52
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       Depending on the specific error details, please review your "
"configuration,\n"
"       basic network connectivity, and/or name resolution, and try again.\n"
"       Error message: %s\n"
msgstr ""

#: ../satellite_tools/messages.py:61
#, python-format
msgid ""
"\n"
"ERROR: a child-channel cannot be synced without its parent being synced as\n"
"       well. A parent needs to be either (a) previously synced or (b) "
"synced\n"
"       in tandem with the desired child-channel. Missing parents for this\n"
"       transaction:\n"
"       %s\n"
msgstr ""

#: ../satellite_tools/messages.py:71
#, python-format
msgid ""
"\n"
"ERROR: you are not entitled to sync a channel in this set of channels.\n"
"Please contact your SUSE Multi-Linux Manager contact\n"
"%s"
msgstr ""

#: ../satellite_tools/messages.py:77
#, python-format
msgid "  ERROR: not enough free space (%s KB) on device."
msgstr ""

#: ../satellite_tools/messages.py:79
#, python-format
msgid "    %3d/%s Fetch successful: %s (%s bytes)"
msgstr ""

#: ../satellite_tools/messages.py:80
#, python-format
msgid "    Extinct package:  %s"
msgstr ""

#: ../satellite_tools/messages.py:81
#, python-format
msgid "   Total size: %s"
msgstr ""

#: ../satellite_tools/messages.py:83
#, python-format
msgid "      Downloaded %s of %s. Estimated remaining time: %s"
msgstr ""

#: ../satellite_tools/messages.py:85
#, python-format
msgid "    Fetch unsuccessful: %s"
msgstr ""

#: ../satellite_tools/messages.py:86
#, python-format
msgid "   RPM fetch summary: %s"
msgstr ""

#: ../satellite_tools/messages.py:87
#, python-format
msgid "       success: %d"
msgstr ""

#: ../satellite_tools/messages.py:88
#, python-format
msgid "       failed:  %d"
msgstr ""

#: ../satellite_tools/messages.py:89
#, python-format
msgid "       extinct: %d"
msgstr ""

#: ../satellite_tools/messages.py:91
#, python-format
msgid "   Retrieving / parsing *relevant* package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:92
#, python-format
msgid "   Retrieving / parsing errata data: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:93
#, python-format
msgid "   Retrieving / parsing kickstart data: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:94
#, python-format
msgid "   Retrieving / parsing kickstart tree files: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:95
#, python-format
msgid "   Importing *relevant* package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:96
msgid "   * WARNING: this may be a slow process."
msgstr ""

#: ../satellite_tools/messages.py:97
msgid "Linking packages to channels"
msgstr ""

#: ../satellite_tools/messages.py:98
#, python-format
msgid "   Importing *relevant* errata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:99
msgid "   No new kickstartable tree to import"
msgstr ""

#: ../satellite_tools/messages.py:100
#, python-format
msgid "Importing kickstartable trees (%d)"
msgstr ""

#: ../satellite_tools/messages.py:101
#, python-format
msgid "Imported kickstartable trees (%d)"
msgstr ""

#: ../satellite_tools/reposync.py:138 ../satellite_tools/satsync.py:519
msgid "+++ sending log as an email +++"
msgstr ""

#: ../satellite_tools/reposync.py:141
#, python-format
msgid "%s sync. report from %s"
msgstr ""

#: ../satellite_tools/reposync.py:151 ../satellite_tools/satsync.py:533
msgid "+++ email requested, but there is nothing to send +++"
msgstr ""

#: ../satellite_tools/satsync.py:305
#, python-format
msgid "No handler for step %s"
msgstr ""

#. Try one more time - this time it should be faster since
#. everything should be cached
#: ../satellite_tools/satsync.py:317
msgid "Environment changed, trying again..."
msgstr ""

#: ../satellite_tools/satsync.py:326
msgid "ERROR: Encountered IntegrityError: \n"
msgstr ""

#: ../satellite_tools/satsync.py:335
msgid "Repeated failures"
msgstr ""

#: ../satellite_tools/satsync.py:344
#, python-format
msgid ""
"    Import complete:\n"
"        Begin time: %s\n"
"        End time:   %s\n"
"        Elapsed:    %s\n"
"          "
msgstr ""

#: ../satellite_tools/satsync.py:370
msgid "hours"
msgstr ""

#: ../satellite_tools/satsync.py:370
msgid "minutes"
msgstr ""

#: ../satellite_tools/satsync.py:370
msgid "seconds"
msgstr ""

#: ../satellite_tools/satsync.py:423
msgid ""
"ERROR: The dump is missing package data, use --no-rpms to skip this step or "
"fix the content to include package data."
msgstr ""

#: ../satellite_tools/satsync.py:479
msgid "The SUSE Multi-Linux Manager master does not support syncing orgs data."
msgstr ""

#: ../satellite_tools/satsync.py:481
msgid "Skipping..."
msgstr ""

#: ../satellite_tools/satsync.py:523
#, python-format
msgid "SUSE Multi-Linux Manager Inter Server sync. report from %s"
msgstr ""

#: ../satellite_tools/satsync.py:611
msgid " - file-system synchronization"
msgstr ""

#: ../satellite_tools/satsync.py:627 ../satellite_tools/satsync.py:643
msgid " - live synchronization"
msgstr ""

#: ../satellite_tools/satsync.py:631
#, python-brace-format
msgid ""
"ERROR: Live content synchronizing with RHN Classic Hosted is no longer "
"supported.\n"
"Please use the cdn-sync command instead unless you are attempting to sync "
"from another {PRODUCT_NAME} via Inter-Server-Sync (ISS), or from local "
"content on disk via Channel Dump ISOs."
msgstr ""

#: ../satellite_tools/satsync.py:644
#, python-format
msgid "   url: %s"
msgstr ""

#: ../satellite_tools/satsync.py:645
#, python-format
msgid "   debug/output level: %s"
msgstr ""

#: ../satellite_tools/satsync.py:661
msgid "ERROR: this server must be registered with SUSE Multi-Linux Manager."
msgstr ""

#: ../satellite_tools/satsync.py:687
#, python-format
msgid "Retrieving / parsing %s data"
msgstr ""

#: ../satellite_tools/satsync.py:697 ../satellite_tools/satsync.py:716
msgid "*** SYSTEM INTERRUPT CALLED ***"
msgstr ""

#: ../satellite_tools/satsync.py:710
msgid "ERROR: fatal parser exception occurred "
msgstr ""

#: ../satellite_tools/satsync.py:711
#, python-format
msgid "(line: %s, col: %s msg: %s)"
msgstr ""

#: ../satellite_tools/satsync.py:714
#, python-format
msgid "ERROR: parser exception occurred: %s"
msgstr ""

#: ../satellite_tools/satsync.py:719
msgid "ERROR: exception (during parse) occurred: "
msgstr ""

#: ../satellite_tools/satsync.py:723
#, python-format
msgid ""
"   Encountered some errors with %s data (see logs (%s) for more information)"
msgstr ""

#: ../satellite_tools/satsync.py:732
#, python-format
msgid "   Encountered some errors with %s data:"
msgstr ""

#: ../satellite_tools/satsync.py:733
#, python-format
msgid "   ------- %s PARSE/IMPORT ERROR -------"
msgstr ""

#: ../satellite_tools/satsync.py:736
msgid "   ---------------------------------------"
msgstr ""

#: ../satellite_tools/satsync.py:742
#, python-format
msgid "%s data complete"
msgstr ""

#: ../satellite_tools/satsync.py:821
msgid "Retrieving / parsing channel data"
msgstr ""

#: ../satellite_tools/satsync.py:896
msgid "Channel data complete"
msgstr ""

#: ../satellite_tools/satsync.py:915
#, python-format
msgid "%10s import from %s"
msgstr ""

#: ../satellite_tools/satsync.py:917
#, python-format
msgid "%10s import from %s - %s"
msgstr ""

#: ../satellite_tools/satsync.py:923
#, python-format
msgid "%10s"
msgstr ""

#: ../satellite_tools/satsync.py:931
msgid "p"
msgstr ""

#: ../satellite_tools/satsync.py:933
msgid "."
msgstr ""

#: ../satellite_tools/satsync.py:949
msgid "   p = previously imported/synced channel"
msgstr ""

#: ../satellite_tools/satsync.py:950
msgid "   . = channel not yet imported/synced"
msgstr ""

#: ../satellite_tools/satsync.py:956
msgid "   e = channel no longer supported (end-of-service)"
msgstr ""

#: ../satellite_tools/satsync.py:958
msgid "   ? = channel label invalid --- typo?"
msgstr ""

#: ../satellite_tools/satsync.py:962
#, python-format
msgid "   %s:"
msgstr ""

#: ../satellite_tools/satsync.py:963
#, python-format
msgid "      %s %-40s %4s %s"
msgstr ""

#: ../satellite_tools/satsync.py:964
msgid "base-channels"
msgstr ""

#: ../satellite_tools/satsync.py:978 ../satellite_tools/satsync.py:2004
msgid "NONE RELEVANT"
msgstr ""

#: ../satellite_tools/satsync.py:1003
msgid "end-of-service"
msgstr ""

#: ../satellite_tools/satsync.py:1004
msgid "e"
msgstr ""

#: ../satellite_tools/satsync.py:1010
msgid "   typos:"
msgstr ""

#: ../satellite_tools/satsync.py:1011
msgid "?"
msgstr ""

#: ../satellite_tools/satsync.py:1028
#, python-format
msgid "XXX: imported channels: %s"
msgstr ""

#: ../satellite_tools/satsync.py:1029
#, python-format
msgid "XXX:   cached channels: %s"
msgstr ""

#: ../satellite_tools/satsync.py:1034
msgid "XXX: list channels called"
msgstr ""

#: ../satellite_tools/satsync.py:1058
msgid "ERROR: these channels either do not exist or are not available:"
msgstr ""

#: ../satellite_tools/satsync.py:1065
#, python-format
msgid "       (to see a list of channel labels: %s --list-channels)"
msgstr ""

#: ../satellite_tools/satsync.py:1122
#, python-format
msgid "   Retrieving / parsing short package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/satsync.py:1211
#, python-format
msgid "Diffing package metadata (what's missing locally?): %s"
msgstr ""

#: ../satellite_tools/satsync.py:1221 ../satellite_tools/satsync.py:1602
msgid "Diffing:    "
msgstr ""

#: ../satellite_tools/satsync.py:1241
msgid "ERROR: incremental dump skipped"
msgstr ""

#: ../satellite_tools/satsync.py:1388
msgid "Downloading rpm packages"
msgstr ""

#: ../satellite_tools/satsync.py:1397
#, python-format
msgid "   Fetching any missing RPMs: %s (%s)"
msgstr ""

#: ../satellite_tools/satsync.py:1398 ../satellite_tools/satsync.py:1483
msgid "NONE MISSING"
msgstr ""

#: ../satellite_tools/satsync.py:1408
msgid "Processing rpm packages complete"
msgstr ""

#: ../satellite_tools/satsync.py:1438
msgid "Downloading package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1472
msgid "Downloading srpm packages"
msgstr ""

#: ../satellite_tools/satsync.py:1482
#, python-format
msgid "   Fetching any missing SRPMs: %s (%s)"
msgstr ""

#: ../satellite_tools/satsync.py:1592
#, python-format
msgid "Diffing source package metadata (what's missing locally?): %s"
msgstr ""

#: ../satellite_tools/satsync.py:1611
msgid "Downloading source package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1697 ../satellite_tools/satsync.py:2519
#, python-format
msgid "Unable to save file %s: %s"
msgstr ""

#. for
#. Retried a number of times and it still failed; log the
#. file as being failed and move on
#: ../satellite_tools/satsync.py:1703
#, python-format
msgid "Failed to fetch file %s"
msgstr ""

#: ../satellite_tools/satsync.py:1708
msgid "Downloading kickstartable trees metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1726
msgid "Downloading kickstartable trees files"
msgstr ""

#: ../satellite_tools/satsync.py:1883
#, python-format
msgid "Grabbing all patches for channel %s"
msgstr ""

#: ../satellite_tools/satsync.py:1937
msgid "Downloading patch data"
msgstr ""

#: ../satellite_tools/satsync.py:1939
msgid "Forcing download of all patch data for requested channels."
msgstr ""

#: ../satellite_tools/satsync.py:1957
msgid "Downloading patch data complete"
msgstr ""

#: ../satellite_tools/satsync.py:1966 ../satellite_tools/satsync.py:1997
msgid "Downloading:"
msgstr ""

#: ../satellite_tools/satsync.py:1972
msgid " - complete"
msgstr ""

#: ../satellite_tools/satsync.py:2026
msgid "Importing source package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:2029
msgid "Importing package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:2041
msgid "Importing:  "
msgstr ""

#: ../satellite_tools/satsync.py:2130
msgid ""
"Package Not Found in Cache, Clear the Cache "
"to                                  Regenerate it."
msgstr ""

#: ../satellite_tools/satsync.py:2138
msgid "Importing channel patches"
msgstr ""

#: ../satellite_tools/satsync.py:2145
#, python-format
msgid "Importing %s patches for channel %s."
msgstr ""

#. Incomplete configuration
#: ../satellite_tools/satsync.py:2605
msgid "ERROR: server.mount_point not set in the configuration file"
msgstr ""

#: ../satellite_tools/satsync.py:2611
#, python-format
msgid "ERROR: server.mount_point %s do not exist"
msgstr ""

#: ../satellite_tools/satsync.py:2621
#, python-format
msgid "ERROR: path under server.mount_point (%s)  do not exist"
msgstr ""

#: ../satellite_tools/satsync.py:2705
#, python-format
msgid "Commandline: %s"
msgstr ""

#: ../satellite_tools/satsync.py:2712
#, python-format
msgid ""
"DEBUG ONLY: max. batch-size for XML/database-import processing (1..%s).\"man "
"mgr-inter-sync\" for more information."
msgstr ""

#: ../satellite_tools/satsync.py:2720
msgid "alternative SSL CA Cert (fullpath to cert file)"
msgstr ""

#: ../satellite_tools/satsync.py:2726
msgid "process data for this channel only"
msgstr ""

#: ../satellite_tools/satsync.py:2732
msgid ""
"disk dump will be considered to be a full export; see \"man mgr-inter-sync\" "
"for more information."
msgstr ""

#: ../satellite_tools/satsync.py:2739
msgid "existing custom channels will also be synced (unless -c is used)"
msgstr ""

#: ../satellite_tools/satsync.py:2745
#, python-format
msgid ""
"override debug level set in /etc/rhn/rhn.conf (which is currently set at %s)."
msgstr ""

#: ../satellite_tools/satsync.py:2752
#, python-format
msgid "requested version of XML dump (default: %s)"
msgstr ""

#: ../satellite_tools/satsync.py:2758
msgid "e-mail a report of what was synced/imported"
msgstr ""

#: ../satellite_tools/satsync.py:2763
msgid "forcibly process all (not a diff of) patch metadata"
msgstr ""

#: ../satellite_tools/satsync.py:2768
msgid "Do not use an http proxy under any circumstances."
msgstr ""

#: ../satellite_tools/satsync.py:2773
msgid "alternative http proxy (hostname:port)"
msgstr ""

#: ../satellite_tools/satsync.py:2778
msgid "alternative http proxy username"
msgstr ""

#: ../satellite_tools/satsync.py:2783
msgid "alternative http proxy password"
msgstr ""

#: ../satellite_tools/satsync.py:2788
msgid "parent SUSE Multi-Linux Manager to import content from"
msgstr ""

#: ../satellite_tools/satsync.py:2794
msgid "list all available channels and exit"
msgstr ""

#: ../satellite_tools/satsync.py:2799
msgid "help on all error codes mgr-inter-sync returns"
msgstr ""

#: ../satellite_tools/satsync.py:2805
msgid "source mount point for import - disk update only"
msgstr ""

#: ../satellite_tools/satsync.py:2807
msgid "do not process patch data"
msgstr ""

#: ../satellite_tools/satsync.py:2811
msgid "do not process kickstart data (provisioning only)"
msgstr ""

#: ../satellite_tools/satsync.py:2816
msgid "do not process full package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:2821
msgid "do not download, or process any RPMs"
msgstr ""

#: ../satellite_tools/satsync.py:2826
msgid "org to which the sync imports data. defaults to the admin account"
msgstr ""

#: ../satellite_tools/satsync.py:2832
msgid "print the configuration and exit"
msgstr ""

#: ../satellite_tools/satsync.py:2838
msgid "alternative server with which to connect (hostname)"
msgstr ""

#: ../satellite_tools/satsync.py:2843
msgid "synchronize to this step (man mgr-inter-sync for more info)"
msgstr ""

#: ../satellite_tools/satsync.py:2849
msgid "write complete data to tempfile before streaming to remainder of app"
msgstr ""

#: ../satellite_tools/satsync.py:2855
msgid "DEBUG ONLY: alternative path to digital system id"
msgstr ""

#: ../satellite_tools/satsync.py:2860
msgid "alternative email address(es) for sync output (--email option)"
msgstr ""

#: ../satellite_tools/satsync.py:2865
msgid "do not remove rpms when importing from local dump"
msgstr ""

#: ../satellite_tools/satsync.py:2871
msgid ""
"the fully qualified domain name of the master Satellite. Valid with --mount-"
"point only. Required if you want to import org data and channel permissions."
msgstr ""

#: ../satellite_tools/satsync.py:2885
#, python-format
msgid "ERROR: these arguments make no sense in this context (try --help): %s"
msgstr ""

#. An SQL error is fatal... crash and burn
#: ../satellite_tools/satsync.py:2898
#, python-format
msgid "ERROR: Can't connect to the database: %s"
msgstr ""

#: ../satellite_tools/satsync.py:2899
msgid "ERROR: Check if your database is running."
msgstr ""

#: ../satellite_tools/satsync.py:2948
#, python-format
msgid "ERROR: --debug-level takes an in integer value within the range %s."
msgstr ""

#: ../satellite_tools/satsync.py:2950
msgid "  0  - little logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2951
msgid "  1  - minimal logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2952
msgid "  2  - normal level of logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2953
msgid "  3  - lots of logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2954
msgid "  4+ - excessive logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2969
msgid "ERROR: The --master option is only valid with the --mount-point option"
msgstr ""

#: ../satellite_tools/satsync.py:2980
#, python-format
msgid "ERROR: Unable to lookup Org Id %s"
msgstr ""

#: ../satellite_tools/satsync.py:2993
msgid ""
"WARNING: --list-channels option overrides any --step option. --step ignored."
msgstr ""

#: ../satellite_tools/satsync.py:3014
#, python-format
msgid ""
"ERROR: '%s' is not a valid step. See 'man mgr-inter-sync' for more detail."
msgstr ""

#: ../satellite_tools/satsync.py:3051
msgid ""
"ERROR: No channels currently imported; try mgr-inter-sync --list-channels; "
"then mgr-inter-sync -c chn0 -c chn1..."
msgstr ""

#: ../satellite_tools/satsync.py:3106 ../satellite_tools/satsync.py:3113
msgid "ERROR: --batch-size must have a value within the range: 1..50"
msgstr ""

#: ../satellite_tools/satsync.py:3123
#, python-format
msgid "ERROR: no such directory %s"
msgstr ""

#: ../satellite_tools/satsync.py:3129
msgid "Error Codes: Returned codes means:"
msgstr ""

#: ../satellite_tools/satsync.py:3130
msgid " -1  - Could not lock file or KeyboardInterrupt or SystemExit"
msgstr ""

#: ../satellite_tools/satsync.py:3131
msgid "  0  - User interrupted or intentional exit"
msgstr ""

#: ../satellite_tools/satsync.py:3132
msgid "  1  - attempting to run more than one instance of mgr-inter-sync."
msgstr ""

#: ../satellite_tools/satsync.py:3133
msgid "  2  - Unable to find synchronization tools."
msgstr ""

#: ../satellite_tools/satsync.py:3134
msgid "  3  - a general socket exception occurred"
msgstr ""

#: ../satellite_tools/satsync.py:3135
msgid "  4  - an SSL error occurred. Recheck your SSL settings."
msgstr ""

#: ../satellite_tools/satsync.py:3136
msgid "  5  - ISS error"
msgstr ""

#: ../satellite_tools/satsync.py:3137
msgid "  6  - unhandled exception occurred"
msgstr ""

#: ../satellite_tools/satsync.py:3138
msgid "  7  - unknown sync error"
msgstr ""

#: ../satellite_tools/satsync.py:3139
msgid "  8  - ERROR: must be root to execute"
msgstr ""

#: ../satellite_tools/satsync.py:3140
msgid "  9  - rpclib fault during synchronization init"
msgstr ""

#: ../satellite_tools/satsync.py:3141
msgid "  10 - synchronization init error"
msgstr ""

#: ../satellite_tools/satsync.py:3142
msgid "  11 - Error parsing XML stream"
msgstr ""

#: ../satellite_tools/satsync.py:3143
msgid "  12 - Channel do not exist"
msgstr ""

#: ../satellite_tools/satsync.py:3144
msgid "  13 - SQL error during importing package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:3145
msgid "  14 - SQL error during linking channel packages"
msgstr ""

#: ../satellite_tools/satsync.py:3146
msgid "  15 - SQL error during xml processing"
msgstr ""

#: ../satellite_tools/satsync.py:3147
msgid "  16 - server.mount_point not set in the configuration file"
msgstr ""

#: ../satellite_tools/satsync.py:3149
msgid ""
"  17 - SQL error during retrieving the channels already imported in the SUSE "
"Multi-Linux Manager database"
msgstr ""

#: ../satellite_tools/satsync.py:3151
msgid "  18 - Wrong db connection string in rhn.conf"
msgstr ""

#: ../satellite_tools/satsync.py:3152
msgid "  19 - Bad arguments"
msgstr ""

#: ../satellite_tools/satsync.py:3153
msgid "  20 - Could not connect to db."
msgstr ""

#: ../satellite_tools/satsync.py:3154
msgid "  21 - Bad debug level"
msgstr ""

#: ../satellite_tools/satsync.py:3155
msgid "  22 - Not valid step"
msgstr ""

#: ../satellite_tools/satsync.py:3156
msgid "  24 - no such file"
msgstr ""

#: ../satellite_tools/satsync.py:3157
msgid "  25 - no such directory"
msgstr ""

#: ../satellite_tools/satsync.py:3158
msgid "  26 - mount_point does not exist"
msgstr ""

#: ../satellite_tools/satsync.py:3159
msgid "  27 - No such org"
msgstr ""

#: ../satellite_tools/satsync.py:3160
msgid "  28 - error: --master is only valid with --mount-point"
msgstr ""

#: ../satellite_tools/satsync.py:3169
#, python-format
msgid "ERROR: unknown dump version, try one of %s"
msgstr ""
