# Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>, 2015. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2011-12-21 12:18+0100\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2015-09-07 06:18-0400\n"
"Last-Translator: Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>\n"
"Language-Team: Catalan\n"
"Language: ca\n"
"X-Generator: Zanata 3.7.1\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"

#: ../server/rhnPackage.py:45 ../server/rhnPackage.py:80
#: ../server/rhnPackage.py:99 ../server/rhnPackage.py:181
#: ../server/rhnPackage.py:205 ../server/rhnPackage.py:287
#, python-format
msgid "Invalid RPM package %s requested"
msgstr ""

#: ../server/rhnPackage.py:104 ../server/rhnPackage.py:293
msgid "Package not found"
msgstr "Paquet no trobat"

#: ../server/apacheAuth.py:58
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "testimoni incomplet del servidor intermediari: %s"

#: ../server/apacheAuth.py:74
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr ""

#: ../server/apacheAuth.py:105
msgid "declined proxy authentication"
msgstr ""

#: ../server/apacheRequest.py:50
#, python-format
msgid "Invalid request received (%s)."
msgstr "Es va rebre una petició no vàlida (%s)."

#: ../server/apacheRequest.py:107
#, python-format
msgid "IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr "MISSATGE IMPORTANT SEGÜENT:\n"
"%s"

#: ../server/apacheRequest.py:132
#, python-format
msgid "While running '%s': caught\n"
"%s : %s\n"
msgstr "Mentre s'executava '%s': es va capturar\n"
"%s : %s\n"

#: ../server/apacheRequest.py:558
#, python-format
msgid "Invalid URI %s"
msgstr "L'URI %s no és vàlid"

#: ../server/rhnServer/server_token.py:80
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "El testimoni `%s' té més d'un canal base assignat"

#: ../server/rhnServer/server_token.py:82
msgid "Conflicting base channels"
msgstr ""

#: ../server/rhnServer/server_token.py:206
#, python-format
msgid "Failed to add server to group %s"
msgstr ""

#: ../server/rhnServer/server_token.py:513
#, python-format
msgid "Maximum usage count of %s reached"
msgstr ""

#: ../server/rhnServer/server_token.py:645
#, python-format
msgid "Registration failed: RHN Software service entitlements exhausted: %s"
msgstr ""

#: ../server/rhnServer/server_token.py:761
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""

#: ../server/rhnServer/server_token.py:839
#, python-format
msgid "Could not find token '%s'"
msgstr "No es va poder tovar el testimoni '%s'"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:871
msgid "Tokens from mismatching orgs"
msgstr ""

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:881
msgid "Kickstart session mismatch"
msgstr ""

#: ../server/rhnServer/server_token.py:901
msgid "Stacking of re-registration tokens is not supported"
msgstr ""

#: ../server/rhnServer/server_class.py:95
#, python-format
msgid "Architecture `%s' is not supported"
msgstr ""

#: ../server/rhnUser.py:383 ../server/rhnUser.py:386
msgid "Invalid username/password combination"
msgstr ""

#. nope, not reserved either
#: ../server/rhnUser.py:539
#, python-format
msgid "Username `%s' has not been reserved"
msgstr ""

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:545
msgid "E-mail address not specified"
msgstr ""

#. wrong organization
#. Invalid org password
#: ../server/rhnUser.py:600 ../server/rhnUser.py:604
msgid "Invalid Organization Credentials"
msgstr ""

#: ../server/rhnUser.py:610
#, python-format
msgid "User `%s' not a member of organization %s"
msgstr ""

#: ../server/rhnUser.py:638
#, python-format
msgid "username should be at least %d characters"
msgstr ""

#: ../server/rhnUser.py:641
#, python-format
msgid "username should be less than %d characters"
msgstr ""

#: ../server/rhnUser.py:652
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr ""

#: ../server/rhnUser.py:670
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr ""

#: ../server/rhnUser.py:743
#, python-format
msgid "password must be at least %d characters"
msgstr ""

#: ../server/rhnUser.py:746
#, python-format
msgid "Password must be shorter than %d characters"
msgstr ""

#: ../server/rhnUser.py:764
#, python-format
msgid "password contains character `%s'"
msgstr ""

#: ../server/rhnUser.py:771
#, python-format
msgid "username should be at least %d characters long"
msgstr ""

#: ../server/rhnUser.py:782
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr ""

#: ../server/rhnChannel.py:1707
#, python-format
msgid ""
"Your account does not have access to any channels matching (release="
"'%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""

#: ../server/rhnChannel.py:1717
msgid ""
"\n"
"If you have a registration number, please register with it first at http://"
"www.redhat.com/apps/activate/ and then try again.\n"
"\n"
msgstr ""

#: ../server/rhnChannel.py:1727
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr ""

#. Various messages that can be reused
#. 
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:1974 ../server/rhnChannel.py:1985
#: ../server/rhnChannel.py:2000 ../server/rhnChannel.py:2008
msgid "System Registered but Inactive"
msgstr ""

#: ../server/rhnChannel.py:1975
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates \n"
"because it is not subscribed to a channel. If you have not yet\n"
"activated your product for service, please visit our website at:\n"
"  \n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...to activate your product."
msgstr ""

#: ../server/rhnChannel.py:1986
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""

#: ../server/rhnChannel.py:1993
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""

#: ../server/rhnChannel.py:2001
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""

#: ../server/rhnChannel.py:2009
msgid ""
"\n"
"  This system has been successfully registered, but the channel "
"subscriptions\n"
"  were exhausted\n"
msgstr ""

#: ../server/rhnHandler.py:61
msgid "Please run rhn_register as root on this client"
msgstr ""

#: ../server/rhnHandler.py:78
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr ""

#: ../server/handlers/applet/applet.py:68
msgid "Your system was not found in the RHN database"
msgstr ""

#: ../server/handlers/sat/auth.py:45
msgid "ISS is disabled on this satellite."
msgstr "ISS està inhabilitat en aquest satellite."

#: ../server/handlers/sat/auth.py:57
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "El servidor \"%s\" no està habilitat per a l'ISS."

#: ../server/handlers/xmlrpc/proxy.py:60
#, python-format
msgid "RHN Proxy service not enabled for server profile: \"%s\""
msgstr ""

#: ../server/handlers/xmlrpc/proxy.py:80
msgid "Invalid session key"
msgstr "la clau de sessió no és vàlida"

#: ../server/handlers/xmlrpc/proxy.py:88
msgid "This server ID no longer exists"
msgstr "Aquest id. de servidor ja no existeix"

#: ../server/handlers/xmlrpc/registration.py:183
msgid "Required data missing"
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:187
msgid "Required members missing"
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:196
msgid "Attempt to register a system to an invalid username"
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:204
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:819
msgid "Invalid system release version requested"
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:1005
msgid "Red Hat Network Welcome Message"
msgstr "Missatge de benvinguda a la Red Hat Network"

#: ../server/handlers/xmlrpc/registration.py:1015
msgid "Red Hat Network Privacy Statement"
msgstr "Declaració de privacitat de la Red Hat Network"

#: ../server/handlers/xmlrpc/registration.py:1036
msgid "Expected a dictionary as a product argument"
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:1068
#: ../server/handlers/xmlrpc/registration.py:1126
#, python-format
msgid "Not a valid Country: %s"
msgstr "No és un país vàlid: %s"

#: ../server/handlers/xmlrpc/registration.py:1349
#, python-format
msgid "Insufficient subscription permissions for release, arch (%s, %s)"
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:1366
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr ""

#: ../server/handlers/xmlrpc/errata.py:59
#, python-format
msgid "Expected a package name, not: %s"
msgstr ""

#: ../server/handlers/xmlrpc/errata.py:109
#, python-format
msgid "Expected a package, not: %s"
msgstr "S'esperava un paquet, no: %s"

#: ../server/handlers/xmlrpc/queue.py:399
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr ""

#: ../server/handlers/xmlrpc/queue.py:424
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "L'acció %s no pertany al servidor %s"

#: ../server/handlers/xmlrpc/up2date.py:232
#, python-format
msgid "Invalid value %s (type %s)"
msgstr "Valor no vàlid %s (tipus %s)"

#: ../server/handlers/xmlrpc/up2date.py:260
#, python-format
msgid "Unable to retrieve package header %s"
msgstr ""

#: ../server/handlers/xmlrpc/up2date.py:407
#, python-format
msgid "Invalid value %s (%s)"
msgstr "Valor no vàlid %s (%s)"

#: ../server/handlers/xmlrpc/up2date.py:479
#, python-format
msgid "Invalid value for %s in package tuple: %s (%s)"
msgstr "Valor no vàlid per %s a la tupla del paquet: %s (%s)"

#: ../server/handlers/xmlrpc/up2date.py:491
#, python-format
msgid "Invalid package parameter %s (%s)"
msgstr "El paràmetre del paquet no és vàlid %s (%s)"

#: ../server/importlib/userAuth.py:108 ../server/importlib/userAuth.py:112
msgid "You are not authorized to manage packages in the null org"
msgstr ""
"No esteu autoritzat per gestionar els paquets de l'organització nul·la"

#: ../server/importlib/userAuth.py:119
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "No esteu autoritzat per gestionar els paquets de l'organització %s"

#: ../server/importlib/userAuth.py:137
msgid "You are not allowed to perform administrative tasks"
msgstr "No esteu autoritzat per realitzar les tasques administratives"

#: ../server/importlib/userAuth.py:164
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr ""
"No esteu autoritzat per gestionar el canal %s, o no exeisteix aquest canal"

#: ../common/rhnTB.py:199
#, python-format
msgid "ERROR: %s %s: %s"
msgstr "ERROR: %s %s: %s"

#: ../common/rhnTB.py:201
#, python-format
msgid "TRACEBACK: %s"
msgstr ""

#: ../common/rhnException.py:42
msgid "Outage mode"
msgstr ""

#. 0-999: RHN client/client-like interaction errors:
#: ../common/rhnException.py:44
msgid "This does not appear to be a valid username."
msgstr ""

#: ../common/rhnException.py:45
msgid "Invalid username and password combination."
msgstr ""

#: ../common/rhnException.py:46
msgid "This login is already taken, or the password is incorrect."
msgstr ""

#: ../common/rhnException.py:47
msgid "Permission denied."
msgstr "Permís denegat."

#: ../common/rhnException.py:48
msgid "Can not create new entry."
msgstr "No es pot crear una nova entrada."

#: ../common/rhnException.py:49
msgid "Object not found."
msgstr "Objecte no trobat."

#: ../common/rhnException.py:50
msgid "Account limits exceeded."
msgstr ""

#: ../common/rhnException.py:51
msgid "Invalid System Digital ID."
msgstr ""

#: ../common/rhnException.py:52
msgid "Invalid System Credentials."
msgstr ""

#: ../common/rhnException.py:53
msgid "Could not retrieve user data from database."
msgstr ""

#: ../common/rhnException.py:54
msgid "Valid username required."
msgstr "Es requereix un nom d'usuari vàlid."

#: ../common/rhnException.py:55
msgid "Valid password required."
msgstr "Es requereix una contrasenya vàlida."

#: ../common/rhnException.py:56
msgid "Minimum username length violation."
msgstr ""

#: ../common/rhnException.py:57
msgid "Minimum password length violation."
msgstr ""

#: ../common/rhnException.py:58
msgid "The username contains invalid characters."
msgstr "El nom d'usuari conté caràcters no vàlids."

#: ../common/rhnException.py:59
msgid "Invalid product registration code."
msgstr "El codi de registrament del producte no és vàlid."

#: ../common/rhnException.py:60
msgid "File not found."
msgstr "Fitxer no trobat."

#: ../common/rhnException.py:61
msgid "Invalid Architecture and OS release combination."
msgstr ""

#: ../common/rhnException.py:62
msgid "Architecture and OS version combination is not supported."
msgstr ""

#: ../common/rhnException.py:63
msgid "Could not retrieve system data from database."
msgstr ""

#: ../common/rhnException.py:64
msgid "Invalid arguments passed to function."
msgstr ""

#: ../common/rhnException.py:65
msgid "Unable to retrieve requested entry."
msgstr ""

#: ../common/rhnException.py:66
msgid "Could not update database entry."
msgstr "No s'ha pogut actualitzar l'entrada de la base de dades."

#: ../common/rhnException.py:67
msgid "Unsupported server architecture."
msgstr "L'arquitectura del servidor no està admesa."

#: ../common/rhnException.py:68
msgid "LDAP operation failed."
msgstr "L'operació LDAP ha fallat."

#: ../common/rhnException.py:69
msgid "Backend RPM database failure: can not retrieve requested information."
msgstr ""

#: ../common/rhnException.py:71
msgid "Server Entry is busy."
msgstr ""

#: ../common/rhnException.py:72
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running rhn_register\n"
"     as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable RHN service for this "
"system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:81
msgid "Record not available in the database."
msgstr ""

#: ../common/rhnException.py:82
msgid "Invalid value for entry."
msgstr "Valor no vàlid per a l'entrada."

#: ../common/rhnException.py:83
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for Red Hat Network.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable RHN service for this "
"system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:89
msgid "Channel error"
msgstr "Error del canal"

#: ../common/rhnException.py:90
msgid "Client session token is invalid."
msgstr "El testimoni de la sessió del client no és vàlid."

#: ../common/rhnException.py:91
msgid "Client session token has expired."
msgstr "El testimoni de la sessió del client ha vençut."

#: ../common/rhnException.py:92
msgid "You are not authorized to retrieve the requested object."
msgstr ""

#: ../common/rhnException.py:93
msgid "Invalid action"
msgstr "Acció no vàlida"

#: ../common/rhnException.py:94
msgid "You are not allowed to perform administrative tasks on this system."
msgstr ""
"No esteu autoritzat per realitzar les tasques administratives en aquest "
"sistema."

#: ../common/rhnException.py:96
msgid "The system is already subscribed to the specified channel."
msgstr "El sistema ja està subscrit al canal especificat."

#: ../common/rhnException.py:97
msgid "The system is not currently subscribed to the specified channel."
msgstr "El sistema actualment no està subscrit al canal especificat."

#: ../common/rhnException.py:98
msgid "The specified channel does not exist."
msgstr "El canal especificat no  existeix."

#: ../common/rhnException.py:99
msgid "Invalid channel version."
msgstr "La versió del canal no és vàlida."

#: ../common/rhnException.py:100
msgid "Invalid ORG_ID requested"
msgstr ""

#: ../common/rhnException.py:101
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for your\n"
"     account if the maximum number of users allowed to subscribe to RHN "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""

#: ../common/rhnException.py:109
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can be\n"
"     subscribed to your RHN account.\n"
"     "
msgstr ""

#: ../common/rhnException.py:117
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by Red Hat Network\n"
"     "
msgstr ""
"\n"
"     Arquitectura no vàlida.\n"
"\n"
"     L'arquitectura del paquet no està admesa per la Red Hat Network\n"
"     "

#: ../common/rhnException.py:122
msgid ""
"\n"
"     Incompatible architectures.\n"
"\n"
"     The architecture of the package you are trying to upload is not\n"
"     compatible with the channel architecture.\n"
"     "
msgstr ""

#: ../common/rhnException.py:128
msgid "Invalid RPM header"
msgstr "Capçalera RPM no vàlida"

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Invalid channel.\n"
"\n"
"     The channel you have specified does not exist.\n"
"     "
msgstr ""
"\n"
"     Canal no vàlid.\n"
"\n"
"     El canal que heu especificat no existeix.\n"
"     "

#: ../common/rhnException.py:134
#, python-format
msgid ""
"\n"
"     You are getting this error because RHN has detected an abuse of\n"
"     service from this system and account. This error is triggered when\n"
"     your system makes too many connections to Red Hat Network. This\n"
"     error can not be triggered under a normal use of the Red Hat Network\n"
"     service as configured by default on Red Hat Linux.\n"
"\n"
"     The Red Hat Network services for this system will remain disabled\n"
"     until you will reduce the RHN network traffic from your system to\n"
"     acceptable limits.\n"
"\n"
"     Please log into RHN and visit https://%(hostname)s/help/contact.pxt\n"
"     to contact technical support if you think you have received this\n"
"     message in error.\n"
"     "
msgstr ""

#. For the uploading tools
#: ../common/rhnException.py:150
msgid "Invalid information uploaded to the server"
msgstr "Informació no vàlida pujada al servidor"

#: ../common/rhnException.py:151
#, python-format
msgid ""
"\n"
"     Demo service currently disabled due to high load. If you would like\n"
"     to see Red Hat's policies on Demo service, or find out how you can\n"
"     purchase a subscription service and receive priority download access,\n"
"     please go to http://%(hostname)s/preview/index.pxt\n"
"     "
msgstr ""

#: ../common/rhnException.py:157
#, python-format
msgid ""
"\n"
"     Access to Red Hat Network is currently limited to subscription "
"customers.\n"
"     Please try again later.  If you would like to become a subscription\n"
"     customer, go to https://%(hostname)s/preview/priority_service.pxt for\n"
"     more information.\n"
"     "
msgstr ""

#: ../common/rhnException.py:163
msgid "Error uploading network interfaces configuration."
msgstr ""
"S'ha produït un error en pujar la configuració de les interfícies de xarxa."

#: ../common/rhnException.py:164
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""

#: ../common/rhnException.py:169
msgid ""
"\n"
"     The --force rhnpush option is disabled on this server. \n"
"     Please contact your Satellite administrator for more help.\n"
"     "
msgstr ""

#. 60-70: token errors
#: ../common/rhnException.py:175
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""

#: ../common/rhnException.py:179
msgid "Too many systems registered using this registration token"
msgstr ""
"Hi ha massa sistemes registrats que utilitzen aquest testimoni de "
"registrament"

#: ../common/rhnException.py:180
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr "El testimoni conté ajustos no vàlids, en desús i insuficients"

#: ../common/rhnException.py:181
msgid "Conflicting activation tokens"
msgstr "Conflicte en els testimonis d'activació"

#. 70-80: channel subscription errors
#: ../common/rhnException.py:184
msgid ""
"\n"
"     All available subscriptions for the requested channel have been "
"exhausted.\n"
"     Please contact a Red Hat Network Sales associate.\n"
"     "
msgstr ""

#: ../common/rhnException.py:188
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""

#: ../common/rhnException.py:193
msgid "You can not unsubscribe from base channel."
msgstr "No us podeu de-subscriure del canal base."

#. 80-90: server group errors
#: ../common/rhnException.py:196
msgid "There was an error while trying to join the system to its groups"
msgstr ""

#. 90-100: entitlement errors
#: ../common/rhnException.py:199
msgid "Unable to entitle system"
msgstr "No es pot donar el dret al sistema"

#: ../common/rhnException.py:200
msgid ""
"Registration token unable to entitle system: maximum membership exceeded"
msgstr ""
"El testimoni de registrament va ser incapaç de donar  el dret del sistema: "
"es va superar la màxima afiliació"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:204
msgid "Maximum e-mail length violation."
msgstr ""

#: ../common/rhnException.py:205
msgid "Changing e-mail address is not supported."
msgstr ""

#: ../common/rhnException.py:206
msgid "This system has been previously registered."
msgstr ""

#: ../common/rhnException.py:207
msgid "Invalid username"
msgstr "El nom d'usuari no és vàlid"

#. 110-129: disabled org errors
#: ../common/rhnException.py:210
msgid "Service for your account has been disabled."
msgstr ""

#: ../common/rhnException.py:211
msgid "Email address not validated; service disabled"
msgstr ""

#: ../common/rhnException.py:212
msgid "Survey not filled out; service disabled"
msgstr ""

#. 130-140: bugzilla errata import errors
#: ../common/rhnException.py:215
msgid "Bugzilla erratum import error"
msgstr ""

#. 140-159 applet errors
#: ../common/rhnException.py:218
msgid "Unable to look up server"
msgstr ""

#. 160-179: OSAD errors
#: ../common/rhnException.py:221
msgid "Required argument is missing"
msgstr ""

#. 500-599: Package Uploader errors
#: ../common/rhnException.py:224
msgid "Missing HTTP header information"
msgstr ""

#: ../common/rhnException.py:225
msgid "The package's checksum signature does not match the header one"
msgstr ""

#: ../common/rhnException.py:226
msgid "Header information does not match package metainformation"
msgstr ""

#: ../common/rhnException.py:227
msgid "Package with a different signature already uploaded"
msgstr ""

#: ../common/rhnException.py:228
msgid "Not an RPM package"
msgstr "No és un paquet RPM"

#: ../common/rhnException.py:229
msgid "Unsigned RPM package"
msgstr "Paquet RPM sense signar"

#: ../common/rhnException.py:230
msgid "Incompatible package and channel architectures"
msgstr ""

#: ../common/rhnException.py:231
msgid "Incompatible checksum type"
msgstr "Tipus de checksum incompatible"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:234
msgid "Invalid Entitlement Number"
msgstr ""

#: ../common/rhnException.py:235
msgid "No entitlement information tied to hardware"
msgstr ""

#: ../common/rhnException.py:236
msgid "Installation number is not entitling"
msgstr ""

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:239
msgid "Maximum username length violation"
msgstr ""

#: ../common/rhnException.py:240
msgid "Maximum password length violation"
msgstr ""

#: ../common/rhnException.py:242
msgid "System Name cannot be less than 3 characters"
msgstr ""

#. 1000-1999: RHN Proxy specific errors:
#. issued by an RHN Proxy to the client
#: ../common/rhnException.py:246
msgid "RHN Proxy error."
msgstr ""

#: ../common/rhnException.py:247
msgid "RHN Proxy unable to login."
msgstr "RHN Proxy va ser incapaç d'iniciar la sessió."

#. issued by an RHN Server/Satellite to the proxy
#: ../common/rhnException.py:249
msgid ""
"\n"
"     RHN Proxy system ID does not match an RHN Proxy Server\n"
"     in the database. Please contact your designated Red Hat representative\n"
"     or visit https://rhn.redhat.com/help/contact.pxt immediately if\n"
"     experiencing difficulties with the process of enabling or continued\n"
"     enablement of this RHN Proxy Server.\n"
"     "
msgstr ""

#: ../common/rhnException.py:256
msgid "RHN Proxy session token is invalid."
msgstr "El testimoni de la sessió del RHN Proxy no és vàlid."

#: ../common/rhnException.py:257
msgid "RHN Proxy session token has expired."
msgstr "El testimoni de la sessió del RHN Proxy ha vençut."

#. 2000-2999: RHN Satellite specific errors:
#: ../common/rhnException.py:261
msgid ""
"\n"
"     RHN Satellite user creation is not allowed via rhn_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""
"\n"
"     La creació de l'usuari del RHN Satellite no està permesa a través de "
"rhn_register;\n"
"     poseu-vos en contacte amb l'administrador del sistema per a què es crei "
"el vostre compte.\n"
"     "

#: ../common/rhnException.py:265
msgid ""
"\n"
"     RHN Satellite system ID does not match an RHN Satellite Server\n"
"     in the database. Please contact your designated Red Hat representative\n"
"     or visit https://rhn.redhat.com/help/contact.pxt immediately if\n"
"     experiencing difficulties with the process of enabling or continued\n"
"     enablement of this RHN Satellite Server.\n"
"     "
msgstr ""

#: ../common/rhnException.py:272
msgid ""
"\n"
"     This satellite server is not allowed to access the specified channel\n"
"     "
msgstr ""
"\n"
"     Aquest servidor de satellite no pot accedir al canal especificat\n"
"     "

#: ../common/rhnException.py:275
msgid ""
"\n"
"     This satellite server is not allowed to use Inter Satellite Sync on "
"this satellite\n"
"     "
msgstr ""
"\n"
"     Aquest servidor de satellite no pot utilitzar la sincronització interna "
"entre els satellite en aquest satellite\n"
"     "

#: ../common/rhnException.py:278
msgid "\n"
"     Inter Satellite Sync is disabled on this satellite.\n"
"     "
msgstr ""
"\n"
"     La sincronització interna entre els satellite està inhabilitada en "
"aquest satellite.\n"
"     "

#. Kickstart errors
#: ../common/rhnException.py:283
msgid "Access denied to kickstart tree"
msgstr "Es va denegar l'accés a l'arbre de kickstart"

#: ../common/rhnException.py:284
msgid "Could not find kickstart file"
msgstr "No es va poder trobar el fitxer de kickstart"

#: ../common/rhnException.py:285
msgid ""
"\n"
"     Kickstart tree would not lint, there are packages\n"
"     missing in the channel\n"
"     "
msgstr ""

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:291
msgid "Invalid datatype passed"
msgstr "Es va passar un tipus de dades no vàlid"

#: ../common/rhnException.py:292
msgid "Unable to retrieve channel"
msgstr "No es pot recuperar el canal"

#: ../common/rhnException.py:293
msgid "Invalid package name"
msgstr "El nom del paquet no és vàlid"

#: ../common/rhnException.py:294
msgid "Unable to retrieve package"
msgstr "No es pot recuperar el paquet"

#: ../common/rhnException.py:295
msgid "Invalid erratum name"
msgstr "El nom de l'errata no és vàlid"

#: ../common/rhnException.py:296
msgid "Unable to retrieve erratum"
msgstr "No es pot recuperar l'errata"

#: ../common/rhnException.py:297
msgid "Invalid satellite certificate"
msgstr "El certificat del satellite no és vàlid"

#: ../common/rhnException.py:298
msgid "File is missing"
msgstr "Falta el fitxer"

#: ../common/rhnException.py:299
msgid "Function retrieval error"
msgstr "Error en la recuperació de la funció"

#: ../common/rhnException.py:300
msgid "Function execution error"
msgstr "Error en l'execució de la funció"

#: ../common/rhnException.py:301
msgid "Missing version string"
msgstr "Falta la cadena de la versió"

#: ../common/rhnException.py:302
msgid "Invalid version string"
msgstr "La cadena de la versió no és vàlida"

#: ../common/rhnException.py:303
msgid "Mismatching versions"
msgstr "Les versions no coincideixen"

#: ../common/rhnException.py:304
msgid "Invalid channel version"
msgstr "La versió del canal no és vàlida"

#: ../common/rhnException.py:305
msgid "Missing snapshot for channels"
msgstr "Falta la instantània per al canal"

#: ../common/rhnException.py:306
msgid "No comps file for channel"
msgstr "No hi ha el fitxer comps per al canal"

#: ../common/rhnException.py:307
msgid "Unable to retrieve comps file"
msgstr "No es pot recuperar el fitxer comps"

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:310
msgid "Configuration action missing"
msgstr "Falta l'acció de configuració"

#: ../common/rhnException.py:311
msgid "File too large"
msgstr "El fitxer és massa gran"

#: ../common/rhnException.py:312
msgid "File contains binary data"
msgstr "El fitxer conté dades binàries"

#: ../common/rhnException.py:313
msgid "Configuration channel is not empty"
msgstr "El canal de configuració no està buit"

#: ../common/rhnException.py:314
msgid "Permission error"
msgstr "Error de permís"

#: ../common/rhnException.py:315
msgid "Content missing for configuration file"
msgstr "Falta contingut per al fitxer de confguració"

#: ../common/rhnException.py:316
msgid "Template delimiters not specified"
msgstr ""

#: ../common/rhnException.py:317
msgid "Configuration channel does not exist"
msgstr "El canal de configuració no existeix"

#: ../common/rhnException.py:318
msgid "Configuration channel already exists"
msgstr "El canal de configuració ja existeix"

#: ../common/rhnException.py:319
msgid "File missing from configuration channel"
msgstr ""

#: ../common/rhnException.py:320
msgid "Different revision of this file is uploaded"
msgstr ""

#: ../common/rhnException.py:321
msgid "File already uploaded to configuration channel"
msgstr ""

#: ../common/rhnException.py:322
msgid "File size exceeds remaining quota space"
msgstr ""

#: ../common/rhnException.py:323
msgid "Full path of file must be specified"
msgstr ""

#: ../common/rhnException.py:324
msgid "Invalid revision number"
msgstr "El número de revisió no és vàlid"

#: ../common/rhnException.py:325
msgid "Cannot compare files of different file type"
msgstr "No es poden comparar els fitxers de diferent tipus de fitxer"

#. 5000 - 5099: entitlement mapper errors
#: ../common/rhnException.py:328
msgid "The speicified item is not present in the input"
msgstr ""

#: ../common/rhnException.py:329
msgid "Invalid item code"
msgstr "El codi de l'element no és vàlid"

#: ../common/rhnException.py:330
msgid "Invalid user role"
msgstr "El rol de l'usuari no és vàlid"

#: ../common/rhnException.py:331
msgid "Invalid server group"
msgstr "El grup del servidor no és vàlid"

#: ../common/rhnException.py:332
msgid "Invalid channel family"
msgstr "La família del canal no és vàlida"

#: ../common/rhnException.py:376
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at bugzilla.redhat.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""

#: ../common/rhnException.py:430
#, python-format
msgid "Error Message:\n"
"    %s\n"
msgstr "Missatge d'error:\n"
"    %s\n"

#: ../common/rhnException.py:432
#, python-format
msgid "Error Class Code: %s\n"
msgstr "Codi de la classe d'error: %s\n"

#: ../common/rhnException.py:435
#, python-format
msgid "Error Class Info: %s\n"
msgstr "Informació de la classe d'error: %s\n"

#: ../common/rhnException.py:437
#, python-format
msgid "Explanation: %s"
msgstr "Explicació: %s"
