# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Martin Minar <skulliq@gmail.com>, 2011.
# Milan Kerslager <kerslage@linux.cz>, 2002,2007.
# Miloslav Trmac <mitr@volny.cz>, 2002.
# Miroslav Suchý <msuchy@redhat.com>, 2011.
# Jiri Dostal <jdostal@redhat.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-09-29 14:21+0200\n"
"PO-Revision-Date: 2020-09-25 17:48+0000\n"
"Last-Translator: Aleš Kastner <alkas@volny.cz>\n"
"Language-Team: Czech <https://l10n.opensuse.org/projects/uyuni/backend/cs/>\n"
"Language: cs\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;\n"
"X-Generator: Weblate 3.6.1\n"

#: ../server/apacheAuth.py:66
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "Neúplný autentifikační token pro proxy: %s"

#: ../server/apacheAuth.py:84
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr "Zaslaný podpis proxy %s neodpovídá našemu %s."

#: ../server/apacheAuth.py:119
msgid "declined proxy authentication"
msgstr "zamítnutá proxy autentifikace"

#: ../server/handlers/app/packages.py:192
#: ../server/handlers/xmlrpc/registration.py:215
#: ../server/handlers/xmlrpc/registration.py:1168
#: ../server/handlers/xmlrpc/registration.py:1307
#: ../server/configFilesHandler.py:129
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   Účet %s byl na tomto serveru deaktivován.\n"
"                   Pro další pomoc kontaktujte správce své organizace."

#: ../server/handlers/applet/applet.py:78
#, python-brace-format
msgid "Your system was not found in the {PRODUCT_NAME} database"
msgstr "Váš systém nebyl v databázi {PRODUCT_NAME} nalezen"

#: ../server/handlers/sat/auth.py:45
msgid "ISS is disabled on this server."
msgstr "ISS je na tomto serveru deaktivováno."

#: ../server/handlers/sat/auth.py:50
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "Server \"%s\" nemá povolen ISS."

#: ../server/handlers/xmlrpc/scap.py:104
msgid "Invalid system_id/action_id pair."
msgstr "Neplatný pár system_id/action_id."

#: ../server/handlers/xmlrpc/errata.py:64
#, python-format
msgid "Expected a package name, not: %s"
msgstr "Očekávám jméno balíku, nikoliv \"%s\""

#: ../server/handlers/xmlrpc/errata.py:115
#, python-format
msgid "Expected a package, not: %s"
msgstr "Očekávám balík, nikoliv \"%s\""

#: ../server/handlers/xmlrpc/queue.py:433
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr "Neplatná hodnota operace typu %s (%s)"

#: ../server/handlers/xmlrpc/queue.py:464
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "Operace %s nenáleží k serveru %s"

#: ../server/handlers/xmlrpc/up2date.py:233
#, python-format
msgid "Invalid value %s (%s)"
msgstr "Neplatná hodnota %s (%s)"

#: ../server/handlers/xmlrpc/proxy.py:65
#, python-format
msgid "SUSE Manager Proxy service not enabled for server profile: \"%s\""
msgstr "Serverový profil \"%s\" nemá aktivovánu službu SUSE Manager Proxy"

#: ../server/handlers/xmlrpc/proxy.py:85
msgid "Invalid session key"
msgstr "Neplatný session key"

#: ../server/handlers/xmlrpc/proxy.py:93
msgid "This server ID no longer exists"
msgstr "Toto ID serveru již neexistuje"

#: ../server/handlers/xmlrpc/registration.py:194
msgid "Required data missing"
msgstr "Chybí požadovaná data"

#: ../server/handlers/xmlrpc/registration.py:198
msgid "Required members missing"
msgstr "Chybí požadovaní členi"

#: ../server/handlers/xmlrpc/registration.py:207
msgid "Attempt to register a system to an invalid username"
msgstr "Pokoušíte se zaregistrovat systém na neexistujicího uživate"

#: ../server/handlers/xmlrpc/registration.py:839
msgid "Invalid system release version requested"
msgstr "Požadována neplatná release verze systému"

#: ../server/handlers/xmlrpc/registration.py:1063
msgid ""
"Unable to find a valid network interface, both ipaddr and ip6addr not found."
msgstr ""
"Nelze najít platné síťové rozhraní, ipaddr (IPv4) a ip6addr (IPv6) nebyly "
"nalezeny."

#: ../server/handlers/xmlrpc/registration.py:1115
#, python-brace-format
msgid "{PRODUCT_NAME} Welcome Message"
msgstr "Uvítací zpráva {PRODUCT_NAME}"

#: ../server/handlers/xmlrpc/registration.py:1125
msgid "Privacy Statement"
msgstr "Prohlášení o ochraně soukromí"

#: ../server/handlers/xmlrpc/registration.py:1146
msgid "Expected a dictionary as a product argument"
msgstr "Jako argument u produktu je očekáván slovník"

#: ../server/handlers/xmlrpc/registration.py:1374
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr "Neplatná hodnota '%s' pro %s (%s)"

#: ../server/importlib/userAuth.py:98
msgid "You are not authorized to manage packages in the null org"
msgstr "Prázdná organizace nemá právo spravovat balíčky"

#: ../server/importlib/userAuth.py:103
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "Nemáte právo spravovat balíčky v organizaci  %s"

#: ../server/importlib/userAuth.py:121
msgid "You are not allowed to perform administrative tasks"
msgstr "Nemáte právo provádět úkoly správy"

#: ../server/importlib/userAuth.py:144
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr "Nemáte právo spravovat kanál %s, nebo takový kanál ani neexistuje"

#: ../server/importlib/userAuth.py:204
#, python-format
msgid ""
"\n"
"               %s Account has been deactivated on this server.\n"
"               Please contact your Org administrator for more help."
msgstr ""
"\n"
"               Účet %s byl na tomto serveru deaktivován.\n"
"               Pro další pomoc kontaktujte správce své organizace."

#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr "Spusťte prosím rhn_register jako superuživatel (root) tohoto klienta"

#: ../server/rhnHandler.py:75
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr "Tato služba není aktivována pro systémový profil: \"%s\""

#: ../server/rhnServer/server_class.py:97
#, python-format
msgid "Architecture `%s' is not supported"
msgstr "Architektura '%s' není podporována"

#: ../server/rhnServer/server_token.py:78
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "Token `%s' má přiřazen více jak jeden kanál"

#: ../server/rhnServer/server_token.py:80
msgid "Conflicting base channels"
msgstr "Konflikt hlavních kanálů"

#: ../server/rhnServer/server_token.py:190
#, python-format
msgid "Failed to add server to group %s"
msgstr "Nepodařilo se přidat server do skupiny %s"

#: ../server/rhnServer/server_token.py:503
#, python-format
msgid "Maximum usage count of %s reached"
msgstr "Bylo dosaženo maximálního počtu užívání %s"

#: ../server/rhnServer/server_token.py:744
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""
"Skládání re-registračních tokenů s povoleními na různé hlavní kanály není "
"podporováno"

#: ../server/rhnServer/server_token.py:811
#, python-format
msgid "Could not find token '%s'"
msgstr "Nepodařilo se nalézt token '%s'"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:843
msgid "Tokens from mismatching orgs"
msgstr "Tokeny jsou z neodpovídajících si organizací"

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:853
msgid "Kickstart session mismatch"
msgstr "Nesouhlasí session kickstartu"

#: ../server/rhnServer/server_token.py:877
msgid "Stacking of re-registration tokens is not supported"
msgstr "Sčítání re-registračních tokenů není podporováno"

#: ../server/rhnUser.py:289 ../server/rhnUser.py:292
msgid "Invalid username/password combination"
msgstr "Neplatná kombinace uživatelského jména a hesla"

#. nope, not reserved either
#: ../server/rhnUser.py:467
#, python-format
msgid "Username `%s' has not been reserved"
msgstr "Uživatelské jméno `%s' nebylo rezerováno"

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:473
msgid "E-mail address not specified"
msgstr "Nebyla udána e-mailová adresa"

#: ../server/rhnUser.py:509
#, python-format
msgid "username should be at least %d characters"
msgstr "uživatelské jméno musí mít minimálně %d znaků"

#: ../server/rhnUser.py:512
#, python-format
msgid "username should be less than %d characters"
msgstr "uživatelské jméno musí být kratší, než %d znaků"

#: ../server/rhnUser.py:523
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr "uživatelské jméno = `%s' obsahuje neplatný znak `%s'"

#: ../server/rhnUser.py:542
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr "Prosím, omezte e-mail adresu na znaky %s"

#: ../server/rhnUser.py:623
#, python-format
msgid "password must be at least %d characters"
msgstr "heslo musí mít nejméně %d znaků"

#: ../server/rhnUser.py:626
#, python-format
msgid "Password must be shorter than %d characters"
msgstr "Heslo musí být kratší, než %d znaků"

#: ../server/rhnUser.py:644
#, python-format
msgid "password contains character `%s'"
msgstr "heslo obsahuje znak `%s'"

#: ../server/rhnUser.py:651
#, python-format
msgid "username should be at least %d characters long"
msgstr "uživatelské jméno by mělo mít alespoň %d znaků"

#: ../server/rhnUser.py:662
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr "Nelze registrovat uživatelská jména končící na %s"

#: ../server/rhnPackage.py:49 ../server/rhnPackage.py:87
#: ../server/rhnPackage.py:107 ../server/rhnPackage.py:158
#, python-format
msgid "Invalid RPM package %s requested"
msgstr "Byl vyžádán neplatný RPM balík %s"

#: ../server/rhnPackage.py:112
msgid "Package not found"
msgstr "Balík nenalezen"

#: ../server/apacheRequest.py:59
#, python-format
msgid "Invalid request received (%s)."
msgstr "Neplatná žádost (%s)."

#: ../server/apacheRequest.py:120
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""
"DŮLEŽITÉ UPOZORNĚNÍ:\n"
"%s"

#: ../server/apacheRequest.py:149
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""
"Při běhu '%s': zachyceno\n"
"%s : %s\n"

#: ../server/apacheRequest.py:606
#, python-format
msgid "Invalid URI %s"
msgstr "Neplatné URI %s"

#: ../server/rhnChannel.py:1992
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""
"Váš systém nemá přístup k žádným kanálům pro (release='%(release)s', "
"arch='%(arch)s')%(www_activation)s"

#: ../server/rhnChannel.py:2002
msgid ""
"\n"
"If you have a registration number, please register with it first at http://"
"www.redhat.com/apps/activate/ and then try again.\n"
"\n"
msgstr ""
"\n"
"Pokud máte registrační číslo, tak se s ním nejdříve zaregistrujte na http://"
"www.redhat.com/apps/activate/ a pak to zkuste znova.\n"
"\n"

#: ../server/rhnChannel.py:2012
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr "Nedostatečná subscription práva pro release (%s, %s"

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2276 ../server/rhnChannel.py:2287
#: ../server/rhnChannel.py:2302
msgid "System Registered but Inactive"
msgstr "Systém je registrován, ale neaktivní"

#: ../server/rhnChannel.py:2277
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it is not subscribed to a channel. If you have not yet\n"
"activated your product for service, please visit our website at:\n"
"\n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...to activate your product."
msgstr ""
"\n"
"Neplatná kombinace architektury a operačního systému (%s, %s).\n"
"Váš systém byl sice zaregistrován, ale nebude dostávat aktualizace,\n"
"protože není přihlášen do žádného kanálu.\n"
"Pokud jste ještě svůj produkt neaktivovali, jděte na:\n"
"  \n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...a aktivujte si ho."

#: ../server/rhnChannel.py:2288
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""
"\n"
"Neplatná kombinace architektury a operačního systému (%s, %s).\n"
"Váš systém byl sice zaregistrován, ale nebude dostávat aktualizace,\n"
"protože nemůže být přihlášen do hlavního kanálu.\n"
"Pro další pomoc kontaktujte správce vaší organizace.\n"

#: ../server/rhnChannel.py:2295
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Systém byl sice zaregistrován, ale ještě nemá povolenu\n"
"  službu.  Pro povolení služby se přihlaste na webové stránky na:\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnChannel.py:2303
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Systém byl sice zaregistrován, ale ještě neměl k dispozici\n"
"  žádné povolené služby.  Pro povolení služby se přihlaste na webové stránky "
"na:\n"
"\n"
"  %(entitlement_url)s\n"

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:53
msgid "This does not appear to be a valid username."
msgstr "Toto asi není platné uživatelské jméno."

#: ../common/rhnException.py:54
msgid "Invalid username and password combination."
msgstr "Neplatná kombinace uživatelského jména a hesla."

#: ../common/rhnException.py:55
msgid "This login is already taken, or the password is incorrect."
msgstr "Tento login je již používán nebo je heslo neplatné."

#: ../common/rhnException.py:56
msgid "Permission denied."
msgstr "Přístup odepřen."

#: ../common/rhnException.py:57
msgid "Object not found."
msgstr "Objekt nenalezen."

#: ../common/rhnException.py:58
msgid "Invalid System Digital ID."
msgstr "Neplatné ID systému."

#: ../common/rhnException.py:59
msgid "Invalid System Credentials."
msgstr "Neplatné přihlašovací údaje do systému."

#: ../common/rhnException.py:60
msgid "Could not retrieve user data from database."
msgstr "Nepodařilo se z databáze získat uživatelská data."

#: ../common/rhnException.py:61
msgid "Valid username required."
msgstr "Vyžadováno platné uživatelské jméno."

#: ../common/rhnException.py:62
msgid "Valid password required."
msgstr "Vyžadováno platné heslo."

#: ../common/rhnException.py:63
msgid "Minimum username length violation."
msgstr "Nedostatečná délka uživatelského jména."

#: ../common/rhnException.py:64
msgid "Minimum password length violation."
msgstr "Nedostatečná délka hesla."

#: ../common/rhnException.py:65
msgid "The username contains invalid characters."
msgstr "Uživatelské jméno obsahuje nepovolené znaky."

#: ../common/rhnException.py:66
msgid "File not found."
msgstr "Soubor nenalezen."

#: ../common/rhnException.py:67
msgid "Architecture and OS version combination is not supported."
msgstr ""
"Tato kombinace architektury a verze operačního systému není podporována."

#: ../common/rhnException.py:68
msgid "Could not retrieve system data from database."
msgstr "Nepodařilo se získat systémová data z databáze."

#: ../common/rhnException.py:69
msgid "Invalid arguments passed to function."
msgstr "Funkci byly předány neplatné argumenty."

#: ../common/rhnException.py:70
msgid "Unable to retrieve requested entry."
msgstr "Nepodařilo se získat požadovaný záznam."

#: ../common/rhnException.py:71
msgid "Could not update database entry."
msgstr "Nepodařilo se aktualizovat záznam v databázi."

#: ../common/rhnException.py:72
msgid "Unsupported server architecture."
msgstr "Nepodporovaná architektura serveru."

#: ../common/rhnException.py:73
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running mgr_register as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     Funkce anonymního serveru již není dostupná.\n"
"\n"
"     Znovu se zaregistrujte jako superuživatel root příkazem mgr_register.\n"
"     Navštivte https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     nebo se přihlaste na https://%(hostname)s a na kartě \"Přehled"
"\" (Overview),\n"
"     zvolte \"Správu předplatných\" (Subscription Management)\n"
"     pro aktivaci služby pro tento systém.\n"
"     "

#: ../common/rhnException.py:81
msgid "Record not available in the database."
msgstr "Tento záznam v databázi neexistuje."

#: ../common/rhnException.py:82
msgid "Invalid value for entry."
msgstr "Neplatná hodnota záznamu."

#: ../common/rhnException.py:83
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for SUSE Manager.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     Tento systém nemá platné oprávnění pro Správce SUSE.\n"
"     Navštivte https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     nebo se přihlaste na https://%(hostname)s a na kartě \"Přehled"
"\" (Overview)\n"
"     zvolte \"Správu předplatných\" (Subscription Management),\n"
"     abyste si aktivovali službu pro tento systém.\n"
"     "

#: ../common/rhnException.py:89
msgid "Channel error"
msgstr "Chyba kanálu"

#: ../common/rhnException.py:90
msgid "Client session token is invalid."
msgstr "Session token klient je neplatný."

#: ../common/rhnException.py:91
msgid "Client session token has expired."
msgstr "Session token klienta vypršel."

#: ../common/rhnException.py:92
msgid "You are not authorized to retrieve the requested object."
msgstr "Nemáte oprávnění k vyzvednutí požadovaného objektu."

#: ../common/rhnException.py:93
msgid "Invalid action"
msgstr "Neplatná operace"

#: ../common/rhnException.py:94
msgid "You are not allowed to perform administrative tasks on this system."
msgstr "Nemáte oprávnění spravovat tento systém."

#: ../common/rhnException.py:96
msgid "The system is already subscribed to the specified channel."
msgstr "Tento systém je již přihlášen do daného kanálu."

#: ../common/rhnException.py:97
msgid "The system is not currently subscribed to the specified channel."
msgstr "Tento systém není momentálně přihlášený do daného kanálu."

#: ../common/rhnException.py:98
msgid "The specified channel does not exist."
msgstr "Požadovaný kanál neexistuje."

#: ../common/rhnException.py:99
msgid "Invalid channel version."
msgstr "Neplatná verze kanálu."

#: ../common/rhnException.py:100
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""
"\n"
"     Překročeny limity členství ve skupině uživatelů.\n"
"\n"
"     Aktuální nastavení účtu neumožňuje přidat další uživatelský účet. "
"Zkontrolujte\n"
"     prosím u správce vaší organizace účet, zda maximální počet uživatelů,\n"
"     kteří se mohou přihlásit k odběru serverových potřeb, má být změněn.\n"
"     "

#: ../common/rhnException.py:108
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""
"\n"
"     Překročeny limity členství ve skupině uživatelů.\n"
"\n"
"     Aktuální nastavení účtu Vám neumožňuje přidat další uživatelský účet.\n"
"     Zkontrolujte u správce vaší organizace účet, zda maximální počet "
"uživatelů,\n"
"     kteří se mohou přihlásit k odběru serverových potřeb, má být změněn.\n"
"     "

#: ../common/rhnException.py:116
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""
"\n"
"     Neplatná architektura.\n"
"\n"
"     Architektura balíčku není podporována\n"
"     "

#: ../common/rhnException.py:121
msgid "Invalid RPM header"
msgstr "Neplatná hlavička RPM"

#: ../common/rhnException.py:122
msgid ""
"\n"
"    This system is already registered as a Salt Minion. If you want to "
"register it as a traditional client\n"
"    please delete it first via the web UI or API and then register it using "
"the traditional tools.\n"
"    "
msgstr ""
"\n"
"    Tento systém je již zaregistrován jako Salt Minion. Chcete-li se "
"zaregistrovat jako tradiční klient,\n"
"    nejprve ho smažte webovým rozhraním UI nebo API a pak ho registrujte "
"tradičními nástroji.\n"
"    "

#. For the uploading tools
#: ../common/rhnException.py:127
msgid "Invalid information uploaded to the server"
msgstr "Na server byla nahrána neplatná informace"

#: ../common/rhnException.py:128
msgid "Error uploading network interfaces configuration."
msgstr "Chyba při nahrávání konfigurace síťových rozhraní."

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""
"\n"
"     Nahrávání balíčku se nezdařilo kvůli porušení jedinečnosti.\n"
"     Ujistěte se, že balíček nemá duplicitní závislosti a je dosud na "
"serveru\n"
"     "

#: ../common/rhnException.py:134
msgid ""
"\n"
"     The --force rhnpush option is disabled on this server.\n"
"     Please contact your SUSE Manager administrator for more help.\n"
"     "
msgstr ""
"\n"
"     Možnost --force rhnpush byla na tomto serveru deaktivována.\n"
"     Pro další pomoc kontaktujte svého správce SUSE Manager.\n"
"     "

#. 60-70: token errors
#: ../common/rhnException.py:140
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""
"\n"
"     Zadaný aktivační žeton nebyl na serveru nalezen.\n"
"     Zkuste to prosím znovu s platným klíčem.\n"
"     "

#: ../common/rhnException.py:144
msgid "Too many systems registered using this registration token"
msgstr ""
"Pomocí tohoto registračního tokenu se registrovalo příliš mnoho systémů"

#: ../common/rhnException.py:145
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr "Token obsahuje neplatné, zastaralé nebo nedostatečné nastavení"

#: ../common/rhnException.py:146
msgid "Conflicting activation tokens"
msgstr "Konflikt aktivačních tokenů"

#. 70-80: channel subscription errors
#: ../common/rhnException.py:149
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""
"\n"
"     Ve vašem systému nebyl nalezen žádný odpovídající základní kanál.\n"
"     "

#: ../common/rhnException.py:152
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""
"\n"
"     Nemáte povolení k odběru určeného kanálu.\n"
"     Pro další podrobnosti se prosím obraťte na\n"
"     kanál vaší organizace nebo na její správce.\n"
"     "

#: ../common/rhnException.py:157
msgid "You can not unsubscribe from base channel."
msgstr "Z hlavního kanálu se nelze odhlásit."

#: ../common/rhnException.py:158
msgid "SUSE Manager or Proxy channel can not be subscribed."
msgstr "Nelze odebírat SUSE Manager nebo Proxy kanál."

#. 80-90: server group errors
#: ../common/rhnException.py:161
msgid "There was an error while trying to join the system to its groups"
msgstr "Při pokusu o připojení systému do jeho skupin došlo k chybě"

#. 90-100: entitlement errors
#: ../common/rhnException.py:164
msgid "Unable to entitle system"
msgstr "Nelze přiřadit oprávnění systému"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:167
msgid "Maximum e-mail length violation."
msgstr "Příliš dlouhý e-mail."

#: ../common/rhnException.py:168
msgid "This system has been previously registered."
msgstr "Tento systém již byl registrován."

#: ../common/rhnException.py:169
msgid "Invalid username"
msgstr "Neplatné uživatelské jméno"

#. 140-159 applet errors
#: ../common/rhnException.py:172
msgid "Unable to look up server"
msgstr "Nepodařilo se dohledat server"

#. 160-179: OSAD errors
#: ../common/rhnException.py:175
msgid "Required argument is missing"
msgstr "Chybý požadovaný argument"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:178
msgid "No entitlement information tied to hardware"
msgstr "K hardwaru nejsou připojeny žádné informace o oprávnění"

#: ../common/rhnException.py:179
msgid "Installation number is not entitling"
msgstr "Číslo instalace není oprávnění"

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:182
msgid "Maximum username length violation"
msgstr "Příliš dlouhé uživatelské jméno"

#: ../common/rhnException.py:183
msgid "Maximum password length violation"
msgstr "Příliš dlouhé heslo"

#: ../common/rhnException.py:184
msgid "This user has read only API access. Action denied."
msgstr "Tento uživatel má k API přístup jen pro čtení. Akce je zamítnuta."

#: ../common/rhnException.py:186
msgid "System Name cannot be less than 1 character"
msgstr "Název systému musí mít alespoň 1 znak"

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:190
msgid "SUSE Manager Proxy error."
msgstr "Chyba SUSE Manager Proxy."

#: ../common/rhnException.py:191
msgid "SUSE Manager Proxy unable to login."
msgstr "SUSE Manager Proxy není schopen se přihlásit."

#. issued by a SUSE Manager Server/Satellite to the proxy
#: ../common/rhnException.py:193
msgid ""
"\n"
"     SUSE Manager Proxy system ID does not match a Spacewalk Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""
"\n"
"     ID systému SUSE Manager Proxy neodpovídá serveru Spacewalk Proxy\n"
"     v databázi.\n"
"     "

#: ../common/rhnException.py:197
msgid "SUSE Manager Proxy session token is invalid."
msgstr "Žeton relace SUSE Manager Proxy je neplatný."

#: ../common/rhnException.py:198
msgid "SUSE Manager Proxy session token has expired."
msgstr "Žeton relace SUSE Manager Proxy vypršel."

#. 2000-2999: Red Hat Satellite specific errors:
#: ../common/rhnException.py:202
msgid ""
"\n"
"      user creation is not allowed via mgr_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""
"\n"
"      vytvoření uživatele není povoleno pomocí mgr_register;\n"
"     obraťte se na svého sysadmina a požádejte ho o vytvoření účtu.\n"
"     "

#: ../common/rhnException.py:206
msgid ""
"\n"
"     This SUSE Manager server is not allowed to use Inter Server Sync on "
"this server\n"
"     "
msgstr ""
"\n"
"     Tento server SUSE Manager nemá na tomto serveru povoleno používat Inter "
"Server Sync\n"
"     "

#: ../common/rhnException.py:209
msgid ""
"\n"
"     Inter Server Sync is disabled on this SUSE Manager Server.\n"
"     "
msgstr ""
"\n"
"     Funkce Inter Server Sync je na tomto serveru SUSE Manager zakázána.\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:214
msgid "Invalid datatype passed"
msgstr "Předán neplatný datový typ"

#: ../common/rhnException.py:215
msgid "Unable to retrieve channel"
msgstr "Nepodařilo se načíst kanál"

#: ../common/rhnException.py:216
msgid "Unable to retrieve package"
msgstr "Nepodařilo se načíst balíček"

#: ../common/rhnException.py:217
msgid "Unable to retrieve erratum"
msgstr "Nepodařilo se načíst erratu"

#: ../common/rhnException.py:218
msgid "File is missing"
msgstr "Soubor nenalezen"

#: ../common/rhnException.py:219
msgid "Function retrieval error"
msgstr "Chyba načítání funkce"

#: ../common/rhnException.py:220
msgid "Function execution error"
msgstr "Chyba provádění funkce"

#: ../common/rhnException.py:221
msgid "Missing version string"
msgstr "Chybějící řetězec verze"

#: ../common/rhnException.py:222
msgid "Invalid version string"
msgstr "Neplatný řetězec verze"

#: ../common/rhnException.py:223
msgid "Mismatching versions"
msgstr "Nesouhlasící verze"

#: ../common/rhnException.py:224
msgid "Invalid channel version"
msgstr "Neplatná verze kanálu"

#: ../common/rhnException.py:225
msgid "No comps file for channel"
msgstr "Pro kanál není k dispozici žádný soubor comps"

#: ../common/rhnException.py:226
msgid "Unable to retrieve comps file"
msgstr "Nelze načíst soubor comps"

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:229
msgid "Configuration action missing"
msgstr "Chybí akce konfigurace"

#: ../common/rhnException.py:230
msgid "File too large"
msgstr "Příliš velký soubor"

#: ../common/rhnException.py:231
msgid "File contains binary data"
msgstr "Soubor obsahuje binární data"

#: ../common/rhnException.py:232
msgid "Configuration channel is not empty"
msgstr "Konfigurační kanál není prázdný"

#: ../common/rhnException.py:233
msgid "Permission error"
msgstr "Chyba oprávnění"

#: ../common/rhnException.py:234
msgid "Content missing for configuration file"
msgstr "Chybí obsah konfiguračního souboru"

#: ../common/rhnException.py:235
msgid "Template delimiters not specified"
msgstr "Oddělovače šablon nejsou zadány"

#: ../common/rhnException.py:236
msgid "Configuration channel does not exist"
msgstr "Konfigurační kanál neexistuje"

#: ../common/rhnException.py:237
msgid "Configuration channel already exists"
msgstr "Konfigurační kanál již existuje"

#: ../common/rhnException.py:238
msgid "File missing from configuration channel"
msgstr "Soubor z konfiguračního kanálu chybí"

#: ../common/rhnException.py:239
msgid "Different revision of this file is uploaded"
msgstr "Je nahrána jiná revize tohoto souboru"

#: ../common/rhnException.py:240
msgid "File already uploaded to configuration channel"
msgstr "Soubor již byl nahrán na konfigurační kanál"

#: ../common/rhnException.py:241
msgid "File size exceeds remaining quota space"
msgstr "Velikost souboru překračuje zbývající prostor kvóty"

#: ../common/rhnException.py:242
msgid "Full path of file must be specified"
msgstr "Musí být zadána úplná cesta k souboru"

#: ../common/rhnException.py:243
msgid "Invalid revision number"
msgstr "Neplatné číslo revize"

#: ../common/rhnException.py:244
msgid "Cannot compare files of different file type"
msgstr "Nelze porovnat soubory různých typů"

#. 5000 - 5999: client content uploading errors
#. 5000 - 5099: crash reporting errors
#: ../common/rhnException.py:248
msgid "Crash information is invalid or incomplete"
msgstr "Údaje o havárii jsou neplatné nebo neúplné"

#: ../common/rhnException.py:249
msgid "Crash file information is invalid or incomplete"
msgstr "Údaje souboru o havárii jsou neplatné nebo neúplné"

#: ../common/rhnException.py:250
msgid "Error composing crash directory path"
msgstr "Chyba při vytváření cesty k adresáři havárie"

#: ../common/rhnException.py:251
msgid "Error composing crash file path"
msgstr "Chyba při vytváření cesty k souboru havárie"

#: ../common/rhnException.py:252 ../common/rhnException.py:259
msgid "Invalid content encoding"
msgstr "Neplatné kódování obsahu"

#: ../common/rhnException.py:253
msgid "Invalid crash name"
msgstr "Neplatný název havárie"

#: ../common/rhnException.py:254
msgid "Crash reporting is disabled for this organization"
msgstr "Hlášení havárií je pro tuto organizaci zakázáno"

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:256
msgid "SCAP results file transfer is invalid or incomplete"
msgstr "Přenos souboru výsledků SCAP je neplatný nebo neúplný"

#: ../common/rhnException.py:257
msgid "Error composing directory path for detailed SCAP results"
msgstr "Chyba při vytváření cesty k adresáři pro podrobné výsledky SCAP"

#: ../common/rhnException.py:258
msgid "Error composing file path for detailed SCAP results"
msgstr "Chyba při vytváření cesty souboru pro podrobné výsledky SCAP"

#: ../common/rhnException.py:306
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at scc.suse.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""
"\n"
"     Při zpracování vašeho požadavku došlo k chybě. Přetrvává-li tento\n"
"     problém, ohlaste prosím chybu na scc.suse.com.\n"
"     Rozhodnete-li se odeslat zprávu o chybě, nezapomeňte připojit\n"
"     podrobnosti o tom, co jste se pokusili udělat, když došlo k této chybě\n"
"     a postup, jak tento problém reprodukovat.\n"

#: ../common/rhnException.py:358
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""
"Chybové hlášení:\n"
"    %s\n"

#: ../common/rhnException.py:360
#, python-format
msgid "Error Class Code: %s\n"
msgstr "Kód třídy chyby: %s\n"

#: ../common/rhnException.py:363
#, python-format
msgid "Error Class Info: %s\n"
msgstr "Informace o třídě chyb: %s\n"

#: ../common/rhnException.py:365
#, python-format
msgid "Explanation: %s"
msgstr "Vysvětlení: %s"

#: ../common/rhnTB.py:205
#, python-format
msgid "ERROR: %s %s: %s"
msgstr "CHYBA: %s %s: %s"

#: ../common/rhnTB.py:207
#, python-format
msgid "TRACEBACK: %s"
msgstr "TRACE-BACK: %s"

#: ../satellite_tools/disk_dumper/iss.py:1294
#: ../satellite_tools/disk_dumper/iss.py:1298
#, python-format
msgid "format of %s should be at least YYYYMMDD.\n"
msgstr "formát %s by měl být alespoň RRRRMMDD.\n"

#: ../satellite_tools/messages.py:26
#, python-format
msgid ""
"\n"
"ERROR: executing step %s. Error is:\n"
"%s\n"
msgstr ""
"\n"
"CHYBA: při provedení kroku %s. Chyba je:\n"
"%s\n"

#: ../satellite_tools/messages.py:31
#, python-format
msgid ""
"\n"
"ERROR: there was a problem accessing the channel data from your temporary\n"
"       repository. Did you migrate all of the data from the channel ISOs\n"
"       do this directory? If so, please recheck the channels ISOs, ensure\n"
"       that you have them all, and then iteratively remount and repopulate\n"
"       the temporary repository (%s).\n"
msgstr ""
"\n"
"CHYBA: došlo k problému s přístupem k datům kanálu z vašeho dočasného\n"
"       úložiště. Přenesli jste všechna data z ISO kanálů do tohoto "
"adresáře?\n"
"       Když ano, znovu zkontrolujte kanály ISO, zajistěte, aby byly "
"všechny,\n"
"       a pak iterativně znovu připojte a znovu naplňte dočasné úložiště "
"(%s).\n"

#: ../satellite_tools/messages.py:39
#, python-format
msgid ""
"\n"
"ERROR: there was a problem synchronizing the information.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"CHYBA: Při synchronizaci informací došlo k potížím.\n"
"       Chybová zpráva: %s\n"

#: ../satellite_tools/messages.py:44
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       Depending on the specific error details, please review your "
"configuration,\n"
"       basic network connectivity, and/or name resolution, and try again.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"CHYBA: Při komunikaci s ISS Master došlo k potížím.\n"
"       V závislosti na konkrétních podrobnostech o chybě ověřte "
"konfiguraci,\n"
"       základní síťové připojení a/nebo překlad názvů (DNS) a akci "
"opakujte.\n"
"       Chybová zpráva: %s\n"

#: ../satellite_tools/messages.py:51
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       If the master satellite is older than v5.3, it does not have ISS "
"capability.\n"
"       Otherwise, depending on the specific error details, please review "
"your\n"
"       configuration, basic network connectivity, and/or name resolution, "
"and try again.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"CHYBA: Při komunikaci s ISS Master došlo k potížím.\n"
"       Pokud je Master Satellite starší než v5.3, nemá schopnost ISS.\n"
"       V opačném případě zkontrolujte konkrétní podrobnosti o chybě,\n"
"       ověřte správnost své konfigurace, základní připojení k síti nebo\n"
"       překlad názvů (DNS) a akci opakujte.\n"
"       Chybová zpráva: %s\n"

#: ../satellite_tools/messages.py:59
#, python-format
msgid ""
"\n"
"ERROR: a child-channel cannot be synced without its parent being synced as\n"
"       well. A parent needs to be either (a) previously synced or (b) "
"synced\n"
"       in tandem with the desired child-channel. Missing parents for this\n"
"       transaction:\n"
"       %s\n"
msgstr ""
"\n"
"CHYBA: podřízený kanál nelze synchronizovat, aniž je jeho rodič také "
"synchronizován.\n"
"       Rodič musí být (a) synchronizován předem nebo (b) synchronizován\n"
"       společně s požadovaným podřízeným kanálem. Chybějící rodiče pro tuto\n"
"       transakci:\n"
"       %s\n"

#: ../satellite_tools/messages.py:67
#, python-format
msgid ""
"\n"
"ERROR: you are not entitled to sync a channel in this set of channels.\n"
"Please contact your SUSE Manager contact\n"
"%s"
msgstr ""
"\n"
"CHYBA: nemáte právo synchronizovat kanál v této sadě kanálů.\n"
"Obraťte se prosím na svůj kontakt u SUSE Manager\n"
"%s"

#: ../satellite_tools/messages.py:72
#, python-format
msgid "  ERROR: not enough free space (%s KB) on device."
msgstr "  CHYBA: na zařízení není dostatek volného místa (%s KB)."

#: ../satellite_tools/messages.py:74
#, python-format
msgid "    %3d/%s Fetch successful: %s (%s bytes)"
msgstr "    %3d/%s úspěšné načtení: %s (%s bajtů)"

#: ../satellite_tools/messages.py:75
#, python-format
msgid "    Extinct package:  %s"
msgstr "    Zaniklý balíček:  %s"

#: ../satellite_tools/messages.py:76
#, python-format
msgid "   Total size: %s"
msgstr "   Celková velikost: %s"

#: ../satellite_tools/messages.py:77
#, python-format
msgid "      Downloaded %s of %s. Estimated remaining time: %s"
msgstr "      Staženo %s z %s. Odhadovaný zbývající čas: %s"

#: ../satellite_tools/messages.py:78
#, python-format
msgid "    Fetch unsuccessful: %s"
msgstr "    Načtení neúspěšné: %s"

#: ../satellite_tools/messages.py:79
#, python-format
msgid "   RPM fetch summary: %s"
msgstr "   Souhrn načtení RPM: %s"

#: ../satellite_tools/messages.py:80
#, python-format
msgid "       success: %d"
msgstr "       úspěch: %d"

#: ../satellite_tools/messages.py:81
#, python-format
msgid "       failed:  %d"
msgstr "       neúspěch:  %d"

#: ../satellite_tools/messages.py:82
#, python-format
msgid "       extinct: %d"
msgstr "       zaniklo: %d"

#: ../satellite_tools/messages.py:84
#, python-format
msgid "   Retrieving / parsing *relevant* package metadata: %s (%s)"
msgstr "   Načítání / analýza *relevantních* metadat balíčku: %s (%s)"

#: ../satellite_tools/messages.py:85
#, python-format
msgid "   Retrieving / parsing errata data: %s (%s)"
msgstr "   Načítání / analýza dat chyb (errata): %s (%s)"

#: ../satellite_tools/messages.py:86
#, python-format
msgid "   Retrieving / parsing kickstart data: %s (%s)"
msgstr "   Načítání / analýza dat kickstartu: %s (%s)"

#: ../satellite_tools/messages.py:87
#, python-format
msgid "   Retrieving / parsing kickstart tree files: %s (%s)"
msgstr "   Načítání / analýza souborů stromu kickstartu: %s (%s)"

#: ../satellite_tools/messages.py:88
#, python-format
msgid "   Importing *relevant* package metadata: %s (%s)"
msgstr "   Import *relevantních* metadat balíčků: %s (%s)"

#: ../satellite_tools/messages.py:89
msgid "   * WARNING: this may be a slow process."
msgstr "   * VÝSTRAHA: Toto může být pomalý proces."

#: ../satellite_tools/messages.py:90
msgid "Linking packages to channels"
msgstr "Propojení balíčků ke kanálům"

#: ../satellite_tools/messages.py:91
#, python-format
msgid "   Importing *relevant* errata: %s (%s)"
msgstr "   Import *relevantních* errat: %s (%s)"

#: ../satellite_tools/messages.py:92
msgid "   No new kickstartable tree to import"
msgstr "   Žádný nový spustitelný strom k importu"

#: ../satellite_tools/messages.py:93
#, python-format
msgid "Importing kickstartable trees (%d)"
msgstr "Import spustitelných stromů (%d)"

#: ../satellite_tools/messages.py:94
#, python-format
msgid "Imported kickstartable trees (%d)"
msgstr "Importované startovatelné stromy (%d)"

#: ../satellite_tools/rhn_satellite_activate.py:198
#, python-format
msgid ""
"\"%s\" (specified in commandline)\n"
"could not be opened and read:\n"
"%s"
msgstr ""
"\"%s\" (uvedeno v příkazovém řádku)\n"
"nelze otevřít a přečíst:\n"
"%s"

#: ../satellite_tools/rhn_satellite_activate.py:205
#, python-format
msgid ""
"\"%s\" could not be opened\n"
"and/or written to:\n"
"%s"
msgstr ""
"\"%s“ nelze otevřít a/nebo\n"
"do něj zapisovat:\n"
"%s"

#: ../satellite_tools/reposync.py:111 ../satellite_tools/satsync.py:439
msgid "+++ sending log as an email +++"
msgstr "+++ odesílání protokolu jako e-mailu +++"

#: ../satellite_tools/reposync.py:114
#, python-format
msgid "%s sync. report from %s"
msgstr "%s synchronizační zpráva od %s"

#: ../satellite_tools/reposync.py:124 ../satellite_tools/satsync.py:449
msgid "+++ email requested, but there is nothing to send +++"
msgstr "+++ vyžadován e-mail, ale není nic k odeslání +++"

#: ../satellite_tools/satsync.py:258
#, python-format
msgid "No handler for step %s"
msgstr "Žádný obslužný program pro krok %s"

#. Try one more time - this time it should be faster since
#. everything should be cached
#: ../satellite_tools/satsync.py:270
msgid "Environment changed, trying again..."
msgstr "Prostředí se změnilo, nový pokus..."

#: ../satellite_tools/satsync.py:277
msgid "ERROR: Encountered IntegrityError: \n"
msgstr "CHYBA: Došlo k chybě integrity: \n"

#: ../satellite_tools/satsync.py:285
msgid "Repeated failures"
msgstr "Opakované závady"

#: ../satellite_tools/satsync.py:290
#, python-format
msgid ""
"    Import complete:\n"
"        Begin time: %s\n"
"        End time:   %s\n"
"        Elapsed:    %s\n"
"          "
msgstr ""
"    Import dokončen:\n"
"        Zahájeno:  %s\n"
"        Ukončeno: %s\n"
"        Uplynulo:   %s\n"
"          "

#: ../satellite_tools/satsync.py:311
msgid "hours"
msgstr "hodin"

#: ../satellite_tools/satsync.py:311
msgid "minutes"
msgstr "minut"

#: ../satellite_tools/satsync.py:311
msgid "seconds"
msgstr "vteřin"

#: ../satellite_tools/satsync.py:357
msgid ""
"ERROR: The dump is missing package data, use --no-rpms to skip this step or "
"fix the content to include package data."
msgstr ""
"CHYBA: Na výpisu chybí data balíčku; použijte --no-rpms k přeskočení tohoto "
"kroku nebo opravte obsah tak, aby obsahoval data balíčku."

#. the orgs() method doesn't exist; that's fine we just
#. won't sync the orgs
#: ../satellite_tools/satsync.py:404
msgid "The SUSE Manager master does not support syncing orgs data."
msgstr "Hlavní server SUSE Manager nepodporuje synchronizaci dat organizací."

#: ../satellite_tools/satsync.py:404
msgid "Skipping..."
msgstr "Přeskakuji..."

#: ../satellite_tools/satsync.py:442
#, python-format
msgid "SUSE Manager Inter Server sync. report from %s"
msgstr "Zpráva o synchronizaci SUSE Manager Inter Server z %s"

#: ../satellite_tools/satsync.py:521
msgid " - file-system synchronization"
msgstr " - synchronizace systému souborů"

#: ../satellite_tools/satsync.py:533 ../satellite_tools/satsync.py:541
msgid " - live synchronization"
msgstr " - živá synchronizace"

#: ../satellite_tools/satsync.py:534
#, python-brace-format
msgid ""
"ERROR: Live content synchronizing with RHN Classic Hosted is no longer "
"supported.\n"
"Please use the cdn-sync command instead unless you are attempting to sync "
"from another {PRODUCT_NAME} via Inter-Server-Sync (ISS), or from local "
"content on disk via Channel Dump ISOs."
msgstr ""
"CHYBA: Synchronizace živého obsahu s RHN Classic Hosted již není "
"podporována.\n"
"Použijte příkaz cdn-sync, nepokoušíte-li se synchronizovat z jiného "
"{PRODUCT_NAME} přes Inter-Server-Sync (ISS), nebo z místního obsahu na disku "
"pomocí obrazů ISO z výpisu kanálu (Channel Dump)."

#: ../satellite_tools/satsync.py:542
#, python-format
msgid "   url: %s"
msgstr "   url: %s"

#: ../satellite_tools/satsync.py:543
#, python-format
msgid "   debug/output level: %s"
msgstr "   úroveň ladění/výstupu: %s"

#: ../satellite_tools/satsync.py:553
msgid "ERROR: this server must be registered with SUSE Manager."
msgstr "CHYBA: tento server musí být zaregistrován u SUSE Manager."

#: ../satellite_tools/satsync.py:575
#, python-format
msgid "Retrieving / parsing %s data"
msgstr "Načítání/analýza dat %s"

#: ../satellite_tools/satsync.py:585 ../satellite_tools/satsync.py:600
msgid "*** SYSTEM INTERRUPT CALLED ***"
msgstr "*** VYVOLÁNO SYSTÉMOVÉ PŘERUŠENÍ ***"

#: ../satellite_tools/satsync.py:593
msgid "ERROR: fatal parser exception occurred "
msgstr "CHYBA: došlo k fatální výjimce analyzátoru "

#: ../satellite_tools/satsync.py:594
#, python-format
msgid "(line: %s, col: %s msg: %s)"
msgstr "(řádek: %s, sloupec: %s zpráva: %s)"

#: ../satellite_tools/satsync.py:598
#, python-format
msgid "ERROR: parser exception occurred: %s"
msgstr "CHYBA: došlo k výjimce analyzátoru: %s"

#: ../satellite_tools/satsync.py:603
msgid "ERROR: exception (during parse) occurred: "
msgstr "CHYBA: došlo k výjimce (během analýzy): "

#: ../satellite_tools/satsync.py:604
#, python-format
msgid ""
"   Encountered some errors with %s data (see logs (%s) for more information)"
msgstr ""
"   Došlo k některým chybám s daty %s (další informace viz protokoly %s)"

#: ../satellite_tools/satsync.py:606
#, python-format
msgid "   Encountered some errors with %s data:"
msgstr "   Došlo k několika chybám s údaji %s:"

#: ../satellite_tools/satsync.py:607
#, python-format
msgid "   ------- %s PARSE/IMPORT ERROR -------"
msgstr "   ------- CHYBA ANALÝZY/IMPORTU %s -------"

#: ../satellite_tools/satsync.py:609
msgid "   ---------------------------------------"
msgstr "   ---------------------------------------"

#: ../satellite_tools/satsync.py:612
#, python-format
msgid "%s data complete"
msgstr "%s dat dokončeno"

#: ../satellite_tools/satsync.py:665
msgid "Retrieving / parsing channel data"
msgstr "Načítání / analýza dat kanálu"

#: ../satellite_tools/satsync.py:718
msgid "Channel data complete"
msgstr "Data kanálu dokončena"

#: ../satellite_tools/satsync.py:736
#, python-format
msgid "%10s import from %s"
msgstr "%10s import z %s"

#: ../satellite_tools/satsync.py:739
#, python-format
msgid "%10s import from %s - %s"
msgstr "%10s import z %s - %s"

#: ../satellite_tools/satsync.py:743
#, python-format
msgid "%10s"
msgstr "%10s"

#: ../satellite_tools/satsync.py:750
msgid "p"
msgstr "p"

#: ../satellite_tools/satsync.py:752
msgid "."
msgstr "."

#: ../satellite_tools/satsync.py:758
msgid "   p = previously imported/synced channel"
msgstr "   p = dříve importovaný / synchronizovaný kanál"

#: ../satellite_tools/satsync.py:759
msgid "   . = channel not yet imported/synced"
msgstr "   . = kanál dosud není importován/synchronizován"

#: ../satellite_tools/satsync.py:765
msgid "   e = channel no longer supported (end-of-service)"
msgstr "   e = kanál již není podporován (ukončení služby)"

#: ../satellite_tools/satsync.py:767
msgid "   ? = channel label invalid --- typo?"
msgstr "   ? = označení kanálu je neplatné --- překlep?"

#: ../satellite_tools/satsync.py:771
#, python-format
msgid "   %s:"
msgstr "   %s:"

#: ../satellite_tools/satsync.py:772
#, python-format
msgid "      %s %-40s %4s %s"
msgstr "      %s %-40s %4s %s"

#: ../satellite_tools/satsync.py:773
msgid "base-channels"
msgstr "základní-kanály"

#: ../satellite_tools/satsync.py:786 ../satellite_tools/satsync.py:1603
msgid "NONE RELEVANT"
msgstr "ŽÁDNÝ RELEVANTNÍ"

#: ../satellite_tools/satsync.py:808
msgid "end-of-service"
msgstr "ukončení-služby"

#: ../satellite_tools/satsync.py:809
msgid "e"
msgstr "e"

#: ../satellite_tools/satsync.py:815
msgid "   typos:"
msgstr "   překlepy:"

#: ../satellite_tools/satsync.py:816
msgid "?"
msgstr "?"

#: ../satellite_tools/satsync.py:831
#, python-format
msgid "XXX: imported channels: %s"
msgstr "XXX: importované kanály: %s"

#: ../satellite_tools/satsync.py:832
#, python-format
msgid "XXX:   cached channels: %s"
msgstr "XXX: kanály v mezipaměti (keši): %s"

#: ../satellite_tools/satsync.py:837
msgid "XXX: list channels called"
msgstr "XXX: seznam volaných kanálů"

#: ../satellite_tools/satsync.py:855
msgid "ERROR: these channels either do not exist or are not available:"
msgstr "CHYBA: tyto kanály neexistují, nebo nejsou dostupné:"

#: ../satellite_tools/satsync.py:859
#, python-format
msgid "       (to see a list of channel labels: %s --list-channels)"
msgstr "       (zobrazení seznamu označení kanálů: %s --list-channels)"

#: ../satellite_tools/satsync.py:904
#, python-format
msgid "   Retrieving / parsing short package metadata: %s (%s)"
msgstr "   Načítání / analýza metadat krátkých balíčků: %s (%s)"

#: ../satellite_tools/satsync.py:965
#, python-format
msgid "Diffing package metadata (what's missing locally?): %s"
msgstr "Srovnání metadat balíčků (co lokálně chybí?): %s"

#: ../satellite_tools/satsync.py:971 ../satellite_tools/satsync.py:1254
msgid "Diffing:    "
msgstr "Srovnávání:    "

#: ../satellite_tools/satsync.py:988
msgid "ERROR: incremental dump skipped"
msgstr "CHYBA: vynechán přírůstkový výpis"

#: ../satellite_tools/satsync.py:1079
msgid "Downloading rpm packages"
msgstr "Stahování balíčků rpm"

#: ../satellite_tools/satsync.py:1084
#, python-format
msgid "   Fetching any missing RPMs: %s (%s)"
msgstr "   Načítání chybějících RPM: %s (%s)"

#: ../satellite_tools/satsync.py:1085 ../satellite_tools/satsync.py:1153
msgid "NONE MISSING"
msgstr "NECHYBÍ ŽÁDNÝ"

#: ../satellite_tools/satsync.py:1094
msgid "Processing rpm packages complete"
msgstr "Zpracování balíčků rpm bylo dokončeno"

#: ../satellite_tools/satsync.py:1121
msgid "Downloading package metadata"
msgstr "Stahování metadat balíčku"

#: ../satellite_tools/satsync.py:1146
msgid "Downloading srpm packages"
msgstr "Stahování balíčků srpm"

#: ../satellite_tools/satsync.py:1152
#, python-format
msgid "   Fetching any missing SRPMs: %s (%s)"
msgstr "   Načítání chybějících SRPM: %s (%s)"

#: ../satellite_tools/satsync.py:1249
#, python-format
msgid "Diffing source package metadata (what's missing locally?): %s"
msgstr "Srovnání metadat zdrojových balíčků (co lokálně chybí?): %s"

#: ../satellite_tools/satsync.py:1260
msgid "Downloading source package metadata"
msgstr "Stahování metadat zdrojového balíčku"

#: ../satellite_tools/satsync.py:1338 ../satellite_tools/satsync.py:2027
#, python-format
msgid "Unable to save file %s: %s"
msgstr "Nelze uložit soubor %s: %s"

#. for
#. Retried a number of times and it still failed; log the
#. file as being failed and move on
#: ../satellite_tools/satsync.py:1345
#, python-format
msgid "Failed to fetch file %s"
msgstr "Načtení souboru %s se nezdařilo"

#: ../satellite_tools/satsync.py:1350
msgid "Downloading kickstartable trees metadata"
msgstr "Stahování metadat startovatelných stromů"

#: ../satellite_tools/satsync.py:1365
msgid "Downloading kickstartable trees files"
msgstr "Stahování souborů startovatelných stromů"

#: ../satellite_tools/satsync.py:1504
#, python-format
msgid "Grabbing all patches for channel %s"
msgstr "Získání všech záplat pro kanál %s"

#: ../satellite_tools/satsync.py:1554
msgid "Downloading patch data"
msgstr "Stahování dat záplaty"

#: ../satellite_tools/satsync.py:1556
msgid "Forcing download of all patch data for requested channels."
msgstr "Vynucuji stažení všech dat záplat pro požadované kanály."

#: ../satellite_tools/satsync.py:1571
msgid "Downloading patch data complete"
msgstr "Stahování dat záplaty dokončeno"

#: ../satellite_tools/satsync.py:1576 ../satellite_tools/satsync.py:1597
msgid "Downloading:"
msgstr "Stahuji:"

#: ../satellite_tools/satsync.py:1579
msgid " - complete"
msgstr " - dokončeno"

#: ../satellite_tools/satsync.py:1624
msgid "Importing source package metadata"
msgstr "Import metadat zdrojového balíčku"

#: ../satellite_tools/satsync.py:1627
msgid "Importing package metadata"
msgstr "Import metadat balíčku"

#: ../satellite_tools/satsync.py:1635
msgid "Importing:  "
msgstr "Importuji:  "

#. not in the cache
#: ../satellite_tools/satsync.py:1703
msgid ""
"Package Not Found in Cache, Clear the Cache "
"to                                  Regenerate it."
msgstr ""
"Balíček nebyl v mezipaměti (keši) nalezen; vymažte mezipaměť "
"do                                  Regenerujte ji."

#: ../satellite_tools/satsync.py:1709
msgid "Importing channel patches"
msgstr "Import záplat kanálu"

#: ../satellite_tools/satsync.py:1714
#, python-format
msgid "Importing %s patches for channel %s."
msgstr "Importuje se %s záplat pro kanál %s."

#. Incomplete configuration
#: ../satellite_tools/satsync.py:2113
msgid "ERROR: server.mount_point not set in the configuration file"
msgstr "CHYBA: v konfiguračním souboru není nastaven server.mount_point"

#: ../satellite_tools/satsync.py:2117
#, python-format
msgid "ERROR: server.mount_point %s do not exist"
msgstr "CHYBA: server.mount_point %s neexistuje"

#: ../satellite_tools/satsync.py:2122
#, python-format
msgid "ERROR: path under server.mount_point (%s)  do not exist"
msgstr "CHYBA: cesta podle nastavení server.mount_point (%s) neexistuje"

#: ../satellite_tools/satsync.py:2199
#, python-format
msgid "Commandline: %s"
msgstr "Příkazový řádek: %s"

#: ../satellite_tools/satsync.py:2202
#, python-format
msgid ""
"DEBUG ONLY: max. batch-size for XML/database-import processing (1..%s).\"man "
"satellite-sync\" for more information."
msgstr ""
"POUZE DEBUG: max. velikost dávky pro zpracování importu XML/databáze (1 .."
"%s). Další informace: \"man satellite-sync\"."

#: ../satellite_tools/satsync.py:2205
msgid "alternative SSL CA Cert (fullpath to cert file)"
msgstr "alternativní certifikát SSL CA (úplná cesta k souboru certifikátu)"

#: ../satellite_tools/satsync.py:2207
msgid "process data for this channel only"
msgstr "zpracovávat data jen pro tento kanál"

#: ../satellite_tools/satsync.py:2209
msgid ""
"disk dump will be considered to be a full export; see \"man satellite-sync\" "
"for more information."
msgstr ""
"výpis disku bude považován za úplný export; další informace viz \"man "
"satellite-sync“."

#: ../satellite_tools/satsync.py:2212
msgid "existing custom channels will also be synced (unless -c is used)"
msgstr ""
"stávající vlastní kanály budou také synchronizovány (není-li použit parametr "
"-c)"

#: ../satellite_tools/satsync.py:2214
#, python-format
msgid ""
"override debug level set in /etc/rhn/rhn.conf (which is currently set at %s)."
msgstr ""
"přepsat úroveň ladění zadanou v /etc/rhn/rhn.conf (aktuálně nastavena na %s)."

#: ../satellite_tools/satsync.py:2216
#, python-format
msgid "requested version of XML dump (default: %s)"
msgstr "požadovaná verze výpisu XML (výchozí: %s)"

#: ../satellite_tools/satsync.py:2218
msgid "e-mail a report of what was synced/imported"
msgstr "pošlete e-mailem zprávu o tom, co bylo synchronizováno/importováno"

#: ../satellite_tools/satsync.py:2220
msgid "forcibly process all (not a diff of) patch metadata"
msgstr "nuceně zpracovat všechna (nejen odlišná) metadata záplat"

#: ../satellite_tools/satsync.py:2222
msgid "Do not use an http proxy under any circumstances."
msgstr "Za žádných okolností nepoužívejte http proxy."

#: ../satellite_tools/satsync.py:2224
msgid "alternative http proxy (hostname:port)"
msgstr "alternativní http proxy (název_počítače_v_síti: port)"

#: ../satellite_tools/satsync.py:2226
msgid "alternative http proxy username"
msgstr "alternativní uživatelské jméno pro http proxy"

#: ../satellite_tools/satsync.py:2228
msgid "alternative http proxy password"
msgstr "alternativní heslo pro http proxy"

#: ../satellite_tools/satsync.py:2230
msgid "parent SUSE Manager to import content from"
msgstr "nadřízený SUSE Manager, z něhož chcete importovat obsah"

#: ../satellite_tools/satsync.py:2232
msgid "list all available channels and exit"
msgstr "výpis všech dostupných kanálů a ukončení"

#: ../satellite_tools/satsync.py:2234
msgid "help on all error codes mgr-inter-sync returns"
msgstr "nápověda ke všem kódům chyb které vrací mgr-inter-sync"

#: ../satellite_tools/satsync.py:2236
msgid "source mount point for import - disk update only"
msgstr "zdrojový bod připojení pro import - jen aktualizace disku"

#: ../satellite_tools/satsync.py:2238
msgid "do not process patch data"
msgstr "nezpracovávat data záplat"

#: ../satellite_tools/satsync.py:2240
msgid "do not process kickstart data (provisioning only)"
msgstr "nezpracovávat data kickstartu (jen ukládání)"

#: ../satellite_tools/satsync.py:2242
msgid "do not process full package metadata"
msgstr "nezpracovávat úplná metadata balíčku"

#: ../satellite_tools/satsync.py:2244
msgid "do not download, or process any RPMs"
msgstr "nestahovat ani nezpracovávat žádné balíčky RPM"

#: ../satellite_tools/satsync.py:2246
msgid "turn off SSL (not recommended)"
msgstr "vypnout SSL (nedoporučuje se)"

#: ../satellite_tools/satsync.py:2248
msgid "org to which the sync imports data. defaults to the admin account"
msgstr ""
"organizace, do níž synchronizace importuje data; výchozí nastavení je účet "
"správce"

#: ../satellite_tools/satsync.py:2250
msgid "print the configuration and exit"
msgstr "vytisknout konfiguraci a skončit"

#: ../satellite_tools/satsync.py:2252
msgid "alternative server with which to connect (hostname)"
msgstr "alternativní server, kam se chcete připojit (název v síti, hostname)"

#: ../satellite_tools/satsync.py:2254
msgid "synchronize to this step (man satellite-sync for more info)"
msgstr ""
"synchronizovat s tímto krokem (více informací poskytne příkaz \"man "
"satellite-sync\")"

#: ../satellite_tools/satsync.py:2256
msgid "write complete data to tempfile before streaming to remainder of app"
msgstr ""
"před streamováním do zbytku aplikace zapište úplná data do dočasného souboru"

#: ../satellite_tools/satsync.py:2258
msgid "DEBUG ONLY: alternative path to digital system id"
msgstr "POUZE DEBUG: alternativní cesta k ID digitálního systému"

#: ../satellite_tools/satsync.py:2260
msgid "alternative email address(es) for sync output (--email option)"
msgstr ""
"alternativní e-mailové adresa(-y) pro výstup synchronizace (volba --email)"

#: ../satellite_tools/satsync.py:2262
msgid "do not remove rpms when importing from local dump"
msgstr "při importu z lokálního výpisu neodstraňujte rpms"

#: ../satellite_tools/satsync.py:2264
msgid ""
"the fully qualified domain name of the master Satellite. Valid with --mount-"
"point only. Required if you want to import org data and channel permissions."
msgstr ""
"plně kvalifikovaný doménový název serveru Master Satellite. Platí pouze s --"
"mount-point. Vyžadován, chcete-li importovat data organizace a oprávnění "
"kanálu."

#: ../satellite_tools/satsync.py:2274
#, python-format
msgid "ERROR: these arguments make no sense in this context (try --help): %s"
msgstr ""
"CHYBA: tyto argumenty nedávají v tomto kontextu žádný smysl (zkuste --help): "
"%s"

#. An SQL error is fatal... crash and burn
#: ../satellite_tools/satsync.py:2286
#, python-format
msgid "ERROR: Can't connect to the database: %s"
msgstr "CHYBA: Nelze se připojit k databázi: %s"

#: ../satellite_tools/satsync.py:2287
msgid "ERROR: Check if your database is running."
msgstr "CHYBA: Prověřte, zda Vaše databáze běží."

#: ../satellite_tools/satsync.py:2322
#, python-format
msgid "ERROR: --debug-level takes an in integer value within the range %s."
msgstr "CHYBA: --debug-level může mít jen celočíselnou hodnotu v rozsahu %s."

#: ../satellite_tools/satsync.py:2324
msgid "  0  - little logging/messaging."
msgstr "  0  - nízká úroveň zaznamenávání/odesílání zpráv."

#: ../satellite_tools/satsync.py:2325
msgid "  1  - minimal logging/messaging."
msgstr "  1  - minimální úroveň zaznamenávání/odesílání zpráv."

#: ../satellite_tools/satsync.py:2326
msgid "  2  - normal level of logging/messaging."
msgstr "  2  - normální úroveň zaznamenávání/odesílání zpráv."

#: ../satellite_tools/satsync.py:2327
msgid "  3  - lots of logging/messaging."
msgstr "  3  - vysoká úroveň zaznamenávání/odesílání zpráv."

#: ../satellite_tools/satsync.py:2328
msgid "  4+ - excessive logging/messaging."
msgstr "  4+ - nadměrná úroveň zaznamenávání/odesílání zpráv."

#: ../satellite_tools/satsync.py:2341
msgid "ERROR: The --master option is only valid with the --mount-point option"
msgstr "CHYBA: Možnost --master je platná pouze s volbou --mount-point"

#: ../satellite_tools/satsync.py:2351
#, python-format
msgid "ERROR: Unable to lookup Org Id %s"
msgstr "CHYBA: Nelze vyhledat ID organizace %s"

#: ../satellite_tools/satsync.py:2360
msgid ""
"WARNING: --list-channels option overrides any --step option. --step ignored."
msgstr ""
"UPOZORNĚNÍ: Volba --list-channels přepíše jakoukoli volbu --step. Volba --"
"step ignorována."

#: ../satellite_tools/satsync.py:2375
#, python-format
msgid ""
"ERROR: '%s' is not a valid step. See 'man mgr-inter-sync' for more detail."
msgstr ""
"CHYBA: '%s' není platný krok. Další podrobnosti viz 'man mgr-inter-sync'."

#: ../satellite_tools/satsync.py:2407
msgid ""
"ERROR: No channels currently imported; try mgr-inter-sync --list-channels; "
"then mgr-inter-sync -c chn0 -c chn1..."
msgstr ""
"CHYBA: Momentálně nejsou importovány žádné kanály; zkuste mgr-inter-sync --"
"list-kanály; pak mgr-inter-sync -c chn0 -c chn1 ..."

#. int(None) --> TypeError
#. int('a')  --> ValueError
#: ../satellite_tools/satsync.py:2457 ../satellite_tools/satsync.py:2461
msgid "ERROR: --batch-size must have a value within the range: 1..50"
msgstr "CHYBA: - velikost dávky musí mít hodnotu v rozsahu: 1..50"

#: ../satellite_tools/satsync.py:2469
#, python-format
msgid "ERROR: no such directory %s"
msgstr "CHYBA: adresář %s neexistuje"

#: ../satellite_tools/satsync.py:2474
msgid "Error Codes: Returned codes means:"
msgstr "Chybové kódy: Vrácené kódy znamenají:"

#: ../satellite_tools/satsync.py:2475
msgid " -1  - Could not lock file or KeyboardInterrupt or SystemExit"
msgstr " -1  - Nelze zamknout soubor nebo KeyboardInterrupt nebo SystemExit"

#: ../satellite_tools/satsync.py:2476
msgid "  0  - User interrupted or intentional exit"
msgstr "  0  - Uživatel přerušen nebo záměrně ukončen"

#: ../satellite_tools/satsync.py:2477
msgid "  1  - attempting to run more than one instance of mgr-inter-sync."
msgstr "  1  - pokus spustit více než jednu instanci mgr-inter-sync."

#: ../satellite_tools/satsync.py:2478
msgid "  2  - Unable to find synchronization tools."
msgstr "  2  - Nelze najít synchronizační nástroje."

#: ../satellite_tools/satsync.py:2479
msgid "  3  - a general socket exception occurred"
msgstr "  3  - došlo k obecné výjimce soketu"

#: ../satellite_tools/satsync.py:2480
msgid "  4  - an SSL error occurred. Recheck your SSL settings."
msgstr "  4  - došlo k chybě SSL. Zkontrolujte nastavení SSL."

#: ../satellite_tools/satsync.py:2481
msgid "  5  - ISS error"
msgstr "  5  - chyba ISS"

#: ../satellite_tools/satsync.py:2482
msgid "  6  - unhandled exception occurred"
msgstr "  6  - došlo k neošetřené výjimce"

#: ../satellite_tools/satsync.py:2483
msgid "  7  - unknown sync error"
msgstr "  7  - neznámá chyba synchronizace"

#: ../satellite_tools/satsync.py:2484
msgid "  8  - ERROR: must be root to execute"
msgstr "  8  - CHYBA: pro spuštění musíte být root"

#: ../satellite_tools/satsync.py:2485
msgid "  9  - rpclib fault during synchronization init"
msgstr "  9  - chyba rpclib během zahájení synchronizace"

#: ../satellite_tools/satsync.py:2486
msgid "  10 - synchronization init error"
msgstr "  10 - chyba zahájení synchronizace"

#: ../satellite_tools/satsync.py:2487
msgid "  11 - Error parsing XML stream"
msgstr "  11 - Chyba při analýze toku XML"

#: ../satellite_tools/satsync.py:2488
msgid "  12 - Channel do not exist"
msgstr "  12 - Kanál neexistuje"

#: ../satellite_tools/satsync.py:2489
msgid "  13 - SQL error during importing package metadata"
msgstr "  13 - Chyba SQL při importu metadat balíčku"

#: ../satellite_tools/satsync.py:2490
msgid "  14 - SQL error during linking channel packages"
msgstr "  14 - Chyba SQL při spojování balíčků kanálů"

#: ../satellite_tools/satsync.py:2491
msgid "  15 - SQL error during xml processing"
msgstr "  15 - Chyba SQL během zpracování xml"

#: ../satellite_tools/satsync.py:2492
msgid "  16 - server.mount_point not set in the configuration file"
msgstr "  16 - server.mount_point není v konfiguračním souboru nastaven"

#: ../satellite_tools/satsync.py:2493
msgid ""
"  17 - SQL error during retrieving the channels already imported in the SUSE "
"Manager database"
msgstr ""
"  17 - Chyba SQL při načítání kanálů již importovaných v databázi SUSE "
"Manager"

#: ../satellite_tools/satsync.py:2494
msgid "  18 - Wrong db connection string in rhn.conf"
msgstr "  18 - Chybný připojovací řetězec db v rhn.conf"

#: ../satellite_tools/satsync.py:2495
msgid "  19 - Bad arguments"
msgstr "  19 - Špatné argumenty"

#: ../satellite_tools/satsync.py:2496
msgid "  20 - Could not connect to db."
msgstr "  20 - Nelze se připojit k databázi."

#: ../satellite_tools/satsync.py:2497
msgid "  21 - Bad debug level"
msgstr "  21 - Špatná úroveň ladění"

#: ../satellite_tools/satsync.py:2498
msgid "  22 - Not valid step"
msgstr "  22 - Neplatný krok"

#: ../satellite_tools/satsync.py:2499
msgid "  24 - no such file"
msgstr "  24 - soubor neexistuje"

#: ../satellite_tools/satsync.py:2500
msgid "  25 - no such directory"
msgstr "  25 - adresář neexistuje"

#: ../satellite_tools/satsync.py:2501
msgid "  26 - mount_point does not exist"
msgstr "  26 - bod připojení (mount_point) neexistuje"

#: ../satellite_tools/satsync.py:2502
msgid "  27 - No such org"
msgstr "  27 - Organizace neexistuje"

#: ../satellite_tools/satsync.py:2503
msgid "  28 - error: --master is only valid with --mount-point"
msgstr "  28 - chyba: --master je platný pouze s --mount-point"

#: ../satellite_tools/satsync.py:2510
#, python-format
msgid "ERROR: unknown dump version, try one of %s"
msgstr "CHYBA: neznámá verze výpisu, zkuste jeden z %s"

#~ msgid "Red Hat Satellite Welcome Message"
#~ msgstr "Uvítací zpráva Red Hat Satellite"
