# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Hirofumi Saito <hi_saito@yk.rim.or.jp>, 2004.
# kiyoto james hashida <khashida@brisbane.redhat.com>, 2007.
# Kiyoto James Hashida <khashida@redhat.com>, 2006.
# Noriko Mizumoto <noriko@redhat.com>, 2004-2007.
# noriko <noriko@fedoraproject.org>, 2011.
# Tadashi Jokagi <fedora@elf.no-ip.org>, 2005.
# Yukihiro Nakai <ynakai@redhat.com>, 2001.
# Jiri Dostal <jdostal@redhat.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-08-26 14:48+0200\n"
"PO-Revision-Date: 2018-03-16 10:54+0000\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language-Team: Japanese <trans-ja@lists.fedoraproject.org>\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Zanata 4.6.2\n"

#: ../server/handlers/app/packages.py:192
#: ../server/handlers/xmlrpc/registration.py:215
#: ../server/handlers/xmlrpc/registration.py:1168
#: ../server/handlers/xmlrpc/registration.py:1307
#: ../server/configFilesHandler.py:129
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   %s アカウントは本サーバー上では非アクティブになっていま"
"す。\n"
"                   組織の管理者にお問い合わせください。"

#: ../server/handlers/applet/applet.py:78
msgid "Your system was not found in the RHN database"
msgstr "システムが RHN データベース内には見つかりませんでした。"

#: ../server/handlers/sat/auth.py:45
msgid "ISS is disabled on this satellite."
msgstr "ISS がこの Satellite では無効になっています。"

#: ../server/handlers/sat/auth.py:50
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "サーバー「%s」は ISS に有効になっていません。"

#: ../server/handlers/xmlrpc/proxy.py:65
#, fuzzy, python-format
msgid "Spacewalk Proxy service not enabled for server profile: \"%s\""
msgstr ""
"RHN Proxy サービスがサーバープロファイルに対して有効になっていません: 「%s」"

#: ../server/handlers/xmlrpc/proxy.py:85
msgid "Invalid session key"
msgstr "無効なセッションキー"

#: ../server/handlers/xmlrpc/proxy.py:93
msgid "This server ID no longer exists"
msgstr "このサーバー ID は既になくなりました"

#: ../server/handlers/xmlrpc/scap.py:104
#, fuzzy
msgid "Invalid system_id/action_id pair."
msgstr "無効なシステム認証情報です。"

#: ../server/handlers/xmlrpc/errata.py:64
#, python-format
msgid "Expected a package name, not: %s"
msgstr "パッケージ名が期待されています、次ではありません: %s"

#: ../server/handlers/xmlrpc/errata.py:115
#, python-format
msgid "Expected a package, not: %s"
msgstr "パッケージが期待されています、 次ではありません: %s"

#: ../server/handlers/xmlrpc/queue.py:433
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr "無効な動作値タイプ %s (%s)"

#: ../server/handlers/xmlrpc/queue.py:464
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "動作 %s はサーバー %s に属していません"

#: ../server/handlers/xmlrpc/registration.py:194
msgid "Required data missing"
msgstr "必要なデータが足りません"

#: ../server/handlers/xmlrpc/registration.py:198
msgid "Required members missing"
msgstr "必要なメンバーが足りません"

#: ../server/handlers/xmlrpc/registration.py:207
msgid "Attempt to register a system to an invalid username"
msgstr "システムを無効なユーザー名に登録しようとしています"

#: ../server/handlers/xmlrpc/registration.py:839
msgid "Invalid system release version requested"
msgstr "無効なシステムリリースバージョンを要求しています"

#: ../server/handlers/xmlrpc/registration.py:1063
msgid ""
"Unable to find a valid network interface, both ipaddr and ip6addr not found."
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:1115
#, fuzzy
msgid "Red Hat Satellite Welcome Message"
msgstr "Red Hat Network のようこそメッセージ"

#: ../server/handlers/xmlrpc/registration.py:1125
#, fuzzy
msgid "Red Hat Satellite Privacy Statement"
msgstr "Red Hat Network プライバシーステートメント"

#: ../server/handlers/xmlrpc/registration.py:1146
msgid "Expected a dictionary as a product argument"
msgstr "製品の引数としてディクショナリが期待されています"

#: ../server/handlers/xmlrpc/registration.py:1374
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr "無効な値 '%s' − %s (%s)"

#: ../server/handlers/xmlrpc/up2date.py:233
#, python-format
msgid "Invalid value %s (%s)"
msgstr "無効な値  %s (%s)"

#: ../server/importlib/userAuth.py:98
msgid "You are not authorized to manage packages in the null org"
msgstr "null org にあるパッケージを管理する権限が与えられていません"

#: ../server/importlib/userAuth.py:103
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "%s org 内のパッケージの管理は許可されていません"

#: ../server/importlib/userAuth.py:121
msgid "You are not allowed to perform administrative tasks"
msgstr "管理に関する作業を行う許可がありません"

#: ../server/importlib/userAuth.py:144
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr ""
"チャンネル %s の管理は許可されていないか、 またはこのチャンネルは存在していま"
"せん"

#: ../server/importlib/userAuth.py:204
#, fuzzy, python-format
msgid ""
"\n"
"               %s Account has been deactivated on this server.\n"
"               Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   %s アカウントは本サーバー上では非アクティブになっていま"
"す。\n"
"                   組織の管理者にお問い合わせください。"

#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr ""

#: ../server/rhnHandler.py:75
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr "システムプロファイルに対してサービスが有効になっていません: 「%s」"

#: ../server/rhnServer/server_class.py:97
#, python-format
msgid "Architecture `%s' is not supported"
msgstr "アーキテクチャ `%s' はサポートされていません"

#: ../server/rhnServer/server_token.py:78
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "トークン `%s' には 1 つ以上のベースチャンネルが割り当てられています"

#: ../server/rhnServer/server_token.py:80
msgid "Conflicting base channels"
msgstr "競合しているベースチャンネル"

#: ../server/rhnServer/server_token.py:190
#, python-format
msgid "Failed to add server to group %s"
msgstr "グループ %s へのサーバーの追加に失敗しました"

#: ../server/rhnServer/server_token.py:503
#, python-format
msgid "Maximum usage count of %s reached"
msgstr "最大使用数 %s に達しました"

#: ../server/rhnServer/server_token.py:744
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""
"異なるベースエンタイトルメントでの再登録トークンの積み重ねには対応していませ"
"ん"

#: ../server/rhnServer/server_token.py:811
#, python-format
msgid "Could not find token '%s'"
msgstr "トークン「%s」は見つかりませんでした"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:843
msgid "Tokens from mismatching orgs"
msgstr "不一致の 　org からのトークンです"

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:853
msgid "Kickstart session mismatch"
msgstr "キックスタートセッションの不一致です"

#: ../server/rhnServer/server_token.py:877
msgid "Stacking of re-registration tokens is not supported"
msgstr "再登録トークンの積み重ねには対応していません"

#: ../server/rhnChannel.py:1992
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""
"ご使用のアカウントには (release='%(release)s', "
"arch='%(arch)s')%(www_activation)s に一致するチャンネルのいずれにもアクセスが"
"ありません。"

#: ../server/rhnChannel.py:2002
msgid ""
"\n"
"If you have a registration number, please register with it first at http://"
"www.redhat.com/apps/activate/ and then try again.\n"
"\n"
msgstr ""
"\n"
"登録番号をお持ちの場合は、 まずその番号を http://www.redhat.com/apps/"
"activate/ にて登録してからやり直してください。\n"
"\n"

#: ../server/rhnChannel.py:2012
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr "リリース (%s, %s にはサブスクリプションパーミッションが足りません。"

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2276 ../server/rhnChannel.py:2287
#: ../server/rhnChannel.py:2302
msgid "System Registered but Inactive"
msgstr "システムは登録されていますが非アクティブになっています"

#: ../server/rhnChannel.py:2277
#, fuzzy, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it is not subscribed to a channel. If you have not yet\n"
"activated your product for service, please visit our website at:\n"
"\n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...to activate your product."
msgstr ""
"\n"
"アーキテクチャとオペレーティングシステムのリリースの組み合わせ (%s、 %s)\n"
"が無効です。 システムは登録されていますが、 チャンネルにサブスクライブされ"
"て\n"
"いないため更新は行われません。 製品のアクティベートをまだ行っていない場合は\n"
"次の Web サイトに行き製品のアクティベートを行ってください。\n"
"  \n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"  "

#: ../server/rhnChannel.py:2288
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""
"\n"
"アーキテクチャとオペレーティングシステムのリリースの組み合わせ (%s、 %s)\n"
"が無効です。 システムは登録されていますが、 ベースチャンネルにサブスクライ"
"ブ\n"
"させることができなかったため更新は行われません。 詳細については組織の管理者"
"に\n"
"お問い合わせください。\n"

#: ../server/rhnChannel.py:2295
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  このシステムは正常に登録されていますが、 エンタイトルメントがまだ付与されて"
"いません。\n"
"  システムにエンタイトルメントを付与するには次の Web サイトにログインしてくだ"
"さい。\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnChannel.py:2303
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  このシステムは正常に登録されていますが、 利用できるエンタイトルメントがあり"
"ませんでした。\n"
"  システムにエンタイトルメントを付与するには次の Web サイトにログインしてくだ"
"さい。\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/apacheAuth.py:66
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "不完全なプロキシ認証トークンです: %s"

#: ../server/apacheAuth.py:84
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr "送信されたプロキシ署名 %s がこちら側の %s と一致しません。"

#: ../server/apacheAuth.py:119
msgid "declined proxy authentication"
msgstr "プロキシ認証が拒否されました"

#: ../server/rhnUser.py:289 ../server/rhnUser.py:292
msgid "Invalid username/password combination"
msgstr "無効なユーザー名とパスワードの組み合わせです"

#. nope, not reserved either
#: ../server/rhnUser.py:467
#, python-format
msgid "Username `%s' has not been reserved"
msgstr "ユーザー名 `%s' は予約されていません"

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:473
msgid "E-mail address not specified"
msgstr "Email アドレスが指定されていません"

#: ../server/rhnUser.py:509
#, python-format
msgid "username should be at least %d characters"
msgstr "ユーザー名は少なくとも %d 文字以上にしてください"

#: ../server/rhnUser.py:512
#, python-format
msgid "username should be less than %d characters"
msgstr "ユーザー名は %d 文字未満にしてください"

#: ../server/rhnUser.py:523
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr "ユーザー名 = `%s'、 無効な文字 `%s'"

#: ../server/rhnUser.py:542
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr "Email アドレスは %s 文字以内にしてください"

#: ../server/rhnUser.py:623
#, python-format
msgid "password must be at least %d characters"
msgstr "パスワードは少なくとも %d 文字に以上にしてください"

#: ../server/rhnUser.py:626
#, python-format
msgid "Password must be shorter than %d characters"
msgstr "パスワードは %d 文字以内にしてください"

#: ../server/rhnUser.py:644
#, python-format
msgid "password contains character `%s'"
msgstr "パスワードに `%s' 文字が含まれています"

#: ../server/rhnUser.py:651
#, python-format
msgid "username should be at least %d characters long"
msgstr "ユーザー名は少なくとも %d 文字以上の長さにしてください"

#: ../server/rhnUser.py:662
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr "%s で終わるユーザー名は登録できません"

#: ../server/apacheRequest.py:59
#, python-format
msgid "Invalid request received (%s)."
msgstr "無効な要求を受け取りました (%s)。"

#: ../server/apacheRequest.py:120
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""
"重要なメッセージです:\n"
"%s"

#: ../server/apacheRequest.py:149
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""
"「%s」の実行中: 次をキャッチしました\n"
"%s : %s\n"

#: ../server/apacheRequest.py:606
#, python-format
msgid "Invalid URI %s"
msgstr "無効な URI %s"

#: ../server/rhnPackage.py:49 ../server/rhnPackage.py:87
#: ../server/rhnPackage.py:107 ../server/rhnPackage.py:158
#, python-format
msgid "Invalid RPM package %s requested"
msgstr "無効な RPM パッケージ %s を要求しています"

#: ../server/rhnPackage.py:112
msgid "Package not found"
msgstr "パッケージが見つかりません"

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:53
msgid "This does not appear to be a valid username."
msgstr "有効なユーザー名ではないようです。"

#: ../common/rhnException.py:54
msgid "Invalid username and password combination."
msgstr "ユーザー名とパスワードの組み合わせが無効です。"

#: ../common/rhnException.py:55
msgid "This login is already taken, or the password is incorrect."
msgstr "このログインは既に使用済か、 またはパスワードが間違っています。"

#: ../common/rhnException.py:56
msgid "Permission denied."
msgstr "パーミッションが拒否されました。"

#: ../common/rhnException.py:57
msgid "Object not found."
msgstr "オブジェクトが見つかりません。"

#: ../common/rhnException.py:58
msgid "Invalid System Digital ID."
msgstr "無効なシステムデジタル ID です。"

#: ../common/rhnException.py:59
msgid "Invalid System Credentials."
msgstr "無効なシステム認証情報です。"

#: ../common/rhnException.py:60
msgid "Could not retrieve user data from database."
msgstr "データベースからユーザーのデータを読み出すことができませんでした。"

#: ../common/rhnException.py:61
msgid "Valid username required."
msgstr "有効なユーザー名が必要です。"

#: ../common/rhnException.py:62
msgid "Valid password required."
msgstr "有効なパスワードが必要です。"

#: ../common/rhnException.py:63
msgid "Minimum username length violation."
msgstr "ユーザー名の最短の長さを違反しています。"

#: ../common/rhnException.py:64
msgid "Minimum password length violation."
msgstr "パスワードの最短の長さを違反しています。"

#: ../common/rhnException.py:65
msgid "The username contains invalid characters."
msgstr "ユーザー名に無効な文字が含まれています。"

#: ../common/rhnException.py:66
msgid "File not found."
msgstr "ファイルが見つかりません。"

#: ../common/rhnException.py:67
msgid "Architecture and OS version combination is not supported."
msgstr ""
"アーキテクチャとオペレーティングシステムのバージョンの組み合わせは対応してい"
"ません。"

#: ../common/rhnException.py:68
msgid "Could not retrieve system data from database."
msgstr "データベースからシステムのデータを読み出すことができませんでした。"

#: ../common/rhnException.py:69
msgid "Invalid arguments passed to function."
msgstr "関数に無効な引数が渡されました。"

#: ../common/rhnException.py:70
msgid "Unable to retrieve requested entry."
msgstr "要求されたエントリを読み出せません。"

#: ../common/rhnException.py:71
msgid "Could not update database entry."
msgstr "データベースのエントリを更新できませんでした。"

#: ../common/rhnException.py:72
msgid "Unsupported server architecture."
msgstr "未対応のサーバーアーキテクチャです。"

#: ../common/rhnException.py:73
#, fuzzy, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running mgr_register as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     匿名サーバー機能は利用できなくなっています。\n"
"\n"
"     root になり rhn_register (Red Hat Enterprise Linux 3+ の場合は\n"
"     up2date --register) を実行してこのシステムの再登録を行ってください。\n"
"     このシステムに対して RHN サービスを有効にする場合は、 \n"
"     https://%(hostname)s/rhn/systems/SystemEntitlements.do に行くか\n"
"     https://%(hostname)s でログインしてから「概要」タブで「サブスクリプショ"
"ン管理」\n"
"     を選択します。"

#: ../common/rhnException.py:81
msgid "Record not available in the database."
msgstr "データベースに使用できる記録がありません。"

#: ../common/rhnException.py:82
msgid "Invalid value for entry."
msgstr "エントリには無効な値です。"

#: ../common/rhnException.py:83
#, fuzzy, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for SUSE Manager.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     Red Hat Network 用の有効なエンタイトルメントがこのシステムにはありませ"
"ん。\n"
"     https://%(hostname)s/rhn/systems/SystemEntitlements.do に行くか、\n"
"     https://%(hostname)s でログインしてから「概要」タブで「サブスクリプショ"
"ン管理」\n"
"     を選択してシステムに RHN サービスを有効にします。\n"
"     "

#: ../common/rhnException.py:89
msgid "Channel error"
msgstr "チャンネルエラー"

#: ../common/rhnException.py:90
msgid "Client session token is invalid."
msgstr "クライアントのセッショントークンが無効です。"

#: ../common/rhnException.py:91
msgid "Client session token has expired."
msgstr "クライアントのセッショントークンの有効期限が切れています。"

#: ../common/rhnException.py:92
msgid "You are not authorized to retrieve the requested object."
msgstr "要求されたオブジェクトを読み出す権限が与えられていません。"

#: ../common/rhnException.py:93
msgid "Invalid action"
msgstr "無効な動作"

#: ../common/rhnException.py:94
msgid "You are not allowed to perform administrative tasks on this system."
msgstr "このシステムで管理関連の作業を行う許可がありません。"

#: ../common/rhnException.py:96
msgid "The system is already subscribed to the specified channel."
msgstr "システムは既に指定チャンネルにサブスクライブされています。"

#: ../common/rhnException.py:97
msgid "The system is not currently subscribed to the specified channel."
msgstr "現在、 システムは指定チャンネルにサブスクライブされていません。"

#: ../common/rhnException.py:98
msgid "The specified channel does not exist."
msgstr "指定されたチャンネルが存在していません。"

#: ../common/rhnException.py:99
msgid "Invalid channel version."
msgstr "無効なチャンネルバージョンです。"

#: ../common/rhnException.py:100
#, fuzzy
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""
"\n"
"     ユーザーグループのメンバーシップの上限を超えています。\n"
"\n"
"     ご使用のアカウントの現在の設定では別のユーザーアカウントの追加は行えませ"
"ん。\n"
"     RHN にサブスクライブさせることができる最小ユーザー数を変更する必要がある"
"場合は\n"
"     組織の管理者にご確認ください。\n"
"     \n"
"     "

#: ../common/rhnException.py:108
#, fuzzy
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""
"\n"
"     システムグループのメンバーシップの上限を超えています。\n"
"\n"
"     ご使用のアカウントの現在の設定では別のシステムプロファイルの追加は行えま"
"せん。\n"
"     RHN アカウントにサブスクライブさせることができる最小システムプロファイル"
"数を\n"
"     変更する必要がある場合は組織の管理者にご確認ください。\n"
"     \n"
"     "

#: ../common/rhnException.py:116
#, fuzzy
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""
"\n"
"     無効なアーキテクチャです。\n"
"\n"
"     このパッケージのこのアーキテクチャは Red Hat Network では対応していませ"
"ん。\n"
"     "

#: ../common/rhnException.py:121
msgid "Invalid RPM header"
msgstr "無効な RPM ヘッダーです"

#: ../common/rhnException.py:122
msgid ""
"\n"
"    This system is already registered as a Salt Minion. If you want to "
"register it as a traditional client\n"
"    please delete it first via the web UI or API and then register it using "
"the traditional tools.\n"
"    "
msgstr ""

#. For the uploading tools
#: ../common/rhnException.py:127
msgid "Invalid information uploaded to the server"
msgstr "サーバーに無効な情報がアップロードされました"

#: ../common/rhnException.py:128
msgid "Error uploading network interfaces configuration."
msgstr ""
"ネットワークインターフェースの設定をアップロード中にエラーが発生しました。"

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""
"\n"
"     一意性制約の違反によりパッケージのアップロードが失敗しました。\n"
"     パッケージに重複する依存関係がないこと、 またはこのパッケージが\n"
"     まだサーバーに存在していないことを確認してください。\n"
"     "

#: ../common/rhnException.py:134
#, fuzzy
msgid ""
"\n"
"     The --force rhnpush option is disabled on this server.\n"
"     Please contact your SUSE Manager administrator for more help.\n"
"     "
msgstr ""
"\n"
"     このサーバー上では --force rhnpush のオプションは無効になっています。\n"
"     詳細については担当の Satellite 管理者にお問い合わせください。\n"
"     "

#. 60-70: token errors
#: ../common/rhnException.py:140
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""
"\n"
"     指定されたアクティベーショントークンがサーバーに見つかりませんでした。\n"
"     有効なキーでやり直してください。\n"
"     "

#: ../common/rhnException.py:144
msgid "Too many systems registered using this registration token"
msgstr "この登録トークンを使用して登録されたシステムが多すぎます"

#: ../common/rhnException.py:145
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr ""
"無効な設定、 またはサポートされていないか不適切な設定を含むトークンです"

#: ../common/rhnException.py:146
msgid "Conflicting activation tokens"
msgstr "アクティベーショントークンが競合しています"

#. 70-80: channel subscription errors
#: ../common/rhnException.py:149
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:152
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""
"\n"
"     指定チャンネルへのサブスクリプションパーミッションがありません。\n"
"     詳細については組織の管理者またはチャンネル管理者にお問い合わせくださ"
"い。\n"
"     \n"
"     "

#: ../common/rhnException.py:157
msgid "You can not unsubscribe from base channel."
msgstr "ベースチャンネルのサブスクリプションを解除することはできません。"

#: ../common/rhnException.py:158
msgid "SUSE Manager or Proxy channel can not be subscribed."
msgstr ""

#. 80-90: server group errors
#: ../common/rhnException.py:161
msgid "There was an error while trying to join the system to its groups"
msgstr "システムをそのグループに参加させる途中でエラーが発生しました"

#. 90-100: entitlement errors
#: ../common/rhnException.py:164
msgid "Unable to entitle system"
msgstr "システムにエンタイトルメントを付与できません"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:167
msgid "Maximum e-mail length violation."
msgstr "Email の最大長を超えています。"

#: ../common/rhnException.py:168
msgid "This system has been previously registered."
msgstr "このシステムは既に登録されています。"

#: ../common/rhnException.py:169
msgid "Invalid username"
msgstr "無効なユーザー名"

#. 140-159 applet errors
#: ../common/rhnException.py:172
msgid "Unable to look up server"
msgstr "サーバーを検出できません"

#. 160-179: OSAD errors
#: ../common/rhnException.py:175
msgid "Required argument is missing"
msgstr "必要な引数がありません"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:178
msgid "No entitlement information tied to hardware"
msgstr "ハードウェアに関連づけられているエンタイトルメント情報がありません"

#: ../common/rhnException.py:179
msgid "Installation number is not entitling"
msgstr "インストール番号にエンタイトルメントが付与されていません"

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:182
msgid "Maximum username length violation"
msgstr "ユーザー名の最大長を超えています"

#: ../common/rhnException.py:183
msgid "Maximum password length violation"
msgstr "パスワードの最大長を超えています"

#: ../common/rhnException.py:184
msgid "This user has read only API access. Action denied."
msgstr ""

#: ../common/rhnException.py:186
#, fuzzy
msgid "System Name cannot be less than 1 character"
msgstr "ユーザー名は %d 文字未満にしてください"

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:190
#, fuzzy
msgid "SUSE Manager Proxy error."
msgstr "RHN Proxy のエラーです。"

#: ../common/rhnException.py:191
#, fuzzy
msgid "SUSE Manager Proxy unable to login."
msgstr "RHN Proxy によるログインができません。"

#. issued by a SUSE Manager Server/Satellite to the proxy
#: ../common/rhnException.py:193
msgid ""
"\n"
"     SUSE Manager Proxy system ID does not match a Spacewalk Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""

#: ../common/rhnException.py:197
#, fuzzy
msgid "SUSE Manager Proxy session token is invalid."
msgstr "RHN Proxy セッショントークンが無効です。"

#: ../common/rhnException.py:198
#, fuzzy
msgid "SUSE Manager Proxy session token has expired."
msgstr "RHN Proxy セッショントークンの期限が切れています。"

#. 2000-2999: Red Hat Satellite specific errors:
#: ../common/rhnException.py:202
#, fuzzy
msgid ""
"\n"
"      user creation is not allowed via mgr_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""
"\n"
"     RHN Satellite ユーザーの作成に rhn_register (Red Hat Enterprise Linux "
"3\n"
"     またはそれ以降の場合は up2date --register) の使用は許可されていません;\n"
"     システム管理者にアカウントの作成を依頼してください。\n"
"     "

#: ../common/rhnException.py:206
#, fuzzy
msgid ""
"\n"
"     This SUSE Manager server is not allowed to use Inter Server Sync on "
"this server\n"
"     "
msgstr ""
"\n"
"     本 Satellite サーバーは本 Satellite での Inter Satellite Sync の使用は許"
"可されていません。\n"
"     "

#: ../common/rhnException.py:209
#, fuzzy
msgid ""
"\n"
"     Inter Server Sync is disabled on this SUSE Manager Server.\n"
"     "
msgstr ""
"\n"
"     Inter Satellite Sync は本 Satellite では無効になっています。\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:214
msgid "Invalid datatype passed"
msgstr "無効なデータタイプが渡されています"

#: ../common/rhnException.py:215
msgid "Unable to retrieve channel"
msgstr "チャンネルが読み出せません"

#: ../common/rhnException.py:216
msgid "Unable to retrieve package"
msgstr "パッケージが読み出せません"

#: ../common/rhnException.py:217
msgid "Unable to retrieve erratum"
msgstr "エラータが読み出せません"

#: ../common/rhnException.py:218
msgid "File is missing"
msgstr "ファイルがありません"

#: ../common/rhnException.py:219
msgid "Function retrieval error"
msgstr "関数読み出しのエラーです"

#: ../common/rhnException.py:220
msgid "Function execution error"
msgstr "関数実行エラーです"

#: ../common/rhnException.py:221
msgid "Missing version string"
msgstr "バージョン文字列がありません"

#: ../common/rhnException.py:222
msgid "Invalid version string"
msgstr "無効なバージョン文字列です"

#: ../common/rhnException.py:223
msgid "Mismatching versions"
msgstr "バージョンが一致しません"

#: ../common/rhnException.py:224
msgid "Invalid channel version"
msgstr "無効なチャンネルバージョンです"

#: ../common/rhnException.py:225
msgid "No comps file for channel"
msgstr "チャンネル用の comps ファイルがありません"

#: ../common/rhnException.py:226
msgid "Unable to retrieve comps file"
msgstr "comps ファイルが読み出せません"

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:229
msgid "Configuration action missing"
msgstr "設定動作がありません"

#: ../common/rhnException.py:230
msgid "File too large"
msgstr "ファイルが長すぎます"

#: ../common/rhnException.py:231
msgid "File contains binary data"
msgstr "ファイルにバイナリデータが含まれています"

#: ../common/rhnException.py:232
msgid "Configuration channel is not empty"
msgstr "設定チャンネルが空になっていません"

#: ../common/rhnException.py:233
msgid "Permission error"
msgstr "パーミッションエラーです"

#: ../common/rhnException.py:234
msgid "Content missing for configuration file"
msgstr "設定ファイルの内容がありません"

#: ../common/rhnException.py:235
msgid "Template delimiters not specified"
msgstr "テンプレートの区切り文字が指定されていません"

#: ../common/rhnException.py:236
msgid "Configuration channel does not exist"
msgstr "設定チャンネルが存在していません"

#: ../common/rhnException.py:237
msgid "Configuration channel already exists"
msgstr "設定チャンネルは既に存在しています"

#: ../common/rhnException.py:238
msgid "File missing from configuration channel"
msgstr "設定チャンネルからのファイルがありません"

#: ../common/rhnException.py:239
msgid "Different revision of this file is uploaded"
msgstr "このファイルの別の改訂版がアップロードされています"

#: ../common/rhnException.py:240
msgid "File already uploaded to configuration channel"
msgstr "ファイルは既に設定チャンネルにアップロードされています"

#: ../common/rhnException.py:241
msgid "File size exceeds remaining quota space"
msgstr "ファイルサイズが残りの上限領域を超えています"

#: ../common/rhnException.py:242
msgid "Full path of file must be specified"
msgstr "ファイルの完全パスを指定してください"

#: ../common/rhnException.py:243
msgid "Invalid revision number"
msgstr "無効な改訂版番号です"

#: ../common/rhnException.py:244
msgid "Cannot compare files of different file type"
msgstr "タイプが異なるファイル同士は比較できません"

#. 5000 - 5999: client content uploading errors
#. 5000 - 5099: crash reporting errors
#: ../common/rhnException.py:248
msgid "Crash information is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:249
msgid "Crash file information is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:250
msgid "Error composing crash directory path"
msgstr ""

#: ../common/rhnException.py:251
msgid "Error composing crash file path"
msgstr ""

#: ../common/rhnException.py:252 ../common/rhnException.py:259
#, fuzzy
msgid "Invalid content encoding"
msgstr "無効なアイテムコード"

#: ../common/rhnException.py:253
#, fuzzy
msgid "Invalid crash name"
msgstr "無効なパッケージ名です"

#: ../common/rhnException.py:254
msgid "Crash reporting is disabled for this organization"
msgstr ""

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:256
msgid "SCAP results file transfer is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:257
msgid "Error composing directory path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:258
msgid "Error composing file path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:306
#, fuzzy
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at scc.suse.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""
"\n"
"     要求の処理中にエラーが発生しました。 問題が解決しない場合は、\n"
"     bugzilla.redhat.com にてバグ報告を提出してください。\n"
"     バグ報告を行う場合は、 エラーが起きたときに何を行おうとしていたのか、\n"
"     また問題を再現する場合の手順などを詳しく記入していただけるよう\n"
"     お願いします。\n"

#: ../common/rhnException.py:358
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""
"エラーメッセージ:\n"
"    %s\n"

#: ../common/rhnException.py:360
#, python-format
msgid "Error Class Code: %s\n"
msgstr "エラークラスコード: %s\n"

#: ../common/rhnException.py:363
#, python-format
msgid "Error Class Info: %s\n"
msgstr "エラークラス情報: %s\n"

#: ../common/rhnException.py:365
#, python-format
msgid "Explanation: %s"
msgstr "説明: %s"

#: ../common/rhnTB.py:205
#, python-format
msgid "ERROR: %s %s: %s"
msgstr ""

#: ../common/rhnTB.py:207
#, python-format
msgid "TRACEBACK: %s"
msgstr ""

#: ../satellite_tools/disk_dumper/iss.py:1294
#: ../satellite_tools/disk_dumper/iss.py:1298
#, python-format
msgid "format of %s should be at least YYYYMMDD.\n"
msgstr ""

#: ../satellite_tools/reposync.py:111 ../satellite_tools/satsync.py:439
msgid "+++ sending log as an email +++"
msgstr ""

#: ../satellite_tools/reposync.py:114
#, python-format
msgid "%s sync. report from %s"
msgstr ""

#: ../satellite_tools/reposync.py:124 ../satellite_tools/satsync.py:449
msgid "+++ email requested, but there is nothing to send +++"
msgstr ""

#: ../satellite_tools/messages.py:26
#, python-format
msgid ""
"\n"
"ERROR: executing step %s. Error is:\n"
"%s\n"
msgstr ""

#: ../satellite_tools/messages.py:31
#, python-format
msgid ""
"\n"
"ERROR: there was a problem accessing the channel data from your temporary\n"
"       repository. Did you migrate all of the data from the channel ISOs\n"
"       do this directory? If so, please recheck the channels ISOs, ensure\n"
"       that you have them all, and then iteratively remount and repopulate\n"
"       the temporary repository (%s).\n"
msgstr ""

#: ../satellite_tools/messages.py:39
#, python-format
msgid ""
"\n"
"ERROR: there was a problem synchronizing the information.\n"
"       Error message: %s\n"
msgstr ""

#: ../satellite_tools/messages.py:44
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       Depending on the specific error details, please review your "
"configuration,\n"
"       basic network connectivity, and/or name resolution, and try again.\n"
"       Error message: %s\n"
msgstr ""

#: ../satellite_tools/messages.py:51
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       If the master satellite is older than v5.3, it does not have ISS "
"capability.\n"
"       Otherwise, depending on the specific error details, please review "
"your\n"
"       configuration, basic network connectivity, and/or name resolution, "
"and try again.\n"
"       Error message: %s\n"
msgstr ""

#: ../satellite_tools/messages.py:59
#, python-format
msgid ""
"\n"
"ERROR: a child-channel cannot be synced without its parent being synced as\n"
"       well. A parent needs to be either (a) previously synced or (b) "
"synced\n"
"       in tandem with the desired child-channel. Missing parents for this\n"
"       transaction:\n"
"       %s\n"
msgstr ""

#: ../satellite_tools/messages.py:67
#, python-format
msgid ""
"\n"
"ERROR: you are not entitled to sync a channel in this set of channels.\n"
"Please contact your SUSE Manager contact\n"
"%s"
msgstr ""

#: ../satellite_tools/messages.py:72
#, python-format
msgid "  ERROR: not enough free space (%s KB) on device."
msgstr ""

#: ../satellite_tools/messages.py:74
#, python-format
msgid "    %3d/%s Fetch successful: %s (%s bytes)"
msgstr ""

#: ../satellite_tools/messages.py:75
#, fuzzy, python-format
msgid "    Extinct package:  %s"
msgstr "パッケージが期待されています、 次ではありません: %s"

#: ../satellite_tools/messages.py:76
#, python-format
msgid "   Total size: %s"
msgstr ""

#: ../satellite_tools/messages.py:77
#, python-format
msgid "      Downloaded %s of %s. Estimated remaining time: %s"
msgstr ""

#: ../satellite_tools/messages.py:78
#, python-format
msgid "    Fetch unsuccessful: %s"
msgstr ""

#: ../satellite_tools/messages.py:79
#, python-format
msgid "   RPM fetch summary: %s"
msgstr ""

#: ../satellite_tools/messages.py:80
#, python-format
msgid "       success: %d"
msgstr ""

#: ../satellite_tools/messages.py:81
#, python-format
msgid "       failed:  %d"
msgstr ""

#: ../satellite_tools/messages.py:82
#, python-format
msgid "       extinct: %d"
msgstr ""

#: ../satellite_tools/messages.py:84
#, python-format
msgid "   Retrieving / parsing *relevant* package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:85
#, python-format
msgid "   Retrieving / parsing errata data: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:86
#, python-format
msgid "   Retrieving / parsing kickstart data: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:87
#, python-format
msgid "   Retrieving / parsing kickstart tree files: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:88
#, python-format
msgid "   Importing *relevant* package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:89
msgid "   * WARNING: this may be a slow process."
msgstr ""

#: ../satellite_tools/messages.py:90
#, fuzzy
msgid "Linking packages to channels"
msgstr "競合しているベースチャンネル"

#: ../satellite_tools/messages.py:91
#, python-format
msgid "   Importing *relevant* errata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:92
msgid "   No new kickstartable tree to import"
msgstr ""

#: ../satellite_tools/messages.py:93
#, python-format
msgid "Importing kickstartable trees (%d)"
msgstr ""

#: ../satellite_tools/messages.py:94
#, python-format
msgid "Imported kickstartable trees (%d)"
msgstr ""

#: ../satellite_tools/satsync.py:258
#, python-format
msgid "No handler for step %s"
msgstr ""

#. Try one more time - this time it should be faster since
#. everything should be cached
#: ../satellite_tools/satsync.py:270
msgid "Environment changed, trying again..."
msgstr ""

#: ../satellite_tools/satsync.py:277
msgid "ERROR: Encountered IntegrityError: \n"
msgstr ""

#: ../satellite_tools/satsync.py:285
msgid "Repeated failures"
msgstr ""

#: ../satellite_tools/satsync.py:290
#, python-format
msgid ""
"    Import complete:\n"
"        Begin time: %s\n"
"        End time:   %s\n"
"        Elapsed:    %s\n"
"          "
msgstr ""

#: ../satellite_tools/satsync.py:311
msgid "hours"
msgstr ""

#: ../satellite_tools/satsync.py:311
msgid "minutes"
msgstr ""

#: ../satellite_tools/satsync.py:311
msgid "seconds"
msgstr ""

#: ../satellite_tools/satsync.py:357
msgid ""
"ERROR: The dump is missing package data, use --no-rpms to skip this step or "
"fix the content to include package data."
msgstr ""

#. the orgs() method doesn't exist; that's fine we just
#. won't sync the orgs
#: ../satellite_tools/satsync.py:404
msgid "The SUSE Manager master does not support syncing orgs data."
msgstr ""

#: ../satellite_tools/satsync.py:404
msgid "Skipping..."
msgstr ""

#: ../satellite_tools/satsync.py:442
#, python-format
msgid "SUSE Manager Inter Server sync. report from %s"
msgstr ""

#: ../satellite_tools/satsync.py:521
msgid " - file-system synchronization"
msgstr ""

#: ../satellite_tools/satsync.py:533 ../satellite_tools/satsync.py:541
msgid " - live synchronization"
msgstr ""

#: ../satellite_tools/satsync.py:534
msgid ""
"ERROR: Live content synchronizing with RHN Classic Hosted is no longer "
"supported.\n"
"Please use the cdn-sync command instead unless you are attempting to sync "
"from another Satellite via Inter-Satelite-Sync (ISS), or from local content "
"on disk via Channel Dump ISOs."
msgstr ""

#: ../satellite_tools/satsync.py:542
#, python-format
msgid "   url: %s"
msgstr ""

#: ../satellite_tools/satsync.py:543
#, python-format
msgid "   debug/output level: %s"
msgstr ""

#: ../satellite_tools/satsync.py:553
msgid "ERROR: this server must be registered with SUSE Manager."
msgstr ""

#: ../satellite_tools/satsync.py:575
#, python-format
msgid "Retrieving / parsing %s data"
msgstr ""

#: ../satellite_tools/satsync.py:585 ../satellite_tools/satsync.py:600
msgid "*** SYSTEM INTERRUPT CALLED ***"
msgstr ""

#: ../satellite_tools/satsync.py:593
msgid "ERROR: fatal parser exception occurred "
msgstr ""

#: ../satellite_tools/satsync.py:594
#, python-format
msgid "(line: %s, col: %s msg: %s)"
msgstr ""

#: ../satellite_tools/satsync.py:598
#, python-format
msgid "ERROR: parser exception occurred: %s"
msgstr ""

#: ../satellite_tools/satsync.py:603
msgid "ERROR: exception (during parse) occurred: "
msgstr ""

#: ../satellite_tools/satsync.py:604
#, python-format
msgid ""
"   Encountered some errors with %s data (see logs (%s) for more information)"
msgstr ""

#: ../satellite_tools/satsync.py:606
#, python-format
msgid "   Encountered some errors with %s data:"
msgstr ""

#: ../satellite_tools/satsync.py:607
#, python-format
msgid "   ------- %s PARSE/IMPORT ERROR -------"
msgstr ""

#: ../satellite_tools/satsync.py:609
msgid "   ---------------------------------------"
msgstr ""

#: ../satellite_tools/satsync.py:612
#, python-format
msgid "%s data complete"
msgstr ""

#: ../satellite_tools/satsync.py:665
msgid "Retrieving / parsing channel data"
msgstr ""

#: ../satellite_tools/satsync.py:718
msgid "Channel data complete"
msgstr ""

#: ../satellite_tools/satsync.py:736
#, python-format
msgid "%10s import from %s"
msgstr ""

#: ../satellite_tools/satsync.py:739
#, python-format
msgid "%10s import from %s - %s"
msgstr ""

#: ../satellite_tools/satsync.py:743
#, python-format
msgid "%10s"
msgstr ""

#: ../satellite_tools/satsync.py:750
msgid "p"
msgstr ""

#: ../satellite_tools/satsync.py:752
msgid "."
msgstr ""

#: ../satellite_tools/satsync.py:758
msgid "   p = previously imported/synced channel"
msgstr ""

#: ../satellite_tools/satsync.py:759
msgid "   . = channel not yet imported/synced"
msgstr ""

#: ../satellite_tools/satsync.py:765
msgid "   e = channel no longer supported (end-of-service)"
msgstr ""

#: ../satellite_tools/satsync.py:767
msgid "   ? = channel label invalid --- typo?"
msgstr ""

#: ../satellite_tools/satsync.py:771
#, python-format
msgid "   %s:"
msgstr ""

#: ../satellite_tools/satsync.py:772
#, python-format
msgid "      %s %-40s %4s %s"
msgstr ""

#: ../satellite_tools/satsync.py:773
#, fuzzy
msgid "base-channels"
msgstr "競合しているベースチャンネル"

#: ../satellite_tools/satsync.py:786 ../satellite_tools/satsync.py:1603
msgid "NONE RELEVANT"
msgstr ""

#: ../satellite_tools/satsync.py:808
msgid "end-of-service"
msgstr ""

#: ../satellite_tools/satsync.py:809
msgid "e"
msgstr ""

#: ../satellite_tools/satsync.py:815
msgid "   typos:"
msgstr ""

#: ../satellite_tools/satsync.py:816
msgid "?"
msgstr ""

#: ../satellite_tools/satsync.py:831
#, python-format
msgid "XXX: imported channels: %s"
msgstr ""

#: ../satellite_tools/satsync.py:832
#, python-format
msgid "XXX:   cached channels: %s"
msgstr ""

#: ../satellite_tools/satsync.py:837
msgid "XXX: list channels called"
msgstr ""

#: ../satellite_tools/satsync.py:855
msgid "ERROR: these channels either do not exist or are not available:"
msgstr ""

#: ../satellite_tools/satsync.py:859
#, python-format
msgid "       (to see a list of channel labels: %s --list-channels)"
msgstr ""

#: ../satellite_tools/satsync.py:904
#, python-format
msgid "   Retrieving / parsing short package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/satsync.py:965
#, python-format
msgid "Diffing package metadata (what's missing locally?): %s"
msgstr ""

#: ../satellite_tools/satsync.py:971 ../satellite_tools/satsync.py:1254
msgid "Diffing:    "
msgstr ""

#: ../satellite_tools/satsync.py:988
msgid "ERROR: incremental dump skipped"
msgstr ""

#: ../satellite_tools/satsync.py:1079
msgid "Downloading rpm packages"
msgstr ""

#: ../satellite_tools/satsync.py:1084
#, python-format
msgid "   Fetching any missing RPMs: %s (%s)"
msgstr ""

#: ../satellite_tools/satsync.py:1085 ../satellite_tools/satsync.py:1153
msgid "NONE MISSING"
msgstr ""

#: ../satellite_tools/satsync.py:1094
msgid "Processing rpm packages complete"
msgstr ""

#: ../satellite_tools/satsync.py:1121
msgid "Downloading package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1146
msgid "Downloading srpm packages"
msgstr ""

#: ../satellite_tools/satsync.py:1152
#, python-format
msgid "   Fetching any missing SRPMs: %s (%s)"
msgstr ""

#: ../satellite_tools/satsync.py:1249
#, python-format
msgid "Diffing source package metadata (what's missing locally?): %s"
msgstr ""

#: ../satellite_tools/satsync.py:1260
msgid "Downloading source package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1338 ../satellite_tools/satsync.py:2027
#, fuzzy, python-format
msgid "Unable to save file %s: %s"
msgstr "システムにエンタイトルメントを付与できません"

#. for
#. Retried a number of times and it still failed; log the
#. file as being failed and move on
#: ../satellite_tools/satsync.py:1345
#, python-format
msgid "Failed to fetch file %s"
msgstr ""

#: ../satellite_tools/satsync.py:1350
msgid "Downloading kickstartable trees metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1365
msgid "Downloading kickstartable trees files"
msgstr ""

#: ../satellite_tools/satsync.py:1504
#, python-format
msgid "Grabbing all patches for channel %s"
msgstr ""

#: ../satellite_tools/satsync.py:1554
msgid "Downloading patch data"
msgstr ""

#: ../satellite_tools/satsync.py:1556
msgid "Forcing download of all patch data for requested channels."
msgstr ""

#: ../satellite_tools/satsync.py:1571
msgid "Downloading patch data complete"
msgstr ""

#: ../satellite_tools/satsync.py:1576 ../satellite_tools/satsync.py:1597
msgid "Downloading:"
msgstr ""

#: ../satellite_tools/satsync.py:1579
msgid " - complete"
msgstr ""

#: ../satellite_tools/satsync.py:1624
msgid "Importing source package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1627
msgid "Importing package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:1635
msgid "Importing:  "
msgstr ""

#. not in the cache
#: ../satellite_tools/satsync.py:1703
msgid ""
"Package Not Found in Cache, Clear the Cache "
"to                                  Regenerate it."
msgstr ""

#: ../satellite_tools/satsync.py:1709
msgid "Importing channel patches"
msgstr ""

#: ../satellite_tools/satsync.py:1714
#, python-format
msgid "Importing %s patches for channel %s."
msgstr ""

#. Incomplete configuration
#: ../satellite_tools/satsync.py:2113
msgid "ERROR: server.mount_point not set in the configuration file"
msgstr ""

#: ../satellite_tools/satsync.py:2117
#, python-format
msgid "ERROR: server.mount_point %s do not exist"
msgstr ""

#: ../satellite_tools/satsync.py:2122
#, python-format
msgid "ERROR: path under server.mount_point (%s)  do not exist"
msgstr ""

#: ../satellite_tools/satsync.py:2199
#, python-format
msgid "Commandline: %s"
msgstr ""

#: ../satellite_tools/satsync.py:2202
#, python-format
msgid ""
"DEBUG ONLY: max. batch-size for XML/database-import processing (1..%s).\"man "
"satellite-sync\" for more information."
msgstr ""

#: ../satellite_tools/satsync.py:2205
msgid "alternative SSL CA Cert (fullpath to cert file)"
msgstr ""

#: ../satellite_tools/satsync.py:2207
msgid "process data for this channel only"
msgstr ""

#: ../satellite_tools/satsync.py:2209
msgid ""
"disk dump will be considered to be a full export; see \"man satellite-sync\" "
"for more information."
msgstr ""

#: ../satellite_tools/satsync.py:2212
msgid "existing custom channels will also be synced (unless -c is used)"
msgstr ""

#: ../satellite_tools/satsync.py:2214
#, python-format
msgid ""
"override debug level set in /etc/rhn/rhn.conf (which is currently set at %s)."
msgstr ""

#: ../satellite_tools/satsync.py:2216
#, python-format
msgid "requested version of XML dump (default: %s)"
msgstr ""

#: ../satellite_tools/satsync.py:2218
msgid "e-mail a report of what was synced/imported"
msgstr ""

#: ../satellite_tools/satsync.py:2220
msgid "forcibly process all (not a diff of) patch metadata"
msgstr ""

#: ../satellite_tools/satsync.py:2222
msgid "Do not use an http proxy under any circumstances."
msgstr ""

#: ../satellite_tools/satsync.py:2224
msgid "alternative http proxy (hostname:port)"
msgstr ""

#: ../satellite_tools/satsync.py:2226
msgid "alternative http proxy username"
msgstr ""

#: ../satellite_tools/satsync.py:2228
msgid "alternative http proxy password"
msgstr ""

#: ../satellite_tools/satsync.py:2230
msgid "parent SUSE Manager to import content from"
msgstr ""

#: ../satellite_tools/satsync.py:2232
msgid "list all available channels and exit"
msgstr ""

#: ../satellite_tools/satsync.py:2234
msgid "help on all error codes mgr-inter-sync returns"
msgstr ""

#: ../satellite_tools/satsync.py:2236
msgid "source mount point for import - disk update only"
msgstr ""

#: ../satellite_tools/satsync.py:2238
msgid "do not process patch data"
msgstr ""

#: ../satellite_tools/satsync.py:2240
msgid "do not process kickstart data (provisioning only)"
msgstr ""

#: ../satellite_tools/satsync.py:2242
msgid "do not process full package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:2244
msgid "do not download, or process any RPMs"
msgstr ""

#: ../satellite_tools/satsync.py:2246
msgid "turn off SSL (not recommended)"
msgstr ""

#: ../satellite_tools/satsync.py:2248
msgid "org to which the sync imports data. defaults to the admin account"
msgstr ""

#: ../satellite_tools/satsync.py:2250
#, fuzzy
msgid "print the configuration and exit"
msgstr "設定チャンネルが存在していません"

#: ../satellite_tools/satsync.py:2252
msgid "alternative server with which to connect (hostname)"
msgstr ""

#: ../satellite_tools/satsync.py:2254
msgid "synchronize to this step (man satellite-sync for more info)"
msgstr ""

#: ../satellite_tools/satsync.py:2256
msgid "write complete data to tempfile before streaming to remainder of app"
msgstr ""

#: ../satellite_tools/satsync.py:2258
msgid "DEBUG ONLY: alternative path to digital system id"
msgstr ""

#: ../satellite_tools/satsync.py:2260
msgid "alternative email address(es) for sync output (--email option)"
msgstr ""

#: ../satellite_tools/satsync.py:2262
msgid "do not remove rpms when importing from local dump"
msgstr ""

#: ../satellite_tools/satsync.py:2264
msgid ""
"the fully qualified domain name of the master Satellite. Valid with --mount-"
"point only. Required if you want to import org data and channel permissions."
msgstr ""

#: ../satellite_tools/satsync.py:2274
#, python-format
msgid "ERROR: these arguments make no sense in this context (try --help): %s"
msgstr ""

#. An SQL error is fatal... crash and burn
#: ../satellite_tools/satsync.py:2286
#, python-format
msgid "ERROR: Can't connect to the database: %s"
msgstr ""

#: ../satellite_tools/satsync.py:2287
msgid "ERROR: Check if your database is running."
msgstr ""

#: ../satellite_tools/satsync.py:2322
#, python-format
msgid "ERROR: --debug-level takes an in integer value within the range %s."
msgstr ""

#: ../satellite_tools/satsync.py:2324
msgid "  0  - little logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2325
msgid "  1  - minimal logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2326
msgid "  2  - normal level of logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2327
msgid "  3  - lots of logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2328
msgid "  4+ - excessive logging/messaging."
msgstr ""

#: ../satellite_tools/satsync.py:2341
msgid "ERROR: The --master option is only valid with the --mount-point option"
msgstr ""

#: ../satellite_tools/satsync.py:2351
#, fuzzy, python-format
msgid "ERROR: Unable to lookup Org Id %s"
msgstr "サーバーを検出できません"

#: ../satellite_tools/satsync.py:2360
msgid ""
"WARNING: --list-channels option overrides any --step option. --step ignored."
msgstr ""

#: ../satellite_tools/satsync.py:2375
#, python-format
msgid ""
"ERROR: '%s' is not a valid step. See 'man satellite-sync' for more detail."
msgstr ""

#: ../satellite_tools/satsync.py:2407
msgid ""
"ERROR: No channels currently imported; try mgr-inter-sync --list-channels; "
"then mgr-inter-sync -c chn0 -c chn1..."
msgstr ""

#. int(None) --> TypeError
#. int('a')  --> ValueError
#: ../satellite_tools/satsync.py:2457 ../satellite_tools/satsync.py:2461
msgid "ERROR: --batch-size must have a value within the range: 1..50"
msgstr ""

#: ../satellite_tools/satsync.py:2469
#, python-format
msgid "ERROR: no such directory %s"
msgstr ""

#: ../satellite_tools/satsync.py:2474
msgid "Error Codes: Returned codes means:"
msgstr ""

#: ../satellite_tools/satsync.py:2475
msgid " -1  - Could not lock file or KeyboardInterrupt or SystemExit"
msgstr ""

#: ../satellite_tools/satsync.py:2476
msgid "  0  - User interrupted or intentional exit"
msgstr ""

#: ../satellite_tools/satsync.py:2477
msgid "  1  - attempting to run more than one instance of mgr-inter-sync."
msgstr ""

#: ../satellite_tools/satsync.py:2478
msgid "  2  - Unable to find synchronization tools."
msgstr ""

#: ../satellite_tools/satsync.py:2479
msgid "  3  - a general socket exception occurred"
msgstr ""

#: ../satellite_tools/satsync.py:2480
msgid "  4  - an SSL error occurred. Recheck your SSL settings."
msgstr ""

#: ../satellite_tools/satsync.py:2481
msgid "  5  - ISS error"
msgstr ""

#: ../satellite_tools/satsync.py:2482
msgid "  6  - unhandled exception occurred"
msgstr ""

#: ../satellite_tools/satsync.py:2483
msgid "  7  - unknown sync error"
msgstr ""

#: ../satellite_tools/satsync.py:2484
msgid "  8  - ERROR: must be root to execute"
msgstr ""

#: ../satellite_tools/satsync.py:2485
msgid "  9  - rpclib fault during synchronization init"
msgstr ""

#: ../satellite_tools/satsync.py:2486
msgid "  10 - synchronization init error"
msgstr ""

#: ../satellite_tools/satsync.py:2487
msgid "  11 - Error parsing XML stream"
msgstr ""

#: ../satellite_tools/satsync.py:2488
#, fuzzy
msgid "  12 - Channel do not exist"
msgstr "指定されたチャンネルが存在していません。"

#: ../satellite_tools/satsync.py:2489
msgid "  13 - SQL error during importing package metadata"
msgstr ""

#: ../satellite_tools/satsync.py:2490
msgid "  14 - SQL error during linking channel packages"
msgstr ""

#: ../satellite_tools/satsync.py:2491
msgid "  15 - SQL error during xml processing"
msgstr ""

#: ../satellite_tools/satsync.py:2492
msgid "  16 - server.mount_point not set in the configuration file"
msgstr ""

#: ../satellite_tools/satsync.py:2493
msgid ""
"  17 - SQL error during retrieving the channels already imported in the SUSE "
"Manager database"
msgstr ""

#: ../satellite_tools/satsync.py:2494
msgid "  18 - Wrong db connection string in rhn.conf"
msgstr ""

#: ../satellite_tools/satsync.py:2495
msgid "  19 - Bad arguments"
msgstr ""

#: ../satellite_tools/satsync.py:2496
msgid "  20 - Could not connect to db."
msgstr ""

#: ../satellite_tools/satsync.py:2497
msgid "  21 - Bad debug level"
msgstr ""

#: ../satellite_tools/satsync.py:2498
msgid "  22 - Not valid step"
msgstr ""

#: ../satellite_tools/satsync.py:2499
msgid "  24 - no such file"
msgstr ""

#: ../satellite_tools/satsync.py:2500
msgid "  25 - no such directory"
msgstr ""

#: ../satellite_tools/satsync.py:2501
msgid "  26 - mount_point does not exist"
msgstr ""

#: ../satellite_tools/satsync.py:2502
msgid "  27 - No such org"
msgstr ""

#: ../satellite_tools/satsync.py:2503
msgid "  28 - error: --master is only valid with --mount-point"
msgstr ""

#: ../satellite_tools/satsync.py:2510
#, python-format
msgid "ERROR: unknown dump version, try one of %s"
msgstr ""

#: ../satellite_tools/rhn_satellite_activate.py:198
#, python-format
msgid ""
"\"%s\" (specified in commandline)\n"
"could not be opened and read:\n"
"%s"
msgstr ""

#: ../satellite_tools/rhn_satellite_activate.py:205
#, python-format
msgid ""
"\"%s\" could not be opened\n"
"and/or written to:\n"
"%s"
msgstr ""
