# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Eunju Kim <eukim@redhat.com>, 2006, 2007.
# Michelle Ji Yeen Kim <mkim@redhat.com>, 2005.
# Michelle J Kim <mkim@redhat.com>, 2003, 2004.
# Michelle Kim <mkim@redhat.com>, 2002.
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-02-24 18:13+0000\n"
"PO-Revision-Date: 2021-03-31 12:58+0000\n"
"Last-Translator: Seeun Lee <selee@e4net.net>\n"
"Language-Team: Korean <https://l10n.opensuse.org/projects/uyuni/backend/ko/"
">\n"
"Language: ko\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Weblate 3.6.1\n"

#: ../server/apacheAuth.py:66
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "미완료 프록시 인증 토큰: %s"

#: ../server/apacheAuth.py:84
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr "전송된 프록시 서명 %s이(가) 시스템의 %s와(과) 일치하지 않습니다."

#: ../server/apacheAuth.py:119
msgid "declined proxy authentication"
msgstr "거부된 프록시 인증"

#: ../server/apacheRequest.py:59
#, python-format
msgid "Invalid request received (%s)."
msgstr "유효하지 않은 요청이 수신되었습니다(%s)."

#: ../server/apacheRequest.py:120
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""
"중요 메시지:\n"
"%s"

#: ../server/apacheRequest.py:149
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""
"'%s' 실행 중: 다음이 catch됨:\n"
"%s : %s\n"

#: ../server/apacheRequest.py:606
#, python-format
msgid "Invalid URI %s"
msgstr "유효하지 않은 URI %s"

#: ../server/configFilesHandler.py:129 ../server/handlers/app/packages.py:192
#: ../server/handlers/xmlrpc/registration.py:217
#: ../server/handlers/xmlrpc/registration.py:1170
#: ../server/handlers/xmlrpc/registration.py:1309
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   %s 계정이 이 서버에서 비활성화되었습니다.\n"
"                   조직 관리자에게 문의하여 추가적인 지원을 요청하십시오."

#: ../server/handlers/applet/applet.py:78
#, python-brace-format
msgid "Your system was not found in the {PRODUCT_NAME} database"
msgstr "{PRODUCT_NAME} 데이터베이스에서 시스템을 찾을 수 없음"

#: ../server/handlers/sat/auth.py:45
msgid "ISS is disabled on this server."
msgstr "이 서버에서 ISS가 비활성화되었습니다."

#: ../server/handlers/sat/auth.py:50
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "\"%s\" 서버가 ISS용으로 활성화되지 않았습니다."

#: ../server/handlers/xmlrpc/errata.py:64
#, python-format
msgid "Expected a package name, not: %s"
msgstr "다음이 아닌 패키지 이름이 필요: %s"

#: ../server/handlers/xmlrpc/errata.py:115
#, python-format
msgid "Expected a package, not: %s"
msgstr "다음이 아닌 패키지 필요: %s"

#: ../server/handlers/xmlrpc/proxy.py:65
#, python-format
msgid "SUSE Manager Proxy service not enabled for server profile: \"%s\""
msgstr ""
"SUSE Manager Proxy 서비스가 다음 서버 프로파일에 대해 활성화되지 않음: \"%s\""

#: ../server/handlers/xmlrpc/proxy.py:85
msgid "Invalid session key"
msgstr "유효하지 않은 세션 키"

#: ../server/handlers/xmlrpc/proxy.py:93
msgid "This server ID no longer exists"
msgstr "이 서버 ID는 더 이상 존재하지 않음"

#: ../server/handlers/xmlrpc/queue.py:434
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr "유효하지 않은 작업 값 유형 %s(%s)"

#: ../server/handlers/xmlrpc/queue.py:462
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "%s 작업은 %s 서버에 속하지 않음"

#: ../server/handlers/xmlrpc/registration.py:196
msgid "Required data missing"
msgstr "필수 데이터 누락"

#: ../server/handlers/xmlrpc/registration.py:200
msgid "Required members missing"
msgstr "필수 멤버 누락"

#: ../server/handlers/xmlrpc/registration.py:209
msgid "Attempt to register a system to an invalid username"
msgstr "시스템의 유효하지 않은 사용자 이름 등록 시도"

#: ../server/handlers/xmlrpc/registration.py:841
msgid "Invalid system release version requested"
msgstr "유효하지 않은 시스템 릴리스 버전 요청됨"

#: ../server/handlers/xmlrpc/registration.py:1065
msgid ""
"Unable to find a valid network interface, both ipaddr and ip6addr not found."
msgstr ""
"유효한 네트워크 인터페이스를 찾을 수 없습니다. ipaddr 및 ip6addr를 모두 찾을 "
"수 없습니다."

#: ../server/handlers/xmlrpc/registration.py:1117
#, python-brace-format
msgid "{PRODUCT_NAME} Welcome Message"
msgstr "{PRODUCT_NAME} 환영 메시지"

#: ../server/handlers/xmlrpc/registration.py:1127
msgid "Privacy Statement"
msgstr "개인정보 보호정책"

#: ../server/handlers/xmlrpc/registration.py:1148
msgid "Expected a dictionary as a product argument"
msgstr "제품 인수로 딕셔너리가 필요함"

#: ../server/handlers/xmlrpc/registration.py:1376
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr "%s(%s)에 유효하지 않은 값 '%s'"

#: ../server/handlers/xmlrpc/scap.py:104
msgid "Invalid system_id/action_id pair."
msgstr "유효하지 않은 system_id/action_id 쌍입니다."

#: ../server/handlers/xmlrpc/up2date.py:249
#, python-format
msgid "Invalid value %s (%s)"
msgstr "유효하지 않은 값 %s(%s)"

#: ../server/importlib/userAuth.py:98
msgid "You are not authorized to manage packages in the null org"
msgstr "Null 조직에서 패키지를 관리할 권한 없음"

#: ../server/importlib/userAuth.py:103
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "%s 조직에서 패키지를 관리할 권한 없음"

#: ../server/importlib/userAuth.py:121
msgid "You are not allowed to perform administrative tasks"
msgstr "관리 작업을 수행할 권한 없음"

#: ../server/importlib/userAuth.py:144
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr "%s 채널을 관리할 권한이 없거나 해당 채널이 없음"

#: ../server/importlib/userAuth.py:204
#, python-format
msgid ""
"\n"
"               %s Account has been deactivated on this server.\n"
"               Please contact your Org administrator for more help."
msgstr ""
"\n"
"               %s 계정이 이 서버에서 비활성화되었습니다.\n"
"               조직의 관리자에게 문의하여 추가 지원을 요청하십시오."

#: ../server/rhnChannel.py:1999
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""
"귀하의 계정은 (릴리스='%(release)s', 아키텍처='%(arch)s')%(www_activation)에 "
"일치하는 채널에 액세스할 수 있는 권한이 없습니다."

#: ../server/rhnChannel.py:2014
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr "릴리스(%s, %s)에 구독하기 위한 권한 부족"

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2278 ../server/rhnChannel.py:2293
msgid "System Registered but Inactive"
msgstr "시스템이 등록되었지만 비활성 상태임"

#: ../server/rhnChannel.py:2279
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""
"\n"
"잘못된 아키텍처와 OS 릴리스 조합(%s, %s)입니다.\n"
"시스템이 등록되었지만, 업데이트할 수 없습니다.\n"
"이유는 기본 채널을 구독할 수 없기 때문입니다.\n"
"조직 관리자에게 문의하여 지원을 요청하십시오.\n"

#: ../server/rhnChannel.py:2286
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  이 시스템은 등록되었지만, 아직 서비스를 제공할 자격이 없습니다.\n"
"  이 시스템에 서비스 권한을 부여하려면 다음 웹 사이트에 로그인:\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnChannel.py:2294
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  이 시스템은 등록되었지만, 이용할 수 있는 서비스 권리 유형이 없습니다.\n"
"  이 시스템에 서비스 권한을 부여하려면 다음 웹 사이트에 로그인:\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr "이 클라이언트에서 root로 rhn_register를 실행하십시오."

#: ../server/rhnHandler.py:75
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr "시스템 프로파일에 대해 서비스가 허용되지 않음: \"%s\""

#: ../server/rhnPackage.py:49 ../server/rhnPackage.py:87
#: ../server/rhnPackage.py:107 ../server/rhnPackage.py:158
#, python-format
msgid "Invalid RPM package %s requested"
msgstr "유효하지 않은 RPM 패키지 %s 요청됨"

#: ../server/rhnPackage.py:112
msgid "Package not found"
msgstr "패키지를 찾을 수 없음"

#: ../server/rhnServer/server_class.py:97
#, python-format
msgid "Architecture `%s' is not supported"
msgstr "'%s' 아키텍처는 지원되지 않습니다."

#: ../server/rhnServer/server_token.py:78
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "'%s' 토큰에 기본 채널이 1개 이상 할당되었습니다."

#: ../server/rhnServer/server_token.py:80
msgid "Conflicting base channels"
msgstr "기본 채널 충돌"

#: ../server/rhnServer/server_token.py:190
#, python-format
msgid "Failed to add server to group %s"
msgstr "%s 그룹에 서버를 추가하지 못했습니다."

#: ../server/rhnServer/server_token.py:503
#, python-format
msgid "Maximum usage count of %s reached"
msgstr "%s의 최대 사용 횟수에 도달했습니다."

#: ../server/rhnServer/server_token.py:744
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr "기본 권리 유형이 다른 토큰 재등록 토큰 스택은 지원되지 않습니다."

#: ../server/rhnServer/server_token.py:811
#, python-format
msgid "Could not find token '%s'"
msgstr "'%s' 토큰을 찾을 수 없음"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:843
msgid "Tokens from mismatching orgs"
msgstr "일치하지 않는 조직에서 제공된 토큰"

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:853
msgid "Kickstart session mismatch"
msgstr "킥스타트 세션 불일치"

#: ../server/rhnServer/server_token.py:877
msgid "Stacking of re-registration tokens is not supported"
msgstr "재등록 토큰 스택은 지원되지 않습니다."

#: ../server/rhnUser.py:289 ../server/rhnUser.py:292
msgid "Invalid username/password combination"
msgstr "잘못된 사용자 이름/비밀번호 조합"

#. nope, not reserved either
#: ../server/rhnUser.py:467
#, python-format
msgid "Username `%s' has not been reserved"
msgstr "'%s' 사용자 이름은 예약되지 않았습니다."

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:473
msgid "E-mail address not specified"
msgstr "이메일 주소가 지정되지 않았습니다."

#: ../server/rhnUser.py:509
#, python-format
msgid "username should be at least %d characters"
msgstr "사용자 이름은 %d자 이상이어야 합니다."

#: ../server/rhnUser.py:512
#, python-format
msgid "username should be less than %d characters"
msgstr "사용자 이름은 %d자 미만이어야 합니다."

#: ../server/rhnUser.py:523
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr "사용자 이름 = `%s', 유효하지 않은 문자 `%s'"

#: ../server/rhnUser.py:542
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr "이메일 주소는 %s자 이하여야 합니다."

#: ../server/rhnUser.py:623
#, python-format
msgid "password must be at least %d characters"
msgstr "비밀번호는 %d자 이상이어야 합니다."

#: ../server/rhnUser.py:626
#, python-format
msgid "Password must be shorter than %d characters"
msgstr "비밀번호는 %d자 미만이어야 합니다."

#: ../server/rhnUser.py:644
#, python-format
msgid "password contains character `%s'"
msgstr "비밀번호에 '%s' 문자가 포함되었습니다."

#: ../server/rhnUser.py:651
#, python-format
msgid "username should be at least %d characters long"
msgstr "사용자 이름의 길이는 %d자 이상이어야 합니다."

#: ../server/rhnUser.py:662
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr "%s(으)로 끝나는 사용자 이름을 등록할 수 없습니다."

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:53
msgid "This does not appear to be a valid username."
msgstr "유효하지 않은 사용자 이름인 것 같습니다."

#: ../common/rhnException.py:54
msgid "Invalid username and password combination."
msgstr "사용자 이름과 비밀번호 조합이 잘못되었습니다."

#: ../common/rhnException.py:55
msgid "This login is already taken, or the password is incorrect."
msgstr "이 로그인은 이미 사용되었거나 비밀번호가 잘못되었습니다."

#: ../common/rhnException.py:56
msgid "Permission denied."
msgstr "권한이 거부되었습니다."

#: ../common/rhnException.py:57
msgid "Object not found."
msgstr "객체를 찾을 수 없습니다."

#: ../common/rhnException.py:58
msgid "Invalid System Digital ID."
msgstr "유효하지 않은 시스템 디지털 ID입니다."

#: ../common/rhnException.py:59
msgid "Invalid System Credentials."
msgstr "유효하지 않은 시스템 자격 증명입니다."

#: ../common/rhnException.py:60
msgid "Could not retrieve user data from database."
msgstr "데이터베이스에서 사용자 데이터를 검색할 수 없습니다."

#: ../common/rhnException.py:61
msgid "Valid username required."
msgstr "올바른 사용자 이름이 필요합니다."

#: ../common/rhnException.py:62
msgid "Valid password required."
msgstr "올바른 비밀번호가 필요합니다."

#: ../common/rhnException.py:63
msgid "Minimum username length violation."
msgstr "사용자 이름 최소 길이가 위반되었습니다."

#: ../common/rhnException.py:64
msgid "Minimum password length violation."
msgstr "비밀번호 최소 길이가 위반되었습니다."

#: ../common/rhnException.py:65
msgid "The username contains invalid characters."
msgstr "사용자 이름에 유효하지 않은 문자가 포함되었습니다."

#: ../common/rhnException.py:66
msgid "File not found."
msgstr "파일을 찾을 수 없습니다."

#: ../common/rhnException.py:67
msgid "Architecture and OS version combination is not supported."
msgstr "지원되지 않는 아키텍처와 OS 버전 조합입니다."

#: ../common/rhnException.py:68
msgid "Could not retrieve system data from database."
msgstr "데이터베이스에서 시스템 데이터를 검색할 수 없습니다."

#: ../common/rhnException.py:69
msgid "Invalid arguments passed to function."
msgstr "유효하지 않은 인수가 함수로 전달되었습니다."

#: ../common/rhnException.py:70
msgid "Unable to retrieve requested entry."
msgstr "요청된 항목을 검색할 수 없습니다."

#: ../common/rhnException.py:71
msgid "Could not update database entry."
msgstr "데이터베이스 항목을 업데이트할 수 없습니다."

#: ../common/rhnException.py:72
msgid "Unsupported server architecture."
msgstr "지원되지 않는 서버 아키텍처입니다."

#: ../common/rhnException.py:73
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running mgr_register as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     익명 서버 기능은 더 이상 사용할 수 없습니다.\n"
"\n"
"     mgr_register를 root로 실행하여 이 시스템을 다시 등록하십시오.\n"
"     이 시스템에 대해 서비스를 사용하려면 https://%(hostname)s/rhn/systems/"
"SystemEntitlements.do로 이동하거나\n"
"     https://%(hostname)s에 로그인한 후, \"개요\" 탭에서\n"
"     \"구독 관리\"를 선택하십시오.\n"
"     "

#: ../common/rhnException.py:81
msgid "Record not available in the database."
msgstr "데이터베이스에서 레코드를 사용할 수 없습니다."

#: ../common/rhnException.py:82
msgid "Invalid value for entry."
msgstr "값이 항목에 유효하지 않습니다."

#: ../common/rhnException.py:83
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for SUSE Manager.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     이 시스템에는 SUSE Manager에 유효한 자격 유형이 없습니다.\n"
"     이 시스템에 대해 서비스를 사용하려면 https://%(hostname)s/rhn/systems/"
"SystemEntitlements.do로 이동하거나\n"
"     https://%(hostname)s에 로그인한 후, \"개요\" 탭에서\n"
"     \"구독 관리\"를 선택하십시오.\n"
"     "

#: ../common/rhnException.py:89
msgid "Channel error"
msgstr "채널 오류"

#: ../common/rhnException.py:90
msgid "Client session token is invalid."
msgstr "클라이언트 세션 토큰이 유효하지 않습니다."

#: ../common/rhnException.py:91
msgid "Client session token has expired."
msgstr "클라이언트 세션 토큰이 만료되었습니다."

#: ../common/rhnException.py:92
msgid "You are not authorized to retrieve the requested object."
msgstr "요청된 객체를 검색할 권한이 없습니다."

#: ../common/rhnException.py:93
msgid "Invalid action"
msgstr "유효하지 않은 작업"

#: ../common/rhnException.py:94
msgid "You are not allowed to perform administrative tasks on this system."
msgstr "이 시스템에서 관리 작업을 수행할 권한이 없습니다."

#: ../common/rhnException.py:96
msgid "The system is already subscribed to the specified channel."
msgstr "이 시스템은 지정된 채널을 이미 구독하고 있습니다."

#: ../common/rhnException.py:97
msgid "The system is not currently subscribed to the specified channel."
msgstr "현재 시스템이 지정된 채널을 구독하고 있지 않습니다."

#: ../common/rhnException.py:98
msgid "The specified channel does not exist."
msgstr "지정된 채널이 없습니다."

#: ../common/rhnException.py:99
msgid "Invalid channel version."
msgstr "유효하지 않은 채널 버전입니다."

#: ../common/rhnException.py:100
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""
"\n"
"     사용자 그룹 구성원 한도에 도달했습니다.\n"
"\n"
"     계정의 현재 설정에서 다른 사용자 계정 추가를 허용하지 않습니다.\n"
"     조직 관리자에게 문의하여 서버에 구독할 수 있는 최대 사용자 수를\n"
"     변경해야 하는지 확인하십시오.\n"
"     "

#: ../common/rhnException.py:108
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""
"\n"
"     사용자 그룹 구성원 한도에 도달했습니다..\n"
"\n"
"     계정의 현재 설정에서 다른 시스템 프로파일 추가를 허용하지 않습니다.\n"
"     조직 관리자에게 문의하여 귀하의 계정을 구독할 수 있는 최대 시스템 프로파"
"일 수를\n"
"     수정해야 하는지 확인하십시오.\n"
"     "

#: ../common/rhnException.py:116
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""
"\n"
"     유효하지 않은 아키텍처입니다.\n"
"\n"
"     패키지 아키텍처가 지원되지 않음\n"
"     "

#: ../common/rhnException.py:121
msgid "Invalid RPM header"
msgstr "유효하지 않은 RPM 헤더"

#: ../common/rhnException.py:122
msgid ""
"\n"
"    This system is already registered as a Salt Minion. If you want to "
"register it as a traditional client\n"
"    please delete it first via the web UI or API and then register it using "
"the traditional tools.\n"
"    "
msgstr ""
"\n"
"    이 시스템은 이미 Salt Minion으로 등록되었습니다. 기존 클라이언트로 등록하"
"려면\n"
"    우선 웹 UI 또는 API를 통해 삭제한 후 기존 도구를 사용하여 등록하십시오.\n"
"    "

#. For the uploading tools
#: ../common/rhnException.py:127
msgid "Invalid information uploaded to the server"
msgstr "유효하지 않은 정보가 서버에 업로드됨"

#: ../common/rhnException.py:128
msgid "Error uploading network interfaces configuration."
msgstr "네트워크 인터페이스 구성을 업로드하는 동안 오류가 발생했습니다."

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""
"\n"
"     고유성 제약 조건이 위반되어 패키지를 업로드하지 못했습니다.\n"
"     패키지에 중복 종속성이 있지 않은지 또는\n"
"     패키지가 이미 서버에 있지 않은지 확인하십시오.\n"
"     "

#: ../common/rhnException.py:134
msgid ""
"\n"
"     The --force mgrpush option is disabled on this server.\n"
"     Please contact your SUSE Manager administrator for more help.\n"
"     "
msgstr ""
"\n"
"     --force mgrpush 옵션이 이 서버에서 사용할 수 없도록 설정되었습니다.\n"
"     SUSE Manager 관리자에게 문의하여 지원을 요청하십시오.\n"
"     "

#. 60-70: token errors
#: ../common/rhnException.py:140
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""
"\n"
"     지정한 활성화 토큰을 서버에서 찾지 못했습니다.\n"
"     유효한 키를 사용하여 다시 시도하십시오.\n"
"     "

#: ../common/rhnException.py:144
msgid "Too many systems registered using this registration token"
msgstr "이 등록 토큰을 사용하여 등록한 시스템이 너무 많습니다."

#: ../common/rhnException.py:145
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr ""
"토큰에 유효하지 않거나 더 이상 사용되지 않거나 충분하지 않는 설정이 포함되어 "
"있습니다."

#: ../common/rhnException.py:146
msgid "Conflicting activation tokens"
msgstr "활성화 토큰 충돌"

#. 70-80: channel subscription errors
#: ../common/rhnException.py:149
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""
"\n"
"     시스템에 일치하는 기본 채널을 찾을 수 없습니다.\n"
"     "

#: ../common/rhnException.py:152
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""
"\n"
"     지정된 채널에 구독할 권한이 없습니다.\n"
"     조직의 채널을 참조하거나 조직 관리자에게\n"
"     자세한 내용을 문의하십시오.\n"
"     "

#: ../common/rhnException.py:157
msgid "You can not unsubscribe from base channel."
msgstr "기본 채널의 구독을 취소할 수 없습니다."

#: ../common/rhnException.py:158
msgid "SUSE Manager or Proxy channel can not be subscribed."
msgstr "SUSE Manager 또는 프록시 채널을 구독할 수 없습니다."

#. 80-90: server group errors
#: ../common/rhnException.py:161
msgid "There was an error while trying to join the system to its groups"
msgstr "시스템이 그룹에 참여할 때 오류가 발생했습니다."

#. 90-100: entitlement errors
#: ../common/rhnException.py:164
msgid "Unable to entitle system"
msgstr "시스템에 권한을 부여할 수 없음"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:167
msgid "Maximum e-mail length violation."
msgstr "최대 이메일 길이가 위반되었습니다."

#: ../common/rhnException.py:168
msgid "This system has been previously registered."
msgstr "이 시스템은 이전에 등록되었습니다."

#: ../common/rhnException.py:169
msgid "Invalid username"
msgstr "유효하지 않은 사용자 이름"

#. 140-159 applet errors
#: ../common/rhnException.py:172
msgid "Unable to look up server"
msgstr "서버를 조회할 수 없음"

#. 160-179: OSAD errors
#: ../common/rhnException.py:175
msgid "Required argument is missing"
msgstr "필수 인수 누락됨"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:178
msgid "No entitlement information tied to hardware"
msgstr "권한 유형 정보가 하드웨어에 연결되지 않음"

#: ../common/rhnException.py:179
msgid "Installation number is not entitling"
msgstr "설치 번호가 유효하지 않습니다."

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:182
msgid "Maximum username length violation"
msgstr "최대 사용자 이름 길이 위반"

#: ../common/rhnException.py:183
msgid "Maximum password length violation"
msgstr "최소 비밀번호 길이 위반"

#: ../common/rhnException.py:184
msgid "This user has read only API access. Action denied."
msgstr ""
"이 사용자에는 API 읽기 전용 액세스 권한이 있습니다. 작업이 거부되었습니다."

#: ../common/rhnException.py:186
msgid "System Name cannot be less than 1 character"
msgstr "시스템 이름은 1자 미만이 아니어야 합니다."

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:190
msgid "SUSE Manager Proxy error."
msgstr "SUSE Manager 프록시 오류입니다."

#: ../common/rhnException.py:191
msgid "SUSE Manager Proxy unable to login."
msgstr "SUSE Manager 프록시에 로그인할 수 없습니다."

#. issued by a SUSE Manager Server/Satellite to the proxy
#: ../common/rhnException.py:193
msgid ""
"\n"
"     SUSE Manager Proxy system ID does not match a Spacewalk Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""
"\n"
"     SUSE Manager 프록시 시스템 ID가 데이터베이스의 Spacewalk 프록시 서버와\n"
"     일치하지 않습니다.\n"
"     "

#: ../common/rhnException.py:197
msgid "SUSE Manager Proxy session token is invalid."
msgstr "SUSE Manager 프록시 세션 토큰이 잘못되었습니다."

#: ../common/rhnException.py:198
msgid "SUSE Manager Proxy session token has expired."
msgstr "SUSE Manager 프록시 세션 토큰이 만료되었습니다."

#. 2000-2999: Red Hat Satellite specific errors:
#: ../common/rhnException.py:202
msgid ""
"\n"
"      user creation is not allowed via mgr_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""
"\n"
"      mgr_register를 통한 사용자 만들기는 허용되지 않습니다.\n"
"     시스템 관리자에게 계정 생성을 요청하십시오.\n"
"     "

#: ../common/rhnException.py:206
msgid ""
"\n"
"     This SUSE Manager server is not allowed to use Inter Server Sync on "
"this server\n"
"     "
msgstr ""
"\n"
"     이 SUSE Manager 서버는 이 서버에서 서버 간 동기화를 사용하도록 허용되지 "
"않습니다.\n"
"     "

#: ../common/rhnException.py:209
msgid ""
"\n"
"     Inter Server Sync is disabled on this SUSE Manager Server.\n"
"     "
msgstr ""
"\n"
"     이 SUSE Manager 서버에서 서버 간 동기화가 비활성화되었습니다.\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:214
msgid "Invalid datatype passed"
msgstr "유효하지 않은 데이터 형식이 전달됨"

#: ../common/rhnException.py:215
msgid "Unable to retrieve channel"
msgstr "채널을 검색할 수 없음"

#: ../common/rhnException.py:216
msgid "Unable to retrieve package"
msgstr "패키지를 검색할 수 없음"

#: ../common/rhnException.py:217
msgid "Unable to retrieve erratum"
msgstr "erratum을 검색할 수 없음"

#: ../common/rhnException.py:218
msgid "File is missing"
msgstr "파일 누락됨"

#: ../common/rhnException.py:219
msgid "Function retrieval error"
msgstr "함수 검색 오류"

#: ../common/rhnException.py:220
msgid "Function execution error"
msgstr "함수 실행 오류"

#: ../common/rhnException.py:221
msgid "Missing version string"
msgstr "누락된 버전 문자열"

#: ../common/rhnException.py:222
msgid "Invalid version string"
msgstr "유효하지 않은 버전 문자열"

#: ../common/rhnException.py:223
msgid "Mismatching versions"
msgstr "일치하지 않는 버전"

#: ../common/rhnException.py:224
msgid "Invalid channel version"
msgstr "유효하지 않은 채널 버전"

#: ../common/rhnException.py:225
msgid "No comps file for channel"
msgstr "채널에 구성 파일 없음"

#: ../common/rhnException.py:226
msgid "Unable to retrieve comps file"
msgstr "구성 파일을 검색할 수 없음"

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:229
msgid "Configuration action missing"
msgstr "구성 작업 누락됨"

#: ../common/rhnException.py:230
msgid "File too large"
msgstr "파일이 너무 큼"

#: ../common/rhnException.py:231
msgid "File contains binary data"
msgstr "파일에 이진 데이터가 포함됨"

#: ../common/rhnException.py:232
msgid "Configuration channel is not empty"
msgstr "구성 채널이 비어 있지 않음"

#: ../common/rhnException.py:233
msgid "Permission error"
msgstr "권한 오류"

#: ../common/rhnException.py:234
msgid "Content missing for configuration file"
msgstr "구성 파일에서 내용이 누락됨"

#: ../common/rhnException.py:235
msgid "Template delimiters not specified"
msgstr "템플릿 구분 기호가 지정되지 않음"

#: ../common/rhnException.py:236
msgid "Configuration channel does not exist"
msgstr "구성 채널 없음"

#: ../common/rhnException.py:237
msgid "Configuration channel already exists"
msgstr "구성 채널 이미 있음"

#: ../common/rhnException.py:238
msgid "File missing from configuration channel"
msgstr "구성 채널에서 파일이 누락됨"

#: ../common/rhnException.py:239
msgid "Different revision of this file is uploaded"
msgstr "이 파일의 다른 버전이 업로드됨"

#: ../common/rhnException.py:240
msgid "File already uploaded to configuration channel"
msgstr "파일이 이미 구성 채널에 업로드됨"

#: ../common/rhnException.py:241
msgid "File size exceeds remaining quota space"
msgstr "파일 크기가 남은 공간 한도를 초과함"

#: ../common/rhnException.py:242
msgid "Full path of file must be specified"
msgstr "파일의 전체 경로를 지정해야 합니다."

#: ../common/rhnException.py:243
msgid "Invalid revision number"
msgstr "유효하지 않은 수정 버전 번호"

#: ../common/rhnException.py:244
msgid "Cannot compare files of different file type"
msgstr "파일 형식이 다른 파일을 비교할 수 없습니다."

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:247
msgid "SCAP results file transfer is invalid or incomplete"
msgstr "SCAP 결과 파일 전달이 잘못되거나 완전하지 않습니다."

#: ../common/rhnException.py:248
msgid "Error composing directory path for detailed SCAP results"
msgstr ""
"자세한 SCAP 결과에 대한 디렉토리 경로를 구성하는 동안 오류가 발생했습니다."

#: ../common/rhnException.py:249
msgid "Error composing file path for detailed SCAP results"
msgstr "자세한 SCAP 결과에 대한 파일 경로를 구성하는 동안 오류가 발생했습니다."

#: ../common/rhnException.py:250
msgid "Invalid content encoding"
msgstr "유효하지 않은 컨텐트 인코딩"

#: ../common/rhnException.py:297
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at scc.suse.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""
"\n"
"     요청을 처리하는 동안 오류가 발생했습니다. 이 문제가 지속되면\n"
"     scc.suse.com에 버그 리포트를 입력해 주십시오.\n"
"     버그 리포트를 제출하려면, 이 오류가 발생할 때 수행한 자세한 사항과\n"
"     이 문제를 재현할 수 있는 방법에 대한 세부 정보를 포함해 주십시오.\n"

#: ../common/rhnException.py:349
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""
"오류 메시지:\n"
"    %s\n"

#: ../common/rhnException.py:351
#, python-format
msgid "Error Class Code: %s\n"
msgstr "오류 클래스 코드: %s\n"

#: ../common/rhnException.py:354
#, python-format
msgid "Error Class Info: %s\n"
msgstr "오류 클래스 정보: %s\n"

#: ../common/rhnException.py:356
#, python-format
msgid "Explanation: %s"
msgstr "설명: %s"

#: ../common/rhnTB.py:205
#, python-format
msgid "ERROR: %s %s: %s"
msgstr "오류: %s %s: %s"

#: ../common/rhnTB.py:207
#, python-format
msgid "TRACEBACK: %s"
msgstr "역추적: %s"

#: ../satellite_tools/disk_dumper/iss.py:1294
#: ../satellite_tools/disk_dumper/iss.py:1298
#, python-format
msgid "format of %s should be at least YYYYMMDD.\n"
msgstr "%s의 형식은 YYYYMMDD여야 합니다.\n"

#: ../satellite_tools/messages.py:26
#, python-format
msgid ""
"\n"
"ERROR: executing step %s. Error is:\n"
"%s\n"
msgstr ""
"\n"
"오류: %s 단계 실행 중. 오류:\n"
"%s\n"

#: ../satellite_tools/messages.py:31
#, python-format
msgid ""
"\n"
"ERROR: there was a problem accessing the channel data from your temporary\n"
"       repository. Did you migrate all of the data from the channel ISOs\n"
"       do this directory? If so, please recheck the channels ISOs, ensure\n"
"       that you have them all, and then iteratively remount and repopulate\n"
"       the temporary repository (%s).\n"
msgstr ""
"\n"
"오류: 임시 리포지토리에서 채널 데이터에 액세스하는 동안 오류가 발생했습니"
"다.\n"
"       채널 ISO에서 이 디렉토리로 모든 데이터를 마이그레이션하셨습니까?\n"
"       그러한 경우, 채널 ISO를 다시 확인하고 데이터가 모두 있는지 확인한 후\n"
"       반복해서 다시 마운트하고 임시 리포지토리(%s)를 다시 채우십시오.\n"

#: ../satellite_tools/messages.py:39
#, python-format
msgid ""
"\n"
"ERROR: there was a problem synchronizing the information.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"오류: 정보를 동기화하는 동안 오류가 발생했습니다.\n"
"       오류 메시지: %s\n"

#: ../satellite_tools/messages.py:44
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       Depending on the specific error details, please review your "
"configuration,\n"
"       basic network connectivity, and/or name resolution, and try again.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"오류: ISS Master와 통신하는 동안 오류가 발생했습니다.\n"
"       오류 세부 정보에 따라, 구성, 기본 네트워크 연결 및/또는 이름 확인을 검"
"토한 후\n"
"       다시 시도하십시오.\n"
"       오류 메시지: %s\n"

#: ../satellite_tools/messages.py:51
#, python-format
msgid ""
"\n"
"ERROR: a child-channel cannot be synced without its parent being synced as\n"
"       well. A parent needs to be either (a) previously synced or (b) "
"synced\n"
"       in tandem with the desired child-channel. Missing parents for this\n"
"       transaction:\n"
"       %s\n"
msgstr ""
"\n"
"오류: 상위 채널이 동기화되지 않은 경우 하위 채널을 동기화할 수 없습니다.\n"
"       상위 채널이 (a) 이전에 동기화되거나 (b) 원하는 하위 채널과 함께 동기화"
"되어야 합니다.\n"
"       이 트랜잭션에서 누락된 상위 채널:\n"
"       %s\n"

#: ../satellite_tools/messages.py:59
#, python-format
msgid ""
"\n"
"ERROR: you are not entitled to sync a channel in this set of channels.\n"
"Please contact your SUSE Manager contact\n"
"%s"
msgstr ""
"\n"
"오류: 이 채널 집합의 채널을 동기화할 권한이 없습니다.\n"
"SUSE Manager 담당자에게 문의하십시오.\n"
"%s"

#: ../satellite_tools/messages.py:64
#, python-format
msgid "  ERROR: not enough free space (%s KB) on device."
msgstr "  오류: 장치의 여유 공간(%sKB)이 부족합니다."

#: ../satellite_tools/messages.py:66
#, python-format
msgid "    %3d/%s Fetch successful: %s (%s bytes)"
msgstr "    %3d/%s 패치 성공: %s(%s바이트)"

#: ../satellite_tools/messages.py:67
#, python-format
msgid "    Extinct package:  %s"
msgstr "    비활성 패키지:  %s"

#: ../satellite_tools/messages.py:68
#, python-format
msgid "   Total size: %s"
msgstr "   총 크기: %s"

#: ../satellite_tools/messages.py:69
#, python-format
msgid "      Downloaded %s of %s. Estimated remaining time: %s"
msgstr "      %s/%s 다운로드 완료. 예상 남은 시간: %s"

#: ../satellite_tools/messages.py:70
#, python-format
msgid "    Fetch unsuccessful: %s"
msgstr "    패치 실패: %s"

#: ../satellite_tools/messages.py:71
#, python-format
msgid "   RPM fetch summary: %s"
msgstr "   RPM 패치 요약: %s"

#: ../satellite_tools/messages.py:72
#, python-format
msgid "       success: %d"
msgstr "       성공: %d"

#: ../satellite_tools/messages.py:73
#, python-format
msgid "       failed:  %d"
msgstr "       실패:  %d"

#: ../satellite_tools/messages.py:74
#, python-format
msgid "       extinct: %d"
msgstr "       비활성: %d"

#: ../satellite_tools/messages.py:76
#, python-format
msgid "   Retrieving / parsing *relevant* package metadata: %s (%s)"
msgstr "   *관련* 패키지 메타데이터 검색 중/구문 분석 중: %s(%s)"

#: ../satellite_tools/messages.py:77
#, python-format
msgid "   Retrieving / parsing errata data: %s (%s)"
msgstr "   오류 데이터 검색 중/구문 분석 중: %s(%s)"

#: ../satellite_tools/messages.py:78
#, python-format
msgid "   Retrieving / parsing kickstart data: %s (%s)"
msgstr "   킥스타트 데이터 검색 중/구문 분석 중: %s(%s)"

#: ../satellite_tools/messages.py:79
#, python-format
msgid "   Retrieving / parsing kickstart tree files: %s (%s)"
msgstr "   킥스타트 트리 파일 검색 중/구문 분석 중: %s(%s)"

#: ../satellite_tools/messages.py:80
#, python-format
msgid "   Importing *relevant* package metadata: %s (%s)"
msgstr "   *관련* 패키지 메타데이터 가져오는 중: %s(%s)"

#: ../satellite_tools/messages.py:81
msgid "   * WARNING: this may be a slow process."
msgstr "   * 경고: 시간이 오래 걸리는 프로세스일 수 있습니다."

#: ../satellite_tools/messages.py:82
msgid "Linking packages to channels"
msgstr "패키지를 채널에 연결"

#: ../satellite_tools/messages.py:83
#, python-format
msgid "   Importing *relevant* errata: %s (%s)"
msgstr "   *관련* 오류 가져오는 중: %s(%s)"

#: ../satellite_tools/messages.py:84
msgid "   No new kickstartable tree to import"
msgstr "   가져올 새 킥스타트 가능 트리 없음"

#: ../satellite_tools/messages.py:85
#, python-format
msgid "Importing kickstartable trees (%d)"
msgstr "킥스타트 가능 트리 가져오기(%d)"

#: ../satellite_tools/messages.py:86
#, python-format
msgid "Imported kickstartable trees (%d)"
msgstr "가져온 킥스타트 가능 트리(%d)"

#: ../satellite_tools/reposync.py:114 ../satellite_tools/satsync.py:439
msgid "+++ sending log as an email +++"
msgstr "+++ 로그를 이메일로 전송 +++"

#: ../satellite_tools/reposync.py:117
#, python-format
msgid "%s sync. report from %s"
msgstr "%s의 %s 동기화 보고서"

#: ../satellite_tools/reposync.py:125 ../satellite_tools/satsync.py:449
msgid "+++ email requested, but there is nothing to send +++"
msgstr "+++ 이메일이 요청되었지만, 전송할 항목이 없음 +++"

#: ../satellite_tools/rhn_satellite_activate.py:198
#, python-format
msgid ""
"\"%s\" (specified in commandline)\n"
"could not be opened and read:\n"
"%s"
msgstr ""
"\"%s\"(명령줄에 지정됨)\n"
"열거나 읽을 수 없음:\n"
"%s"

#: ../satellite_tools/rhn_satellite_activate.py:205
#, python-format
msgid ""
"\"%s\" could not be opened\n"
"and/or written to:\n"
"%s"
msgstr ""
"\"%s\"을(를) 열거나\n"
"쓸 수 없는 대상:\n"
"%s"

#: ../satellite_tools/satsync.py:258
#, python-format
msgid "No handler for step %s"
msgstr "%s 단계에 대한 핸들러 없음"

#. Try one more time - this time it should be faster since
#. everything should be cached
#: ../satellite_tools/satsync.py:270
msgid "Environment changed, trying again..."
msgstr "환경이 변경되었습니다. 다시 시도하는 중..."

#: ../satellite_tools/satsync.py:277
msgid "ERROR: Encountered IntegrityError: \n"
msgstr "오류: 무결성 오류 발생: \n"

#: ../satellite_tools/satsync.py:285
msgid "Repeated failures"
msgstr "반복 실패"

#: ../satellite_tools/satsync.py:290
#, python-format
msgid ""
"    Import complete:\n"
"        Begin time: %s\n"
"        End time:   %s\n"
"        Elapsed:    %s\n"
"          "
msgstr ""
"    가져오기 완료:\n"
"        시작 시간: %s\n"
"        종료 시간:   %s\n"
"        경과된 시간:    %s\n"
"          "

#: ../satellite_tools/satsync.py:311
msgid "hours"
msgstr "시간"

#: ../satellite_tools/satsync.py:311
msgid "minutes"
msgstr "분"

#: ../satellite_tools/satsync.py:311
msgid "seconds"
msgstr "초"

#: ../satellite_tools/satsync.py:357
msgid ""
"ERROR: The dump is missing package data, use --no-rpms to skip this step or "
"fix the content to include package data."
msgstr ""
"오류: 덤프에서 패키지 데이터가 누락되었습니다. --no-rpms를 사용하여 이 단계"
"를 건너뛰거나 패키지 데이터를 포함하도록 컨텐트를 수정하십시오."

#. the orgs() method doesn't exist; that's fine we just
#. won't sync the orgs
#: ../satellite_tools/satsync.py:404
msgid "The SUSE Manager master does not support syncing orgs data."
msgstr "SUSE Manager는 조직 데이터 동기화를 지원하지 않습니다."

#: ../satellite_tools/satsync.py:404
msgid "Skipping..."
msgstr "건너뛰는 중..."

#: ../satellite_tools/satsync.py:442
#, python-format
msgid "SUSE Manager Inter Server sync. report from %s"
msgstr "%s의 SUSE Manager 내부 서버 동기화 보고서"

#: ../satellite_tools/satsync.py:520
msgid " - file-system synchronization"
msgstr " - 파일-시스템 동기화"

#: ../satellite_tools/satsync.py:532 ../satellite_tools/satsync.py:540
msgid " - live synchronization"
msgstr " - 라이브 동기화"

#: ../satellite_tools/satsync.py:533
#, python-brace-format
msgid ""
"ERROR: Live content synchronizing with RHN Classic Hosted is no longer "
"supported.\n"
"Please use the cdn-sync command instead unless you are attempting to sync "
"from another {PRODUCT_NAME} via Inter-Server-Sync (ISS), or from local "
"content on disk via Channel Dump ISOs."
msgstr ""
"오류: RHN Classic Hosted와의 라이브 컨텐트 동기화는 더 이상 지원되지 않습니"
"다.\n"
"Inter-Server-Sync(ISS)를 통해 다른 {PRODUCT_NAME}에서 또는 채널 덤프 ISO를 통"
"해 디스크의 로컬 컨텐트에서 동기화를 시도 중인 경우를 제외하고 cdn-sync 명령"
"을 대신 사용하십시오."

#: ../satellite_tools/satsync.py:541
#, python-format
msgid "   url: %s"
msgstr "   URL: %s"

#: ../satellite_tools/satsync.py:542
#, python-format
msgid "   debug/output level: %s"
msgstr "   디버그/출력 수준: %s"

#: ../satellite_tools/satsync.py:552
msgid "ERROR: this server must be registered with SUSE Manager."
msgstr "오류: 이 서버를 SUSE Manager에 등록해야 합니다."

#: ../satellite_tools/satsync.py:574
#, python-format
msgid "Retrieving / parsing %s data"
msgstr "%s 데이터 검색 중/구문 분석 중"

#: ../satellite_tools/satsync.py:584 ../satellite_tools/satsync.py:599
msgid "*** SYSTEM INTERRUPT CALLED ***"
msgstr "*** 시스템 인터럽트 호출됨 ***"

#: ../satellite_tools/satsync.py:592
msgid "ERROR: fatal parser exception occurred "
msgstr "오류: 심각한 구문 분석기 예외가 발생했습니다. "

#: ../satellite_tools/satsync.py:593
#, python-format
msgid "(line: %s, col: %s msg: %s)"
msgstr "(라인: %s, 열: %s 메시지: %s)"

#: ../satellite_tools/satsync.py:597
#, python-format
msgid "ERROR: parser exception occurred: %s"
msgstr "오류: 구문 분석이 예외 발생: %s"

#: ../satellite_tools/satsync.py:602
msgid "ERROR: exception (during parse) occurred: "
msgstr "오류: (구문 분석 중) 오류 발생: "

#: ../satellite_tools/satsync.py:603
#, python-format
msgid ""
"   Encountered some errors with %s data (see logs (%s) for more information)"
msgstr "   %s 데이터에서 일부 오류 발생(자세한 정보는 로그(%s) 참조)"

#: ../satellite_tools/satsync.py:605
#, python-format
msgid "   Encountered some errors with %s data:"
msgstr "   %s 데이터에서 일부 오류 발생:"

#: ../satellite_tools/satsync.py:606
#, python-format
msgid "   ------- %s PARSE/IMPORT ERROR -------"
msgstr "   ------- %s 구문 분석기/가져오기 오류 -------"

#: ../satellite_tools/satsync.py:608
msgid "   ---------------------------------------"
msgstr "   ---------------------------------------"

#: ../satellite_tools/satsync.py:611
#, python-format
msgid "%s data complete"
msgstr "%s 데이터 완료"

#: ../satellite_tools/satsync.py:664
msgid "Retrieving / parsing channel data"
msgstr "채널 데이터 가져오는 중/구문 분석 중"

#: ../satellite_tools/satsync.py:717
msgid "Channel data complete"
msgstr "채널 데이터 완료"

#: ../satellite_tools/satsync.py:735
#, python-format
msgid "%10s import from %s"
msgstr "%s에서 %10s 가져오기"

#: ../satellite_tools/satsync.py:738
#, python-format
msgid "%10s import from %s - %s"
msgstr "%s - %s에서 %10s 가져오기"

#: ../satellite_tools/satsync.py:742
#, python-format
msgid "%10s"
msgstr "%10s"

#: ../satellite_tools/satsync.py:749
msgid "p"
msgstr "p"

#: ../satellite_tools/satsync.py:751
msgid "."
msgstr "."

#: ../satellite_tools/satsync.py:757
msgid "   p = previously imported/synced channel"
msgstr "   p = 이전에 가져온/동기화된 채널"

#: ../satellite_tools/satsync.py:758
msgid "   . = channel not yet imported/synced"
msgstr "   . = 채널을 아직 가져오기/동기화하지 않음"

#: ../satellite_tools/satsync.py:764
msgid "   e = channel no longer supported (end-of-service)"
msgstr "   e = 채널이 더 이상 지원되지 않음(서비스 종료)"

#: ../satellite_tools/satsync.py:766
msgid "   ? = channel label invalid --- typo?"
msgstr "   ? = 채널 레이블 잘못됨 --- 오타?"

#: ../satellite_tools/satsync.py:770
#, python-format
msgid "   %s:"
msgstr "   %s:"

#: ../satellite_tools/satsync.py:771
#, python-format
msgid "      %s %-40s %4s %s"
msgstr "      %s %-40s %4s %s"

#: ../satellite_tools/satsync.py:772
msgid "base-channels"
msgstr "기본 채널"

#: ../satellite_tools/satsync.py:785 ../satellite_tools/satsync.py:1619
msgid "NONE RELEVANT"
msgstr "관련 항목 없음"

#: ../satellite_tools/satsync.py:807
msgid "end-of-service"
msgstr "서비스 종료"

#: ../satellite_tools/satsync.py:808
msgid "e"
msgstr "e"

#: ../satellite_tools/satsync.py:814
msgid "   typos:"
msgstr "   오타:"

#: ../satellite_tools/satsync.py:815
msgid "?"
msgstr "?"

#: ../satellite_tools/satsync.py:830
#, python-format
msgid "XXX: imported channels: %s"
msgstr "XXX: 가져온 채널: %s"

#: ../satellite_tools/satsync.py:831
#, python-format
msgid "XXX:   cached channels: %s"
msgstr "XXX:   캐시된 채널: %s"

#: ../satellite_tools/satsync.py:836
msgid "XXX: list channels called"
msgstr "XXX: 호출된 채널 목록"

#: ../satellite_tools/satsync.py:854
msgid "ERROR: these channels either do not exist or are not available:"
msgstr "오류: 이러한 채널이 없거나 사용할 수 없음:"

#: ../satellite_tools/satsync.py:858
#, python-format
msgid "       (to see a list of channel labels: %s --list-channels)"
msgstr "       (채널 목록을 확인하려면: %s --list-channels)"

#: ../satellite_tools/satsync.py:903
#, python-format
msgid "   Retrieving / parsing short package metadata: %s (%s)"
msgstr "   짧은 패키지 메타데이터 검색 중/구문 분석 중: %s(%s)"

#: ../satellite_tools/satsync.py:981
#, python-format
msgid "Diffing package metadata (what's missing locally?): %s"
msgstr "패키지 메타데이터 비교(로컬에서 누락된 항목이 무엇입니까?): %s"

#: ../satellite_tools/satsync.py:987 ../satellite_tools/satsync.py:1270
msgid "Diffing:    "
msgstr "비교:    "

#: ../satellite_tools/satsync.py:1004
msgid "ERROR: incremental dump skipped"
msgstr "오류: 증분 덤프 건너뜀"

#: ../satellite_tools/satsync.py:1095
msgid "Downloading rpm packages"
msgstr "RPM 패키지 다운로드 중"

#: ../satellite_tools/satsync.py:1100
#, python-format
msgid "   Fetching any missing RPMs: %s (%s)"
msgstr "   누락된 모든 RPM을 가져오는 중: %s(%s)"

#: ../satellite_tools/satsync.py:1101 ../satellite_tools/satsync.py:1169
msgid "NONE MISSING"
msgstr "누락 항목 없음"

#: ../satellite_tools/satsync.py:1110
msgid "Processing rpm packages complete"
msgstr "RPM 패키지 처리 완료"

#: ../satellite_tools/satsync.py:1137
msgid "Downloading package metadata"
msgstr "패키지 메타데이터 다운로드 중"

#: ../satellite_tools/satsync.py:1162
msgid "Downloading srpm packages"
msgstr "srpm 패키지 다운로드 중"

#: ../satellite_tools/satsync.py:1168
#, python-format
msgid "   Fetching any missing SRPMs: %s (%s)"
msgstr "   누락된 모든 SRPM을 가져오는 중: %s(%s)"

#: ../satellite_tools/satsync.py:1265
#, python-format
msgid "Diffing source package metadata (what's missing locally?): %s"
msgstr "소스 패키지 메타데이터 비교(로컬에서 누락된 항목이 무엇입니까?): %s"

#: ../satellite_tools/satsync.py:1276
msgid "Downloading source package metadata"
msgstr "소스 패키지 메타데이터 다운로드 중"

#: ../satellite_tools/satsync.py:1354 ../satellite_tools/satsync.py:2043
#, python-format
msgid "Unable to save file %s: %s"
msgstr "%s 파일을 저장할 수 없음: %s"

#. for
#. Retried a number of times and it still failed; log the
#. file as being failed and move on
#: ../satellite_tools/satsync.py:1361
#, python-format
msgid "Failed to fetch file %s"
msgstr "%s 파일을 가져오지 못함"

#: ../satellite_tools/satsync.py:1366
msgid "Downloading kickstartable trees metadata"
msgstr "킥스타트 가능 트리 메타데이터 다운로드 중"

#: ../satellite_tools/satsync.py:1381
msgid "Downloading kickstartable trees files"
msgstr "킥스타트 가능 트리 파일 다운로드 중"

#: ../satellite_tools/satsync.py:1520
#, python-format
msgid "Grabbing all patches for channel %s"
msgstr "%s 채널에 대한 모든 패치를 캡처하는 중"

#: ../satellite_tools/satsync.py:1570
msgid "Downloading patch data"
msgstr "패치 데이터 다운로드 중"

#: ../satellite_tools/satsync.py:1572
msgid "Forcing download of all patch data for requested channels."
msgstr "요청된 채널에 대한 모든 패치 데이터를 강제로 다운로드하는 중입니다."

#: ../satellite_tools/satsync.py:1587
msgid "Downloading patch data complete"
msgstr "패치 데이터 다운로드 완료"

#: ../satellite_tools/satsync.py:1592 ../satellite_tools/satsync.py:1613
msgid "Downloading:"
msgstr "다운로드:"

#: ../satellite_tools/satsync.py:1595
msgid " - complete"
msgstr " - 완료"

#: ../satellite_tools/satsync.py:1640
msgid "Importing source package metadata"
msgstr "소스 패키지 메타데이터를 가져오는 중"

#: ../satellite_tools/satsync.py:1643
msgid "Importing package metadata"
msgstr "패키지 메타데이터를 가져오는 중"

#: ../satellite_tools/satsync.py:1651
msgid "Importing:  "
msgstr "가져오기:  "

#. not in the cache
#: ../satellite_tools/satsync.py:1719
msgid ""
"Package Not Found in Cache, Clear the Cache "
"to                                  Regenerate it."
msgstr "캐시에서 패키지를 찾을 수 없음, 다시 생성하려면 캐시를 삭제하십시오."

#: ../satellite_tools/satsync.py:1725
msgid "Importing channel patches"
msgstr "채널 패치를 가져오는 중"

#: ../satellite_tools/satsync.py:1730
#, python-format
msgid "Importing %s patches for channel %s."
msgstr "%s 채널의 %s 패치를 가져오는 중입니다."

#. Incomplete configuration
#: ../satellite_tools/satsync.py:2129
msgid "ERROR: server.mount_point not set in the configuration file"
msgstr "오류: server.mount_point가 구성 파일에 설정되지 않음"

#: ../satellite_tools/satsync.py:2133
#, python-format
msgid "ERROR: server.mount_point %s do not exist"
msgstr "오류: server.mount_point %s 없음"

#: ../satellite_tools/satsync.py:2138
#, python-format
msgid "ERROR: path under server.mount_point (%s)  do not exist"
msgstr "오류: server.mount_point(%s) 아래에 경로 없음"

#: ../satellite_tools/satsync.py:2215
#, python-format
msgid "Commandline: %s"
msgstr "명령줄: %s"

#: ../satellite_tools/satsync.py:2218
#, python-format
msgid ""
"DEBUG ONLY: max. batch-size for XML/database-import processing (1..%s).\"man "
"mgr-inter-sync\" for more information."
msgstr ""
"디버그 전용: XML/데이터베이스-가져오기 처리(1..%s)를 위한 최대 배치 크기입니"
"다. 자세한 정보는 \"man mgr-inter-sync\"를 참조하십시오."

#: ../satellite_tools/satsync.py:2221
msgid "alternative SSL CA Cert (fullpath to cert file)"
msgstr "대체 SSL CA 인증서(인증서 파일의 전체 경로)"

#: ../satellite_tools/satsync.py:2223
msgid "process data for this channel only"
msgstr "이 채널의 데이터만 처리"

#: ../satellite_tools/satsync.py:2225
msgid ""
"disk dump will be considered to be a full export; see \"man mgr-inter-sync\" "
"for more information."
msgstr ""
"디스크 덤프는 전체 내보내기로 간주됩니다. 자세한 내용은 \"man mgr-inter-sync"
"\"를 참조하십시오."

#: ../satellite_tools/satsync.py:2228
msgid "existing custom channels will also be synced (unless -c is used)"
msgstr "기존 사용자 지정 채널도 동기화됨(-c를 사용하는 경우 제외)"

#: ../satellite_tools/satsync.py:2230
#, python-format
msgid ""
"override debug level set in /etc/rhn/rhn.conf (which is currently set at %s)."
msgstr "/etc/rhn/rhn.conf에 설정된 디버그 수준을 무효화합니다(현재 설정: %s)."

#: ../satellite_tools/satsync.py:2232
#, python-format
msgid "requested version of XML dump (default: %s)"
msgstr "요청된 XML 덤프 버전(기본값: %s)"

#: ../satellite_tools/satsync.py:2234
msgid "e-mail a report of what was synced/imported"
msgstr "동기화된/가져온 항목 보고서를 이메일로 전송"

#: ../satellite_tools/satsync.py:2236
msgid "forcibly process all (not a diff of) patch metadata"
msgstr "모든 패치 메타데이터(비교 제외) 강제 처리"

#: ../satellite_tools/satsync.py:2238
msgid "Do not use an http proxy under any circumstances."
msgstr "모든 환경에서 http 프록시를 사용하지 마십시오."

#: ../satellite_tools/satsync.py:2240
msgid "alternative http proxy (hostname:port)"
msgstr "대체 http 프록시(hostname:port)"

#: ../satellite_tools/satsync.py:2242
msgid "alternative http proxy username"
msgstr "대체 http 프록시 사용자 이름"

#: ../satellite_tools/satsync.py:2244
msgid "alternative http proxy password"
msgstr "대체 http 프록시 비밀번호"

#: ../satellite_tools/satsync.py:2246
msgid "parent SUSE Manager to import content from"
msgstr "컨텐트를 가져올 상위 SUSE Manager"

#: ../satellite_tools/satsync.py:2248
msgid "list all available channels and exit"
msgstr "사용할 수 있는 모든 채널을 나열 후 종료"

#: ../satellite_tools/satsync.py:2250
msgid "help on all error codes mgr-inter-sync returns"
msgstr "mgr-inter-sync에서 반환된 모든 오류 코드에 대한 도움말"

#: ../satellite_tools/satsync.py:2252
msgid "source mount point for import - disk update only"
msgstr "가져올 소스 마운트 포인트 - 디스크 업데이트 전용"

#: ../satellite_tools/satsync.py:2254
msgid "do not process patch data"
msgstr "패치 데이터를 처리하지 않음"

#: ../satellite_tools/satsync.py:2256
msgid "do not process kickstart data (provisioning only)"
msgstr "킥스타트 데이터를 처리하지 않음(프로비저닝 전용)"

#: ../satellite_tools/satsync.py:2258
msgid "do not process full package metadata"
msgstr "전체 패키지 메타데이터를 처리하지 않음"

#: ../satellite_tools/satsync.py:2260
msgid "do not download, or process any RPMs"
msgstr "RPM을 다운로드하거나 처리하지 않음"

#: ../satellite_tools/satsync.py:2262
msgid "org to which the sync imports data. defaults to the admin account"
msgstr "동기화에서 데이터를 가져올 조직. 기본값은 관리자 계정임"

#: ../satellite_tools/satsync.py:2264
msgid "print the configuration and exit"
msgstr "구성 인쇄 후 종료"

#: ../satellite_tools/satsync.py:2266
msgid "alternative server with which to connect (hostname)"
msgstr "연결 대상 대체 서버(호스트 이름)"

#: ../satellite_tools/satsync.py:2268
msgid "synchronize to this step (man mgr-inter-sync for more info)"
msgstr "이 단계 동기화(자세한 정보는 man mgr-inter-sync 참조)"

#: ../satellite_tools/satsync.py:2270
msgid "write complete data to tempfile before streaming to remainder of app"
msgstr "임시 파일에 전체 데이터를 쓴 후 앱의 나머지로 스트리밍"

#: ../satellite_tools/satsync.py:2272
msgid "DEBUG ONLY: alternative path to digital system id"
msgstr "디버그 전용: 디지털 시스템 ID의 대체 경로"

#: ../satellite_tools/satsync.py:2274
msgid "alternative email address(es) for sync output (--email option)"
msgstr "동기화 출력의 대체 이메일 주소(--email 옵션)"

#: ../satellite_tools/satsync.py:2276
msgid "do not remove rpms when importing from local dump"
msgstr "로컬 덤프를 가져올 때 rpm을 제거하지 않음"

#: ../satellite_tools/satsync.py:2278
msgid ""
"the fully qualified domain name of the master Satellite. Valid with --mount-"
"point only. Required if you want to import org data and channel permissions."
msgstr ""
"마스터 Satellite의 정규화된 도메인 이름입니다. --mount-point에만 유효합니다. "
"조직 데이터 및 채널 권한을 가져올 때 필요합니다."

#: ../satellite_tools/satsync.py:2288
#, python-format
msgid "ERROR: these arguments make no sense in this context (try --help): %s"
msgstr "오류: 이러한 인수는 이 컨텍스트에서 적합하지 않음(--help 시도): %s"

#. An SQL error is fatal... crash and burn
#: ../satellite_tools/satsync.py:2300
#, python-format
msgid "ERROR: Can't connect to the database: %s"
msgstr "오류: 데이터베이스에 연결할 수 없음: %s"

#: ../satellite_tools/satsync.py:2301
msgid "ERROR: Check if your database is running."
msgstr "오류: 데이터베이스가 실행 중인지 확인하십시오."

#: ../satellite_tools/satsync.py:2334
#, python-format
msgid "ERROR: --debug-level takes an in integer value within the range %s."
msgstr "오류: --debug-level에는 %s 범위 이내의 정수값을 사용해야 합니다."

#: ../satellite_tools/satsync.py:2336
msgid "  0  - little logging/messaging."
msgstr "  0  - 로깅/메시지 없음."

#: ../satellite_tools/satsync.py:2337
msgid "  1  - minimal logging/messaging."
msgstr "  1  - 로깅/메시지 최소."

#: ../satellite_tools/satsync.py:2338
msgid "  2  - normal level of logging/messaging."
msgstr "  2  - 로깅/메시지 정상 수준."

#: ../satellite_tools/satsync.py:2339
msgid "  3  - lots of logging/messaging."
msgstr "  3  - 로깅/메시지 많음."

#: ../satellite_tools/satsync.py:2340
msgid "  4+ - excessive logging/messaging."
msgstr "  4+ - 로깅/메시지 너무 많음."

#: ../satellite_tools/satsync.py:2353
msgid "ERROR: The --master option is only valid with the --mount-point option"
msgstr ""
"오류: --master 옵션은 --mount-point 옵션과 함께 사용할 때만 사용할 수 있음"

#: ../satellite_tools/satsync.py:2363
#, python-format
msgid "ERROR: Unable to lookup Org Id %s"
msgstr "오류: 조직 ID %s을(를) 조회할 수 없음"

#: ../satellite_tools/satsync.py:2372
msgid ""
"WARNING: --list-channels option overrides any --step option. --step ignored."
msgstr ""
"경고: --list-channels 옵션은 모든 --step 옵션을 재정의합니다. --step이 무시되"
"었습니다."

#: ../satellite_tools/satsync.py:2387
#, python-format
msgid ""
"ERROR: '%s' is not a valid step. See 'man mgr-inter-sync' for more detail."
msgstr ""
"오류: '%s'은(는) 유효한 단계가 아닙니다. 자세한 내용은 'man mgr-inter-"
"sync'를 참조하십시오."

#: ../satellite_tools/satsync.py:2419
msgid ""
"ERROR: No channels currently imported; try mgr-inter-sync --list-channels; "
"then mgr-inter-sync -c chn0 -c chn1..."
msgstr ""
"오류: 현재 가져온 채널이 없습니다. mgr-inter-sync --list-channels을 사용한 "
"후 mgr-inter-sync -c chn0 -c chn1를 사용하십시오..."

#. int(None) --> TypeError
#. int('a')  --> ValueError
#: ../satellite_tools/satsync.py:2468 ../satellite_tools/satsync.py:2472
msgid "ERROR: --batch-size must have a value within the range: 1..50"
msgstr "오류: --batch-size는 다음 범위 내의 값을 가져야 함: 1..50"

#: ../satellite_tools/satsync.py:2480
#, python-format
msgid "ERROR: no such directory %s"
msgstr "오류: 해당 디렉토리 %s 없음"

#: ../satellite_tools/satsync.py:2485
msgid "Error Codes: Returned codes means:"
msgstr "오류 코드: 반환된 코드의 의미:"

#: ../satellite_tools/satsync.py:2486
msgid " -1  - Could not lock file or KeyboardInterrupt or SystemExit"
msgstr " -1  - 파일을 잠글 수 없음 또는 KeyboardInterrupt 또는 SystemExit"

#: ../satellite_tools/satsync.py:2487
msgid "  0  - User interrupted or intentional exit"
msgstr "  0  - 사용자 인터럽트됨 또는 미리 계획된 종료"

#: ../satellite_tools/satsync.py:2488
msgid "  1  - attempting to run more than one instance of mgr-inter-sync."
msgstr ""
"  1  - mgr-inter-sync의 인스턴스를 1개 이상 실행하기 위해 시도하는 중입니다."

#: ../satellite_tools/satsync.py:2489
msgid "  2  - Unable to find synchronization tools."
msgstr "  2  - 동기화 도구를 찾을 수 없습니다."

#: ../satellite_tools/satsync.py:2490
msgid "  3  - a general socket exception occurred"
msgstr "  3  - 일반 소켓 예외 발생"

#: ../satellite_tools/satsync.py:2491
msgid "  4  - an SSL error occurred. Recheck your SSL settings."
msgstr "  4  - SSL 오류가 발생했습니다. SSL 설정을 다시 확인하십시오."

#: ../satellite_tools/satsync.py:2492
msgid "  5  - ISS error"
msgstr "  5  - ISS 오류"

#: ../satellite_tools/satsync.py:2493
msgid "  6  - unhandled exception occurred"
msgstr "  6  - 처리되지 않은 예외 발생"

#: ../satellite_tools/satsync.py:2494
msgid "  7  - unknown sync error"
msgstr "  7  - 알 수 없는 동기화 오류"

#: ../satellite_tools/satsync.py:2495
msgid "  8  - ERROR: must be root to execute"
msgstr "  8  - 오류: 루트로 실행해야 함"

#: ../satellite_tools/satsync.py:2496
msgid "  9  - rpclib fault during synchronization init"
msgstr "  9  - 동기화 초기화 중 rpclib 오류"

#: ../satellite_tools/satsync.py:2497
msgid "  10 - synchronization init error"
msgstr "  10 - 동기화 초기화 오류"

#: ../satellite_tools/satsync.py:2498
msgid "  11 - Error parsing XML stream"
msgstr "  11 - XML 스트림 구문 분석 중 오류"

#: ../satellite_tools/satsync.py:2499
msgid "  12 - Channel do not exist"
msgstr "  12 - 채널 없음"

#: ../satellite_tools/satsync.py:2500
msgid "  13 - SQL error during importing package metadata"
msgstr "  13 - 패키지 메타데이터를 가져오는 중 SQL 오류"

#: ../satellite_tools/satsync.py:2501
msgid "  14 - SQL error during linking channel packages"
msgstr "  14 - 채널 패키지를 연결하는 중 SQL 오류"

#: ../satellite_tools/satsync.py:2502
msgid "  15 - SQL error during xml processing"
msgstr "  15 - xml 처리 중 SQL 오류"

#: ../satellite_tools/satsync.py:2503
msgid "  16 - server.mount_point not set in the configuration file"
msgstr "  16 - server.mount_point가 구성 파일에 설정되지 않음"

#: ../satellite_tools/satsync.py:2504
msgid ""
"  17 - SQL error during retrieving the channels already imported in the SUSE "
"Manager database"
msgstr "  17 - 이미 가져온 SUSE Manager 데이터베이스의 채널 검색 중 SQL 오류"

#: ../satellite_tools/satsync.py:2505
msgid "  18 - Wrong db connection string in rhn.conf"
msgstr "  18 - rhn.conf의 잘못된 db 연결 문자열"

#: ../satellite_tools/satsync.py:2506
msgid "  19 - Bad arguments"
msgstr "  19 - 잘못된 인수"

#: ../satellite_tools/satsync.py:2507
msgid "  20 - Could not connect to db."
msgstr "  20 - db에 연결할 수 없습니다."

#: ../satellite_tools/satsync.py:2508
msgid "  21 - Bad debug level"
msgstr "  21 - 잘못된 디버그 레벨"

#: ../satellite_tools/satsync.py:2509
msgid "  22 - Not valid step"
msgstr "  22 - 유효한 단계 아님"

#: ../satellite_tools/satsync.py:2510
msgid "  24 - no such file"
msgstr "  24 - 해당 파일 없음"

#: ../satellite_tools/satsync.py:2511
msgid "  25 - no such directory"
msgstr "  25 - 해당 디렉토리 없음"

#: ../satellite_tools/satsync.py:2512
msgid "  26 - mount_point does not exist"
msgstr "  26 - mount_point 없음"

#: ../satellite_tools/satsync.py:2513
msgid "  27 - No such org"
msgstr "  27 - 해당 조직 없음"

#: ../satellite_tools/satsync.py:2514
msgid "  28 - error: --master is only valid with --mount-point"
msgstr "  28 - 오류: --master는 --mount-point와 함께 사용하는 경우에만 유효함"

#: ../satellite_tools/satsync.py:2521
#, python-format
msgid "ERROR: unknown dump version, try one of %s"
msgstr "오류: 알 수 없는 덤프 버전, %s 중 하나 시도"
