# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# David Barzilay <barzilay@redhat.com>, 2004, 2005.
# Igor Pires Soares <igor@projetofedora.org>, 2007.
# Pedro Fernandes Macedo <webmaster@margo.bijoux.nom.br>, 2004.
# Pedro Macedo <pmacedo@intel.dcc.ufmg.br>, 2005.
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-09-29 14:21+0200\n"
"PO-Revision-Date: 2020-10-15 01:49+0000\n"
"Last-Translator: Rodrigo Macedo <rmsolucoeseminformatic4@gmail.com>\n"
"Language-Team: Portuguese (Brazil) <https://l10n.opensuse.org/projects/uyuni/"
"backend/pt_BR/>\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n > 1;\n"
"X-Generator: Weblate 3.6.1\n"

#: ../server/apacheAuth.py:66
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "token de autenticação de proxy incompleto: %s"

#: ../server/apacheAuth.py:84
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr "A assinatura de proxy enviada %s não corresponde à nossa %s."

#: ../server/apacheAuth.py:119
msgid "declined proxy authentication"
msgstr "autenticação de proxy recusada"

#: ../server/handlers/app/packages.py:192
#: ../server/handlers/xmlrpc/registration.py:215
#: ../server/handlers/xmlrpc/registration.py:1168
#: ../server/handlers/xmlrpc/registration.py:1307
#: ../server/configFilesHandler.py:129
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   A conta %s foi desativada neste servidor.\n"
"                   Entre em contato com o administrador da organização para "
"obter mais ajuda."

#: ../server/handlers/applet/applet.py:78
#, python-brace-format
msgid "Your system was not found in the {PRODUCT_NAME} database"
msgstr "Seu sistema não foi encontrado no banco de dados do {PRODUCT_NAME}"

#: ../server/handlers/sat/auth.py:45
msgid "ISS is disabled on this server."
msgstr "O ISS está desativado neste servidor."

#: ../server/handlers/sat/auth.py:50
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "O servidor \"%s\" não está ativado para o ISS."

#: ../server/handlers/xmlrpc/scap.py:104
msgid "Invalid system_id/action_id pair."
msgstr "Par system_id / action_id inválido."

#: ../server/handlers/xmlrpc/errata.py:64
#, python-format
msgid "Expected a package name, not: %s"
msgstr "Esperado um nome de pacote, não: %s"

#: ../server/handlers/xmlrpc/errata.py:115
#, python-format
msgid "Expected a package, not: %s"
msgstr "Esperado um pacote, não: %s"

#: ../server/handlers/xmlrpc/queue.py:433
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr "Tipo de valor de ação inválido%s (%s)"

#: ../server/handlers/xmlrpc/queue.py:464
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "A ação %s não pertence ao servidor %s"

#: ../server/handlers/xmlrpc/up2date.py:233
#, python-format
msgid "Invalid value %s (%s)"
msgstr "Valor inválido %s (%s)"

#: ../server/handlers/xmlrpc/proxy.py:65
#, python-format
msgid "SUSE Manager Proxy service not enabled for server profile: \"%s\""
msgstr ""
"O serviço SUSE Manager Proxy não está habilitado para o perfil do servidor: "
"\"%s\""

#: ../server/handlers/xmlrpc/proxy.py:85
msgid "Invalid session key"
msgstr "Chave de sessão inválida"

#: ../server/handlers/xmlrpc/proxy.py:93
msgid "This server ID no longer exists"
msgstr "Esse ID de servidor não existe mais"

#: ../server/handlers/xmlrpc/registration.py:194
msgid "Required data missing"
msgstr "Dados necessários ausentes"

#: ../server/handlers/xmlrpc/registration.py:198
msgid "Required members missing"
msgstr "Membros necessários ausentes"

#: ../server/handlers/xmlrpc/registration.py:207
msgid "Attempt to register a system to an invalid username"
msgstr "Tentativa de registrar um sistema para um nome de usuário inválido"

#: ../server/handlers/xmlrpc/registration.py:839
msgid "Invalid system release version requested"
msgstr "Versão de lançamento do sistema solicitada inválida"

#: ../server/handlers/xmlrpc/registration.py:1063
msgid ""
"Unable to find a valid network interface, both ipaddr and ip6addr not found."
msgstr ""
"Não foi possível encontrar uma interface de rede válida, ipaddr e ip6addr "
"não encontrados."

#: ../server/handlers/xmlrpc/registration.py:1115
#, python-brace-format
msgid "{PRODUCT_NAME} Welcome Message"
msgstr "{PRODUCT_NAME} Mensagem de Boas vindas"

#: ../server/handlers/xmlrpc/registration.py:1125
msgid "Privacy Statement"
msgstr "Declaração de Privacidade"

#: ../server/handlers/xmlrpc/registration.py:1146
msgid "Expected a dictionary as a product argument"
msgstr "Esperado um dicionário como argumento do produto"

#: ../server/handlers/xmlrpc/registration.py:1374
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr "Valor inválido '%s' para %s (%s)"

#: ../server/importlib/userAuth.py:98
msgid "You are not authorized to manage packages in the null org"
msgstr "Você não está autorizado a gerenciar pacotes na organização nula"

#: ../server/importlib/userAuth.py:103
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "Você não tem permissão para gerenciar pacotes na organização %s"

#: ../server/importlib/userAuth.py:121
msgid "You are not allowed to perform administrative tasks"
msgstr "Você não tem permissão para executar tarefas administrativas"

#: ../server/importlib/userAuth.py:144
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr ""
"Você não tem permissão para gerenciar o canal %s, ou esse canal não existe"

#: ../server/importlib/userAuth.py:204
#, python-format
msgid ""
"\n"
"               %s Account has been deactivated on this server.\n"
"               Please contact your Org administrator for more help."
msgstr ""
"\n"
"               A conta %s foi desativada neste servidor.\n"
"               Entre em contato com o administrador da organização para "
"obter mais ajuda."

#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr "Execute rhn_register como root neste cliente"

#: ../server/rhnHandler.py:75
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr "Serviço não ativado para o perfil do sistema: \"%s\""

#: ../server/rhnServer/server_class.py:97
#, python-format
msgid "Architecture `%s' is not supported"
msgstr "A arquitetura `%s' não é suportada"

#: ../server/rhnServer/server_token.py:78
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "O token `%s' possui mais de um canal base atribuído"

#: ../server/rhnServer/server_token.py:80
msgid "Conflicting base channels"
msgstr "Canais básicos conflitantes"

#: ../server/rhnServer/server_token.py:190
#, python-format
msgid "Failed to add server to group %s"
msgstr "Falha ao adicionar servidor ao grupo %s"

#: ../server/rhnServer/server_token.py:503
#, python-format
msgid "Maximum usage count of %s reached"
msgstr "Contagem máxima de uso de %s atingida"

#: ../server/rhnServer/server_token.py:744
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""
"O empilhamento de tokens de recadastramento com diferentes direitos de base "
"não é suportado"

#: ../server/rhnServer/server_token.py:811
#, python-format
msgid "Could not find token '%s'"
msgstr "Não foi possível encontrar o token '%s'"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:843
msgid "Tokens from mismatching orgs"
msgstr "Tokens de organizações incompatíveis"

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:853
msgid "Kickstart session mismatch"
msgstr "Incompatibilidade de sessão do Kickstart"

#: ../server/rhnServer/server_token.py:877
msgid "Stacking of re-registration tokens is not supported"
msgstr "O empilhamento de tokens de re-registro não é suportado"

#: ../server/rhnUser.py:289 ../server/rhnUser.py:292
msgid "Invalid username/password combination"
msgstr "Combinação de nome de usuário/senha inválido"

#. nope, not reserved either
#: ../server/rhnUser.py:467
#, python-format
msgid "Username `%s' has not been reserved"
msgstr "O nome de usuário `%s 'não foi reservado"

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:473
msgid "E-mail address not specified"
msgstr "Endereço de email não especificado"

#: ../server/rhnUser.py:509
#, python-format
msgid "username should be at least %d characters"
msgstr "o nome de usuário deve ter pelo menos %d caracteres"

#: ../server/rhnUser.py:512
#, python-format
msgid "username should be less than %d characters"
msgstr "o nome de usuário deve ter menos de %d caracteres"

#: ../server/rhnUser.py:523
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr "nome de usuário = `%s', caractere inválido`%s'"

#: ../server/rhnUser.py:542
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr "Por favor limite seu endereço de e-mail a %s caracteres"

#: ../server/rhnUser.py:623
#, python-format
msgid "password must be at least %d characters"
msgstr "a senha deve ter pelo menos %d caracteres"

#: ../server/rhnUser.py:626
#, python-format
msgid "Password must be shorter than %d characters"
msgstr "A senha deve ter menos de %d caracteres"

#: ../server/rhnUser.py:644
#, python-format
msgid "password contains character `%s'"
msgstr "a senha contém o caractere `%s '"

#: ../server/rhnUser.py:651
#, python-format
msgid "username should be at least %d characters long"
msgstr "o nome de usuário deve ter pelo menos %d caracteres"

#: ../server/rhnUser.py:662
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr "Não é possível registrar nomes de usuário que terminem com %s"

#: ../server/rhnPackage.py:49 ../server/rhnPackage.py:87
#: ../server/rhnPackage.py:107 ../server/rhnPackage.py:158
#, python-format
msgid "Invalid RPM package %s requested"
msgstr "Pacote RPM inválido %s solicitado"

#: ../server/rhnPackage.py:112
msgid "Package not found"
msgstr "Pacote não encontrado"

#: ../server/apacheRequest.py:59
#, python-format
msgid "Invalid request received (%s)."
msgstr "Solicitação inválida recebida (%s)."

#: ../server/apacheRequest.py:120
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""
"SEGUINTE MENSAGEM IMPORTANTE:\n"
"%s"

#: ../server/apacheRequest.py:149
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""
"Durante a execução de '%s': capturado\n"
"%s : %s\n"

#: ../server/apacheRequest.py:606
#, python-format
msgid "Invalid URI %s"
msgstr "URI %s inválida"

#: ../server/rhnChannel.py:1992
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""
"Sua conta não tem acesso a nenhum canal correspondente (release "
"='%(release)s', arch='%(arch)s')%(www_activation)s"

#: ../server/rhnChannel.py:2002
msgid ""
"\n"
"If you have a registration number, please register with it first at http://"
"www.redhat.com/apps/activate/ and then try again.\n"
"\n"
msgstr ""
"\n"
"Se você tiver um número de registro, registre-se primeiro em http://www."
"redhat.com/apps/activate/ e tente novamente.\n"
"\n"

#: ../server/rhnChannel.py:2012
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr "Permissões de assinatura insuficientes para liberação (%s, %s"

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2276 ../server/rhnChannel.py:2287
#: ../server/rhnChannel.py:2302
msgid "System Registered but Inactive"
msgstr "Sistema Registrado, mas Inativo"

#: ../server/rhnChannel.py:2277
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it is not subscribed to a channel. If you have not yet\n"
"activated your product for service, please visit our website at:\n"
"\n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...to activate your product."
msgstr ""
"\n"
"Combinação de liberação de arquitetura e sistema operacional inválida (%s, "
"%s).\n"
"Seu sistema foi registrado, mas não receberá atualizações\n"
"porque não está inscrito em um canal. Se você ainda não\n"
"ativou seu produto para manutenção, visite nosso site em:\n"
"\n"
"       http://www.redhat.com/apps/activate/\n"
"\n"
"... para ativar seu produto."

#: ../server/rhnChannel.py:2288
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""
"\n"
"Combinação de liberação de arquitetura e sistema operacional inválida (%s, "
"%s).\n"
"Seu sistema foi registrado, mas não receberá atualizações\n"
"porque não pôde ser inscrito em um canal base.\n"
"Por favor entre em contato com o administrador da organização para obter "
"assistência.\n"

#: ../server/rhnChannel.py:2295
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Este sistema foi registrado com sucesso, mas ainda não tem direito\n"
"  para servir.  Para autorizar esse sistema a fazer serviço, faça login no "
"site em:\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnChannel.py:2303
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Este sistema foi registrado com sucesso, mas nenhum direito ao serviço\n"
"  estavam disponíveis.  Para autorizar esse sistema a fazer serviço, faça "
"login no site em:\n"
"\n"
"  %(entitlement_url)s\n"

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:53
msgid "This does not appear to be a valid username."
msgstr "Este não parece ser um nome de usuário válido."

#: ../common/rhnException.py:54
msgid "Invalid username and password combination."
msgstr "Combinação de nome de usuário e senha inválida."

#: ../common/rhnException.py:55
msgid "This login is already taken, or the password is incorrect."
msgstr "Este login já foi realizado ou a senha está incorreta."

#: ../common/rhnException.py:56
msgid "Permission denied."
msgstr "Permissão negada."

#: ../common/rhnException.py:57
msgid "Object not found."
msgstr "Objeto não encontrado."

#: ../common/rhnException.py:58
msgid "Invalid System Digital ID."
msgstr "ID digital do sistema inválido."

#: ../common/rhnException.py:59
msgid "Invalid System Credentials."
msgstr "Credenciais do sistema inválidas."

#: ../common/rhnException.py:60
msgid "Could not retrieve user data from database."
msgstr "Não foi possível recuperar os dados do usuário do banco de dados."

#: ../common/rhnException.py:61
msgid "Valid username required."
msgstr "Nome de usuário válido necessário."

#: ../common/rhnException.py:62
msgid "Valid password required."
msgstr "Senha válida necessária."

#: ../common/rhnException.py:63
msgid "Minimum username length violation."
msgstr "Violação mínima do comprimento do nome de usuário."

#: ../common/rhnException.py:64
msgid "Minimum password length violation."
msgstr "Violação mínima do comprimento da senha."

#: ../common/rhnException.py:65
msgid "The username contains invalid characters."
msgstr "O nome de usuário contém caracteres inválidos."

#: ../common/rhnException.py:66
msgid "File not found."
msgstr "Arquivo não encontrado."

#: ../common/rhnException.py:67
msgid "Architecture and OS version combination is not supported."
msgstr "A combinação de arquitetura e versão do SO não é suportada."

#: ../common/rhnException.py:68
msgid "Could not retrieve system data from database."
msgstr "Não foi possível recuperar os dados do sistema do banco de dados."

#: ../common/rhnException.py:69
msgid "Invalid arguments passed to function."
msgstr "Argumentos inválidos transmitidos para a função."

#: ../common/rhnException.py:70
msgid "Unable to retrieve requested entry."
msgstr "Não foi possível recuperar a entrada solicitada."

#: ../common/rhnException.py:71
msgid "Could not update database entry."
msgstr "Não foi possível atualizar a entrada do banco de dados."

#: ../common/rhnException.py:72
msgid "Unsupported server architecture."
msgstr "Arquitetura de servidor não suportada."

#: ../common/rhnException.py:73
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running mgr_register as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     A funcionalidade do servidor anônimo não está mais disponível.\n"
"\n"
"     Por favor, registre novamente este sistema executando mgr_register como "
"root.\n"
"     Por favor visite https://%(hostname)s/rhn/systems/SystemEntitlements."
"do\n"
"     ou faça login em https://%(hostname)s, e na guia \"Visão geral\",\n"
"     selecione \"Gerenciamento de assinatura\" para ativar o serviço para "
"este sistema.\n"
"     "

#: ../common/rhnException.py:81
msgid "Record not available in the database."
msgstr "Registro não disponível no banco de dados."

#: ../common/rhnException.py:82
msgid "Invalid value for entry."
msgstr "Valor inválido para entrada."

#: ../common/rhnException.py:83
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for SUSE Manager.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     Este sistema não possui um direito válido para o SUSE Manager.\n"
"     Por favor visite https://%(hostname)s/rhn/systems/SystemEntitlements."
"do\n"
"     ou faça login em https://%(hostname)s, e na guia \"Visão geral\",\n"
"     selecione \"Gerenciamento de assinatura\" para ativar o serviço para "
"este sistema.\n"
"     "

#: ../common/rhnException.py:89
msgid "Channel error"
msgstr "Erro no canal"

#: ../common/rhnException.py:90
msgid "Client session token is invalid."
msgstr "O token da sessão do cliente é inválido."

#: ../common/rhnException.py:91
msgid "Client session token has expired."
msgstr "O token da sessão do cliente expirou."

#: ../common/rhnException.py:92
msgid "You are not authorized to retrieve the requested object."
msgstr "Você não está autorizado a recuperar o objeto solicitado."

#: ../common/rhnException.py:93
msgid "Invalid action"
msgstr "Ação inválida"

#: ../common/rhnException.py:94
msgid "You are not allowed to perform administrative tasks on this system."
msgstr ""
"Você não tem permissão para executar tarefas administrativas neste sistema."

#: ../common/rhnException.py:96
msgid "The system is already subscribed to the specified channel."
msgstr "O sistema já está inscrito no canal especificado."

#: ../common/rhnException.py:97
msgid "The system is not currently subscribed to the specified channel."
msgstr "O sistema não está atualmente inscrito no canal especificado."

#: ../common/rhnException.py:98
msgid "The specified channel does not exist."
msgstr "O canal especificado não existe."

#: ../common/rhnException.py:99
msgid "Invalid channel version."
msgstr "Versão do canal inválida."

#: ../common/rhnException.py:100
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""
"\n"
"     Limites de associação ao grupo de usuários excedidos.\n"
"\n"
"      As configurações atuais da sua conta não permitem adicionar outro\n"
"      conta de usuário. Verifique com o administrador da organização o seu\n"
"      conta se o número máximo de usuários com permissão para se inscrever "
"nas necessidades do servidor\n"
"      para ser mudado.\n"
"     "

#: ../common/rhnException.py:108
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""
"\n"
"     Limites de associação ao grupo do sistema excedidos.\n"
"     As configurações atuais da sua conta não permitem adicionar outro\n"
"     perfil do sistema. Verifique com o administrador da organização\n"
"     para modificar o número máximo de perfis do sistema que podem ser\n"
"     inscrito na sua conta.\n"
"     "

#: ../common/rhnException.py:116
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""
"\n"
"     Arquitetura inválida.\n"
"\n"
"     A arquitetura do pacote não é suportada por\n"
"     "

#: ../common/rhnException.py:121
msgid "Invalid RPM header"
msgstr "Cabeçalho RPM inválido"

#: ../common/rhnException.py:122
msgid ""
"\n"
"    This system is already registered as a Salt Minion. If you want to "
"register it as a traditional client\n"
"    please delete it first via the web UI or API and then register it using "
"the traditional tools.\n"
"    "
msgstr ""
"\n"
"    Esse sistema já está registrado como Salt Minion. Se você deseja "
"registrá-lo como um cliente tradicional\n"
"     por favor exclua-o primeiro pela interface da Web ou API da Web e "
"depois registre-o usando as ferramentas tradicionais.\n"
"    "

#. For the uploading tools
#: ../common/rhnException.py:127
msgid "Invalid information uploaded to the server"
msgstr "Informações inválidas carregadas no servidor"

#: ../common/rhnException.py:128
msgid "Error uploading network interfaces configuration."
msgstr "Erro ao carregar a configuração de interfaces de rede."

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""
"\n"
"     Falha no upload do pacote devido a violação de restrição de "
"exclusividade.\n"
"     Verifique se o pacote não possui dependências duplicadas ou\n"
"     se já não existe no servidor\n"
"     "

#: ../common/rhnException.py:134
msgid ""
"\n"
"     The --force rhnpush option is disabled on this server.\n"
"     Please contact your SUSE Manager administrator for more help.\n"
"     "
msgstr ""
"\n"
"     A opção --force rhnpush está desativada neste servidor.\n"
"     Entre em contato com o administrador do SUSE Manager para obter mais "
"ajuda.\n"
"     "

#. 60-70: token errors
#: ../common/rhnException.py:140
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""
"\n"
"     O token de ativação especificado não pôde ser encontrado no servidor.\n"
"     Tente novamente com uma chave válida.\n"
"     "

#: ../common/rhnException.py:144
msgid "Too many systems registered using this registration token"
msgstr "Muitos sistemas registrados usando esse token de registro"

#: ../common/rhnException.py:145
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr "O token contém configurações inválidas, obsoletas ou insuficientes"

#: ../common/rhnException.py:146
msgid "Conflicting activation tokens"
msgstr "Tokens de ativação conflitantes"

#. 70-80: channel subscription errors
#: ../common/rhnException.py:149
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""
"\n"
"     Nenhum canal base correspondente encontrado para o seu sistema.\n"
"     "

#: ../common/rhnException.py:152
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""
"\n"
"     Você não tem permissão de assinatura para o canal designado.\n"
"     Por favor consulte o canal ou os administradores da organização\n"
"     para obter mais detalhes.\n"
"     "

#: ../common/rhnException.py:157
msgid "You can not unsubscribe from base channel."
msgstr "Você não pode cancelar a inscrição no canal base."

#: ../common/rhnException.py:158
msgid "SUSE Manager or Proxy channel can not be subscribed."
msgstr "O canal SUSE Manager ou Proxy não pode ser assinado."

#. 80-90: server group errors
#: ../common/rhnException.py:161
msgid "There was an error while trying to join the system to its groups"
msgstr "Ocorreu um erro ao tentar ingressar no sistema em seus grupos"

#. 90-100: entitlement errors
#: ../common/rhnException.py:164
msgid "Unable to entitle system"
msgstr "Não foi possível habilitar o sistema"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:167
msgid "Maximum e-mail length violation."
msgstr "Violação de tamanho máximo de email."

#: ../common/rhnException.py:168
msgid "This system has been previously registered."
msgstr "Este sistema foi registrado anteriormente."

#: ../common/rhnException.py:169
msgid "Invalid username"
msgstr "Nome de usuário Inválido"

#. 140-159 applet errors
#: ../common/rhnException.py:172
msgid "Unable to look up server"
msgstr "Não foi possível procurar o servidor"

#. 160-179: OSAD errors
#: ../common/rhnException.py:175
msgid "Required argument is missing"
msgstr "O argumento necessário está ausente"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:178
msgid "No entitlement information tied to hardware"
msgstr "Nenhuma informação de direito vinculada ao hardware"

#: ../common/rhnException.py:179
msgid "Installation number is not entitling"
msgstr "O número da instalação não está autorizado"

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:182
msgid "Maximum username length violation"
msgstr "Violação máxima do tamanho do nome de usuário"

#: ../common/rhnException.py:183
msgid "Maximum password length violation"
msgstr "Violação máxima do comprimento da senha"

#: ../common/rhnException.py:184
msgid "This user has read only API access. Action denied."
msgstr "Este usuário possui acesso apenas à API. Ação negada."

#: ../common/rhnException.py:186
msgid "System Name cannot be less than 1 character"
msgstr "O nome do sistema não pode ter menos de 1 caractere"

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:190
msgid "SUSE Manager Proxy error."
msgstr "Erro de proxy do SUSE Manager."

#: ../common/rhnException.py:191
msgid "SUSE Manager Proxy unable to login."
msgstr "Proxy do SUSE Manager não pode efetuar login."

#. issued by a SUSE Manager Server/Satellite to the proxy
#: ../common/rhnException.py:193
msgid ""
"\n"
"     SUSE Manager Proxy system ID does not match a Spacewalk Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""
"\n"
"     O ID do sistema SUSE Manager Proxy não corresponde a um Spacewalk Proxy "
"Server\n"
"     no banco de dados.\n"
"     "

#: ../common/rhnException.py:197
msgid "SUSE Manager Proxy session token is invalid."
msgstr "O token de sessão do SUSE Manager Proxy é inválido."

#: ../common/rhnException.py:198
msgid "SUSE Manager Proxy session token has expired."
msgstr "O token de sessão do SUSE Manager Proxy expirou."

#. 2000-2999: Red Hat Satellite specific errors:
#: ../common/rhnException.py:202
msgid ""
"\n"
"      user creation is not allowed via mgr_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""
"\n"
"      a criação do usuário não é permitida via mgr_register;\n"
"     entre em contato com o administrador do sistema para criar sua conta.\n"
"     "

#: ../common/rhnException.py:206
msgid ""
"\n"
"     This SUSE Manager server is not allowed to use Inter Server Sync on "
"this server\n"
"     "
msgstr ""
"\n"
"     Este servidor do SUSE Manager não tem permissão para usar o Inter "
"Server Sync neste servidor\n"
"     "

#: ../common/rhnException.py:209
msgid ""
"\n"
"     Inter Server Sync is disabled on this SUSE Manager Server.\n"
"     "
msgstr ""
"\n"
"     A sincronização entre servidores está desabilitada neste servidor do "
"SUSE Manager.\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:214
msgid "Invalid datatype passed"
msgstr "Tipo de dados inválido passado"

#: ../common/rhnException.py:215
msgid "Unable to retrieve channel"
msgstr "Não foi possível recuperar o canal"

#: ../common/rhnException.py:216
msgid "Unable to retrieve package"
msgstr "Não foi possível recuperar o pacote"

#: ../common/rhnException.py:217
msgid "Unable to retrieve erratum"
msgstr "Não foi possível recuperar a errata"

#: ../common/rhnException.py:218
msgid "File is missing"
msgstr "Falta o arquivo"

#: ../common/rhnException.py:219
msgid "Function retrieval error"
msgstr "Erro de recuperação de função"

#: ../common/rhnException.py:220
msgid "Function execution error"
msgstr "Erro de execução da função"

#: ../common/rhnException.py:221
msgid "Missing version string"
msgstr "String de versão ausente"

#: ../common/rhnException.py:222
msgid "Invalid version string"
msgstr "String de versão inválida"

#: ../common/rhnException.py:223
msgid "Mismatching versions"
msgstr "Versões incompatíveis"

#: ../common/rhnException.py:224
msgid "Invalid channel version"
msgstr "Versão do canal inválida"

#: ../common/rhnException.py:225
msgid "No comps file for channel"
msgstr "Nenhum arquivo de comps para o canal"

#: ../common/rhnException.py:226
msgid "Unable to retrieve comps file"
msgstr "Não foi possível recuperar o arquivo comps"

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:229
msgid "Configuration action missing"
msgstr "Ação de configuração ausente"

#: ../common/rhnException.py:230
msgid "File too large"
msgstr "Arquivo muito grande"

#: ../common/rhnException.py:231
msgid "File contains binary data"
msgstr "O arquivo contém dado binário"

#: ../common/rhnException.py:232
msgid "Configuration channel is not empty"
msgstr "Canal de configuração não está vazio"

#: ../common/rhnException.py:233
msgid "Permission error"
msgstr "Erro de permissão"

#: ../common/rhnException.py:234
msgid "Content missing for configuration file"
msgstr "Conteúdo ausente para o arquivo de configuração"

#: ../common/rhnException.py:235
msgid "Template delimiters not specified"
msgstr "Delimitadores de modelo não especificados"

#: ../common/rhnException.py:236
msgid "Configuration channel does not exist"
msgstr "O canal de configuração não existe"

#: ../common/rhnException.py:237
msgid "Configuration channel already exists"
msgstr "O canal de configuração já existe"

#: ../common/rhnException.py:238
msgid "File missing from configuration channel"
msgstr "Arquivo ausente no canal de configuração"

#: ../common/rhnException.py:239
msgid "Different revision of this file is uploaded"
msgstr "Upload diferente da revisão deste arquivo"

#: ../common/rhnException.py:240
msgid "File already uploaded to configuration channel"
msgstr "Arquivo já carregado no canal de configuração"

#: ../common/rhnException.py:241
msgid "File size exceeds remaining quota space"
msgstr "O tamanho do arquivo excede o espaço restante da cota"

#: ../common/rhnException.py:242
msgid "Full path of file must be specified"
msgstr "O caminho completo do arquivo deve ser especificado"

#: ../common/rhnException.py:243
msgid "Invalid revision number"
msgstr "Número de revisão inválido"

#: ../common/rhnException.py:244
msgid "Cannot compare files of different file type"
msgstr "Não é possível comparar arquivos de outro tipo"

#. 5000 - 5999: client content uploading errors
#. 5000 - 5099: crash reporting errors
#: ../common/rhnException.py:248
msgid "Crash information is invalid or incomplete"
msgstr "As informações de falha são inválidas ou incompletas"

#: ../common/rhnException.py:249
msgid "Crash file information is invalid or incomplete"
msgstr "As informações do arquivo de falha são inválidas ou incompletas"

#: ../common/rhnException.py:250
msgid "Error composing crash directory path"
msgstr "Erro ao compor o caminho do diretório de falha"

#: ../common/rhnException.py:251
msgid "Error composing crash file path"
msgstr "Erro ao compor o caminho do arquivo de falha"

#: ../common/rhnException.py:252 ../common/rhnException.py:259
msgid "Invalid content encoding"
msgstr "Codificação de conteúdo inválida"

#: ../common/rhnException.py:253
msgid "Invalid crash name"
msgstr "Nome de falha inválido"

#: ../common/rhnException.py:254
msgid "Crash reporting is disabled for this organization"
msgstr "Os relatórios de falhas estão desativados para esta organização"

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:256
msgid "SCAP results file transfer is invalid or incomplete"
msgstr "A transferência do arquivo de resultados SCAP é inválida ou incompleta"

#: ../common/rhnException.py:257
msgid "Error composing directory path for detailed SCAP results"
msgstr ""
"Erro ao compor o caminho do diretório para obter resultados detalhados do "
"SCAP"

#: ../common/rhnException.py:258
msgid "Error composing file path for detailed SCAP results"
msgstr ""
"Erro ao compor o caminho do arquivo para obter resultados detalhados do SCAP"

#: ../common/rhnException.py:306
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at scc.suse.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""
"\n"
"     Ocorreu um erro ao processar o seu pedido. Se esse problema\n"
"     persistir, envie um relatório de erro em scc.suse.com.\n"
"     Se você optar por enviar o relatório de bug, por favor não deixe de "
"incluir\n"
"     detalhes do que estava tentando fazer quando esse erro ocorreu e\n"
"     detalhes sobre como reproduzir esse problema.\n"

#: ../common/rhnException.py:358
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""
"Mensagem De Erro:\n"
"     %s\n"

#: ../common/rhnException.py:360
#, python-format
msgid "Error Class Code: %s\n"
msgstr "Código da classe de erro: %s\n"

#: ../common/rhnException.py:363
#, python-format
msgid "Error Class Info: %s\n"
msgstr "Informações da classe de erro: %s\n"

#: ../common/rhnException.py:365
#, python-format
msgid "Explanation: %s"
msgstr "Explicação: %s"

#: ../common/rhnTB.py:205
#, python-format
msgid "ERROR: %s %s: %s"
msgstr "ERRO: %s %s: %s"

#: ../common/rhnTB.py:207
#, python-format
msgid "TRACEBACK: %s"
msgstr "RASTREAR: %s"

#: ../satellite_tools/disk_dumper/iss.py:1294
#: ../satellite_tools/disk_dumper/iss.py:1298
#, python-format
msgid "format of %s should be at least YYYYMMDD.\n"
msgstr "formato de %s deve ser pelo menos AAAAMMDD.\n"

#: ../satellite_tools/messages.py:26
#, python-format
msgid ""
"\n"
"ERROR: executing step %s. Error is:\n"
"%s\n"
msgstr ""
"\n"
"ERRO: executando a etapa %s. O erro é:\n"
"%s\n"

#: ../satellite_tools/messages.py:31
#, python-format
msgid ""
"\n"
"ERROR: there was a problem accessing the channel data from your temporary\n"
"       repository. Did you migrate all of the data from the channel ISOs\n"
"       do this directory? If so, please recheck the channels ISOs, ensure\n"
"       that you have them all, and then iteratively remount and repopulate\n"
"       the temporary repository (%s).\n"
msgstr ""
"\n"
"ERRO: Teve um problema acessando o canal de dados do seu repositório\n"
"     temporário. Você migrou todos os dados do seu canal de ISOs\n"
"     para esse diretório? Se sim, por favor verificar os canais de ISOs, "
"Assegure\n"
"    que você tem todos, e então remontar e repovoar iterativamente\n"
"    o repositório temporário (%s).\n"

#: ../satellite_tools/messages.py:39
#, python-format
msgid ""
"\n"
"ERROR: there was a problem synchronizing the information.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"ERRO: Teve um problema sincronizando as informações.\n"
"     Mensagem de erro: %s\n"

#: ../satellite_tools/messages.py:44
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       Depending on the specific error details, please review your "
"configuration,\n"
"       basic network connectivity, and/or name resolution, and try again.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"ERRO: Ocorreu um problema na comunicação com o ISS Master.\n"
"     Dependendo dos detalhes específicos do erro, revise sua configuração,\n"
"     conectividade básica de rede e / ou resolução de nomes e tente "
"novamente.\n"
"     Mensagem de erro: %s\n"

#: ../satellite_tools/messages.py:51
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       If the master satellite is older than v5.3, it does not have ISS "
"capability.\n"
"       Otherwise, depending on the specific error details, please review "
"your\n"
"       configuration, basic network connectivity, and/or name resolution, "
"and try again.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"ERRO: Ocorreu um problema na comunicação com o ISS Master.\n"
"     Se o satélite principal for anterior à v5.3, ele não possui capacidade "
"ISS.\n"
"     Caso contrário, dependendo dos detalhes específicos do erro, revise "
"sua\n"
"     configuração, conectividade básica de rede e / ou resolução de nomes e "
"tente novamente.\n"
"     Mensagens de erro; %s\n"

#: ../satellite_tools/messages.py:59
#, python-format
msgid ""
"\n"
"ERROR: a child-channel cannot be synced without its parent being synced as\n"
"       well. A parent needs to be either (a) previously synced or (b) "
"synced\n"
"       in tandem with the desired child-channel. Missing parents for this\n"
"       transaction:\n"
"       %s\n"
msgstr ""
"\n"
"ERRO: um canal filho não pode ser sincronizado sem que seu pai também seja\n"
"     sincronizado. Um pai precisa ser (a) sincronizado anteriormente ou (b) "
"sincronizado\n"
"     em conjunto com o canal filho desejado. Pais ausentes para esta\n"
"     transação:\n"
"     %s\n"

#: ../satellite_tools/messages.py:67
#, python-format
msgid ""
"\n"
"ERROR: you are not entitled to sync a channel in this set of channels.\n"
"Please contact your SUSE Manager contact\n"
"%s"
msgstr ""
"\n"
"ERRO: você não tem o direito de sincronizar um canal neste conjunto de "
"canais.\n"
"Entre em contato com seu contato do SUSE Manager\n"
"%s"

#: ../satellite_tools/messages.py:72
#, python-format
msgid "  ERROR: not enough free space (%s KB) on device."
msgstr "  ERRO: sem espaço suficiente (%s KB) no dispostivo."

#: ../satellite_tools/messages.py:74
#, python-format
msgid "    %3d/%s Fetch successful: %s (%s bytes)"
msgstr "    %3d/%s Busca bem sucedida: %s (%s bytes)"

#: ../satellite_tools/messages.py:75
#, python-format
msgid "    Extinct package:  %s"
msgstr "    Pacote extinto:  %s"

#: ../satellite_tools/messages.py:76
#, python-format
msgid "   Total size: %s"
msgstr "   Tamanho total: %s"

#: ../satellite_tools/messages.py:77
#, python-format
msgid "      Downloaded %s of %s. Estimated remaining time: %s"
msgstr "      Baixado %s de %s. Tempo restante estimado: %s"

#: ../satellite_tools/messages.py:78
#, python-format
msgid "    Fetch unsuccessful: %s"
msgstr "    Busca mal sucedida: %s"

#: ../satellite_tools/messages.py:79
#, python-format
msgid "   RPM fetch summary: %s"
msgstr "   Busca de sumário RPM: %s"

#: ../satellite_tools/messages.py:80
#, python-format
msgid "       success: %d"
msgstr "       sucesso: %d"

#: ../satellite_tools/messages.py:81
#, python-format
msgid "       failed:  %d"
msgstr "       falhou:  %d"

#: ../satellite_tools/messages.py:82
#, python-format
msgid "       extinct: %d"
msgstr "       extinto: %d"

#: ../satellite_tools/messages.py:84
#, python-format
msgid "   Retrieving / parsing *relevant* package metadata: %s (%s)"
msgstr "   Recuperando/analisando metadados do pacote *relevantes*: %s (%s)"

#: ../satellite_tools/messages.py:85
#, python-format
msgid "   Retrieving / parsing errata data: %s (%s)"
msgstr "   Recuperando/analisando dados de erratas: %s (%s)"

#: ../satellite_tools/messages.py:86
#, python-format
msgid "   Retrieving / parsing kickstart data: %s (%s)"
msgstr "   Recuperando/analisando dados do kickstart: %s (%s)"

#: ../satellite_tools/messages.py:87
#, python-format
msgid "   Retrieving / parsing kickstart tree files: %s (%s)"
msgstr "   Recuperando/analisando arquivos da árvore do kickstart: %s (%s)"

#: ../satellite_tools/messages.py:88
#, python-format
msgid "   Importing *relevant* package metadata: %s (%s)"
msgstr "   Importando metadados *relevantes* do pacote: %s (%s)"

#: ../satellite_tools/messages.py:89
msgid "   * WARNING: this may be a slow process."
msgstr "   * AVISO: este pode ser um processo lento."

#: ../satellite_tools/messages.py:90
msgid "Linking packages to channels"
msgstr "Vinculando pacotes aos canais"

#: ../satellite_tools/messages.py:91
#, python-format
msgid "   Importing *relevant* errata: %s (%s)"
msgstr "   Importando errata *relevante*: %s (%s)"

#: ../satellite_tools/messages.py:92
msgid "   No new kickstartable tree to import"
msgstr "   Nenhuma nova árvore kickstartable para importar"

#: ../satellite_tools/messages.py:93
#, python-format
msgid "Importing kickstartable trees (%d)"
msgstr "Importando árvores kickstartable (%d)"

#: ../satellite_tools/messages.py:94
#, python-format
msgid "Imported kickstartable trees (%d)"
msgstr "Árvores kickstartable importadas (%d)"

#: ../satellite_tools/rhn_satellite_activate.py:198
#, python-format
msgid ""
"\"%s\" (specified in commandline)\n"
"could not be opened and read:\n"
"%s"
msgstr ""
"\"%s\" (especificado na linha de comando)\n"
"não pôde ser aberto e lido:\n"
"%s"

#: ../satellite_tools/rhn_satellite_activate.py:205
#, python-format
msgid ""
"\"%s\" could not be opened\n"
"and/or written to:\n"
"%s"
msgstr ""
"Não foi possível abrir \"%s\"\n"
"e/ou escrito para:\n"
"%s"

#: ../satellite_tools/reposync.py:111 ../satellite_tools/satsync.py:439
msgid "+++ sending log as an email +++"
msgstr "+++ enviar log como um email +++"

#: ../satellite_tools/reposync.py:114
#, python-format
msgid "%s sync. report from %s"
msgstr "%s sincronizado. relatório de %s"

#: ../satellite_tools/reposync.py:124 ../satellite_tools/satsync.py:449
msgid "+++ email requested, but there is nothing to send +++"
msgstr "+++ email solicitado, mas não há nada para enviar +++"

#: ../satellite_tools/satsync.py:258
#, python-format
msgid "No handler for step %s"
msgstr "Nenhum manipulador para a etapa %s"

#. Try one more time - this time it should be faster since
#. everything should be cached
#: ../satellite_tools/satsync.py:270
msgid "Environment changed, trying again..."
msgstr "Ambiente alterado, tentando novamente..."

#: ../satellite_tools/satsync.py:277
msgid "ERROR: Encountered IntegrityError: \n"
msgstr "ERRO: Erro de integridade encontrado: \n"

#: ../satellite_tools/satsync.py:285
msgid "Repeated failures"
msgstr "Falhas repetidas"

#: ../satellite_tools/satsync.py:290
#, python-format
msgid ""
"    Import complete:\n"
"        Begin time: %s\n"
"        End time:   %s\n"
"        Elapsed:    %s\n"
"          "
msgstr ""
"    Importação concluída:\n"
"        Hora de início: %s\n"
"        Hora de término: %s\n"
"        Decorrido: %s\n"
"          "

#: ../satellite_tools/satsync.py:311
msgid "hours"
msgstr "horas"

#: ../satellite_tools/satsync.py:311
msgid "minutes"
msgstr "minutos"

#: ../satellite_tools/satsync.py:311
msgid "seconds"
msgstr "segundos"

#: ../satellite_tools/satsync.py:357
msgid ""
"ERROR: The dump is missing package data, use --no-rpms to skip this step or "
"fix the content to include package data."
msgstr ""
"ERRO: O dump está faltando dados do pacote, use --no-rpms para ignorar esta "
"etapa ou corrigir o conteúdo para incluir dados do pacote."

#. the orgs() method doesn't exist; that's fine we just
#. won't sync the orgs
#: ../satellite_tools/satsync.py:404
msgid "The SUSE Manager master does not support syncing orgs data."
msgstr ""
"O mestre do SUSE Manager não suporta a sincronização de dados da organização."

#: ../satellite_tools/satsync.py:404
msgid "Skipping..."
msgstr "Pulando..."

#: ../satellite_tools/satsync.py:442
#, python-format
msgid "SUSE Manager Inter Server sync. report from %s"
msgstr "Sincronização do SUSE Manager Inter Server. relatório de %s"

#: ../satellite_tools/satsync.py:521
msgid " - file-system synchronization"
msgstr " - sincronização do sistema de arquivos"

#: ../satellite_tools/satsync.py:533 ../satellite_tools/satsync.py:541
msgid " - live synchronization"
msgstr " - sincronização ao vivo"

#: ../satellite_tools/satsync.py:534
#, python-brace-format
msgid ""
"ERROR: Live content synchronizing with RHN Classic Hosted is no longer "
"supported.\n"
"Please use the cdn-sync command instead unless you are attempting to sync "
"from another {PRODUCT_NAME} via Inter-Server-Sync (ISS), or from local "
"content on disk via Channel Dump ISOs."
msgstr ""
"ERRO: A sincronização de conteúdo Live com o RHN Classic Hosted não é mais "
"suportada.\n"
"Use o comando cdn-sync em vez disso, a menos que você esteja tentando "
"sincronizar de outro {PRODUCT_NAME} via Inter-Server-Sync (ISS), ou de "
"conteúdo local no disco via Channel Dump ISOs."

#: ../satellite_tools/satsync.py:542
#, python-format
msgid "   url: %s"
msgstr "   url: %s"

#: ../satellite_tools/satsync.py:543
#, python-format
msgid "   debug/output level: %s"
msgstr "   depuração/nível de saída: %s"

#: ../satellite_tools/satsync.py:553
msgid "ERROR: this server must be registered with SUSE Manager."
msgstr "ERRO: este servidor deve ser registrado no SUSE Manager."

#: ../satellite_tools/satsync.py:575
#, python-format
msgid "Retrieving / parsing %s data"
msgstr "Recuperando/analisando %s dados"

#: ../satellite_tools/satsync.py:585 ../satellite_tools/satsync.py:600
msgid "*** SYSTEM INTERRUPT CALLED ***"
msgstr "*** INTERRUPÇÃO DO SISTEMA CHAMADO ***"

#: ../satellite_tools/satsync.py:593
msgid "ERROR: fatal parser exception occurred "
msgstr "ERRO: ocorreu uma exceção fatal do analisador "

#: ../satellite_tools/satsync.py:594
#, python-format
msgid "(line: %s, col: %s msg: %s)"
msgstr "(linha: %s, col: %s msg: %s)"

#: ../satellite_tools/satsync.py:598
#, python-format
msgid "ERROR: parser exception occurred: %s"
msgstr "ERRO: ocorreu uma exceção do analisador: %s"

#: ../satellite_tools/satsync.py:603
msgid "ERROR: exception (during parse) occurred: "
msgstr "ERRO: ocorreu uma exceção (durante a análise): "

#: ../satellite_tools/satsync.py:604
#, python-format
msgid ""
"   Encountered some errors with %s data (see logs (%s) for more information)"
msgstr ""
"   Foram encontrados alguns erros com os dados %s (consulte os logs (%s) "
"para obter mais informações)"

#: ../satellite_tools/satsync.py:606
#, python-format
msgid "   Encountered some errors with %s data:"
msgstr "   Foram encontrados alguns erros com %s dados:"

#: ../satellite_tools/satsync.py:607
#, python-format
msgid "   ------- %s PARSE/IMPORT ERROR -------"
msgstr "   ------- %s ANALISAR/IMPORTAR ERRO -------"

#: ../satellite_tools/satsync.py:609
msgid "   ---------------------------------------"
msgstr "   ---------------------------------------"

#: ../satellite_tools/satsync.py:612
#, python-format
msgid "%s data complete"
msgstr "%s dados concluídos"

#: ../satellite_tools/satsync.py:665
msgid "Retrieving / parsing channel data"
msgstr "Recuperando / analisando dados do canal"

#: ../satellite_tools/satsync.py:718
msgid "Channel data complete"
msgstr "Dados do canal concluídos"

#: ../satellite_tools/satsync.py:736
#, python-format
msgid "%10s import from %s"
msgstr "%10s importado de %s"

#: ../satellite_tools/satsync.py:739
#, python-format
msgid "%10s import from %s - %s"
msgstr "%10s importado de %s - %s"

#: ../satellite_tools/satsync.py:743
#, python-format
msgid "%10s"
msgstr "%10s"

#: ../satellite_tools/satsync.py:750
msgid "p"
msgstr "p"

#: ../satellite_tools/satsync.py:752
msgid "."
msgstr "."

#: ../satellite_tools/satsync.py:758
msgid "   p = previously imported/synced channel"
msgstr "   p = canal importado/sincronizado anteriormente"

#: ../satellite_tools/satsync.py:759
msgid "   . = channel not yet imported/synced"
msgstr "   . = canal ainda não importado/sincronizado"

#: ../satellite_tools/satsync.py:765
msgid "   e = channel no longer supported (end-of-service)"
msgstr "   e = canal não é mais suportado (fim de serviço)"

#: ../satellite_tools/satsync.py:767
msgid "   ? = channel label invalid --- typo?"
msgstr "   ? = etiqueta do canal inválida --- erro de digitação?"

#: ../satellite_tools/satsync.py:771
#, python-format
msgid "   %s:"
msgstr "   %s:"

#: ../satellite_tools/satsync.py:772
#, python-format
msgid "      %s %-40s %4s %s"
msgstr "      %s %-40s %4s %s"

#: ../satellite_tools/satsync.py:773
msgid "base-channels"
msgstr "canais-base"

#: ../satellite_tools/satsync.py:786 ../satellite_tools/satsync.py:1603
msgid "NONE RELEVANT"
msgstr "NADA RELEVANTE"

#: ../satellite_tools/satsync.py:808
msgid "end-of-service"
msgstr "fim-do-serviço"

#: ../satellite_tools/satsync.py:809
msgid "e"
msgstr "e"

#: ../satellite_tools/satsync.py:815
msgid "   typos:"
msgstr "   erros de digitação:"

#: ../satellite_tools/satsync.py:816
msgid "?"
msgstr "?"

#: ../satellite_tools/satsync.py:831
#, python-format
msgid "XXX: imported channels: %s"
msgstr "XXX: canais importados: %s"

#: ../satellite_tools/satsync.py:832
#, python-format
msgid "XXX:   cached channels: %s"
msgstr "XXX:   canais em cache: %s"

#: ../satellite_tools/satsync.py:837
msgid "XXX: list channels called"
msgstr "XXX: listar canais cancelados"

#: ../satellite_tools/satsync.py:855
msgid "ERROR: these channels either do not exist or are not available:"
msgstr "ERRO: esses canais não existem ou não estão disponíveis:"

#: ../satellite_tools/satsync.py:859
#, python-format
msgid "       (to see a list of channel labels: %s --list-channels)"
msgstr "       (para ver uma lista de rótulos de canais: %s --list-channels)"

#: ../satellite_tools/satsync.py:904
#, python-format
msgid "   Retrieving / parsing short package metadata: %s (%s)"
msgstr "   Recuperando/analisando metadados curtos do pacote: %s (%s)"

#: ../satellite_tools/satsync.py:965
#, python-format
msgid "Diffing package metadata (what's missing locally?): %s"
msgstr ""
"Diferenciar os metadados do pacote (o que está faltando localmente?): %s"

#: ../satellite_tools/satsync.py:971 ../satellite_tools/satsync.py:1254
msgid "Diffing:    "
msgstr "Diferença:    "

#: ../satellite_tools/satsync.py:988
msgid "ERROR: incremental dump skipped"
msgstr "ERRO: despejo incremental ignorado"

#: ../satellite_tools/satsync.py:1079
msgid "Downloading rpm packages"
msgstr "Fazendo download de pacotes rpm"

#: ../satellite_tools/satsync.py:1084
#, python-format
msgid "   Fetching any missing RPMs: %s (%s)"
msgstr "   Buscando RPMs ausentes: %s (%s)"

#: ../satellite_tools/satsync.py:1085 ../satellite_tools/satsync.py:1153
msgid "NONE MISSING"
msgstr "NENHUM AUSENTE"

#: ../satellite_tools/satsync.py:1094
msgid "Processing rpm packages complete"
msgstr "Processando pacotes rpm completos"

#: ../satellite_tools/satsync.py:1121
msgid "Downloading package metadata"
msgstr "Fazendo Download de Metadados do Pacote"

#: ../satellite_tools/satsync.py:1146
msgid "Downloading srpm packages"
msgstr "Fazendo download de pacotes srpm"

#: ../satellite_tools/satsync.py:1152
#, python-format
msgid "   Fetching any missing SRPMs: %s (%s)"
msgstr "   Buscando quaisquer SRPMs ausentes: %s (%s)"

#: ../satellite_tools/satsync.py:1249
#, python-format
msgid "Diffing source package metadata (what's missing locally?): %s"
msgstr ""
"Diferenciar os metadados do pacote de origem (o que está faltando "
"localmente?): %s"

#: ../satellite_tools/satsync.py:1260
msgid "Downloading source package metadata"
msgstr "Fazendo Download de Metadados do Pacote de Origem"

#: ../satellite_tools/satsync.py:1338 ../satellite_tools/satsync.py:2027
#, python-format
msgid "Unable to save file %s: %s"
msgstr "Não foi possível salvar o arquivo %s: %s"

#. for
#. Retried a number of times and it still failed; log the
#. file as being failed and move on
#: ../satellite_tools/satsync.py:1345
#, python-format
msgid "Failed to fetch file %s"
msgstr "Falha ao buscar o arquivo %s"

#: ../satellite_tools/satsync.py:1350
msgid "Downloading kickstartable trees metadata"
msgstr "Download de metadados de árvores kickstartable"

#: ../satellite_tools/satsync.py:1365
msgid "Downloading kickstartable trees files"
msgstr "Download de arquivos de árvores kickstartable"

#: ../satellite_tools/satsync.py:1504
#, python-format
msgid "Grabbing all patches for channel %s"
msgstr "Transferindo todos os patches para o canal %s"

#: ../satellite_tools/satsync.py:1554
msgid "Downloading patch data"
msgstr "Fazendo download de dados de patch"

#: ../satellite_tools/satsync.py:1556
msgid "Forcing download of all patch data for requested channels."
msgstr ""
"Forçar o download de todos os dados do patch para os canais solicitados."

#: ../satellite_tools/satsync.py:1571
msgid "Downloading patch data complete"
msgstr "Download dos dados do patch concluídos"

#: ../satellite_tools/satsync.py:1576 ../satellite_tools/satsync.py:1597
msgid "Downloading:"
msgstr "Baixando:"

#: ../satellite_tools/satsync.py:1579
msgid " - complete"
msgstr " - completo"

#: ../satellite_tools/satsync.py:1624
msgid "Importing source package metadata"
msgstr "Importando Metadados do Pacote de Origem"

#: ../satellite_tools/satsync.py:1627
msgid "Importing package metadata"
msgstr "Importando Metadados do Pacote"

#: ../satellite_tools/satsync.py:1635
msgid "Importing:  "
msgstr "Importação:  "

#. not in the cache
#: ../satellite_tools/satsync.py:1703
msgid ""
"Package Not Found in Cache, Clear the Cache "
"to                                  Regenerate it."
msgstr "Pacote não encontrado no cache, limpe o cache para regenerá-lo."

#: ../satellite_tools/satsync.py:1709
msgid "Importing channel patches"
msgstr "Importando patches de canal"

#: ../satellite_tools/satsync.py:1714
#, python-format
msgid "Importing %s patches for channel %s."
msgstr "Importando %s patches para o canal %s."

#. Incomplete configuration
#: ../satellite_tools/satsync.py:2113
msgid "ERROR: server.mount_point not set in the configuration file"
msgstr "ERRO: server.mount_point não definido no arquivo de configuração"

#: ../satellite_tools/satsync.py:2117
#, python-format
msgid "ERROR: server.mount_point %s do not exist"
msgstr "ERRO: server.mount_point %s não existe"

#: ../satellite_tools/satsync.py:2122
#, python-format
msgid "ERROR: path under server.mount_point (%s)  do not exist"
msgstr "ERRO: o caminho em server.mount_point (%s) não existe"

#: ../satellite_tools/satsync.py:2199
#, python-format
msgid "Commandline: %s"
msgstr "Linha de comando: %s"

#: ../satellite_tools/satsync.py:2202
#, python-format
msgid ""
"DEBUG ONLY: max. batch-size for XML/database-import processing (1..%s).\"man "
"satellite-sync\" for more information."
msgstr ""
"APENAS PARA DEBUGAR: máx. tamanho do lote para processamento de importação "
"XML/banco de dados (1..%s).\"man satellite-sync\" para obter mais "
"informações."

#: ../satellite_tools/satsync.py:2205
msgid "alternative SSL CA Cert (fullpath to cert file)"
msgstr ""
"certificado alternativo da CA SSL (caminho completo para o arquivo cert)"

#: ../satellite_tools/satsync.py:2207
msgid "process data for this channel only"
msgstr "processar dados apenas para este canal"

#: ../satellite_tools/satsync.py:2209
msgid ""
"disk dump will be considered to be a full export; see \"man satellite-sync\" "
"for more information."
msgstr ""
"despejo de disco será considerado uma exportação completa; veja \"man "
"satellite-sync\" para mais informações."

#: ../satellite_tools/satsync.py:2212
msgid "existing custom channels will also be synced (unless -c is used)"
msgstr ""
"os canais personalizados existentes também serão sincronizados (a menos que -"
"c seja usado)"

#: ../satellite_tools/satsync.py:2214
#, python-format
msgid ""
"override debug level set in /etc/rhn/rhn.conf (which is currently set at %s)."
msgstr ""
"substitua o nível de depuração definido em /etc/rhn/rhn.conf (atualmente "
"definido em %s)."

#: ../satellite_tools/satsync.py:2216
#, python-format
msgid "requested version of XML dump (default: %s)"
msgstr "versão solicitada do dump XML (padrão: %s)"

#: ../satellite_tools/satsync.py:2218
msgid "e-mail a report of what was synced/imported"
msgstr "envie por e-mail um relatório do que foi sincronizado/importado"

#: ../satellite_tools/satsync.py:2220
msgid "forcibly process all (not a diff of) patch metadata"
msgstr "forçosamente processar todos os metadados (não diferentes) dos patches"

#: ../satellite_tools/satsync.py:2222
msgid "Do not use an http proxy under any circumstances."
msgstr "Não use um proxy http em nenhuma circunstância."

#: ../satellite_tools/satsync.py:2224
msgid "alternative http proxy (hostname:port)"
msgstr "http proxy alternativo (hostname:port)"

#: ../satellite_tools/satsync.py:2226
msgid "alternative http proxy username"
msgstr "nome de usuário do proxy http alternativo"

#: ../satellite_tools/satsync.py:2228
msgid "alternative http proxy password"
msgstr "senha alternativa do proxy http"

#: ../satellite_tools/satsync.py:2230
msgid "parent SUSE Manager to import content from"
msgstr "SUSE Manager pai para importar conteúdo de"

#: ../satellite_tools/satsync.py:2232
msgid "list all available channels and exit"
msgstr "listar todos os canais disponíveis e sair"

#: ../satellite_tools/satsync.py:2234
msgid "help on all error codes mgr-inter-sync returns"
msgstr "ajuda em todos os códigos de erro retornos de mgr-inter-sync"

#: ../satellite_tools/satsync.py:2236
msgid "source mount point for import - disk update only"
msgstr ""
"ponto de montagem de origem para importação - somente atualização de disco"

#: ../satellite_tools/satsync.py:2238
msgid "do not process patch data"
msgstr "não processe dados de correção"

#: ../satellite_tools/satsync.py:2240
msgid "do not process kickstart data (provisioning only)"
msgstr "não processe dados do kickstart (apenas provisionamento)"

#: ../satellite_tools/satsync.py:2242
msgid "do not process full package metadata"
msgstr "não processe metadados de pacote completo"

#: ../satellite_tools/satsync.py:2244
msgid "do not download, or process any RPMs"
msgstr "não faça o download ou processe quaisquer RPMs"

#: ../satellite_tools/satsync.py:2246
msgid "turn off SSL (not recommended)"
msgstr "desativar o SSL (não recomendado)"

#: ../satellite_tools/satsync.py:2248
msgid "org to which the sync imports data. defaults to the admin account"
msgstr ""
"organização para a qual a sincronização importa dados. o padrão é a conta de "
"administrador"

#: ../satellite_tools/satsync.py:2250
msgid "print the configuration and exit"
msgstr "imprima a configuração e saia"

#: ../satellite_tools/satsync.py:2252
msgid "alternative server with which to connect (hostname)"
msgstr "servidor alternativo ao qual se conectar (nome do host)"

#: ../satellite_tools/satsync.py:2254
msgid "synchronize to this step (man satellite-sync for more info)"
msgstr "sincronize com esta etapa (man satellite-sync para mais informações)"

#: ../satellite_tools/satsync.py:2256
msgid "write complete data to tempfile before streaming to remainder of app"
msgstr ""
"gravar dados completos no arquivo temporário antes de transmitir para o "
"restante do aplicativo"

#: ../satellite_tools/satsync.py:2258
msgid "DEBUG ONLY: alternative path to digital system id"
msgstr ""
"APENAS DEBUG: caminho alternativo para a identificação do sistema digital"

#: ../satellite_tools/satsync.py:2260
msgid "alternative email address(es) for sync output (--email option)"
msgstr ""
"endereços de email alternativos para saída de sincronização (opção --email)"

#: ../satellite_tools/satsync.py:2262
msgid "do not remove rpms when importing from local dump"
msgstr "não remova rpms ao importar do dump local"

#: ../satellite_tools/satsync.py:2264
msgid ""
"the fully qualified domain name of the master Satellite. Valid with --mount-"
"point only. Required if you want to import org data and channel permissions."
msgstr ""
"o nome de domínio totalmente qualificado do Satellite principal. Válido "
"apenas com --mount-point. Necessário se você deseja importar dados da "
"organização e permissões de canal."

#: ../satellite_tools/satsync.py:2274
#, python-format
msgid "ERROR: these arguments make no sense in this context (try --help): %s"
msgstr ""
"ERRO: esses argumentos não fazem sentido neste contexto (tente --help): %s"

#. An SQL error is fatal... crash and burn
#: ../satellite_tools/satsync.py:2286
#, python-format
msgid "ERROR: Can't connect to the database: %s"
msgstr "ERRO: Não é possível conectar ao banco de dados: %s"

#: ../satellite_tools/satsync.py:2287
msgid "ERROR: Check if your database is running."
msgstr "ERRO: Verifique se o seu banco de dados está em execução."

#: ../satellite_tools/satsync.py:2322
#, python-format
msgid "ERROR: --debug-level takes an in integer value within the range %s."
msgstr "ERRO: --debug-level aceita um valor inteiro dentro do intervalo %s."

#: ../satellite_tools/satsync.py:2324
msgid "  0  - little logging/messaging."
msgstr "  0  - pouco registro/mensagens."

#: ../satellite_tools/satsync.py:2325
msgid "  1  - minimal logging/messaging."
msgstr "  1  - registro/mensagens mínimos."

#: ../satellite_tools/satsync.py:2326
msgid "  2  - normal level of logging/messaging."
msgstr "  2  - nível normal de registro/mensagens."

#: ../satellite_tools/satsync.py:2327
msgid "  3  - lots of logging/messaging."
msgstr "  3  - muitos registros/mensagens."

#: ../satellite_tools/satsync.py:2328
msgid "  4+ - excessive logging/messaging."
msgstr "  4+ - registro/mensagens excessivos."

#: ../satellite_tools/satsync.py:2341
msgid "ERROR: The --master option is only valid with the --mount-point option"
msgstr "ERRO: A opção --master é válida apenas com a opção --mount-point"

#: ../satellite_tools/satsync.py:2351
#, python-format
msgid "ERROR: Unable to lookup Org Id %s"
msgstr "ERRO: Não foi possível procurar a ID da organização %s"

#: ../satellite_tools/satsync.py:2360
msgid ""
"WARNING: --list-channels option overrides any --step option. --step ignored."
msgstr ""
"AVISO: a opção --list-channels substitui qualquer opção --step. - passo "
"ignorado."

#: ../satellite_tools/satsync.py:2375
#, python-format
msgid ""
"ERROR: '%s' is not a valid step. See 'man mgr-inter-sync' for more detail."
msgstr ""
"ERRO: '%s' não é uma etapa válida. Veja 'man mgr-inter-sync' para mais "
"detalhes."

#: ../satellite_tools/satsync.py:2407
msgid ""
"ERROR: No channels currently imported; try mgr-inter-sync --list-channels; "
"then mgr-inter-sync -c chn0 -c chn1..."
msgstr ""
"ERRO: nenhum canal importado no momento; tente mgr-inter-sync --list-"
"channels; então mgr-inter-sync -c chn0 -c chn1 ..."

#. int(None) --> TypeError
#. int('a')  --> ValueError
#: ../satellite_tools/satsync.py:2457 ../satellite_tools/satsync.py:2461
msgid "ERROR: --batch-size must have a value within the range: 1..50"
msgstr "ERRO: - o tamanho do lote deve ter um valor dentro do intervalo: 1..50"

#: ../satellite_tools/satsync.py:2469
#, python-format
msgid "ERROR: no such directory %s"
msgstr "ERRO: nenhum diretório %s"

#: ../satellite_tools/satsync.py:2474
msgid "Error Codes: Returned codes means:"
msgstr "Códigos de erro: códigos retornados significa:"

#: ../satellite_tools/satsync.py:2475
msgid " -1  - Could not lock file or KeyboardInterrupt or SystemExit"
msgstr ""
" -1  - Não foi possível bloquear o arquivo ou KeyboardInterrupt ou SystemExit"

#: ../satellite_tools/satsync.py:2476
msgid "  0  - User interrupted or intentional exit"
msgstr "  0  - Saída interrompida ou intencional pelo usuário"

#: ../satellite_tools/satsync.py:2477
msgid "  1  - attempting to run more than one instance of mgr-inter-sync."
msgstr "  1  - tentando executar mais de uma instância do mgr-inter-sync."

#: ../satellite_tools/satsync.py:2478
msgid "  2  - Unable to find synchronization tools."
msgstr "  2  - Não foi possível encontrar as ferramentas de sincronização."

#: ../satellite_tools/satsync.py:2479
msgid "  3  - a general socket exception occurred"
msgstr "  3  - ocorreu uma exceção geral do soquete"

#: ../satellite_tools/satsync.py:2480
msgid "  4  - an SSL error occurred. Recheck your SSL settings."
msgstr ""
"  4  - ocorreu um erro de SSL. Verifique novamente suas configurações de SSL."

#: ../satellite_tools/satsync.py:2481
msgid "  5  - ISS error"
msgstr "  5  - Erro ISS"

#: ../satellite_tools/satsync.py:2482
msgid "  6  - unhandled exception occurred"
msgstr "  6  - ocorreu uma exceção não tratada"

#: ../satellite_tools/satsync.py:2483
msgid "  7  - unknown sync error"
msgstr "  7  - erro de sincronização desconhecido"

#: ../satellite_tools/satsync.py:2484
msgid "  8  - ERROR: must be root to execute"
msgstr "  8  - ERRO: deve ser root para executar"

#: ../satellite_tools/satsync.py:2485
msgid "  9  - rpclib fault during synchronization init"
msgstr "  9  - falha rpclib durante a sincronização init"

#: ../satellite_tools/satsync.py:2486
msgid "  10 - synchronization init error"
msgstr "  10 - erro de inicialização de sincronização"

#: ../satellite_tools/satsync.py:2487
msgid "  11 - Error parsing XML stream"
msgstr "  11 - Erro ao analisar o fluxo XML"

#: ../satellite_tools/satsync.py:2488
msgid "  12 - Channel do not exist"
msgstr "  12 - O canal não existe"

#: ../satellite_tools/satsync.py:2489
msgid "  13 - SQL error during importing package metadata"
msgstr "  13 - Erro SQL durante a importação de metadados do pacote"

#: ../satellite_tools/satsync.py:2490
msgid "  14 - SQL error during linking channel packages"
msgstr "  14 - Erro SQL durante a vinculação de pacotes de canais"

#: ../satellite_tools/satsync.py:2491
msgid "  15 - SQL error during xml processing"
msgstr "  15 - Erro SQL durante o processamento xml"

#: ../satellite_tools/satsync.py:2492
msgid "  16 - server.mount_point not set in the configuration file"
msgstr "  16 - server.mount_point não definido no arquivo de configuração"

#: ../satellite_tools/satsync.py:2493
msgid ""
"  17 - SQL error during retrieving the channels already imported in the SUSE "
"Manager database"
msgstr ""
"  17 - Erro SQL durante a recuperação dos canais já importados no banco de "
"dados do SUSE Manager"

#: ../satellite_tools/satsync.py:2494
msgid "  18 - Wrong db connection string in rhn.conf"
msgstr "  18 - Cadeia de conexão db incorreta no rhn.conf"

#: ../satellite_tools/satsync.py:2495
msgid "  19 - Bad arguments"
msgstr "  19 - Argumentos incorretos"

#: ../satellite_tools/satsync.py:2496
msgid "  20 - Could not connect to db."
msgstr "  20 - Não foi possível conectar ao db."

#: ../satellite_tools/satsync.py:2497
msgid "  21 - Bad debug level"
msgstr "  21 - Nível de depuração incorreto"

#: ../satellite_tools/satsync.py:2498
msgid "  22 - Not valid step"
msgstr "  22 - Etapa inválida"

#: ../satellite_tools/satsync.py:2499
msgid "  24 - no such file"
msgstr "  24 - arquivo inexistente"

#: ../satellite_tools/satsync.py:2500
msgid "  25 - no such directory"
msgstr "  25 - nenhum diretório"

#: ../satellite_tools/satsync.py:2501
msgid "  26 - mount_point does not exist"
msgstr "  26 - mount_point não existe"

#: ../satellite_tools/satsync.py:2502
msgid "  27 - No such org"
msgstr "  27 - Essa organização não existe"

#: ../satellite_tools/satsync.py:2503
msgid "  28 - error: --master is only valid with --mount-point"
msgstr "  28 - erro: --master é válido apenas com --mount-point"

#: ../satellite_tools/satsync.py:2510
#, python-format
msgid "ERROR: unknown dump version, try one of %s"
msgstr "ERRO: versão de despejo desconhecida, tente um dos %s"

#~ msgid "Red Hat Satellite Welcome Message"
#~ msgstr "Mensagem de Boas-vindas do Red Hat Satellite"
