# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Mike Karas <zoliqe@gmail.com>, 2005.
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-09-29 14:21+0200\n"
"PO-Revision-Date: 2020-09-25 13:48+0000\n"
"Last-Translator: Ferdinand Galko <galko.ferdinand@gmail.com>\n"
"Language-Team: Slovak <https://l10n.opensuse.org/projects/uyuni/backend/sk/"
">\n"
"Language: sk\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;\n"
"X-Generator: Weblate 3.6.1\n"

#: ../server/apacheAuth.py:66
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "neúplný token overenia proxy: %s"

#: ../server/apacheAuth.py:84
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr "Zaslaný podpis proxy %s nezodpovedá nášmu %s."

#: ../server/apacheAuth.py:119
msgid "declined proxy authentication"
msgstr "zamietnuté overenie proxy"

#: ../server/handlers/app/packages.py:192
#: ../server/handlers/xmlrpc/registration.py:215
#: ../server/handlers/xmlrpc/registration.py:1168
#: ../server/handlers/xmlrpc/registration.py:1307
#: ../server/configFilesHandler.py:129
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   Na tomto serveri bol účet %s deaktivovaný.\n"
"                   Pre ďalšiu pomoc kontaktujte administrátora svojej "
"organizácie."

#: ../server/handlers/applet/applet.py:78
#, python-brace-format
msgid "Your system was not found in the {PRODUCT_NAME} database"
msgstr "Váš systém sa nenašiel v databáze {PRODUCT_NAME}"

#: ../server/handlers/sat/auth.py:45
msgid "ISS is disabled on this server."
msgstr "Na tomto serveri je ISS zakázané."

#: ../server/handlers/sat/auth.py:50
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "Server \"%s\" nie je povolený pre ISS."

#: ../server/handlers/xmlrpc/scap.py:104
msgid "Invalid system_id/action_id pair."
msgstr "Neplatný pár system_id/action_id."

#: ../server/handlers/xmlrpc/errata.py:64
#, python-format
msgid "Expected a package name, not: %s"
msgstr "Očakávaný názov balíka, nie: %s"

#: ../server/handlers/xmlrpc/errata.py:115
#, python-format
msgid "Expected a package, not: %s"
msgstr "Očakávaný balík, nie: %s"

#: ../server/handlers/xmlrpc/queue.py:433
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr "Neplatný typ hodnoty akcie %s (%s)"

#: ../server/handlers/xmlrpc/queue.py:464
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "Akcia %s nepatrí k serveru %s"

#: ../server/handlers/xmlrpc/up2date.py:233
#, python-format
msgid "Invalid value %s (%s)"
msgstr "Neplatná hodnota %s (%s)"

#: ../server/handlers/xmlrpc/proxy.py:65
#, python-format
msgid "SUSE Manager Proxy service not enabled for server profile: \"%s\""
msgstr "Služba SUSE Manager Proxy nie je povolená pre profil servera: \"%s\""

#: ../server/handlers/xmlrpc/proxy.py:85
msgid "Invalid session key"
msgstr "Neplatný kľúč sedenia"

#: ../server/handlers/xmlrpc/proxy.py:93
msgid "This server ID no longer exists"
msgstr "Toto ID servera už neexistuje"

#: ../server/handlers/xmlrpc/registration.py:194
msgid "Required data missing"
msgstr "Chýbajú požadované dáta"

#: ../server/handlers/xmlrpc/registration.py:198
msgid "Required members missing"
msgstr "Chýbajú požadovaní členovia"

#: ../server/handlers/xmlrpc/registration.py:207
msgid "Attempt to register a system to an invalid username"
msgstr "Pokus o registráciu systému na neplatné používateľské meno"

#: ../server/handlers/xmlrpc/registration.py:839
msgid "Invalid system release version requested"
msgstr "Požaduje sa neplatná verzia vydania systému"

#: ../server/handlers/xmlrpc/registration.py:1063
msgid ""
"Unable to find a valid network interface, both ipaddr and ip6addr not found."
msgstr ""
"Nepodarilo sa nájsť platné sieťové rozhranie, ipaddr a ip6addr sa nenašli."

#: ../server/handlers/xmlrpc/registration.py:1115
#, python-brace-format
msgid "{PRODUCT_NAME} Welcome Message"
msgstr "Uvítacia správa {PRODUCT_NAME}"

#: ../server/handlers/xmlrpc/registration.py:1125
msgid "Privacy Statement"
msgstr "Vyhlásenie o ochrane súkromia"

#: ../server/handlers/xmlrpc/registration.py:1146
msgid "Expected a dictionary as a product argument"
msgstr "Očakávaný slovník ako argument produktu"

#: ../server/handlers/xmlrpc/registration.py:1374
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr "Neplatná hodnota '%s' pre %s (%s)"

#: ../server/importlib/userAuth.py:98
msgid "You are not authorized to manage packages in the null org"
msgstr "Nemáte oprávnenie spravovať balíky v null org"

#: ../server/importlib/userAuth.py:103
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "Nemáte oprávnenie spravovať balíky v %s org"

#: ../server/importlib/userAuth.py:121
msgid "You are not allowed to perform administrative tasks"
msgstr "Nemáte oprávnenie vykonávať administratívne úlohy"

#: ../server/importlib/userAuth.py:144
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr "Nemáte oprávnenie spravovať kanál %s, alebo tento kanál neexistuje"

#: ../server/importlib/userAuth.py:204
#, python-format
msgid ""
"\n"
"               %s Account has been deactivated on this server.\n"
"               Please contact your Org administrator for more help."
msgstr ""
"\n"
"               Na tomto serveri bol účet %s deaktivovaný.\n"
"               Pre ďalšiu pomoc kontaktujte administrátora svojej "
"organizácie."

#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr "Prosím, spustite rhn_register ako správca systému na tomto klientovi"

#: ../server/rhnHandler.py:75
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr "Služba nie je povolená pre systémový profil: \"%s\""

#: ../server/rhnServer/server_class.py:97
#, python-format
msgid "Architecture `%s' is not supported"
msgstr "Architektúra `%s' nie je podporovaná"

#: ../server/rhnServer/server_token.py:78
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "Token `%s' má priradený viac ako jeden základný kanál"

#: ../server/rhnServer/server_token.py:80
msgid "Conflicting base channels"
msgstr "Konfliktné základné kanály"

#: ../server/rhnServer/server_token.py:190
#, python-format
msgid "Failed to add server to group %s"
msgstr "Zlyhalo pridanie servera do skupiny %s"

#: ../server/rhnServer/server_token.py:503
#, python-format
msgid "Maximum usage count of %s reached"
msgstr "Dosiahol sa maximálny počet použití %s"

#: ../server/rhnServer/server_token.py:744
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""
"Skladanie tokenov opätovnej registrácie s rôznymi základnými oprávneniami "
"nie je podporované"

#: ../server/rhnServer/server_token.py:811
#, python-format
msgid "Could not find token '%s'"
msgstr "Nepodarilo sa nájsť token '%s'"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:843
msgid "Tokens from mismatching orgs"
msgstr "Žetóny z nezhodujúcich sa organizácií"

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:853
msgid "Kickstart session mismatch"
msgstr "Nesúlad sedenia kickstart"

#: ../server/rhnServer/server_token.py:877
msgid "Stacking of re-registration tokens is not supported"
msgstr "Skladanie tokenov opätovnej registrácie nie je podporované"

#: ../server/rhnUser.py:289 ../server/rhnUser.py:292
msgid "Invalid username/password combination"
msgstr "Neplatná kombinácia používateľského mena/hesla"

#. nope, not reserved either
#: ../server/rhnUser.py:467
#, python-format
msgid "Username `%s' has not been reserved"
msgstr "Používateľské meno `%s' nebolo rezervované"

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:473
msgid "E-mail address not specified"
msgstr "E-mailová adresa nie je uvedená"

#: ../server/rhnUser.py:509
#, python-format
msgid "username should be at least %d characters"
msgstr "používateľské meno by malo mať najmenej %d znakov"

#: ../server/rhnUser.py:512
#, python-format
msgid "username should be less than %d characters"
msgstr "používateľské meno by malo mať menej ako %d znakov"

#: ../server/rhnUser.py:523
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr "používateľské meno = `%s', neplatný znak `%s'"

#: ../server/rhnUser.py:542
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr "Prosím, obmedzte svoju e-mailovú adresu na %s znakov"

#: ../server/rhnUser.py:623
#, python-format
msgid "password must be at least %d characters"
msgstr "heslo musí mať najmenej %d znakov"

#: ../server/rhnUser.py:626
#, python-format
msgid "Password must be shorter than %d characters"
msgstr "Heslo musí byť kratšie ako %d znakov"

#: ../server/rhnUser.py:644
#, python-format
msgid "password contains character `%s'"
msgstr "heslo obsahuje znak `%s'"

#: ../server/rhnUser.py:651
#, python-format
msgid "username should be at least %d characters long"
msgstr "používateľské meno by malo byť najmenej %d znakov dlhé"

#: ../server/rhnUser.py:662
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr "Nie je možné zaregistrovať používateľské mená končiace s %s"

#: ../server/rhnPackage.py:49 ../server/rhnPackage.py:87
#: ../server/rhnPackage.py:107 ../server/rhnPackage.py:158
#, python-format
msgid "Invalid RPM package %s requested"
msgstr "Požaduje sa neplatný balík RPM %s"

#: ../server/rhnPackage.py:112
msgid "Package not found"
msgstr "Balík nebol nájdený"

#: ../server/apacheRequest.py:59
#, python-format
msgid "Invalid request received (%s)."
msgstr "Prijatá neplatná požiadavka (%s)."

#: ../server/apacheRequest.py:120
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""
"DÔLEŽITÁ SPRÁVA NASLEDUJE:\n"
"%s"

#: ../server/apacheRequest.py:149
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""
"Počas behu '%s': zachytené\n"
"%s : %s\n"

#: ../server/apacheRequest.py:606
#, python-format
msgid "Invalid URI %s"
msgstr "Neplatné URI %s"

#: ../server/rhnChannel.py:1992
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""
"Váš účet nemá prístup k žiadnym kanálom, ktoré zodpovedajú "
"(vydanie='%(release)s', arch='%(arch)s')%(www_activation)s"

#: ../server/rhnChannel.py:2002
msgid ""
"\n"
"If you have a registration number, please register with it first at http://"
"www.redhat.com/apps/activate/ and then try again.\n"
"\n"
msgstr ""
"\n"
"Ak máte registračné číslo, zaregistrujte sa s ním najskôr na http://www."
"redhat.com/apps/activate/ a potom skúste znova.\n"
"\n"

#: ../server/rhnChannel.py:2012
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr "Nedostatočné práva predplatného na vydanie (%s, %s"

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2276 ../server/rhnChannel.py:2287
#: ../server/rhnChannel.py:2302
msgid "System Registered but Inactive"
msgstr "Systém je registrovaný, ale neaktívny"

#: ../server/rhnChannel.py:2277
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it is not subscribed to a channel. If you have not yet\n"
"activated your product for service, please visit our website at:\n"
"\n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...to activate your product."
msgstr ""
"\n"
"Neplatná kombinácia architektúry a vydania OS (%s, %s).\n"
"Váš systém bol zaregistrovaný, ale nebude dostávať aktualizácie,\n"
"pretože nie je prihlásený ku kanálu. Ak ste ešte svoj produkt\n"
"neaktivovali pre servis, prosím, navštívte našu webovú stránku na:\n"
"\n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...na aktiváciu vášho produktu."

#: ../server/rhnChannel.py:2288
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""
"\n"
"Neplatná kombinácia architektúry a vydania OS (%s, %s).\n"
"Váš systém bol zaregistrovaný, ale nebude dostávať aktualizácie,\n"
"pretože sa nemohol prihlásiť k základnému kanálu.\n"
"Požiadajte o pomoc administrátora svojej organizácie.\n"

#: ../server/rhnChannel.py:2295
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Tento systém bol úspešne zaregistrovaný, ale zatiaľ nie je oprávnený na "
"službu.\n"
"  Na oprávnenie tohto systému na servis sa prihláste na webovej stránke:\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnChannel.py:2303
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  Tento systém bol úspešne zaregistrovaný, ale neboli k dispozícii žiadne "
"oprávnenia\n"
"  na službu.  Na oprávnenie tohto systému na servis sa prihláste na webovej "
"stránke:\n"
"\n"
"  %(entitlement_url)s\n"

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:53
msgid "This does not appear to be a valid username."
msgstr "Nezdá sa, že je to platné používateľské meno."

#: ../common/rhnException.py:54
msgid "Invalid username and password combination."
msgstr "Neplatná kombinácia používateľského mena a hesla."

#: ../common/rhnException.py:55
msgid "This login is already taken, or the password is incorrect."
msgstr "Toto prihlasovacie meno je už obsadené, alebo je heslo nesprávne."

#: ../common/rhnException.py:56
msgid "Permission denied."
msgstr "Prístup zamietnutý."

#: ../common/rhnException.py:57
msgid "Object not found."
msgstr "Objekt nebol nájdený."

#: ../common/rhnException.py:58
msgid "Invalid System Digital ID."
msgstr "Neplatné digitálne ID systému."

#: ../common/rhnException.py:59
msgid "Invalid System Credentials."
msgstr "Neplatné prihlasovanie údaje do systému."

#: ../common/rhnException.py:60
msgid "Could not retrieve user data from database."
msgstr "Nepodarilo získať z databázy používateľské dáta."

#: ../common/rhnException.py:61
msgid "Valid username required."
msgstr "Vyžaduje sa platné používateľské meno."

#: ../common/rhnException.py:62
msgid "Valid password required."
msgstr "Vyžaduje sa platné heslo."

#: ../common/rhnException.py:63
msgid "Minimum username length violation."
msgstr "Nedodržanie minimálnej dĺžky používateľského mena."

#: ../common/rhnException.py:64
msgid "Minimum password length violation."
msgstr "Nedodržanie minimálnej dĺžky hesla."

#: ../common/rhnException.py:65
msgid "The username contains invalid characters."
msgstr "Používateľské meno obsahuje neplatné znaky."

#: ../common/rhnException.py:66
msgid "File not found."
msgstr "Súbor nebol nájdený."

#: ../common/rhnException.py:67
msgid "Architecture and OS version combination is not supported."
msgstr "Kombinácia architektúry a verzie OS nie je podporovaná."

#: ../common/rhnException.py:68
msgid "Could not retrieve system data from database."
msgstr "Nepodarilo získať z databázy systémové dáta."

#: ../common/rhnException.py:69
msgid "Invalid arguments passed to function."
msgstr "Funkcii boli odovzdané neplatné argumenty."

#: ../common/rhnException.py:70
msgid "Unable to retrieve requested entry."
msgstr "Požadovanú položku sa nepodarilo získať."

#: ../common/rhnException.py:71
msgid "Could not update database entry."
msgstr "Nepodarilo sa aktualizovať položku databázy."

#: ../common/rhnException.py:72
msgid "Unsupported server architecture."
msgstr "Nepodporovaná architektúra servera."

#: ../common/rhnException.py:73
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running mgr_register as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     Funkcia anonymného servera už nie je k dispozícii.\n"
"\n"
"     Znova zaregistrujte tento systém spustením mgr_register ako root.\n"
"     Prosím navštívte https://%(hostname)s/rhn/systems/SystemEntitlements."
"do\n"
"     alebo sa prihláste na https://%(hostname)s a z karty \"Prehľad\" "
"vyberte\n"
"     \"Správa predplatného\" na aktiváciu služby pre tento systém.\n"
"     "

#: ../common/rhnException.py:81
msgid "Record not available in the database."
msgstr "Záznam nie je dostupný v databáze."

#: ../common/rhnException.py:82
msgid "Invalid value for entry."
msgstr "Neplatná hodnota pre položku."

#: ../common/rhnException.py:83
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for SUSE Manager.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     Tento systém nemá platné oprávnenie pre SUSE Manager.\n"
"     Prosím navštívte https://%(hostname)s/rhn/systems/SystemEntitlements."
"do\n"
"     alebo sa prihláste na https://%(hostname)s a z karty \"Prehľad\" "
"vyberte\n"
"     \"Správa predplatného\"vna aktiváciu služby pre tento systém.\n"
"     "

#: ../common/rhnException.py:89
msgid "Channel error"
msgstr "Chyba kanála"

#: ../common/rhnException.py:90
msgid "Client session token is invalid."
msgstr "Token klientského sedenia je neplatný."

#: ../common/rhnException.py:91
msgid "Client session token has expired."
msgstr "Platnosť tokenu klientského sedenia vypršala."

#: ../common/rhnException.py:92
msgid "You are not authorized to retrieve the requested object."
msgstr "Nemáte oprávnenie získať požadovaný objekt."

#: ../common/rhnException.py:93
msgid "Invalid action"
msgstr "Neplatná akcia"

#: ../common/rhnException.py:94
msgid "You are not allowed to perform administrative tasks on this system."
msgstr "Nemáte oprávnenie vykonávať administratívne úlohy v tomto systéme."

#: ../common/rhnException.py:96
msgid "The system is already subscribed to the specified channel."
msgstr "Systém je už prihlásený k zadanému kanálu."

#: ../common/rhnException.py:97
msgid "The system is not currently subscribed to the specified channel."
msgstr "Systém nie je momentálne prihlásený k zadanému kanálu."

#: ../common/rhnException.py:98
msgid "The specified channel does not exist."
msgstr "Zadaný kanál neexistuje."

#: ../common/rhnException.py:99
msgid "Invalid channel version."
msgstr "Neplatná verzia kanála."

#: ../common/rhnException.py:100
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""
"\n"
"     Limity členstva v používateľských skupinách boli prekročené.\n"
"\n"
"     Aktuálne nastavenia vášho účtu vám neumožňujú pridať ďalší "
"používateľský\n"
"     účet. Prosím, overte si u administrátora organizácie pre váš účet, či "
"sa\n"
"     musí zmeniť maximálny počet používateľov, ktorí sa môžu prihlásiť k "
"serveru.\n"
"     k serveru.\n"
"     "

#: ../common/rhnException.py:108
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""
"\n"
"     Limity členstva v systémových skupinách boli prekročené.\n"
"\n"
"     Aktuálne nastavenia vášho účtu vám neumožňujú pridať ďalší systémový\n"
"     profil. Prosím, obráťte sa na administrátora organizácie pre váš účet,\n"
"     ak chcete upraviť maximálny počet systémových profilov, ktoré je môžu "
"byť\n"
"     prihlásené k vášmu účtu.\n"
"     "

#: ../common/rhnException.py:116
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""
"\n"
"     Neplatná architektúra.\n"
"\n"
"     Architektúru balíka nie je podporovaná\n"
"     "

#: ../common/rhnException.py:121
msgid "Invalid RPM header"
msgstr "Neplatná hlavička RPM"

#: ../common/rhnException.py:122
msgid ""
"\n"
"    This system is already registered as a Salt Minion. If you want to "
"register it as a traditional client\n"
"    please delete it first via the web UI or API and then register it using "
"the traditional tools.\n"
"    "
msgstr ""
"\n"
"    Tento systém je už zaregistrovaný ako Salt Minion. Ak ho chcete "
"zaregistrovať ako tradičného klienta,\n"
"    najskôr ho vymažte cez webové UI alebo API a potom ho zaregistrujte "
"pomocou tradičných nástrojov.\n"
"    "

#. For the uploading tools
#: ../common/rhnException.py:127
msgid "Invalid information uploaded to the server"
msgstr "Na server boli nahrané neplatné informácie"

#: ../common/rhnException.py:128
msgid "Error uploading network interfaces configuration."
msgstr "Chyba pri nahrávaní konfigurácie sieťových rozhraní."

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""
"\n"
"     Nahranie balíka zlyhalo z dôvodu porušenia obmedzení jedinečnosti.\n"
"     Uistite sa, že balík nemá duplicitné závislosti alebo už neexistuje\n"
"     na serveri.\n"
"     "

#: ../common/rhnException.py:134
msgid ""
"\n"
"     The --force rhnpush option is disabled on this server.\n"
"     Please contact your SUSE Manager administrator for more help.\n"
"     "
msgstr ""
"\n"
"     Na tomto serveri je zakázaná voľba --force rhnpush.\n"
"     Pre ďalšiu pomoc kontaktujte svojho administrátora SUSE Manager.\n"
"     "

#. 60-70: token errors
#: ../common/rhnException.py:140
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""
"\n"
"     Zadaný aktivačný token nebolo možné nájsť na serveri.\n"
"     Prosím, skúste to znova s platným kľúčom.\n"
"     "

#: ../common/rhnException.py:144
msgid "Too many systems registered using this registration token"
msgstr ""
"Pomocou tohto registračného tokenu bolo zaregistrovaných príliš veľa systémov"

#: ../common/rhnException.py:145
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr "Token obsahuje neplatné, zastarané alebo nedostatočné nastavenia"

#: ../common/rhnException.py:146
msgid "Conflicting activation tokens"
msgstr "Konfliktné aktivačné tokeny"

#. 70-80: channel subscription errors
#: ../common/rhnException.py:149
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""
"\n"
"     Pre váš systém sa nenašiel žiadny zodpovedajúci základný kanál.\n"
"     "

#: ../common/rhnException.py:152
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""
"\n"
"     Nemáte oprávnenie predplatného k určenému kanálu.\n"
"     Ďalšie podrobnosti nájdete v kanáli svojej organizácie alebo\n"
"     administrátora organizácie.\n"
"     "

#: ../common/rhnException.py:157
msgid "You can not unsubscribe from base channel."
msgstr "Nemôžete sa odhlásiť zo základného kanála."

#: ../common/rhnException.py:158
msgid "SUSE Manager or Proxy channel can not be subscribed."
msgstr "Nie je možné prihlásiť sa k SUSE Manager alebo Proxy kanálu."

#. 80-90: server group errors
#: ../common/rhnException.py:161
msgid "There was an error while trying to join the system to its groups"
msgstr "Pri pokuse o pripojenie systému k jeho skupinám sa vyskytla chyba"

#. 90-100: entitlement errors
#: ../common/rhnException.py:164
msgid "Unable to entitle system"
msgstr "Nie je možné priradiť oprávnenie systému"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:167
msgid "Maximum e-mail length violation."
msgstr "Nedodržanie maximálnej dĺžky e-mailu."

#: ../common/rhnException.py:168
msgid "This system has been previously registered."
msgstr "Tento systém bol predtým zaregistrovaný."

#: ../common/rhnException.py:169
msgid "Invalid username"
msgstr "Neplatné používateľské meno"

#. 140-159 applet errors
#: ../common/rhnException.py:172
msgid "Unable to look up server"
msgstr "Server sa nepodarilo vyhľadať"

#. 160-179: OSAD errors
#: ../common/rhnException.py:175
msgid "Required argument is missing"
msgstr "Chýba požadovaný argument"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:178
msgid "No entitlement information tied to hardware"
msgstr "S hardvérom nie sú spojené žiadne informácie o oprávneniach"

#: ../common/rhnException.py:179
msgid "Installation number is not entitling"
msgstr "Inštalačné číslo nie je oprávňujúce"

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:182
msgid "Maximum username length violation"
msgstr "Nedodržanie maximálnej dĺžky používateľského mena"

#: ../common/rhnException.py:183
msgid "Maximum password length violation"
msgstr "Nedodržanie maximálnej dĺžky hesla"

#: ../common/rhnException.py:184
msgid "This user has read only API access. Action denied."
msgstr "Tento používateľ má prístup iba na čítanie API. Akcia zamietnutá."

#: ../common/rhnException.py:186
msgid "System Name cannot be less than 1 character"
msgstr "Názov systému nesmie mať menej ako 1 znak"

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:190
msgid "SUSE Manager Proxy error."
msgstr "Chyba SUSE Manager Proxy."

#: ../common/rhnException.py:191
msgid "SUSE Manager Proxy unable to login."
msgstr "SUSE Manager Proxy sa nemôže prihlásiť."

#. issued by a SUSE Manager Server/Satellite to the proxy
#: ../common/rhnException.py:193
msgid ""
"\n"
"     SUSE Manager Proxy system ID does not match a Spacewalk Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""
"\n"
"     ID systému SUSE Manager Proxy nezodpovedá Spacewalk Proxy Server\n"
"     v databáze.\n"
"     "

#: ../common/rhnException.py:197
msgid "SUSE Manager Proxy session token is invalid."
msgstr "Token sedenia SUSE Manager Proxy je neplatný."

#: ../common/rhnException.py:198
msgid "SUSE Manager Proxy session token has expired."
msgstr "Platnosť tokenu sedenia SUSE Manager Proxy vypršala."

#. 2000-2999: Red Hat Satellite specific errors:
#: ../common/rhnException.py:202
msgid ""
"\n"
"      user creation is not allowed via mgr_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""
"\n"
"      vytváranie používateľov nie je povolené cez mgr_register;\n"
"     kontaktujte svojho správcu systémov a požiadajte ho o vytvorenie účtu.\n"
"     "

#: ../common/rhnException.py:206
msgid ""
"\n"
"     This SUSE Manager server is not allowed to use Inter Server Sync on "
"this server\n"
"     "
msgstr ""
"\n"
"     Tento server SUSE Manager nemá povolenie na tomto serveri používať "
"Inter Server Sync\n"
"     "

#: ../common/rhnException.py:209
msgid ""
"\n"
"     Inter Server Sync is disabled on this SUSE Manager Server.\n"
"     "
msgstr ""
"\n"
"     Inter Server Sync je zakázaný na tomto SUSE Manager Server.\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:214
msgid "Invalid datatype passed"
msgstr "Odovzdaný neplatný dátový typ"

#: ../common/rhnException.py:215
msgid "Unable to retrieve channel"
msgstr "Nie je možné získať kanál"

#: ../common/rhnException.py:216
msgid "Unable to retrieve package"
msgstr "Nie je možné získať balík"

#: ../common/rhnException.py:217
msgid "Unable to retrieve erratum"
msgstr "Nie je možné získať tlačovú chybu"

#: ../common/rhnException.py:218
msgid "File is missing"
msgstr "Súbor chýba"

#: ../common/rhnException.py:219
msgid "Function retrieval error"
msgstr "Chyba načítania funkcie"

#: ../common/rhnException.py:220
msgid "Function execution error"
msgstr "Chyba vykonávania funkcie"

#: ../common/rhnException.py:221
msgid "Missing version string"
msgstr "Chýba reťazec verzie"

#: ../common/rhnException.py:222
msgid "Invalid version string"
msgstr "Neplatný reťazec verzie"

#: ../common/rhnException.py:223
msgid "Mismatching versions"
msgstr "Nezhodné verzie"

#: ../common/rhnException.py:224
msgid "Invalid channel version"
msgstr "Neplatná verzia kanála"

#: ../common/rhnException.py:225
msgid "No comps file for channel"
msgstr "Žiadny súbor comps pre kanál"

#: ../common/rhnException.py:226
msgid "Unable to retrieve comps file"
msgstr "Nie je možné získať súbor comps"

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:229
msgid "Configuration action missing"
msgstr "Chýba konfiguračná akcia"

#: ../common/rhnException.py:230
msgid "File too large"
msgstr "Súbor je príliš veľký"

#: ../common/rhnException.py:231
msgid "File contains binary data"
msgstr "Súbor obsahuje binárne dáta"

#: ../common/rhnException.py:232
msgid "Configuration channel is not empty"
msgstr "Konfiguračný kanál nie je prázdny"

#: ../common/rhnException.py:233
msgid "Permission error"
msgstr "Chyba oprávnení"

#: ../common/rhnException.py:234
msgid "Content missing for configuration file"
msgstr "Chýba obsah konfiguračného súboru"

#: ../common/rhnException.py:235
msgid "Template delimiters not specified"
msgstr "Oddeľovače šablón nie sú uvedené"

#: ../common/rhnException.py:236
msgid "Configuration channel does not exist"
msgstr "Konfiguračný kanál neexistuje"

#: ../common/rhnException.py:237
msgid "Configuration channel already exists"
msgstr "Konfiguračný kanál už existuje"

#: ../common/rhnException.py:238
msgid "File missing from configuration channel"
msgstr "Chýba súbor z konfiguračného kanála"

#: ../common/rhnException.py:239
msgid "Different revision of this file is uploaded"
msgstr "Nahraná je iná revízia tohto súboru"

#: ../common/rhnException.py:240
msgid "File already uploaded to configuration channel"
msgstr "Súbor už bol nahraný na konfiguračný kanál"

#: ../common/rhnException.py:241
msgid "File size exceeds remaining quota space"
msgstr "Veľkosť súboru presahuje zostávajúci priestor kvóty"

#: ../common/rhnException.py:242
msgid "Full path of file must be specified"
msgstr "Musí byť zadaná úplná cesta k súboru"

#: ../common/rhnException.py:243
msgid "Invalid revision number"
msgstr "Neplatné číslo revízie"

#: ../common/rhnException.py:244
msgid "Cannot compare files of different file type"
msgstr "Nie je možné porovnávať súbory rôznych súborových typov"

#. 5000 - 5999: client content uploading errors
#. 5000 - 5099: crash reporting errors
#: ../common/rhnException.py:248
msgid "Crash information is invalid or incomplete"
msgstr "Informácie o zlyhaní sú neplatné alebo neúplné"

#: ../common/rhnException.py:249
msgid "Crash file information is invalid or incomplete"
msgstr "Informácie o zlyhaní súboru sú neplatné alebo neúplné"

#: ../common/rhnException.py:250
msgid "Error composing crash directory path"
msgstr "Chyba pri vytváraní cesty adresára zlyhania"

#: ../common/rhnException.py:251
msgid "Error composing crash file path"
msgstr "Chyba pri vytváraní cesty súboru zlyhania"

#: ../common/rhnException.py:252 ../common/rhnException.py:259
msgid "Invalid content encoding"
msgstr "Neplatné kódovanie obsahu"

#: ../common/rhnException.py:253
msgid "Invalid crash name"
msgstr "Neplatný názov zlyhania"

#: ../common/rhnException.py:254
msgid "Crash reporting is disabled for this organization"
msgstr "Hlásenie zlyhaní je pre túto organizáciu zakázané"

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:256
msgid "SCAP results file transfer is invalid or incomplete"
msgstr "Prenos súboru výsledkov SCAP je neplatný alebo neúplný"

#: ../common/rhnException.py:257
msgid "Error composing directory path for detailed SCAP results"
msgstr "Chyba pri vytváraní cesty adresára pre podrobné výsledky SCAP"

#: ../common/rhnException.py:258
msgid "Error composing file path for detailed SCAP results"
msgstr "Chyba pri vytváraní cesty súboru pre podrobné výsledky SCAP"

#: ../common/rhnException.py:306
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at scc.suse.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""
"\n"
"     Pri spracovaní vašej požiadavky sa vyskytla chyba. Ak problém\n"
"     pretrváva, zadajte, prosím, hlásenie o chybe na scc.suse.com.\n"
"     Ak sa rozhodnete odoslať hlásenie o chybe, nezabudnite uviesť\n"
"     podrobnosti o tom, čo ste sa pokúsili urobiť, keď sa vyskytla táto\n"
"     chyba, a podrobnosti o tom, ako tento problém reprodukovať.\n"

#: ../common/rhnException.py:358
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""
"Chybová správa:\n"
"    %s\n"

#: ../common/rhnException.py:360
#, python-format
msgid "Error Class Code: %s\n"
msgstr "Kód triedy chyby: %s\n"

#: ../common/rhnException.py:363
#, python-format
msgid "Error Class Info: %s\n"
msgstr "Informácia o triede chýb: %s\n"

#: ../common/rhnException.py:365
#, python-format
msgid "Explanation: %s"
msgstr "Vysvetlenie: %s"

#: ../common/rhnTB.py:205
#, python-format
msgid "ERROR: %s %s: %s"
msgstr "CHYBA: %s %s: %s"

#: ../common/rhnTB.py:207
#, python-format
msgid "TRACEBACK: %s"
msgstr "TRACEBACK: %s"

#: ../satellite_tools/disk_dumper/iss.py:1294
#: ../satellite_tools/disk_dumper/iss.py:1298
#, python-format
msgid "format of %s should be at least YYYYMMDD.\n"
msgstr "formát %s by mal byť aspoň RRRRMMDD.\n"

#: ../satellite_tools/messages.py:26
#, python-format
msgid ""
"\n"
"ERROR: executing step %s. Error is:\n"
"%s\n"
msgstr ""
"\n"
"CHYBA: vykonanie kroku %s. Chyba je:\n"
"%s\n"

#: ../satellite_tools/messages.py:31
#, python-format
msgid ""
"\n"
"ERROR: there was a problem accessing the channel data from your temporary\n"
"       repository. Did you migrate all of the data from the channel ISOs\n"
"       do this directory? If so, please recheck the channels ISOs, ensure\n"
"       that you have them all, and then iteratively remount and repopulate\n"
"       the temporary repository (%s).\n"
msgstr ""
"\n"
"CHYBA: pri prístupe k údajom kanála z dočasného úložiska sa vyskytol\n"
"       problém. Migrovali ste všetky dáta z kanálových ISO do tohto\n"
"       adresára? Ak áno, znovu skontrolujte kanálové ISO, uistite sa,\n"
"       že ich máte všetky a potom iteratívne znovu pripojte a znovu\n"
"       naplňte dočasné úložisko (%s).\n"

#: ../satellite_tools/messages.py:39
#, python-format
msgid ""
"\n"
"ERROR: there was a problem synchronizing the information.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"CHYBA: pri synchronizácii informácií sa vyskytol problém.\n"
"       Chybová správa: %s\n"

#: ../satellite_tools/messages.py:44
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       Depending on the specific error details, please review your "
"configuration,\n"
"       basic network connectivity, and/or name resolution, and try again.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"CHYBA: Pri komunikácii s ISS Master sa vyskytol problém.\n"
"       V závislosti od konkrétnych podrobností o chybe skontrolujte svoju "
"konfiguráciu,\n"
"       základné sieťové pripojenie a/alebo rozlíšenie názvov a skúste "
"znova.\n"
"       Chybová správa: %s\n"

#: ../satellite_tools/messages.py:51
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       If the master satellite is older than v5.3, it does not have ISS "
"capability.\n"
"       Otherwise, depending on the specific error details, please review "
"your\n"
"       configuration, basic network connectivity, and/or name resolution, "
"and try again.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"CHYBA: Pri komunikácii s ISS Master sa vyskytol problém.\n"
"       Ak je hlavný satellite starší ako v5.3, nemá schopnosť ISS.\n"
"       Inak v závislosti od konkrétnych podrobností o chybe skontrolujte "
"svoju\n"
"       konfiguráciu, základné sieťové pripojenie a/alebo rozlíšenie názvov a "
"skúste znova.\n"
"       Chybová správa: %s\n"

#: ../satellite_tools/messages.py:59
#, python-format
msgid ""
"\n"
"ERROR: a child-channel cannot be synced without its parent being synced as\n"
"       well. A parent needs to be either (a) previously synced or (b) "
"synced\n"
"       in tandem with the desired child-channel. Missing parents for this\n"
"       transaction:\n"
"       %s\n"
msgstr ""
"\n"
"CHYBA: kanál potomka nie je možné synchronizovať bez synchronizácie jeho\n"
"       rodiča. Rodič musí byť buď (a) predtým synchronizovaný alebo (b) "
"synchronizovaný\n"
"       spolu s požadovaným kanálom potomka. Chýbajúci rodičia pre túto\n"
"       transakciu:\n"
"       %s\n"

#: ../satellite_tools/messages.py:67
#, python-format
msgid ""
"\n"
"ERROR: you are not entitled to sync a channel in this set of channels.\n"
"Please contact your SUSE Manager contact\n"
"%s"
msgstr ""
"\n"
"CHYBA: nemáte právo synchronizovať kanál v tejto skupine kanálov.\n"
"Obráťte sa na svoj kontakt pre SUSE Manager\n"
"%s"

#: ../satellite_tools/messages.py:72
#, python-format
msgid "  ERROR: not enough free space (%s KB) on device."
msgstr "  CHYBA: na zariadení nie je dostatok voľného miesta (%s KB)."

#: ../satellite_tools/messages.py:74
#, python-format
msgid "    %3d/%s Fetch successful: %s (%s bytes)"
msgstr "    %3d/%s Stiahnutie úspešné: %s (%s bajtov)"

#: ../satellite_tools/messages.py:75
#, python-format
msgid "    Extinct package:  %s"
msgstr "    Zaniknutý balík:  %s"

#: ../satellite_tools/messages.py:76
#, python-format
msgid "   Total size: %s"
msgstr "   Celková veľkosť: %s"

#: ../satellite_tools/messages.py:77
#, python-format
msgid "      Downloaded %s of %s. Estimated remaining time: %s"
msgstr "      Stiahnutých %s z %s. Odhadovaný zostávajúci čas: %s"

#: ../satellite_tools/messages.py:78
#, python-format
msgid "    Fetch unsuccessful: %s"
msgstr "    Stiahnutie neúspešné: %s"

#: ../satellite_tools/messages.py:79
#, python-format
msgid "   RPM fetch summary: %s"
msgstr "   Zhrnutie stiahnutia RPM: %s"

#: ../satellite_tools/messages.py:80
#, python-format
msgid "       success: %d"
msgstr "       úspech: %d"

#: ../satellite_tools/messages.py:81
#, python-format
msgid "       failed:  %d"
msgstr "       neúspešné:  %d"

#: ../satellite_tools/messages.py:82
#, python-format
msgid "       extinct: %d"
msgstr "       zaniknuté: %d"

#: ../satellite_tools/messages.py:84
#, python-format
msgid "   Retrieving / parsing *relevant* package metadata: %s (%s)"
msgstr "   Získavanie / analyzovanie metadát *relevantných* balíkov: %s (%s)"

#: ../satellite_tools/messages.py:85
#, python-format
msgid "   Retrieving / parsing errata data: %s (%s)"
msgstr "   Získavanie / analyzovanie dát tlačových chýb: %s (%s)"

#: ../satellite_tools/messages.py:86
#, python-format
msgid "   Retrieving / parsing kickstart data: %s (%s)"
msgstr "   Získavanie / analyzovanie dát kickstart: %s (%s)"

#: ../satellite_tools/messages.py:87
#, python-format
msgid "   Retrieving / parsing kickstart tree files: %s (%s)"
msgstr "   Získavanie / analyzovanie súborov stromov kickstart: %s (%s)"

#: ../satellite_tools/messages.py:88
#, python-format
msgid "   Importing *relevant* package metadata: %s (%s)"
msgstr "   Importovanie metadát *relevantných* balíkov: %s (%s)"

#: ../satellite_tools/messages.py:89
msgid "   * WARNING: this may be a slow process."
msgstr "   * UPOZORNENIE: toto môže byť pomalý proces."

#: ../satellite_tools/messages.py:90
msgid "Linking packages to channels"
msgstr "Prepojenie balíkov ku kanálom"

#: ../satellite_tools/messages.py:91
#, python-format
msgid "   Importing *relevant* errata: %s (%s)"
msgstr "   Importovanie *relevantných* tlačových chýb: %s (%s)"

#: ../satellite_tools/messages.py:92
msgid "   No new kickstartable tree to import"
msgstr "   Žiadny nový strom schopný kickstart na import"

#: ../satellite_tools/messages.py:93
#, python-format
msgid "Importing kickstartable trees (%d)"
msgstr "Importovanie stromov schopných kickstart (%d)"

#: ../satellite_tools/messages.py:94
#, python-format
msgid "Imported kickstartable trees (%d)"
msgstr "Importované stromy schopné kickstart (%d)"

#: ../satellite_tools/rhn_satellite_activate.py:198
#, python-format
msgid ""
"\"%s\" (specified in commandline)\n"
"could not be opened and read:\n"
"%s"
msgstr ""
"\"%s\" (uvedené v príkazovom riadku)\n"
"sa nepodarilo otvoriť a čítať:\n"
"%s"

#: ../satellite_tools/rhn_satellite_activate.py:205
#, python-format
msgid ""
"\"%s\" could not be opened\n"
"and/or written to:\n"
"%s"
msgstr ""
"\"%s\" sa nepodarilo otvoriť\n"
"a/alebo zapísať do:\n"
"%s"

#: ../satellite_tools/reposync.py:111 ../satellite_tools/satsync.py:439
msgid "+++ sending log as an email +++"
msgstr "+++ odosielanie záznamu ako e-mail +++"

#: ../satellite_tools/reposync.py:114
#, python-format
msgid "%s sync. report from %s"
msgstr "%s sync. správa od %s"

#: ../satellite_tools/reposync.py:124 ../satellite_tools/satsync.py:449
msgid "+++ email requested, but there is nothing to send +++"
msgstr "+++ požadovaný e-mail, ale nie je čo +++"

#: ../satellite_tools/satsync.py:258
#, python-format
msgid "No handler for step %s"
msgstr "Žiadna obsluha pre krok %s"

#. Try one more time - this time it should be faster since
#. everything should be cached
#: ../satellite_tools/satsync.py:270
msgid "Environment changed, trying again..."
msgstr "Prostredie sa zmenilo, opätovné skúšanie..."

#: ../satellite_tools/satsync.py:277
msgid "ERROR: Encountered IntegrityError: \n"
msgstr "CHYBA: Vyskytla sa ChybaIntegrity: \n"

#: ../satellite_tools/satsync.py:285
msgid "Repeated failures"
msgstr "Opakované zlyhania"

#: ../satellite_tools/satsync.py:290
#, python-format
msgid ""
"    Import complete:\n"
"        Begin time: %s\n"
"        End time:   %s\n"
"        Elapsed:    %s\n"
"          "
msgstr ""
"    Import je dokončený:\n"
"        Začiatočný čas: %s\n"
"        Koncový čas:   %s\n"
"        Uplynulý:    %s\n"
"          "

#: ../satellite_tools/satsync.py:311
msgid "hours"
msgstr "hodiny"

#: ../satellite_tools/satsync.py:311
msgid "minutes"
msgstr "minúty"

#: ../satellite_tools/satsync.py:311
msgid "seconds"
msgstr "sekundy"

#: ../satellite_tools/satsync.py:357
msgid ""
"ERROR: The dump is missing package data, use --no-rpms to skip this step or "
"fix the content to include package data."
msgstr ""
"CHYBA: Na výpise chýbajú dáta balíkov, použite --no-rpms na preskočenie "
"tohto kroku alebo opravte obsah tak, aby obsahoval dáta balíkov."

#. the orgs() method doesn't exist; that's fine we just
#. won't sync the orgs
#: ../satellite_tools/satsync.py:404
msgid "The SUSE Manager master does not support syncing orgs data."
msgstr "SUSE Manager master nepodporuje synchronizáciu údajov organizácií."

#: ../satellite_tools/satsync.py:404
msgid "Skipping..."
msgstr "Preskakovanie..."

#: ../satellite_tools/satsync.py:442
#, python-format
msgid "SUSE Manager Inter Server sync. report from %s"
msgstr "Správa synchronizácie pre SUSE Manager Inter Server od %s"

#: ../satellite_tools/satsync.py:521
msgid " - file-system synchronization"
msgstr " - synchronizácia súborového systému"

#: ../satellite_tools/satsync.py:533 ../satellite_tools/satsync.py:541
msgid " - live synchronization"
msgstr " - živá synchronizácia"

#: ../satellite_tools/satsync.py:534
#, python-brace-format
msgid ""
"ERROR: Live content synchronizing with RHN Classic Hosted is no longer "
"supported.\n"
"Please use the cdn-sync command instead unless you are attempting to sync "
"from another {PRODUCT_NAME} via Inter-Server-Sync (ISS), or from local "
"content on disk via Channel Dump ISOs."
msgstr ""
"CHYBA: Synchronizácia živého obsahu so serverom RHN Classic Hosted už nie je "
"podporovaná.\n"
"Namiesto toho použite príkaz cdn-sync, pokiaľ sa nepokúšate synchronizovať s "
"ďalším {PRODUCT_NAME} cez Inter-Satelite-Sync (ISS) alebo s lokálnym obsahom "
"na disku cez Channel Dump ISO."

#: ../satellite_tools/satsync.py:542
#, python-format
msgid "   url: %s"
msgstr "   url: %s"

#: ../satellite_tools/satsync.py:543
#, python-format
msgid "   debug/output level: %s"
msgstr "   ladiaca/výstupná úroveň: %s"

#: ../satellite_tools/satsync.py:553
msgid "ERROR: this server must be registered with SUSE Manager."
msgstr "CHYBA: tento server musí byť zaregistrovaný v SUSE Manager."

#: ../satellite_tools/satsync.py:575
#, python-format
msgid "Retrieving / parsing %s data"
msgstr "Získavanie / analyzovanie dát %s"

#: ../satellite_tools/satsync.py:585 ../satellite_tools/satsync.py:600
msgid "*** SYSTEM INTERRUPT CALLED ***"
msgstr "*** VOLANÉ SYSTÉMOVÉ PRERUŠENIE ***"

#: ../satellite_tools/satsync.py:593
msgid "ERROR: fatal parser exception occurred "
msgstr "CHYBA: vyskytla sa kritická výnimka analyzátora "

#: ../satellite_tools/satsync.py:594
#, python-format
msgid "(line: %s, col: %s msg: %s)"
msgstr "(riadok: %s, stĺpec: %s správa: %s)"

#: ../satellite_tools/satsync.py:598
#, python-format
msgid "ERROR: parser exception occurred: %s"
msgstr "CHYBA: vyskytla sa výnimka analyzátora: %s"

#: ../satellite_tools/satsync.py:603
msgid "ERROR: exception (during parse) occurred: "
msgstr "CHYBA: vyskytla sa výnimka (počas analýzy): "

#: ../satellite_tools/satsync.py:604
#, python-format
msgid ""
"   Encountered some errors with %s data (see logs (%s) for more information)"
msgstr ""
"   Vyskytli sa nejaké chyby s dátami %s (ďalšie informácie nájdete v "
"záznamoch (%s))"

#: ../satellite_tools/satsync.py:606
#, python-format
msgid "   Encountered some errors with %s data:"
msgstr "   Vyskytli sa nejaké chyby s dátami %s:"

#: ../satellite_tools/satsync.py:607
#, python-format
msgid "   ------- %s PARSE/IMPORT ERROR -------"
msgstr "   ------- CHYBA ANALÝZY / IMPORTU %s -------"

#: ../satellite_tools/satsync.py:609
msgid "   ---------------------------------------"
msgstr "   ---------------------------------------"

#: ../satellite_tools/satsync.py:612
#, python-format
msgid "%s data complete"
msgstr "dáta %s sú kompletné"

#: ../satellite_tools/satsync.py:665
msgid "Retrieving / parsing channel data"
msgstr "Získavanie / analyzovanie dát kanála"

#: ../satellite_tools/satsync.py:718
msgid "Channel data complete"
msgstr "Dáta kanála sú kompletné"

#: ../satellite_tools/satsync.py:736
#, python-format
msgid "%10s import from %s"
msgstr "%10s import z %s"

#: ../satellite_tools/satsync.py:739
#, python-format
msgid "%10s import from %s - %s"
msgstr "%10s import z %s - %s"

#: ../satellite_tools/satsync.py:743
#, python-format
msgid "%10s"
msgstr "%10s"

#: ../satellite_tools/satsync.py:750
msgid "p"
msgstr "p"

#: ../satellite_tools/satsync.py:752
msgid "."
msgstr "."

#: ../satellite_tools/satsync.py:758
msgid "   p = previously imported/synced channel"
msgstr "   p = predtým importovaný/synchronizovaný kanál"

#: ../satellite_tools/satsync.py:759
msgid "   . = channel not yet imported/synced"
msgstr "   . = kanál ešte nebol importovaný/synchronizovaný"

#: ../satellite_tools/satsync.py:765
msgid "   e = channel no longer supported (end-of-service)"
msgstr "   e = kanál už nie je podporovaný (koniec služby)"

#: ../satellite_tools/satsync.py:767
msgid "   ? = channel label invalid --- typo?"
msgstr "   ? = štítok kanála je neplatný --- preklep?"

#: ../satellite_tools/satsync.py:771
#, python-format
msgid "   %s:"
msgstr "   %s:"

#: ../satellite_tools/satsync.py:772
#, python-format
msgid "      %s %-40s %4s %s"
msgstr "      %s %-40s %4s %s"

#: ../satellite_tools/satsync.py:773
msgid "base-channels"
msgstr "základné-kanály"

#: ../satellite_tools/satsync.py:786 ../satellite_tools/satsync.py:1603
msgid "NONE RELEVANT"
msgstr "ŽIADNE RELEVANTNÉ"

#: ../satellite_tools/satsync.py:808
msgid "end-of-service"
msgstr "koniec-služby"

#: ../satellite_tools/satsync.py:809
msgid "e"
msgstr "e"

#: ../satellite_tools/satsync.py:815
msgid "   typos:"
msgstr "   preklepy:"

#: ../satellite_tools/satsync.py:816
msgid "?"
msgstr "?"

#: ../satellite_tools/satsync.py:831
#, python-format
msgid "XXX: imported channels: %s"
msgstr "XXX: importované kanály: %s"

#: ../satellite_tools/satsync.py:832
#, python-format
msgid "XXX:   cached channels: %s"
msgstr "XXX:   kanály vo vyrovnávacej pamäti: %s"

#: ../satellite_tools/satsync.py:837
msgid "XXX: list channels called"
msgstr "XXX: zoznam volaných kanálov"

#: ../satellite_tools/satsync.py:855
msgid "ERROR: these channels either do not exist or are not available:"
msgstr "CHYBA: tieto kanály buď neexistujú, alebo nie sú k dispozícii:"

#: ../satellite_tools/satsync.py:859
#, python-format
msgid "       (to see a list of channel labels: %s --list-channels)"
msgstr "       (pozrieť si zoznam štítkov kanálov: %s --list-channels)"

#: ../satellite_tools/satsync.py:904
#, python-format
msgid "   Retrieving / parsing short package metadata: %s (%s)"
msgstr "   Získavanie / analyzovanie metadát krátkych balíkov: %s (%s)"

#: ../satellite_tools/satsync.py:965
#, python-format
msgid "Diffing package metadata (what's missing locally?): %s"
msgstr "Porovnávanie metadát balíkov (čo chýba lokálne?): %s"

#: ../satellite_tools/satsync.py:971 ../satellite_tools/satsync.py:1254
msgid "Diffing:    "
msgstr "Porovnávanie:    "

#: ../satellite_tools/satsync.py:988
msgid "ERROR: incremental dump skipped"
msgstr "CHYBA: preskočený prírastkový výpis"

#: ../satellite_tools/satsync.py:1079
msgid "Downloading rpm packages"
msgstr "Sťahovanie rpm balíkov"

#: ../satellite_tools/satsync.py:1084
#, python-format
msgid "   Fetching any missing RPMs: %s (%s)"
msgstr "   Sťahovanie všetkých chýbajúcich RPM: %s (%s)"

#: ../satellite_tools/satsync.py:1085 ../satellite_tools/satsync.py:1153
msgid "NONE MISSING"
msgstr "ŽIADNY NECHÝBA"

#: ../satellite_tools/satsync.py:1094
msgid "Processing rpm packages complete"
msgstr "Spracovanie rpm balíkov je dokončené"

#: ../satellite_tools/satsync.py:1121
msgid "Downloading package metadata"
msgstr "Sťahovanie metadát balíkov"

#: ../satellite_tools/satsync.py:1146
msgid "Downloading srpm packages"
msgstr "Sťahovanie srpm balíkov"

#: ../satellite_tools/satsync.py:1152
#, python-format
msgid "   Fetching any missing SRPMs: %s (%s)"
msgstr "   Sťahovanie všetkých chýbajúcich SRPM: %s (%s)"

#: ../satellite_tools/satsync.py:1249
#, python-format
msgid "Diffing source package metadata (what's missing locally?): %s"
msgstr "Porovnávanie metadát zdrojových balíkov (čo chýba lokálne?): %s"

#: ../satellite_tools/satsync.py:1260
msgid "Downloading source package metadata"
msgstr "Sťahovanie metadát zdrojových balíkov"

#: ../satellite_tools/satsync.py:1338 ../satellite_tools/satsync.py:2027
#, python-format
msgid "Unable to save file %s: %s"
msgstr "Nepodarilo sa uložiť súbor %s: %s"

#. for
#. Retried a number of times and it still failed; log the
#. file as being failed and move on
#: ../satellite_tools/satsync.py:1345
#, python-format
msgid "Failed to fetch file %s"
msgstr "Zlyhalo stiahnutie súboru %s"

#: ../satellite_tools/satsync.py:1350
msgid "Downloading kickstartable trees metadata"
msgstr "Sťahovanie metadát stromov schopných kickstart"

#: ../satellite_tools/satsync.py:1365
msgid "Downloading kickstartable trees files"
msgstr "Sťahovanie súborov stromov schopných kickstart"

#: ../satellite_tools/satsync.py:1504
#, python-format
msgid "Grabbing all patches for channel %s"
msgstr "Získanie všetkých opráv pre kanál %s"

#: ../satellite_tools/satsync.py:1554
msgid "Downloading patch data"
msgstr "Sťahovanie dát opráv"

#: ../satellite_tools/satsync.py:1556
msgid "Forcing download of all patch data for requested channels."
msgstr "Vynútenie stiahnutia všetkých dát opráv pre požadované kanály."

#: ../satellite_tools/satsync.py:1571
msgid "Downloading patch data complete"
msgstr "Sťahovanie dát opráv je dokončené"

#: ../satellite_tools/satsync.py:1576 ../satellite_tools/satsync.py:1597
msgid "Downloading:"
msgstr "Sťahovanie:"

#: ../satellite_tools/satsync.py:1579
msgid " - complete"
msgstr " - dokončené"

#: ../satellite_tools/satsync.py:1624
msgid "Importing source package metadata"
msgstr "Importovanie metadát zdrojových balíkov"

#: ../satellite_tools/satsync.py:1627
msgid "Importing package metadata"
msgstr "Importovanie metadát balíkov"

#: ../satellite_tools/satsync.py:1635
msgid "Importing:  "
msgstr "Importovanie:  "

#. not in the cache
#: ../satellite_tools/satsync.py:1703
msgid ""
"Package Not Found in Cache, Clear the Cache "
"to                                  Regenerate it."
msgstr ""
"Balík sa nenašiel vo vyrovnávacej pamäti, vyčistite vyrovnávaciu pamäť "
"do                                  Obnovte ju."

#: ../satellite_tools/satsync.py:1709
msgid "Importing channel patches"
msgstr "Importovanie opráv kanálov"

#: ../satellite_tools/satsync.py:1714
#, python-format
msgid "Importing %s patches for channel %s."
msgstr "Importovanie %s opráv pre kanál %s."

#. Incomplete configuration
#: ../satellite_tools/satsync.py:2113
msgid "ERROR: server.mount_point not set in the configuration file"
msgstr "CHYBA: server.bod_pripojenia nie je nastavený v konfiguračnom súbore"

#: ../satellite_tools/satsync.py:2117
#, python-format
msgid "ERROR: server.mount_point %s do not exist"
msgstr "CHYBA: server.bod_pripojenia %s neexistuje"

#: ../satellite_tools/satsync.py:2122
#, python-format
msgid "ERROR: path under server.mount_point (%s)  do not exist"
msgstr "CHYBA: cesta pod server.bod_pripojenia (%s)  neexistuje"

#: ../satellite_tools/satsync.py:2199
#, python-format
msgid "Commandline: %s"
msgstr "Príkazový riadok: %s"

#: ../satellite_tools/satsync.py:2202
#, python-format
msgid ""
"DEBUG ONLY: max. batch-size for XML/database-import processing (1..%s).\"man "
"satellite-sync\" for more information."
msgstr ""
"IBA LADIŤ: max. veľkosť-dávky pre spracovanie XML/database-import (1..%s). "
"Viac informácií v \"man satellite-sync\"."

#: ../satellite_tools/satsync.py:2205
msgid "alternative SSL CA Cert (fullpath to cert file)"
msgstr "alternatívny SSL CA certifikát (úplná cesta k certifikačnému súboru)"

#: ../satellite_tools/satsync.py:2207
msgid "process data for this channel only"
msgstr "spracovať dáta iba pre tento kanál"

#: ../satellite_tools/satsync.py:2209
msgid ""
"disk dump will be considered to be a full export; see \"man satellite-sync\" "
"for more information."
msgstr ""
"výpis disku sa bude považovať za úplný export; ďalšie informácie nájdete v "
"\"man satellite-sync\"."

#: ../satellite_tools/satsync.py:2212
msgid "existing custom channels will also be synced (unless -c is used)"
msgstr ""
"existujúce vlastné kanály budú tiež synchronizované (pokiaľ sa nepoužije -c)"

#: ../satellite_tools/satsync.py:2214
#, python-format
msgid ""
"override debug level set in /etc/rhn/rhn.conf (which is currently set at %s)."
msgstr ""
"prepísať nastavenie úrovne ladenia v /etc/rhn/rhn.conf (ktoré je momentálne "
"nastavené na %s)."

#: ../satellite_tools/satsync.py:2216
#, python-format
msgid "requested version of XML dump (default: %s)"
msgstr "požadovaná verzia výpisu XML (predvolené: %s)"

#: ../satellite_tools/satsync.py:2218
msgid "e-mail a report of what was synced/imported"
msgstr "poslať e-mailom správu o tom, čo bolo synchronizované/importované"

#: ../satellite_tools/satsync.py:2220
msgid "forcibly process all (not a diff of) patch metadata"
msgstr "nútene spracovať všetky (nie odlišné) metadáta opráv"

#: ../satellite_tools/satsync.py:2222
msgid "Do not use an http proxy under any circumstances."
msgstr "Za žiadnych okolností nepoužiť http proxy."

#: ../satellite_tools/satsync.py:2224
msgid "alternative http proxy (hostname:port)"
msgstr "alternatívne http proxy (názov_hostiteľa:port)"

#: ../satellite_tools/satsync.py:2226
msgid "alternative http proxy username"
msgstr "používateľské meno alternatívneho http proxy"

#: ../satellite_tools/satsync.py:2228
msgid "alternative http proxy password"
msgstr "heslo alternatívneho http proxy"

#: ../satellite_tools/satsync.py:2230
msgid "parent SUSE Manager to import content from"
msgstr "rodičovský SUSE Manager, z ktorého sa má importovať obsah"

#: ../satellite_tools/satsync.py:2232
msgid "list all available channels and exit"
msgstr "vypísať zoznam všetkých dostupných kanálov a ukončiť"

#: ../satellite_tools/satsync.py:2234
msgid "help on all error codes mgr-inter-sync returns"
msgstr "pomocník pri všetkých chybových kódoch, ktoré vracia mgr-inter-sync"

#: ../satellite_tools/satsync.py:2236
msgid "source mount point for import - disk update only"
msgstr "zdrojový bod pripojenia pre import - iba aktualizácia disku"

#: ../satellite_tools/satsync.py:2238
msgid "do not process patch data"
msgstr "nespracovávať dáta opráv"

#: ../satellite_tools/satsync.py:2240
msgid "do not process kickstart data (provisioning only)"
msgstr "nespracovávať dáta kickstart (iba poskytovanie)"

#: ../satellite_tools/satsync.py:2242
msgid "do not process full package metadata"
msgstr "nespracovávať úplné metadáta balíkov"

#: ../satellite_tools/satsync.py:2244
msgid "do not download, or process any RPMs"
msgstr "nesťahovať ani nespracovávať žiadne RPM"

#: ../satellite_tools/satsync.py:2246
msgid "turn off SSL (not recommended)"
msgstr "vypnúť SSL (neodporúča sa)"

#: ../satellite_tools/satsync.py:2248
msgid "org to which the sync imports data. defaults to the admin account"
msgstr ""
"organizácia, do ktorej synchronizácia importuje dáta. predvolené nastavenia "
"pre účet administrátora"

#: ../satellite_tools/satsync.py:2250
msgid "print the configuration and exit"
msgstr "vytlačiť konfiguráciu a ukončiť"

#: ../satellite_tools/satsync.py:2252
msgid "alternative server with which to connect (hostname)"
msgstr "alternatívny server, s ktorým sa možno spojiť (názov hostiteľa)"

#: ../satellite_tools/satsync.py:2254
msgid "synchronize to this step (man satellite-sync for more info)"
msgstr "synchronizovať s týmto krokom (viac informácií v man satellite-sync)"

#: ../satellite_tools/satsync.py:2256
msgid "write complete data to tempfile before streaming to remainder of app"
msgstr ""
"zapísať kompletné dáta do dočasného súboru pred streamovaním do zvyšku "
"aplikácie"

#: ../satellite_tools/satsync.py:2258
msgid "DEBUG ONLY: alternative path to digital system id"
msgstr "IBA LADIŤ: alternatívna cesta k digitálnemu systémovému id"

#: ../satellite_tools/satsync.py:2260
msgid "alternative email address(es) for sync output (--email option)"
msgstr ""
"alternatívne emailové adresa(y) pre synchronizovaný výstup (voľba --email)"

#: ../satellite_tools/satsync.py:2262
msgid "do not remove rpms when importing from local dump"
msgstr "neodstraňovať rpm pri importe z lokálneho výpisu"

#: ../satellite_tools/satsync.py:2264
msgid ""
"the fully qualified domain name of the master Satellite. Valid with --mount-"
"point only. Required if you want to import org data and channel permissions."
msgstr ""
"plne kvalifikovaný názov domény hlavného Satellite. Platné iba s --mount-"
"point. Vyžaduje sa, ak chcete importovať dáta organizácie a oprávnenia "
"kanálov."

#: ../satellite_tools/satsync.py:2274
#, python-format
msgid "ERROR: these arguments make no sense in this context (try --help): %s"
msgstr ""
"CHYBA: tieto argumenty nedávajú v tejto súvislosti žiadny zmysel (skúste --"
"help): %s"

#. An SQL error is fatal... crash and burn
#: ../satellite_tools/satsync.py:2286
#, python-format
msgid "ERROR: Can't connect to the database: %s"
msgstr "ERROR: Nedá sa pripojiť k databáze: %s"

#: ../satellite_tools/satsync.py:2287
msgid "ERROR: Check if your database is running."
msgstr "CHYBA: Skontrolujte, či je vaša databáza spustená."

#: ../satellite_tools/satsync.py:2322
#, python-format
msgid "ERROR: --debug-level takes an in integer value within the range %s."
msgstr "CHYBA: --debug-level vezme celé číslo v rozsahu %s."

#: ../satellite_tools/satsync.py:2324
msgid "  0  - little logging/messaging."
msgstr "  0  - málo zaznamenávania/odosielania správ."

#: ../satellite_tools/satsync.py:2325
msgid "  1  - minimal logging/messaging."
msgstr "  1  - minimálne zaznamenávanie/odosielanie správ."

#: ../satellite_tools/satsync.py:2326
msgid "  2  - normal level of logging/messaging."
msgstr "  2  - normálna úroveň zaznamenávania/odosielania správ."

#: ../satellite_tools/satsync.py:2327
msgid "  3  - lots of logging/messaging."
msgstr "  3  - veľa zaznamenávania/odosielania správ."

#: ../satellite_tools/satsync.py:2328
msgid "  4+ - excessive logging/messaging."
msgstr "  4+ - nadmerné zaznamenávanie/odosielanie správ."

#: ../satellite_tools/satsync.py:2341
msgid "ERROR: The --master option is only valid with the --mount-point option"
msgstr "CHYBA: Voľba --master je platná iba s voľbou --mount-point"

#: ../satellite_tools/satsync.py:2351
#, python-format
msgid "ERROR: Unable to lookup Org Id %s"
msgstr "CHYBA: Nepodarilo sa nájsť Org Id %s"

#: ../satellite_tools/satsync.py:2360
msgid ""
"WARNING: --list-channels option overrides any --step option. --step ignored."
msgstr ""
"UPOZORNENIE: Voľba --list-channels prepíše akúkoľvek voľbu --step. --step "
"ignorované."

#: ../satellite_tools/satsync.py:2375
#, python-format
msgid ""
"ERROR: '%s' is not a valid step. See 'man mgr-inter-sync' for more detail."
msgstr ""
"CHYBA: '%s' nie je platný krok. Ďalšie informácie nájdete v 'man mgr-inter-"
"sync'."

#: ../satellite_tools/satsync.py:2407
msgid ""
"ERROR: No channels currently imported; try mgr-inter-sync --list-channels; "
"then mgr-inter-sync -c chn0 -c chn1..."
msgstr ""
"CHYBA: Momentálne nie sú importované žiadne kanály; skúste mgr-inter-sync --"
"list-channels; potom mgr-inter-sync -c chn0 -c chn1..."

#. int(None) --> TypeError
#. int('a')  --> ValueError
#: ../satellite_tools/satsync.py:2457 ../satellite_tools/satsync.py:2461
msgid "ERROR: --batch-size must have a value within the range: 1..50"
msgstr "CHYBA: --batch-size musí mať hodnotu v rozsahu: 1..50"

#: ../satellite_tools/satsync.py:2469
#, python-format
msgid "ERROR: no such directory %s"
msgstr "CHYBA: adresár %s neexistuje"

#: ../satellite_tools/satsync.py:2474
msgid "Error Codes: Returned codes means:"
msgstr "Chybové kódy: Vrátené kódy znamenajú:"

#: ../satellite_tools/satsync.py:2475
msgid " -1  - Could not lock file or KeyboardInterrupt or SystemExit"
msgstr ""
" -1  - Nepodarilo sa zamknúť súbor alebo PrerušenieKlávesnice alebo "
"UkončenieSystém"

#: ../satellite_tools/satsync.py:2476
msgid "  0  - User interrupted or intentional exit"
msgstr "  0  - Používateľ prerušil alebo úmyselne ukončil"

#: ../satellite_tools/satsync.py:2477
msgid "  1  - attempting to run more than one instance of mgr-inter-sync."
msgstr "  1  - pokus o spustenie viac ako jednej inštancie mgr-inter-sync."

#: ../satellite_tools/satsync.py:2478
msgid "  2  - Unable to find synchronization tools."
msgstr "  2  - Nepodarilo sa nájsť synchronizačné nástroje."

#: ../satellite_tools/satsync.py:2479
msgid "  3  - a general socket exception occurred"
msgstr "  3  - vyskytla sa všeobecná výnimka soketu"

#: ../satellite_tools/satsync.py:2480
msgid "  4  - an SSL error occurred. Recheck your SSL settings."
msgstr "  4  - vyskytla sa chyba SSL. Prekontrolujte svoje nastavenia SSL."

#: ../satellite_tools/satsync.py:2481
msgid "  5  - ISS error"
msgstr "  5  - chyba ISS"

#: ../satellite_tools/satsync.py:2482
msgid "  6  - unhandled exception occurred"
msgstr "  6  - vyskytla sa neošetrená výnimka"

#: ../satellite_tools/satsync.py:2483
msgid "  7  - unknown sync error"
msgstr "  7  - neznáma chyba synchronizácie"

#: ../satellite_tools/satsync.py:2484
msgid "  8  - ERROR: must be root to execute"
msgstr "  8  - CHYBA: na vykonanie musí byť správca systému"

#: ../satellite_tools/satsync.py:2485
msgid "  9  - rpclib fault during synchronization init"
msgstr "  9  - zlyhanie rpclib počas inicializácie synchronizácie"

#: ../satellite_tools/satsync.py:2486
msgid "  10 - synchronization init error"
msgstr "  10 - chyba inicializácie synchronizácie"

#: ../satellite_tools/satsync.py:2487
msgid "  11 - Error parsing XML stream"
msgstr "  11 - Chyba analýzy prúdu XML"

#: ../satellite_tools/satsync.py:2488
msgid "  12 - Channel do not exist"
msgstr "  12 - Kanál neexistuje"

#: ../satellite_tools/satsync.py:2489
msgid "  13 - SQL error during importing package metadata"
msgstr "  13 - Chyba SQL počas importovania metadát balíka"

#: ../satellite_tools/satsync.py:2490
msgid "  14 - SQL error during linking channel packages"
msgstr "  14 - Chyba SQL počas prepájania balíkov kanálov"

#: ../satellite_tools/satsync.py:2491
msgid "  15 - SQL error during xml processing"
msgstr "  15 - chyba SQL počas spracovania xml"

#: ../satellite_tools/satsync.py:2492
msgid "  16 - server.mount_point not set in the configuration file"
msgstr "  16 - server.bod_pripojenia nie je nastavené v konfiguračnom súbore"

#: ../satellite_tools/satsync.py:2493
msgid ""
"  17 - SQL error during retrieving the channels already imported in the SUSE "
"Manager database"
msgstr ""
"  17 - chyba SQL počas získavania kanálov už importovaných v databáze SUSE "
"Manager"

#: ../satellite_tools/satsync.py:2494
msgid "  18 - Wrong db connection string in rhn.conf"
msgstr "  18 - Nesprávny reťazec pripojenia db v rhn.conf"

#: ../satellite_tools/satsync.py:2495
msgid "  19 - Bad arguments"
msgstr "  19 - Zlé argumenty"

#: ../satellite_tools/satsync.py:2496
msgid "  20 - Could not connect to db."
msgstr "  20 - Nepodarilo sa pripojiť k db."

#: ../satellite_tools/satsync.py:2497
msgid "  21 - Bad debug level"
msgstr "  21 - Zlá úroveň ladenia"

#: ../satellite_tools/satsync.py:2498
msgid "  22 - Not valid step"
msgstr "  22 - Neplatný krok"

#: ../satellite_tools/satsync.py:2499
msgid "  24 - no such file"
msgstr "  24 - súbor neexistuje"

#: ../satellite_tools/satsync.py:2500
msgid "  25 - no such directory"
msgstr "  25 - adresár neexistuje"

#: ../satellite_tools/satsync.py:2501
msgid "  26 - mount_point does not exist"
msgstr "  26 - bod_pripojenia neexistuje"

#: ../satellite_tools/satsync.py:2502
msgid "  27 - No such org"
msgstr "  27 - Organizácia neexistuje"

#: ../satellite_tools/satsync.py:2503
msgid "  28 - error: --master is only valid with --mount-point"
msgstr "  28 - chyba: --master je platné iba s --mount-point"

#: ../satellite_tools/satsync.py:2510
#, python-format
msgid "ERROR: unknown dump version, try one of %s"
msgstr "CHYBA: neznáma verzia výpisu, vyskúšajte jeden z %s"

#~ msgid "Red Hat Satellite Welcome Message"
#~ msgstr "Uvítacia správa Red Hat Satellite"
